### PR TITLE
`FLANN::knnSearch` kNN assertion

### LINKED ISSUE #10548: `FLANN::knnSearch` does not assert the kNN value
##### System information (version)
- OpenCV => 3.4.0-dev
- Operating System / Platform => ALL
- Compiler => ALL

##### Detailed description
FLANN returns garbage indices and distances when kNN is larger than its training dataset size.
More importantly, when kNN is slightly larger than the dataset size (e.g. `kNN=3, size()=2`), the returned indices beyond the dataset size are zeros, which creates silent, misleading correspondences.

##### Steps to reproduce
This is not a Python bug, it is also reproducible using C++
```.py
import numpy as np
import cv2

kNN = 7 #Any number bigger that len(index_points) will do
index_points = np.array([[0, 1, 2], [3, 4, 5]], np.float32)
query_points = np.array([[1, 2, 3]], np.float32)

flann_index = cv2.flann.Index if cv2.__version__.startswith('2') else cv2.flann_Index
flann = flann_index(index_points, dict(algorithm=0, trees=5))
idx, dist = flann.knnSearch(query_points, kNN, params = {})

np.set_printoptions(formatter={'all':lambda x: '{0:.3g},'.format(x)})
print(idx)
print(dist)
```

##### Expected result
```
[[0, 1, nan, nan, nan, nan, nan,]]
[[3, 12, nan, nan, nan, nan, nan,]]
```
OR to throw an exception!

##### Actual result
```
[[0, 1, 1.63e+09, 1.7e+09, 0, 0, 15,]]
[[3, 12, 7.26e-39, 8.72e-39, 7.35e-39, 7.26e-39, 6.7e-39,]]
```

### PR DESCRIPTION
**Pull request by Sahloul**
resolves #10548
### This pullrequest changes
- Prevent the user from using kNN values larger than the dataset size

### CODE REVIEW

File: modules/flann/src/miniflann.cpp [hunk 1]
```diff
@@ -482,15 +482,18 @@ void runKnnSearch_(void* index, const Mat& query, Mat& indices, Mat& dists,
     typedef typename Distance::ResultType DistanceType;
     int type = DataType<ElementType>::type;
     int dtype = DataType<DistanceType>::type;
+    IndexType* index_ = (IndexType*)index;
+
+    CV_Assert(knn <= index_->size());
```
Comment (Sahloul) [inline modules/flann/src/miniflann.cpp]: There are two main strategies:
- Failure-avoidance strategies
    - Set `knn = MIN(knn, index_->size());`
    - Swallow it and return NaNs for the additional kNNs.
- Raise and exception to reject the user input

Is it my imagination, or this is also related to #8300? In that case, I guess the vote for this matter is meaningless, as there are cases where one strategy is better than the other, and vise versa.

In this specific case, the user is expecting a matrix of kNN width, returning smaller one is not a sane choice.
Moreover, while returning NaNs in the distance makes sense, the indices matrix needs to be `int`-type. Accordingly, while I am a fan of failure-avoidance strategies, it just does not make sense here, and an exception is the best choice.

File: modules/flann/src/miniflann.cpp [hunk 2]
```diff
@@ -482,15 +482,18 @@ void runKnnSearch_(void* index, const Mat& query, Mat& indices, Mat& dists,
     typedef typename Distance::ResultType DistanceType;
     int type = DataType<ElementType>::type;
     int dtype = DataType<DistanceType>::type;
+    IndexType* index_ = (IndexType*)index;
+
+    CV_Assert((size_t)knn <= index_->size());
```
Comment (Sahloul) [inline modules/flann/src/miniflann.cpp]: There are two main strategies:
- Failure-avoidance strategies
    - Set `knn = MIN(knn, index_->size());`
    - Swallow it and return NaNs for the additional kNNs.
- Raise and exception to reject the user input

Is it my imagination, or this is also related to #8300? In that case, I guess the vote for this matter is meaningless, as there are cases where one strategy is better than the other, and vise versa.

In this specific case, the user is expecting a matrix of kNN width, returning smaller one is not a sane choice.
Moreover, while returning NaNs in the distance makes sense, the indices matrix needs to be `int`-type. Accordingly, while I am a fan of failure-avoidance strategies, it just does not make sense here, and an exception is the best choice.

Comment (alalek) [reply modules/flann/src/miniflann.cpp]: #8300 is about an empty cv::Mat as input parameter. Is empty cv::Mat an invalid parameter or not?

This parameters check is fine here.
