### PR TITLE
Fixes issue 16777.

### LINKED ISSUE #16777: core: getNumThreads() result is wrong on Win32/Concurrency backend
getNumThreads() returns `nCPUs+1` by default:
- 4 cores: `getNumThreads()` => 5
- 4 cores + HT: `getNumThreads()` => 9

relates https://github.com/opencv/opencv/commit/460644b8a4325558414f1d30ba15138857434875

### PR DESCRIPTION
**Pull request by saskatchewancatch**
### Pull Request Readiness Checklist

fixes #16777 Fairly obvious change.

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by alalek** [comment]
See issue's comments

File: modules/core/src/parallel.cpp [hunk 1]
```diff
@@ -618,9 +618,9 @@ int getNumThreads(void)
 
 #elif defined HAVE_CONCURRENCY
 
-    return 1 + (pplScheduler == 0
+    return (pplScheduler == 0)
         ? Concurrency::CurrentScheduler::Get()->GetNumberOfVirtualProcessors()
-        : pplScheduler->GetNumberOfVirtualProcessors());
+        : pplScheduler->GetNumberOfVirtualProcessors();
```
Comment (alalek) [inline modules/core/src/parallel.cpp]:
```
    return (pplScheduler == 0)
        ? Concurrency::CurrentScheduler::Get()->GetNumberOfVirtualProcessors()
        : (1 + pplScheduler->GetNumberOfVirtualProcessors());
```

(you can check that through `--test_threads=2` command-line parameter for OpenCV tests)
