### PR TITLE
calib3d: add CALIB_FIX_TANGENT_DIST flag to stereoCalibrate

### LINKED ISSUE #9461: CALIB_FIX_TANGENT_DIST does not work with cv::stereoCalibrate
##### System information (version)
- OpenCV => Latest
- Operating System / Platform => Ubuntu 16.04
- Compiler => GCC 5.4

##### Detailed description

#9153 fixes `cv::CALIB_FIX_TANGENT_DIST` for `cv::calibrateCamera` but not `cv::stereoCalibrate`. When running `cv::stereoCalibrate` with `cv::CALIB_FIX_TANGENT_DIST` flag, the tangential distortion still changes.

### PR DESCRIPTION
**Pull request by sovrasov**
resolves #9461
This flag works only when `CALIB_USE_INTRINSIC_GUESS` was specified (like `CALIB_FIX_K1`...`CALIB_FIX_K3` do).

### CODE REVIEW

File: modules/calib3d/src/solvepnp.cpp [hunk 1]
```diff
@@ -137,7 +137,7 @@ bool solvePnP( InputArray _opoints, InputArray _ipoints,
         CvMat c_cameraMatrix = cameraMatrix, c_distCoeffs = distCoeffs;
         CvMat c_rvec = rvec, c_tvec = tvec;
         cvFindExtrinsicCameraParams2(&c_objectPoints, &c_imagePoints, &c_cameraMatrix,
-                                     c_distCoeffs.rows*c_distCoeffs.cols ? &c_distCoeffs : 0,
+                                     c_distCoeffs.rows*c_distCoeffs.cols != 0 ? &c_distCoeffs : 0,
```
Comment (alalek) [inline modules/calib3d/src/solvepnp.cpp]: GCC warning means this change:
```
(c_distCoeffs.rows && c_distCoeffs.cols)
or
(c_distCoeffs.rows != 0 && c_distCoeffs.cols != 0)
```

```
modules/calib3d/src/solvepnp.cpp:140:55: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
                                      c_distCoeffs.rows*c_distCoeffs.cols ? &c_distCoeffs : 0,
                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

**Comment by alalek** [comment]
:+1:
