### PR TITLE
cuda4dnn(Eltwise, Power): fix eltwise fusion, enable more eltwise fusion, fix power fusion

### LINKED ISSUE #17934: DNN model crashes on detect for Yolo with CUDA backend
##### System information (version)
- OpenCV => 4.4
- Operating System / Platform => Ubuntu 18.04 64 Bit and Ubuntu 18.04 Arm64
- Compiler => gcc
- Nvidia driver = 440.82
- Cuda = 10.2

##### Detailed description

I get a segmentation fault when using the [**DNN detection model**](https://docs.opencv.org/master/d3/df1/classcv_1_1dnn_1_1DetectionModel.html) detect function from **Python** 3.6. This happens only when using **CUDA** backends, running on CPU works fine. I am running some custom yolov3 config and weights, trained with [Darknet](https://github.com/AlexeyAB/darknet/).
The same code of mine works fine with older versions of OpenCV. Both on current master and the 4.4.0 release the segmentation fault happens. As a workaround I am using now OpenCV at commit 0ccc839397e50f8df27424aef20827f678e96cea and the extra modules at [468345511f94ca54079c739f47e64e2520a6f8e9](https://github.com/opencv/opencv_contrib/commit/468345511f94ca54079c739f47e64e2520a6f8e9). I use those only because I knew that master worked for me at that point in time. Maybe newer versions work as well.

I was running my code in GDB and backtrace gave me this output:
```
#0  0x00007f877de6d123 in cv::dnn::dnn4_v20200609::Net::Impl::fuseLayers(std::vector<cv::dnn::dnn4_v20200609::LayerPin, std::allocator<cv::dnn::dnn4_v20200609::LayerPin> > const&) ()
    at /usr/local/lib/libopencv_dnn.so.4.4
#1  0x00007f877de6ecd5 in cv::dnn::dnn4_v20200609::Net::Impl::allocateLayers(std::vector<cv::dnn::dnn4_v20200609::LayerPin, std::allocator<cv::dnn::dnn4_v20200609::LayerPin> > const&) ()
    at /usr/local/lib/libopencv_dnn.so.4.4
#2  0x00007f877de7201f in cv::dnn::dnn4_v20200609::Net::Impl::setUpNet(std::vector<cv::dnn::dnn4_v20200609::LayerPin, std::allocator<cv::dnn::dnn4_v20200609::LayerPin> > const&) ()
    at /usr/local/lib/libopencv_dnn.so.4.4
#3  0x00007f877de73363 in cv::dnn::dnn4_v20200609::Net::forward(cv::_OutputArray const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) () at /usr/local/lib/libopencv_dnn.so.4.4
#4  0x00007f877dfd9442 in cv::dnn::dnn4_v20200609::Model::Impl::predict(cv::dnn::dnn4_v20200609::Net&, cv::Mat const&, cv::_OutputArray const&) () at /usr/local/lib/libopencv_dnn.so.4.4
#5  0x00007f877dfdda84 in cv::dnn::dnn4_v20200609::DetectionModel::detect(cv::_InputArray const&, std::vector<int, std::allocator<int> >&, std::vector<float, std::allocator<float> >&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, float, float) () at /usr/local/lib/libopencv_dnn.so.4.4
#6  0x00007f8787999ab5 in pyopencv_cv_dnn_dnn_DetectionModel_detect(_object*, _object*, _object*) () at /usr/local/lib/python3.6/dist-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so
```

The 64 bit code I am usually running from within Docker, using this as a base image: [nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04](https://hub.docker.com/layers/nvidia/cuda/10.0-cudnn7-devel-ubuntu18.04/images/sha256-e277b9eef79d6995b10d07e30228daa9e7d42f49bcfc29d512c1534b42d91841?context=explore) . It happens also outside of Docker though.

OpenCV is build from source using this Cmake command:
`cmake -DBUILD_opencv_python2=OFF -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DENABLE_PRECOMPILED_HEADERS=OFF -DWITH_GSTREAMER=ON -DWITH_FFMPEG=ON -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules -DWITH_CUDA=ON ..`

##### Steps to reproduce
Some sample code, showing how I use the dnn model

```
import cv2

net = cv2.dnn.readNetFromDarknet(config_file, weights_file)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)
model = cv2.dnn_DetectionModel(net)
model.setInputSize(size)
model.setInputScale(1.0 / 255)
classes = open('data/config/coco.names').read().strip().split('\n')

height, width, channels = frame.shape
    if size[0] != width or size[1] != height:
        frame_resized = cv2.resize(frame, size, interpolation=cv2.INTER_LINEAR)
    else:
        frame_resized = frame

#crashes here        
classes, confidences, boxes = self.model.detect(frame_resized, confThreshold=score_thresh, nmsThreshold=nms_thresh)
```

The yolov3 config used is close to this [template](https://github.com/AlexeyAB/darknet/blob/master/cfg/csresnext50-panet-spp-original-optimal.cfg).

### LINKED ISSUE #17946: dnn(opencl, cuda): missed eltwise fusion opportunity
##### System information (version)
- OpenCV => 3.4.11, 4.4.0

##### Detailed description

```
Convolution
Eltwise
ReLU
```

Eltwise is not fused with convolution if `ReLU` is the last layer of the network because of this check in 3.4:

https://github.com/opencv/opencv/blob/5bfa43f7d5e14e40166777f67840af189811cac9/modules/dnn/src/dnn.cpp#L2461

I think the `pinsToKeep` check shouldn't be there at all. The `lpNext` is the pin to the activation layer's output blob. It was last set here:

https://github.com/opencv/opencv/blob/5bfa43f7d5e14e40166777f67840af189811cac9/modules/dnn/src/dnn.cpp#L2456

Why should the fusion not take place if the activation layer's output is required by the user?

Note that the following code sets the output blobs of the eltwise and the activation layer to that of the convolution layer.

https://github.com/opencv/opencv/blob/5bfa43f7d5e14e40166777f67840af189811cac9/modules/dnn/src/dnn.cpp#L2492-L2495

Therefore, returning the activation layer's blob will automatically return the fused convolution's output blob which is correct. So there is no problem with fusing even if the output blob of the activation layer is required?

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by YashasSamaga**
Eltwise layer can create two types of operators: `ShortcutOp` and `EltwiseOp`. There is a dynamic cast to `EltwiseOpBase` to retrieve configuration to check fusion compatibility. No check is made to see if the cast was successful (required since some `EltwiseLayer` use `cuda4dnn::ShortcutOp` which is not derived from `EltwiseOpBase`).

fixes #17934 
fixes #17946 for master
fixes cuda part of #17964 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by YashasSamaga** [comment]
To ensure that this doesn't happen again and to catch future bugs, I was thinking of adding a test for every possible fusion in the CUDA backend.

1. create `test_cuda_layers.hpp`
2. create test templates for:
    - conv + activation
    - conv + eltwise + activation
    - conv + eltwise
    - conv + activation + eltwise
3. add a test case for conv + shortcut

I would create a test template that would create the above scenarios. It will compare the outputs of the CUDA backend (and maybe others?) against OCV CPU backend without fusions.

Shall I do this?

**Comment by mshabunin** [comment]
@YashasSamaga , yes,  generic fusion tests would be useful for all backends.

Is this PR ready to be merged?

**Comment by YashasSamaga** [comment]
@mshabunin I was waiting for a reply for the tests. I will finish this PR in maybe another 6-8 hours.

**Comment by dkurt** [comment]
I agree that it would be nice to have the generic tests. You may build it in runtime, without test data like here: https://github.com/opencv/opencv/blob/master/modules/dnn/test/test_layers.cpp

**Comment by YashasSamaga** [comment]
PR is ready. There is an unrelated test from calib3d that is failing in Win64 OpenCL that prevents the PR from turning green.

Results of fusion tests #17976 in 4.4.0 with debug printfs enabled: https://gist.github.com/YashasSamaga/354b2ef2cf570dcd5beb8fc91c657b84

File: modules/dnn/src/dnn.cpp [hunk 1]
```diff
@@ -2725,7 +2714,7 @@ struct Net::Impl : public detail::NetImplBase
                                 {
                                     nextData = &layers[eltwiseData->consumers[0].lid];
                                     lpNext = LayerPin(eltwiseData->consumers[0].lid, 0);
-                                    if (pinsToKeep.count(lpNext) == 0 && nextData->outputBlobs.size() == 1)
+                                    if (nextData->outputBlobs.size() == 1)
```
Comment (mshabunin) [inline modules/dnn/src/dnn.cpp:2717]: Lets add an assertion `CV_Assert(nextData)` for safety.
