### PR TITLE
dnn: support ONNX Tile

### LINKED ISSUE #22789: OpenCV cannot import ONNX model: Can't create layer "..." of type "Tile"
### System Information

OpenCV => Python opencv-python-rolling 4.6.0.20221022
Operating System / Platform Windows 10 64 bit
Python =>3.10.4

### Detailed description

I converted the DANets from PaddleSeg to ONNX: 

https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/configs/danet 

This fails to load in OpenCV 4.6 pre-release:
```
[ERROR:0@0.494] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1050) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Tile]:(onnx_node!p2o.Tile.0) from domain='ai.onnx'
Traceback (most recent call last):
  File "d:\Local\devel\Python\OpenCV\dnn_segmentation_paddle_danet_resnet50_os8_voc12aug\inference.py", line 123, in <module>
    model = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.6.0-dev) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1069: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Tile@ai.onnx]:(onnx_node!p2o.Tile.0) parse error: OpenCV(4.6.0-dev) d:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.hpp:107: error: (-2:Unspecified error) Can't create layer "onnx_node!p2o.Tile.0" of type "Tile" in function 'cv::dnn::dnn4_v20220524::Net::Impl::getLayerInstance'
```

### Steps to reproduce

```
model = cv2.dnn.readNet(model_path)
```
Find one of the models here:
https://drive.google.com/file/d/1ajtfuQ9pCsirxxb6JPJJv9N29gayTLvk/view?usp=sharing

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by fengyuentau**
Fixes #22789

Merge with https://github.com/opencv/opencv_extra/pull/1017

ONNX doc for Tile:
- Opset 1: 3 inputs (https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Tile-1)
- Opset 6: 2 inputs (https://github.com/onnx/onnx/blob/main/docs/Changelog.md#Tile-6)
- Opset 13: 2 inputs (https://github.com/onnx/onnx/blob/main/docs/Operators.md#Tile)
- Opset 13 is basically the same as Opset 6 for inference.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@fengyuentau Thanks for the contribution! Could you enable related "conformance" tests too?

**Comment by fengyuentau** [comment]
> Could you enable related "conformance" tests too?

Actually we cannot. This implementation requires one of the input (called `repeats`) being constant in order to determine the output shape. However, both of the two conformance tests of tile have two non-constant inputs.

**Review by vpisarev — APPROVED** [review]

File: modules/dnn/src/layers/tile_layer.cpp [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+    }
+
+    virtual bool getMemoryShapes(const std::vector<MatShape> &inputs,
+                                 const int requiredOutputs,
+                                 std::vector<MatShape> &outputs,
+                                 std::vector<MatShape> &internals) const CV_OVERRIDE
+    {
+        // inputs[0]: input, a tensor of any shape
+        // inputs[1]: repeats, ignored
+        CV_CheckLE(inputs.size(), 2ull, "Tile: should have at most two inputs"); // TODO: support tile-1
```
Comment (rogday) [inline modules/dnn/src/layers/tile_layer.cpp:44]: Does this work for all-const inputs?

File: modules/dnn/src/layers/tile_layer.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+        return backendId == DNN_BACKEND_OPENCV;
+    }
+
+    virtual bool getMemoryShapes(const std::vector<MatShape> &inputs,
+                                 const int requiredOutputs,
+                                 std::vector<MatShape> &outputs,
+                                 std::vector<MatShape> &internals) const CV_OVERRIDE
+    {
+        // inputs[0]: input, a tensor of any shape
+        // inputs[1]: repeats, ignored
```
Comment (rogday) [inline modules/dnn/src/layers/tile_layer.cpp:43]: If we don't support it, we should expect 1 input.

**Review by rogday — COMMENTED** [review]
Thank you for contribution!

File: modules/dnn/src/layers/tile_layer.cpp (hunk 2 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/tile_layer.cpp:43]: Indeed one input should be expected, but `repeats` is an input item for Tile. I did not find a example on removing a constant input from the inputs of a layer in the ONNX importer though. Maybe I missed something.

So I just leave it as-is but put it in the list of parameters in addition.

File: modules/dnn/src/layers/tile_layer.cpp (hunk 1 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/tile_layer.cpp]: It should, the input size should still be 2 for tile>1 and 3 for tile-1.

Comment (rogday) [reply modules/dnn/src/layers/tile_layer.cpp]: Do we have a test for that? It's just you send only 1 input as far as I can see

```cpp
        std::vector<Mat> inputs, output;
        Mat input0_blob = getBlob(node_proto, 0);
        inputs.push_back(input0_blob);
        runLayer(layerParams, inputs, output);
        CV_Assert(output.size() == 1);
        addConstant(node_proto.output(0), output[0]);
        return;
```

File: modules/dnn/src/layers/tile_layer.cpp (hunk 2 above)
Comment (rogday) [reply modules/dnn/src/layers/tile_layer.cpp:48]: You  can see the example here:
https://github.com/opencv/opencv/blob/3f371fe2dd909b29fa6cc01b35649e3b58b265f2/modules/dnn/src/onnx/onnx_importer.cpp#L660
I might've missed something obvious in the API(pop_back or something), but my approach is clear inputs and add new ones manually. In your case that would be clear + add first input.

Comment (fengyuentau) [reply modules/dnn/src/layers/tile_layer.cpp:48]: Surprisingly, the number of input (printed in `getMemoryShapes`) is always one regardless of the 'clear + add first input' change.

I also had a try with the tile onnx model with `repeats` being `category: Constant` instead of `category: Initializer`, and the number of input is still one.

Any ideas?

Comment (rogday) [reply modules/dnn/src/layers/tile_layer.cpp:48]: Yeah, you're right. Since mentioned inputs don't become constant layers, we get only the first one. Then we just need to change the assert from <=3 to exactly 1.

**Review by rogday — APPROVED** [review]
LGTM! :+1:
