### PR TITLE
video tracking (dnn): set backend and target for TrackerVit

### LINKED ISSUE #24460: video tracking (dnn): TrackerVit does not initialized with given backend and target
### System Information

latest opencv

### Detailed description

`TrackerVit::Params` accepts backend and target but they are not used anywhere.

https://github.com/opencv/opencv/blob/1911c6382619bb26827dfd2f66b9b09fa1b24702/modules/video/src/tracking/tracker_vit.cpp#L24-L36

https://github.com/opencv/opencv/blob/1911c6382619bb26827dfd2f66b9b09fa1b24702/modules/video/src/tracking/tracker_vit.cpp#L43-L48

### Steps to reproduce

N/A

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by fengyuentau**
Resolves #24460 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/video/src/tracking/tracker_vit.cpp [hunk 1]
```diff
@@ -45,6 +45,11 @@ class TrackerVitImpl : public TrackerVit
     {
         net = dnn::readNet(params.net);
         CV_Assert(!net.empty());
+
+        if (params.backend != -1 && params.target != -1) {
```
Comment (dkurt) [inline modules/video/src/tracking/tracker_vit.cpp:49]: Values `-1` are used in case of `#ifndef HAVE_OPENCV_DNN`. So this `if` statement is not actual.

Comment (fengyuentau) [reply modules/video/src/tracking/tracker_vit.cpp]: Good catch, thank you!

**Review by dkurt — APPROVED** [review]
