### PR TITLE
Stereo calibration fixed when intrinsic guess is given

### LINKED ISSUE #22421: LevMarq does not converge at stereo calibration
##### System information (version)

- OpenCV => 5.x
- Operating System / Platform => Ubuntu 20.04 (can be OS-independent)
- Compiler => GCC 9.4.0 (can be compiler-independent)

##### Detailed description

Was discovered by @ivashmak 

The final optimization in `stereoCalibrate` does not converge to some practical values.
It's known that it converged in 4.x when the old LevMarq engine was used.

##### Steps to reproduce

Compile & run `main.cpp` with OpenCV 5.x, the final optimization result should be the same as in `log.txt`.

See the zip file attached.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
 - [x] I updated to the latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

[levmarqstereo.zip](https://github.com/opencv/opencv/files/9410523/levmarqstereo.zip)

### PR DESCRIPTION
**Pull request by savuor**
Fixes #22421
Connected test data PR: [#1003@extra](https://github.com/opencv/opencv_extra/pull/1003)

### Changes
* Stereo Calibration is fixed for cases when intrinsic camera matrices are provided by user and don't have to be recomputed
  * Erroneous variable initialization removed, see [this commit](https://github.com/opencv/opencv/pull/22460/commits/96e2d326185fd1639238c8158ff9daf10d25c712)
* Regression test for the case
* Less address arithmetics, making valgrind happy
* Fix for `CALIB_SAME_FOCAL_LENGTH` flag:
  * Volatile variable (i.e. that is changed by the callback) made mask-fixed as it should be
  * See [this commit](https://github.com/opencv/opencv/pull/22460/commits/a8b4ffac50b195670fef2c0017a36b38d223ad81)
* Other `stereoCalibrateImpl()` refactoring changes

### TODOs for next PRs to improve convergence:
* Implement SE(3) exponential increment
* Try classic callback (no J^T * J and J^T * b, just J and b) for geodesic acceleration

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by vpisarev** [comment]
@savuor, big thanks! @ivashmak, can you check your code with this patch, whether it solves the problem on your side?

**Comment by ivashmak** [comment]
> @savuor, big thanks! @ivashmak, can you check your code with this patch, whether it solves the problem on your side?

Yes, it solves my problem. Thanks a lot @savuor

File: modules/calib/src/calibration.cpp [hunk 1]
```diff
@@ -1010,23 +1003,35 @@ static double stereoCalibrateImpl(
...
+                                Je.at<double>(p, j) = de3dr1(j);
+
+                            for(int j = 0; j < 3; j++)
+                                Je.at<double>(p, 3+j) = de3dt1(j);
+
+                            for(int j = 0; j < 3; j++)
+                                J_LR.at<double>(p, j) = de3dr2(j);
+
+                            for(int j = 0; j < 3; j++)
+                                J_LR.at<double>(p, 3+j) = de3dt2(j);
```
Comment (asmorkalov) [inline modules/calib/src/calibration.cpp:1034]: This part could be done without memory copy. Let's discuss offline.

**Comment by asmorkalov** [comment]
@savuor The changes looks good to me in general. Couple of general recommendations:
- Clean commits history and squash common commits. 13 commits is too many.
- Please define the issue reason in PR description. Actual issue and solution is not visible in large refactoring.

**Comment by savuor** [comment]
@asmorkalov Squashed into 5 commits, added links to them in PR description, looks better now?

**Review by asmorkalov — APPROVED** [review]

**Comment by alalek** [comment]
Too many commits pushed as merge

**Comment by alalek** [comment]
`git bisect` works properly iff each commit is green.
So we should not have malformed state in the git history.
