### PR TITLE
Solve issue 5035

### LINKED ISSUE #4427: Native camera does not work on HTC One S with Android ICS 4.0.4
Transferred from http://code.opencv.org/issues/2359
```
|| Alexander Smorkalov on 2012-09-17 07:34
|| Priority: High
|| Affected: 2.4.0 - 2.4.7
|| Category: android
|| Tracker: Bug
|| Difficulty: 
|| PR: https://github.com/Itseez/opencv/pull/2501
|| Platform: ARM / Android
```

Native camera does not work on HTC One S with Android ICS 4.0.4
-----------
```
Surface texture destructor crashes with message:
F/libc    (12544): @@@ ABORTING: INVALID HEAP ADDRESS IN dlfree
F/libc    (12544): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
```

History
-------
##### Alexander Smorkalov on 2012-09-17 07:35
```
-   Priority changed from Low to High
```
##### Alexander Smorkalov on 2012-09-27 11:18
```
Issue reproduced on Samsung Galaxy Note with Android 4.0.4
-   File opencv-galaxy-note-20120926-175835.log added
```
##### Andrey Kamaev on 2012-10-31 14:06
```
-   Target version changed from 2.4.3 to 3.0
```
##### Shichao Gao on 2012-11-08 09:57
```
A similar native camera crash is reproduced on an Motorola Atrix 2 (4.0.4) as the attached log shows.
-   File Atrix2.log added
```
##### Alexander Smorkalov on 2012-12-26 08:01
```
HTC One S and Motorola Atrix 2 gets update up to Android 4.1.x. Native camera works fine.
```
##### Alexander Smorkalov on 2014-03-24 20:28
```
-   Affected version set to 2.4.0 - 2.4.7
-   Pull request set to https://github.com/Itseez/opencv/pull/2501
-   Operating System set to Android
-   HW Platform set to ARM
-   Status changed from Open to Done
```
##### kaorshi nguyen on 2015-05-21 00:41
```
HTC 610 with android 4.4, same issue.
-   Status changed from Done to Open
```

### LINKED ISSUE #5035: Opengl Assertion in debug mode
Transferred from http://code.opencv.org/issues/4427

```
|| Laurent Berger on 2015-06-22 16:33
|| Priority: Low
|| Affected: branch 'master' (3.0-dev)
|| Category: None
|| Tracker: Bug
|| Difficulty: Easy
|| PR: 
|| Platform: x64 / Windows
```
## Opengl Assertion in debug mode 

```
In example in debug mode an assertion occurs in example detect_mser
_OpenCV Error: OpenGL API call (An unacceptable value is specified for an enumera
ted argument) in cv::ogl::Arrays::bind, file ..\..\..\modules\core\src\opengl.cp
p, line 1348_
It seems that this problem exist in other configuration http://answers.opencv.org/question/31920/opencv-error-opengl-api-call-cvoglarraysbind/

gl::Error return value gl::INVALID_ENUM : (https://www.opengl.org/wiki/OpenGL_Error)
_ GL_INVALID_ENUM, 0x0500
    Given when an enumeration parameter is not a legal enumeration for that function. This is given only for local problems; if the spec allows the enumeration in certain circumstances, where other parameters or state dictate those circumstances, then GL_INVALID_OPERATION is the result instead.
_

This assertion can be deleted if function     bool checkError(const char* file, const int line, const char* func = 0) at line 62 is modified
in file modules\core\src\opengl.cpp
```

### PR DESCRIPTION
**Pull request by LaurentBerger**
Assertion in Debug mode using windows for OpenGL windows
resolves #5035

### CODE REVIEW

**Comment by alalek** [comment]
Looks like the second issue is not related to this patch

**Comment by alalek** [comment]
IMHO, In debug mode we should raise more errors than in release mode, instead of "eating" them.

**Comment by LaurentBerger** [comment]
I'm agree in debug we should raise more errors than in release mode. Now this exception does not happen on linux or in release mode using VS 2012-2013-2015.

If you tell me where is this error in detect_mser.cpp or give me a program using opencv and opengl (in 3D) no problem. I am not sure that in viz this part of code is used.

**Comment by LaurentBerger** [comment]
Sorr I have found error (with @berak help) function glTexEnvi was the problem in detect_mser sample.

File: samples/cpp/detect_mser.cpp [hunk 1]
```diff
@@ -271,7 +271,6 @@ static void DrawOpenGLMSER(Mat img, Mat result)
     data->tex.bind();
 
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
-    glTexEnvi(GL_TEXTURE_2D, GL_TEXTURE_ENV_MODE, GL_REPLACE);
```
Comment (alalek) [inline samples/cpp/detect_mser.cpp]: Probably this should work:
```
glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE);
```

Comment (LaurentBerger) [inline samples/cpp/detect_mser.cpp]: bingo 👍

**Comment by alalek** [comment]
:+1:

**Comment by LaurentBerger** [comment]
Sorry for typo in my comment

File: samples/cpp/detect_mser.cpp (hunk 1 above)
Comment (kebiro) [reply samples/cpp/detect_mser.cpp]: 👍👍👍
