### PR TITLE
dnn: fix processing of input shapes

### LINKED ISSUE #16618: DNN: network loading should not initialize inputs
Test code:

```.cpp
    // 1. load network
    const string proto = findDataFile("dnn/bvlc_alexnet.prototxt");
    const string model = findDataFile("dnn/bvlc_alexnet.caffemodel", false);
    Net net = readNetFromCaffe(proto, model);

    // 2. mistake: no inputs are specified through .setInput()

    // 3. try inference
    Mat res;
    EXPECT_THROW(
    {
        res = net.forward();  // no inputs after loading => should fail
    }, cv::Exception);
    EXPECT_TRUE(res.empty()) << res.size;
```

### PR DESCRIPTION
**Pull request by alalek**
resolves #16618

- ~~importer(caffe): fix `net.input_dim` handling~~ (moved to #16617)
- importers: avoid using of `setInput()` => `setInputShape()`
- setInput(): shape limitation check (partial)

<cut/>

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2020.1.0:16.04
build_image:Custom Win=openvino-2020.1.0
build_image:Custom Mac=openvino-2020.1.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by dkurt** [comment]
@alalek, I think that it's better to experiment with this feature on master branch. Because it's actually used there and we decided to backport to 3.4 branch just to make it easier for merging.

File: modules/dnn/test/test_misc.cpp [hunk 1]
```diff
@@ -78,6 +78,65 @@ TEST(readNet, Regression)
     EXPECT_FALSE(net.empty());
 }
 
+TEST(readNet, do_not_call_setInput)  // https://github.com/opencv/opencv/issues/16618
+{
+    // 1. load network
+    const string proto = findDataFile("dnn/bvlc_alexnet.prototxt");
+    const string model = findDataFile("dnn/bvlc_alexnet.caffemodel", false);
```
Comment (dkurt) [inline modules/dnn/test/test_misc.cpp]: Let's replace to smaller squeezenet

File: modules/dnn/test/test_misc.cpp [hunk 2]
```diff
@@ -78,6 +78,65 @@ TEST(readNet, Regression)
     EXPECT_FALSE(net.empty());
 }
 
+TEST(readNet, do_not_call_setInput)  // https://github.com/opencv/opencv/issues/16618
+{
+    // 1. load network
+    const string proto = findDataFile("dnn/dnn/squeezenet_v1.1.prototxt");
+    const string model = findDataFile("dnn/dnn/squeezenet_v1.1.caffemodel", false);
```
Comment (dkurt) [inline modules/dnn/test/test_misc.cpp]: extra `dnn`
