### PR TITLE
TFLite fixes for Face Blendshapes V2

### LINKED ISSUE #27211: tflite scalar support
### Describe the feature and motivation

on 4.11, attempting to run the mediapipe [blendshape](https://storage.googleapis.com/mediapipe-assets/Model%20Card%20Blendshape%20V2.pdf) model (from the task [here](https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker)) fails on [this assert](https://github.com/opencv/opencv/blob/31b0eeea0b44b370fd0712312df4214d4ae1b158/modules/dnn/src/tflite/tflite_importer.cpp#L91) that a tensor has a shape.

the model runs correctly using the `tf.lite.Interpreter` in python. 

investigating the tensor shapes, this model has some entries with scalar values like ```{'name': 'model_1/GhumMarkerPoserMlpMixerGeneral/tf.math.truediv/truediv;model_1/GhumMarkerPoserMlpMixerGeneral/tf.math.truediv/truediv/y', 'index': 58, 'shape': array([], dtype=int32), 'shape_signature': array([], dtype=int32), 'dtype': <class 'numpy.float16'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}``` 

note `'shape_signature': array([], dtype=int32)` in particular. i don't see anything with an empty shape in other models that import correctly so i suspect this is the issue.

apparently this should be interpreted as a scalar. can the importer fall back to a [1] shape in these cases?

apologies if my analysis is wrong, or if this is considered a bug instead of a feature.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dkurt**
### Pull Request Readiness Checklist

* Scalars support
* Better handling of 1D tensors
* New ops import: SUB, SQRT, DIV, NEG, SQUARED_DIFFERENCE, SUM
* Number of NHWC<->NCHW layouts compatibility improvements

resolves #27211

**Merge with extra**: https://github.com/opencv/opencv_extra/pull/1257

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by dkurt** [comment]
@asmorkalov can you please check [macOS-ARM64-Vulkan / BuildAndTest](https://github.com/opencv/opencv/actions/runs/15013883922/job/42187483077?pr=27307#logs) ?
```
Run DOWNLOAD_MODELS_FILE='download_models.py'
Updating DNN models list
This script requires 'requests' library
Error: Process completed with exit code 13.
```

**Comment by asmorkalov** [comment]
cc @avdivan

**Comment by asmorkalov** [comment]
CUDA:
```
[ RUN      ] Test_TFLite.face_blendshapes/0, where GetParam() = CUDA/CUDA
unknown file: Failure
C++ exception with description "OpenCV(4.12.0-dev) /home/ci/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:43: error: (-215:Assertion failed) is_shape_same(dest, src) in function 'copy'
" thrown in the test body.
[  FAILED  ] Test_TFLite.face_blendshapes/0, where GetParam() = CUDA/CUDA (43 ms)
[ RUN      ] Test_TFLite.face_blendshapes/1, where GetParam() = CUDA/CUDA_FP16
unknown file: Failure
C++ exception with description "OpenCV(4.12.0-dev) /home/ci/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/tensor_ops.hpp:43: error: (-215:Assertion failed) is_shape_same(dest, src) in function 'copy'
" thrown in the test body.
[  FAILED  ] Test_TFLite.face_blendshapes/1, where GetParam() = CUDA/CUDA_FP16 (50 ms)
```

File: modules/dnn/src/legacy_backend.hpp [hunk 1]
```diff
@@ -213,6 +213,7 @@ struct BlobManager
             {
                 reuse(bestBlobPin, lp);
                 dst = bestBlob.reshape(1, 1).colRange(0, targetTotal).reshape(1, shape);
+                dst.dims = shape.size();
```
Comment (dkurt) [inline modules/dnn/src/legacy_backend.hpp:216]: Probably, make sense to move to a separate PR?

Comment (dkurt) [reply modules/dnn/src/legacy_backend.hpp:216]: Works fine for now on 4.x

**Review by asmorkalov — APPROVED** [review]
