### PR TITLE
QRCodeDetector::decodeMulti() fixed invalid usage fixedType()

### LINKED ISSUE #19363: QRCodeDetector::decodeMulti() invalid usage of `.fixedType()`
`.fixedType()` should be used with external arguments only.

[Code](https://github.com/opencv/opencv/blame/7a790d0d353bcbe48f1d62fb917c787ab4185846/modules/objdetect/src/qrcode.cpp#L3596-L3605):
```
    vector<Mat> tmp_straight_qrcodes;
    if (straight_qrcode.needed())
    {
        for (size_t i = 0; i < straight_barcode.size(); i++)
        {
            Mat tmp_straight_qrcode;
            tmp_straight_qrcodes.push_back(tmp_straight_qrcode);
            straight_barcode[i].convertTo(((OutputArray)tmp_straight_qrcodes[i]),
                                             ((OutputArray)tmp_straight_qrcodes[i]).fixedType() ?
                                             ((OutputArray)tmp_straight_qrcodes[i]).type() : CV_32FC2);
```

relates #15338

### PR DESCRIPTION
**Pull request by rayonnant14**
**Merge with extra**: https://github.com/opencv/opencv_extra/pull/845

fix #19363

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/objdetect/src/qrcode.cpp [hunk 1]
```diff
@@ -3615,18 +3615,17 @@ bool QRCodeDetector::decodeMulti(
             for_copy.push_back(straight_barcode[i]);
     }
     straight_barcode = for_copy;
-    vector<Mat> tmp_straight_qrcodes;
-    if (straight_qrcode.needed())
+    if (straight_qrcode.needed() &&
+       (straight_barcode.size() > 0))
```
Comment (alalek) [inline modules/objdetect/src/qrcode.cpp:3619]: > `straight_barcode.size() > 0`

```
if (straight_qrcode.needed() && straight_barcode.size() == 0)
{
    straight_qrcode.release()
}
else if (...)
```

File: modules/objdetect/src/qrcode.cpp [hunk 2]
```diff
@@ -3615,18 +3615,17 @@ bool QRCodeDetector::decodeMulti(
...
         for (size_t i = 0; i < straight_barcode.size(); i++)
         {
-            Mat tmp_straight_qrcode;
-            tmp_straight_qrcodes.push_back(tmp_straight_qrcode);
-            straight_barcode[i].convertTo(((OutputArray)tmp_straight_qrcodes[i]),
-                                             ((OutputArray)tmp_straight_qrcodes[i]).fixedType() ?
-                                             ((OutputArray)tmp_straight_qrcodes[i]).type() : CV_32FC2);
+            straight_barcode[i].convertTo(tmp_straight_qrcodes[i],
+                                          straight_qrcode.fixedType() ?
+                                          straight_qrcode.type() : CV_32FC2);
```
Comment (alalek) [inline modules/objdetect/src/qrcode.cpp:3626]: > CV_32FC2

What is stored here?

Documentation says:

> The optional output vector of images containing rectified and binarized QR codes
> The optional output image containing rectified and binarized QR code

What is about simple tests for checking output parameter types?

Comment (alalek) [reply modules/objdetect/src/qrcode.cpp]: > binarized

https://en.wikipedia.org/wiki/Binary_image

Why do we need floating point type here? `8UC1` is enough.

File: modules/objdetect/src/qrcode.cpp [hunk 3]
```diff
@@ -2486,17 +2486,24 @@ cv::String QRCodeDetector::decode(InputArray in, InputArray points,
...
+    if(!ok && straight_qrcode.needed())
+    {
+        straight_qrcode.release();
+    }
+    else if (straight_qrcode.needed())
     {
         qrdec.getStraightBarcode().convertTo(straight_qrcode,
                                              straight_qrcode.fixedType() ?
-                                             straight_qrcode.type() : CV_32FC2);
+                                             straight_qrcode.type() : CV_8UC1);
```
Comment (alalek) [inline modules/objdetect/src/qrcode.cpp:2506]: Perhaps we should ignore this `.fixedType()` check and force `8UC1` only.
Exception would be raised in case of type mismatch (by `convertTo`).

The assertion check above about channels is not necessary too.

File: modules/objdetect/src/qrcode.cpp [hunk 4]
```diff
@@ -3615,18 +3635,22 @@ bool QRCodeDetector::decodeMulti(
...
-            straight_barcode[i].convertTo(((OutputArray)tmp_straight_qrcodes[i]),
-                                             ((OutputArray)tmp_straight_qrcodes[i]).fixedType() ?
-                                             ((OutputArray)tmp_straight_qrcodes[i]).type() : CV_32FC2);
+            straight_barcode[i].convertTo(tmp_straight_qrcodes[i],
+                                          straight_qrcode.fixedType() ?
+                                          straight_qrcode.type() : CV_8UC1);
         }
-        straight_qrcode.createSameSize(tmp_straight_qrcodes, CV_32FC2);
+        straight_qrcode.create(OutputArray(tmp_straight_qrcodes).size(),
+                               OutputArray(tmp_straight_qrcodes).type());
```
Comment (alalek) [inline modules/objdetect/src/qrcode.cpp:3653]: > `OutputArray(tmp_straight_qrcodes)`

No need to wrap into `OutputArray`.
You already have all necessary values.

File: modules/objdetect/src/qrcode.cpp (hunk 3 above)
Comment (rayonnant14) [reply modules/objdetect/src/qrcode.cpp:2506]: @alalek `convertTo` isn't raise a exception in case type or channel number mismatch, but there will be exception later `Mat::type() == traits::Type<_Tp>::value` if we don't use `.fixedType()` check.
By this reason, it is better to continue use assertion check about channels number and `.fixedType()` check

**Review by alalek — APPROVED** [review]
