### PR TITLE
fix peaky test failure

### LINKED ISSUE #19389: cudalegacy: test CUDA_Calib3D/SolvePnPRansac is peaky
##### System information (version)

- OpenCV => recent 3.4 ( 235e648bf5aa613b36f98bd84b7ee10a52aab40b ) /master/next
- Operating System / Platform => Jetson Xavier (Ubuntu 18.04)
- Compiler => GCC 7.5.0

##### Detailed description

```
[----------] 1 test from CUDA_Calib3D/SolvePnPRansac
[ RUN      ] CUDA_Calib3D/SolvePnPRansac.Accuracy/0, where GetParam() = Xavier
/mnt/sd/opencv-fork/modules/cudalegacy/test/test_calib3d.cpp:187: Failure
Expected: (cv::norm(tvec - tvec_gold)) <= (1e-3), actual: 0.11245 vs 0.001
[  FAILED  ] CUDA_Calib3D/SolvePnPRansac.Accuracy/0, where GetParam() = Xavier (286 ms)
[----------] 1 test from CUDA_Calib3D/SolvePnPRansac (286 ms total)
```

This test sometimes pass, sometimes fail.

```
[----------] 1 test from CUDA_Calib3D/SolvePnPRansac
[ RUN      ] CUDA_Calib3D/SolvePnPRansac.Accuracy/0, where GetParam() = Xavier
[       OK ] CUDA_Calib3D/SolvePnPRansac.Accuracy/0 (263 ms)
[----------] 1 test from CUDA_Calib3D/SolvePnPRansac (263 ms total)
```

Looking in the [test](https://github.com/opencv/opencv/blob/bbad38b2c51c78e71d3364814e58b1e6e887705a/modules/cudalegacy/test/test_calib3d.cpp#L166), it's generating 5000 points in [0:100] range
https://github.com/opencv/opencv/blob/bbad38b2c51c78e71d3364814e58b1e6e887705a/modules/cudalegacy/test/test_calib3d.cpp#L166
It's too dense for estimating the correspondence, so many false projection.
It only depends on seed whether the test fails or passes.
This patch will make the test more stable.

##### Steps to reproduce

```
GTEST_FILTER=CUDA_Calib3D/SolvePnPRansac*  ./bin/opencv_test_cudalegacy --gtest_repeat=-1
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by tomoaki0705**
closes #19389 

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4
build_image:Custom=ubuntu-cuda:18.04
```

### CODE REVIEW

File: modules/cudalegacy/test/test_calib3d.cpp [hunk 1]
```diff
@@ -184,7 +184,7 @@ CUDA_TEST_P(SolvePnPRansac, Accuracy)
                             rvec, tvec, false, 200, 2.f, 100, &inliers);
 
     ASSERT_LE(cv::norm(rvec - rvec_gold), 1e-3);
-    ASSERT_LE(cv::norm(tvec - tvec_gold), 1e-3);
+    ASSERT_LE(cv::norm(tvec - tvec_gold)/cv::norm(tvec_gold), 1e-3);
```
Comment (alalek) [inline modules/cudalegacy/test/test_calib3d.cpp:187]: > `cv::norm(tvec - tvec_gold)/cv::norm(tvec_gold)`

```
cv::norm(tvec, tvec_gold, NORM_L2 | NORM_RELATIVE);
```

**Review by alalek — APPROVED** [review]
