### PR TITLE
Replace System.exit(-1) with exceptions in HighGui.java (#28696)

### LINKED ISSUE #28696: HighGui.java: System.exit(-1) in library code should throw exceptions instead
HighGui.java calls System.exit(-1) in 3 places (imshow with empty image, waitKey without prior imshow, waitKey with null image). Library code should never call System.exit() as it kills the entire JVM. Should throw IllegalArgumentException or IllegalStateException instead. Also has printStackTrace() in InterruptedException catch block.

### PR DESCRIPTION
**Pull request by PDGGK**
## Summary

Library code should never call System.exit() as it kills the entire JVM. Replaced all 3 instances with appropriate exceptions.

Closes #28696

## Changes

- `imshow()` with empty image: `System.exit(-1)` -> `throw new IllegalArgumentException("Image is empty")`
- `waitKey()` with no windows: `System.exit(-1)` -> `throw new IllegalStateException("No windows created. Call imshow() first")`
- `waitKey()` with null window image: `System.exit(-1)` -> `throw new IllegalStateException("No image set for window: ... Call imshow() first")`
- `InterruptedException` catch: `printStackTrace()` -> `Thread.currentThread().interrupt()`

### CODE REVIEW

File: modules/highgui/misc/java/src/java/highgui+HighGui.java [hunk 1]
```diff
@@ -157,7 +154,7 @@ public static int waitKey(int delay) {
                 latch.await(delay, TimeUnit.MILLISECONDS);
             }
         } catch (InterruptedException e) {
-            e.printStackTrace();
```
Comment (asmorkalov) [inline modules/highgui/misc/java/src/java/highgui+HighGui.java:160]: I propose presume the original message printing:
```
e.printStackTrace();
```

**Comment by PDGGK** [comment]
Thanks @asmorkalov, done. Added back e.printStackTrace() for logcat visibility while keeping Thread.currentThread().interrupt() to restore the interrupt flag.
