### PR TITLE
 Fix issues in RISC-V Vector (RVV) Universal Intrinsic

### LINKED ISSUE #26936: Core_ConvertScale/ElemWiseTest.accuracy/0 test crashes with sigsegv on risc-v rvv with GCC 14.2
### System Information

The issue was introduced in https://github.com/opencv/opencv/pull/26804
Not visible with Debug and Release with Debug info, release ony

Device: spacemit muse pi v30
Compiler: gcc 14.2 (spacemit-toolchain-linux-glibc-x86_64-v1.0.4)

### Detailed description

```
➜  cross-build gdb ./opencv_test_core 
GNU gdb (Bianbu 15.0.50.20240403-0ubuntu1bb2) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "riscv64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./opencv_test_core...
(gdb) run --gtest_filter="*Scale*"
Starting program: /home/opencv/cross-build/opencv_test_core --gtest_filter="*Scale*"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/riscv64-linux-gnu/libthread_db.so.1".
CTEST_FULL_OUTPUT
OpenCV version: 4.12.0-dev
OpenCV VCS version: 4.11.0-146-g680fd4d975-dirty
Build type: Release
Compiler: /mnt/Projects/spacemit/spacemit-toolchain-linux-glibc-x86_64-v1.0.4/bin/riscv64-unknown-linux-gnu-g++  (ver 14.2.1)
Algorithm hint: ALGO_HINT_ACCURATE
HAL: YES (HAL RVV (ver 0.0.1))
Parallel framework: pthreads (nthreads=8)
CPU features: RVV
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = *Scale*
[==========] Running 4 tests from 4 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Core_ConvertScale/ElemWiseTest
[ RUN      ] Core_ConvertScale/ElemWiseTest.accuracy/0, where GetParam() = 16-byte object <F0-99 5F-00 00-00 00-00 70-9B 5F-00 00-00 00-00>

Program received signal SIGSEGV, Segmentation fault.
0x0000003ff74994ea in cv::cpu_baseline::cvtScale8s64f(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*) () from /home/opencv/cross-build/libopencv_core.so.412
(gdb) bt
#0  0x0000003ff74994ea in cv::cpu_baseline::cvtScale8s64f(unsigned char const*, unsigned long, unsigned char const*, unsigned long, unsigned char*, unsigned long, cv::Size_<int>, void*) () from /home/opencv/cross-build/libopencv_core.so.412
#1  0x0000003ff74942f4 in cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const () from /home/opencv/cross-build/libopencv_core.so.412
#2  0x000000000006bc84 in opencv_test::(anonymous namespace)::ConvertScaleOp::op(std::vector<cv::Mat, std::allocator<cv::Mat> > const&, cv::Mat&, cv::Mat const&) ()
#3  0x0000000000089b02 in opencv_test::(anonymous namespace)::ElemWiseTest_accuracy_Test::Body() ()
#4  0x0000000000089f46 in opencv_test::(anonymous namespace)::ElemWiseTest_accuracy_Test::TestBody() ()
#5  0x000000000043ab4c in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#6  0x000000000043ad24 in testing::Test::Run() ()
#7  0x000000000043af62 in testing::TestInfo::Run() ()
#8  0x000000000043afe4 in testing::TestCase::Run() ()
#9  0x000000000043b5fe in testing::internal::UnitTestImpl::RunAllTests() ()
#10 0x000000000043b72a in testing::UnitTest::Run() ()
#11 0x000000000004c5a8 in main ()
```

### Steps to reproduce

```
opencv_test_core --gtest_filter="*Scale*"
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by hanliutong**
This PR aims to make `opencv_test_core` pass on RVV, via following two parts:

1. Fix bug in Universal Intrinsic when VLEN >= 512:
- `max_nlanes` should be multiplied by 2, because we use LMUL=2 in RVV Universal Intrinsic since #26318.
- Related tests are also expanded to match longer registers
- Relax the precision threshold of `v_erf` to make the tests pass

2. Temporary fix  #26936
- Disable 3 Universal Intrinsic code blocks on GCC
- This is just a temporary fix until we figure out if it's our issue or GCC/something else's

This patch is tested under the following conditions:
- Compier: GCC 14.2, Clang 19.1.7
- Device: Muse-Pi (VLEN=256), QEMU (VLEN=512, 1024)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
I confirm that item 2 has been resolved.

**Comment by asmorkalov** [comment]
@hanliutong Please take a look on warnings with MS Visual Studio.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
@fengyuentau Please take a look too.

File: modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp [hunk 1]
```diff
@@ -1594,19 +1595,27 @@ static uint64_t idx_interleave_pairs[] = { \
...
+    0xa7a3a6a2a5a1a4a0, 0xafabaeaaada9aca8, 0xb7b3b6b2b5b1b4b0, 0xbfbbbebabdb9bcb8, \
+    0xc7c3c6c2c5c1c4c0, 0xcfcbcecacdc9ccc8, 0xd7d3d6d2d5d1d4d0, 0xdfdbdedaddd9dcd8, \
+    0xe7e3e6e2e5e1e4e0, 0xefebeeeaede9ece8, 0xf7f3f6f2f5f1f4f0, 0xfffbfefafdf9fcf8};
 
 #define OPENCV_HAL_IMPL_RVV_INTERLEAVED_PQ_NOEXPEND(_Tpvec, func) \
 inline _Tpvec v_interleave_##func(const _Tpvec& vec) { \
     CV_CheckLE(VTraits<_Tpvec>::vlanes(), VTraits<_Tpvec>::max_nlanes, "RVV implementation only supports VLEN in the range [128, 1024]"); \
     vuint8m2_t vidx = __riscv_vundefined_u8m2();\
-    vidx = __riscv_vreinterpret_u8m2(__riscv_vle64_v_u64m2(idx_interleave_##func, 16)); \
+    vidx = __riscv_vreinterpret_u8m2(__riscv_vle64_v_u64m2(idx_interleave_##func, 32)); \
```
Comment (fengyuentau) [inline modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp:1618]: What about using std::array to store `idx_interleave_quads` so that we can get array length instead of a fixed number here to avoid mistakes.

Comment (hanliutong) [reply modules/core/include/opencv2/core/hal/intrin_rvv_scalable.hpp]: Updated

**Comment by fengyuentau** [comment]
As for https://github.com/opencv/opencv/issues/26936, most probably it is due to gcc because I did not see the problem with clang.

```
OpenCV version: 4.12.0-dev
OpenCV VCS version: 4.11.0-174-gdbd3ef9a6f
Build type: Release
Compiler: /home/tao/workspace/fytao/k1/spacemit-toolchain-linux-glibc-x86_64-v1.0.4/bin/clang++  (ver 18.1.8)
Algorithm hint: ALGO_HINT_ACCURATE
HAL: YES (HAL RVV (ver 0.0.1))
Parallel framework: pthreads (nthreads=8)
CPU features: RVV
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
Note: Google Test filter = Core_ConvertScale/ElemWiseTest.accuracy/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from Core_ConvertScale/ElemWiseTest
[ RUN      ] Core_ConvertScale/ElemWiseTest.accuracy/0, where GetParam() = 16-byte object <20-89 9B-E9 2A-00 00-00 A0-8A 9B-E9 2A-00 00-00>
[       OK ] Core_ConvertScale/ElemWiseTest.accuracy/0 (2184 ms)
[----------] 1 test from Core_ConvertScale/ElemWiseTest (2184 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2186 ms total)
[  PASSED  ] 1 test.
```

File: modules/core/test/test_intrin_utils.hpp [hunk 2]
```diff
@@ -978,7 +986,11 @@ template<typename R> struct TheTest
         R l = dataB;
         dataB[1] = mask_one;
         dataB[VTraits<R>::vlanes() / 2] = mask_one;
-        dataC *= (LaneType)-1;
+        for (int i = 0; i < VTraits<R>::vlanes(); i++)
+        {
+            auto c_signed = dataC.as_int(i);
+            dataC[i] = (LaneType)(c_signed == 0 ? -1 : -std::abs(c_signed));
+        }
```
Comment (opencv-alalek) [inline modules/core/test/test_intrin_utils.hpp:993]: Why do we need to change that?

It is code for testing, all checks are below.

Comment (hanliutong) [reply modules/core/test/test_intrin_utils.hpp:993]: Because we need `dataC` to be all negative numbers, then `v_check_all(c)` will be `true`.
```
R c = dataC;
EXPECT_EQ(true, v_check_all(c));
```

The previous `dataC *= (LaneType)-1;` cannot handle the case where the length of `dataC` greater than `128` for `int_8`
