### PR TITLE
Take into account overflow for connected components

### LINKED ISSUE #27568: Opencv-python's connectedComponentsWithStats method segfaults
### System Information

Python 3.10.12, opencv-python 4.12.0.88, Ubuntu 22.04.

### Detailed description

See [this repository](https://github.com/AlexDFischer/opencv_bug_MWE/tree/master) for example code that causes a segfault with opencv-python's connectedComponentsWithStats method. This is with Python 3.10.12, opencv-python 4.12.0.88.

### Steps to reproduce

Clone [this repository](https://github.com/AlexDFischer/opencv_bug_MWE/tree/master). Using Python 3.10.12 and opencv-python 4.12.0.88, run `python connected_components_segfault.py`.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### Pull Request Readiness Checklist

Fix #27568 

The problem was caused by a label type overflow (`debug_example.npy` contains `92103` labels, that doesn't fit in the `CV_16U` (`unsigned short`) type). If pass `CV_32S` instead of `CV_16U` as `ltype` - everything will be calculated successfully

Added overflow detection to throw exception with a clear error message instead of strange segfault/assertion error

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/src/connectedcomponents.cpp [hunk 1]
```diff
@@ -261,13 +261,25 @@ namespace cv{
...
     inline static
-    void flattenL(LabelT *P, const int start, const int nElem, LabelT& k){
+    void checkLabelTypeOverflow(const LabelT numLabels) {
+        constexpr LabelT maxLabelTypeValue = std::numeric_limits<LabelT>::max();
+        if (numLabels == maxLabelTypeValue) {
+            CV_Error(
+                cv::Error::StsError,
+                "Total number of labels overflowed label type. Try using CV_32S instead of CV_16U as ltype");
+        }
+    }
```
Comment (asmorkalov) [inline modules/imgproc/src/connectedcomponents.cpp]: You can use `CV_CheckLE` instead of new function everywhere: https://docs.opencv.org/4.x/d1/d26/check_8hpp.html#a7b8e786a57dcee88dc0cae752adab921

**Comment by asmorkalov** [comment]
Thanks a lot for the contribution!

File: modules/imgproc/src/connectedcomponents.cpp (hunk 1 above)
Comment (MaximSmolskiy) [reply modules/imgproc/src/connectedcomponents.cpp]: I agree that it is better to use `CV_CheckLT` in the implementation of the new function (done). But I would prefer to use the new function everywhere instead of its implementation - it is shorter, clearer (the name of the function serves as a fairly clear comment) and if we, for example, want to change the error message in the future, then we will only need to do it in one place instead of `20`
