### PR TITLE
[G-API] Fix blocking desc usage

### LINKED ISSUE #19719: G-API: Python tests failed in builds with OpenVINO
Nightly builds with OpenVINO, like:
master_openvino-skl-lin64: [good](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/953) / [bad](http://pullrequest.opencv.org/buildbot/builders/master_openvino-skl-lin64/builds/954)
master_openvino-win64: [good](http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64/builds/661) / [bad](http://pullrequest.opencv.org/buildbot/builders/master_openvino-win64/builds/662) (crashed)

Test: `test_person_detection_retail_0013 (test_gapi_infer.test_gapi_infer)`

relates #19707

/cc @AsyaPronina @TolyaTalamanov @dbudniko

---

Run gapi tests only:

```
OPENCV_PYTEST_FILTER=test_gapi* ./setup_vars.sh python3 <opencv_dir>/modules/python/test/test.py -v --repo <opencv_dir>
```

### PR DESCRIPTION
**Pull request by TolyaTalamanov**
resolves #19719

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [ ] I agree to contribute to the project under Apache 2 License.
- [ ] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [ ] The PR is proposed to proper branch
- [ ] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### Build configuration
```
Xforce_builders_only=linux,docs
force_builders=Custom,Custom Win,Custom Mac
build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

Xbuild_image:Custom=centos:7
Xbuildworker:Custom=linux-1
build_gapi_standalone:Custom=ade-0.1.1f

build_image:Custom=ubuntu-openvino-2021.1.0:20.04
build_image:Custom Win=openvino-2021.1.0
build_image:Custom Mac=openvino-2021.2.0

test_modules:Custom=gapi,python2,python3,java
test_modules:Custom Win=gapi,python2,python3,java
test_modules:Custom Mac=gapi,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by TolyaTalamanov** [comment]
This going to fix: https://github.com/opencv/opencv/issues/19719

**Comment by TolyaTalamanov** [comment]
@AsyaPronina Could you have a look ?

File: modules/gapi/src/backends/ie/giebackend.cpp [hunk 1]
```diff
@@ -130,11 +130,10 @@ inline IE::TensorDesc toIE(const cv::Mat &mat, cv::gapi::ie::TraitAs hint) {
         const size_t height   = mat.size().height;
         const size_t width    = mat.size().width;
 
-        const size_t strideH  = mat.step[0];
-
-        IE::BlockingDesc bdesc({1, height, width, channels} /* dims */,
-                               {0, 2, 3, 1} /* order for NHWC */,
-                               0 /* offset */,
+        const size_t strideH  = mat.step1();
+        IE::BlockingDesc bdesc({1, channels, height, width} /* dims */,
```
Comment (TolyaTalamanov) [inline modules/gapi/src/backends/ie/giebackend.cpp:134]: BTW `{1, height, width, channels}` also works,    
 but I think it's a bit clearer, @AsyaPronina  what do you think ?

File: modules/gapi/src/backends/ie/giebackend.cpp [hunk 2]
```diff
@@ -130,11 +130,10 @@ inline IE::TensorDesc toIE(const cv::Mat &mat, cv::gapi::ie::TraitAs hint) {
...
+                               {0, 2, 3, 1} /* order for NHWC   */,
+                               0            /* offset           */,
                                {0, 0, 0, 0} /* offsets for dims */,
                                {strideH * height, strideH, channels, 1} /* strides for dims */);
```
Comment (alalek) [inline modules/gapi/src/backends/ie/giebackend.cpp:138]: > `{1, channels, height, width} /* dims */`
> ...
> `{strideH * height, strideH, channels, 1} /* strides for dims */`

Does `strides` correspond to `dims` after the change?

**Review by alalek — COMMENTED** [review]
It make sense to add C++ regression test for that case.

File: modules/gapi/src/backends/ie/giebackend.cpp [hunk 3]
```diff
@@ -130,11 +130,10 @@ inline IE::TensorDesc toIE(const cv::Mat &mat, cv::gapi::ie::TraitAs hint) {
         const size_t height   = mat.size().height;
         const size_t width    = mat.size().width;
 
-        const size_t strideH  = mat.step[0];
-
-        IE::BlockingDesc bdesc({1, height, width, channels} /* dims */,
-                               {0, 2, 3, 1} /* order for NHWC */,
-                               0 /* offset */,
+        const size_t strideH  = mat.step1();
```
Comment (TolyaTalamanov) [inline modules/gapi/src/backends/ie/giebackend.cpp:133]: @AsyaPronina we shouldn't consider the channel size in bytes, it's reason to use `step1()`

From OpenCV documentation:
```
Returns a normalized step.

The method returns a matrix step divided by Mat::elemSize1() . It can be useful to quickly access an arbitrary matrix element.
```

File: modules/gapi/src/backends/ie/giebackend.cpp (hunk 2 above)
Comment (TolyaTalamanov) [reply modules/gapi/src/backends/ie/giebackend.cpp:138]: Usually dims follow in logical order - `NCHW`, but strides describe actual layout.
The problem was in `step` we don't need to consider size of precision in bytes there.
For instance: CV_FLOAT32C3 - 3 elements in strides, but we used 3 * sizeof(float)

**Comment by TolyaTalamanov** [comment]
@AsyaPronina The fix is OK ?

File: modules/gapi/src/backends/ie/giebackend.cpp (hunk 1 above)
Comment (TolyaTalamanov) [reply modules/gapi/src/backends/ie/giebackend.cpp:134]: `{1, channels, height, width}` - the correct way

**Review by AsyaPronina — APPROVED** [review]

**Comment by AsyaPronina** [comment]
> @AsyaPronina The fix is OK ?

Yes, thanks!

**Comment by TolyaTalamanov** [comment]
@alalek Could you help with CI, please ?
https://pullrequest.opencv.org/buildbot/builders/precommit_custom_mac/builds/1791/steps/test_python3/logs/stdio

**Comment by alalek** [comment]
There is email notification about NCS2 stick in public CI (~1 week ago). The latest IE version should be used.

File: modules/gapi/src/backends/ie/giebackend.cpp (hunk 2 above)
Comment (alalek) [reply modules/gapi/src/backends/ie/giebackend.cpp:138]: @ilya-lavrenov Could you please take a look how to properly pass cv::Mat to `InferenceEngine` here? (or point to some example in IE / OMZ)

Comment (ilya-lavrenov) [reply modules/gapi/src/backends/ie/giebackend.cpp:138]: https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Memory_primitives.html

Code after the fix looks good to me

Comment (ilya-lavrenov) [reply modules/gapi/src/backends/ie/giebackend.cpp:138]: CC @ilyachur

File: modules/gapi/src/backends/ie/giebackend.cpp [hunk 4]
```diff
@@ -130,11 +130,10 @@ inline IE::TensorDesc toIE(const cv::Mat &mat, cv::gapi::ie::TraitAs hint) {
         const size_t height   = mat.size().height;
         const size_t width    = mat.size().width;
 
-        const size_t strideH  = mat.step[0];
-
-        IE::BlockingDesc bdesc({1, height, width, channels} /* dims */,
```
Comment (ilya-lavrenov) [inline modules/gapi/src/backends/ie/giebackend.cpp:135]: looks like the original code actually is correct in terms of order for "blocked_dims", they should come in actual order NHWC..

Comment (ilyachur) [reply modules/gapi/src/backends/ie/giebackend.cpp:135]: I agree. BlockedDims already describes the physical dimensions.
