### PR TITLE
Fix integer overflow when accumulating timing values

### LINKED ISSUE #13062: Overflow with cv::dnn:getPerfProfile() and Mask R-CNN or net with heavy computation
##### System information (version)

- OpenCV => 4.0
- Operating System / Platform => Ubuntu 16.04
- C++ or Python (tested with 2.7) API

##### Detailed description

I got negative time when doing `t, _ = net.getPerfProfile()`, probably due to some overflow.
For instance with the following code and Mask R-CNN:

```
    t, timings = net.getPerfProfile()
    print('timings: ', timings)
    print('Time: ', t)
```

<details>

```
[('timings: ', array([[  1.43855200e+06],
       [  0.00000000e+00],
       [  1.93971610e+07],
       [  1.68231050e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  8.22405800e+06],
       [  7.70376600e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.12977991e+08],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  3.99801700e+06],
       [  4.79644300e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.60207300e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.21372830e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.88668900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.63454220e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.28457170e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  8.19715800e+06],
       [  4.28057500e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.98936000e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.31075800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.40734300e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.09635000e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.66641690e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.27343810e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.02351840e+07],
       [  6.78569700e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.28528580e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.29219520e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.10055600e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.63075930e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.15953800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.02587400e+06],
       [  0.00000000e+00],
       [  9.42525300e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.03535000e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  4.12691800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.09282600e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  8.13403000e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.41161400e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  8.52772500e+06],
       [  6.43437900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  8.39615900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  4.37146800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.66095400e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.40581000e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.41835600e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.08300940e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.70878900e+06],
       [  6.01560900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.14861300e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.88400700e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.31348580e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.98565200e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.15182740e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.60748620e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.22338300e+06],
       [  7.19830500e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.71430100e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.88507200e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.43548450e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.10908180e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.64944960e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.31598280e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.58423000e+06],
       [  5.00148100e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.79180254e+08],
       [  0.00000000e+00],
       [  3.16105900e+06],
       [  2.23494700e+06],
       [  4.17640000e+04],
       [  3.24400000e+03],
       [  1.75692300e+06],
       [  5.03600000e+03],
       [  1.14520000e+05],
       [  1.93400000e+03],
       [  6.22106000e+05],
       [  1.64251840e+07],
       [  8.82333970e+07],
       [  1.84622300e+07],
       [  1.07359590e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.52966700e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.78198990e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  6.11532960e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.69601030e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.35121490e+07],
       [  1.47499700e+06],
       [  1.76437720e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.50354900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.20174680e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.60298800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.41354430e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.94369810e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.92150090e+07],
       [  6.19933400e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.39004000e+06],
       [  1.79984800e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.75278500e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.07695720e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.15495520e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.59443640e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.94263710e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.73803340e+07],
       [  8.34701900e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.87942500e+06],
       [  2.45312100e+06],
       [  4.84470000e+04],
       [  4.71200000e+03],
       [  2.01616500e+06],
       [  3.79837000e+05],
       [  2.71100000e+03],
       [  1.82900000e+03],
       [  2.21017000e+05],
       [  1.49070000e+04],
       [  2.76100000e+03],
       [  9.88200000e+03],
       [  3.01038600e+06],
       [  2.08100000e+03],
       [  1.32900000e+03],
       [  1.05262900e+06],
       [  8.65640300e+06],
       [  2.14184450e+07],
       [  1.44702370e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  7.94102800e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.28856140e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  5.98875620e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.64981910e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.01399180e+07],
       [  1.47576500e+06],
       [  1.66904690e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.07886200e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.24092380e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.06620590e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.41386920e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.84327800e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.00946370e+07],
       [  6.21078500e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.61859300e+06],
       [  1.67167510e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  9.26616700e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  2.28260600e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.03624260e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.67093050e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.78635120e+07],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.75464790e+07],
       [  8.03819200e+06],
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  1.41180600e+06],
       [  3.34893971e+08],
       [  1.56801818e+09],
       [  0.00000000e+00],
       [  1.35115682e+08],
       [  9.13400000e+03],
       [  1.41345690e+07]]))
('Time: ', -1998224263L)
```
</details>

##### Steps to reproduce

<!-- to add code example fence it with triple backticks and optional file extension
    ```.cpp
    // C++ code example
    ```](url)
 or attach as .txt or .zip file
-->
Run `mask_rcnn.py` or `openpose.py` in dnn sample directory since the computation is heavy, either using C++ or Python.

### PR DESCRIPTION
**Pull request by catree**
resolves #13062

### CODE REVIEW

File: modules/dnn/src/dnn.cpp [hunk 1]
```diff
@@ -3074,7 +3074,7 @@ void Net::setHalideScheduler(const String& scheduler)
 int64 Net::getPerfProfile(std::vector<double>& timings)
 {
     timings = std::vector<double>(impl->layersTimings.begin() + 1, impl->layersTimings.end());
-    int64 total = std::accumulate(timings.begin(), timings.end(), 0);
+    int64 total = std::accumulate(timings.begin(), timings.end(), (int64)0);
```
Comment (alalek) [inline modules/dnn/src/dnn.cpp]: May be accumulate in 'doubles'?
```
int64 total = (int64)std::accumulate(timings.begin(), timings.end(), 0.0);
```

Comment (catree) [reply modules/dnn/src/dnn.cpp]: Yes you are right.
