### PR TITLE
kmeans: number of channels in _centers fixed

### LINKED ISSUE #10174: samples/cpp/kmeans.cpp: Invalid layout of "center"
Sample code expects `CV_32FC2` type, but it is CV_32FC1 with 2 cols.

Reproduced in Debug build only (catched by `CV_DbgAssert()`).

```
        for (i = 0; i < centers.rows; ++i)
        {
            Point2f c = centers.at<Point2f>(i);     // <=== problem is here
            circle( img, c, 40, colorTab[i], 1, LINE_AA );
        }
```

Changing declaration of centers:
```.diff
-Mat centers;
+std::vector<Point2f> centers;
```
doesn't work (exception during `kmeans()` call).
Perhaps we should support this implicit conversion (via reshape).

### PR DESCRIPTION
**Pull request by savuor**
resolves #10174

### CODE REVIEW

File: modules/core/src/kmeans.cpp [hunk 1]
```diff
@@ -458,7 +458,11 @@ double cv::kmeans( InputArray _data, int K,
         {
             best_compactness = compactness;
             if( _centers.needed() )
+            {
+                if(_centers.channels() == dims)
```
Comment (terfendail) [inline modules/core/src/kmeans.cpp]: It looks like the function allow to pass complex configuration of input points since in L239 `int dims = (isrow ? 1 : data0.cols)*data0.channels()`. IMHO it should be possible for the user to provide the same configuration for the `OutputArray _centers`

Comment (savuor) [reply modules/core/src/kmeans.cpp]: This makes sense, will be implemented

File: modules/core/src/kmeans.cpp [hunk 2]
```diff
@@ -458,7 +458,14 @@ double cv::kmeans( InputArray _data, int K,
         {
             best_compactness = compactness;
             if( _centers.needed() )
-                centers.copyTo(_centers);
+            {
+                Mat reshaped = centers;
+                if(_centers.rows() == 1 && _centers.channels() == dims)
```
Comment (vpisarev) [inline modules/core/src/kmeans.cpp]: the fix is incorrect. The function behavior should not be dependent on the current shape of the output array. Instead, you should check whether the output array (`_centers`) has the fixed type (e.g. when `_centers` is `std::vector<someT>`) or not.

Comment (savuor) [reply modules/core/src/kmeans.cpp]: Done.
But we need to check actual `channels()` number (which shouldn't depend on current shape of array).
