### PR TITLE
Fixing imread() function 16 bit APNG reading problem

### LINKED ISSUE #27073: imread() function APNG reading problem
### System Information

OpenCV 4.12.0-dev

### Detailed description

`img = cv.imread("033.png",cv.IMREAD_UNCHANGED)` successfully read the APNG image but cv.IMREAD_GRAYSCALE and cv.IMREAD_COLOR fails.

### Steps to reproduce

using test image https://github.com/onevcat/APNGKit/blob/master/Tests/APNGKitTests/Resources/SpecTesting/033.png
```
import cv2 as cv

img = cv.imread("033.png",cv.IMREAD_UNCHANGED)
print(cv.imwrite("033_0.png", img))

img = cv.imread("033.png",cv.IMREAD_GRAYSCALE)
if not img is None:
    print(cv.imwrite("033_0.png", img))

img = cv.imread("033.png",cv.IMREAD_COLOR)
if not img is None:
    print(cv.imwrite("033_0.png", img))
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by sturkmen72**
closes #27073
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgcodecs/test/test_animation.cpp [hunk 1]
```diff
@@ -638,4 +638,42 @@ TEST(Imgcodecs_APNG, imencode_animation)
...
+    EXPECT_FALSE(img.empty());
+    EXPECT_TRUE(img.type() == CV_16UC4);
+    EXPECT_EQ(0,     img.at<ushort>(0, 0));
+    EXPECT_EQ(0,     img.at<ushort>(0, 1));
+    EXPECT_EQ(65280, img.at<ushort>(0, 2));
+    EXPECT_EQ(65535, img.at<ushort>(0, 3));
+
+    img = imread(filename, IMREAD_GRAYSCALE);
+    EXPECT_FALSE(img.empty());
+    EXPECT_TRUE(img.type() == CV_8UC1);
```
Comment (vrabaud) [inline modules/imgcodecs/test/test_animation.cpp:659]: Is 033.png 16 bit or 8 bit? Asking for grayscale should keep the depth

Comment (sturkmen72) [reply modules/imgcodecs/test/test_animation.cpp:659]: 033.png is `CV_16UC4`

IMREAD_GRAYSCALE converts it to `CV_8UC1` by default.

let me check `IMREAD_GRAYSCALE | IMREAD_ANYDEPTH`

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@vrabaud Do you have any issues with the solution? I want to merge the pr.

**Comment by sturkmen72** [comment]
Note: There is a bug in grfmt_spng.cpp about reading 16 bit png images. I will provide a fix later.

**Review by vrabaud — APPROVED** [review]
@asmorkalov LGTM now
