### PR TITLE
Restored legacy intrinsics operators in a separate header

### LINKED ISSUE #27267: hal_intrinsics operators breakage in 4.11
### System Information

System: Ubuntu x64 20.04 but not really matter
gcc 9.3

### Detailed description

4.11 breaks backward compatibility for `hal/intrin.hpp`

### Steps to reproduce

Sample code
```
#include <opencv2/core/hal/intrin.hpp>
#include <iostream>
int main()
{
        cv::v_float32x4 x=cv::v_setall_f32(1.0f);
        cv::v_float32x4 y=cv::v_setall_f32(2.0f);
        cv::v_float32x4 z=x+y;
        std::cout << z.get0() << std::endl;
}

```

Using OpenCV 4.10 and below:

```
$ g++ -I /path/to/opencv4.10/opencv4 -O2 -g -Wall test.cpp 
$ ./a.out
3
```

Using OpenCV 4.11

```
$ g++ -I /path/to/opencv4.11/opencv4 -O2 -g -Wall test.cpp 
test.cpp: In function 'int main()':
test.cpp:7:21: error: no match for 'operator+' (operand types are 'cv::hal_baseline::v_float32x4' and 'cv::hal_baseline::v_float32x4')
    7 |  cv::v_float32x4 z=x+y;
      |                    ~^~
      |                    | |
      |                    | cv::hal_baseline::v_float32x4
      |                    cv::hal_baseline::v_float32x4

```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by mshabunin**
resolves #27267

* New header with removed universal intrinsics operator overloads must be included manually by the user if necessary. Transition to operator-less API is recommended.
* Basic compilation test can be performed by defining OPENCV_ENABLE_INLINE_INTRIN_OPERATOR_TEST macro before header inclusion. It is not meant to be run
* shift operators have not been defined due to potential conflicts with io streams
* safety checks for opencv build, opencv version and risc-v platform would produce compiler warnings and errors

### CODE REVIEW

File: modules/core/include/opencv2/core/hal/intrin_legacy_ops.h [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+#error "Universal Intrinsics operators are deprecated and should not be used in OpenCV library"
+#endif
+
+#ifdef __riscv
+#warning "Operators might conflict with built-in functions on RISC-V platform"
+#endif
+
+#if defined(CV_VERSION) && CV_VERSION_MAJOR == 4 && CV_VERSION_MINOR < 11
+#warning "Older versions of OpenCV (<4.11) already have Universal Intrinscs operators"
+#endif
```
Comment (s-trinh) [inline modules/core/include/opencv2/core/hal/intrin_legacy_ops.h:22]: It is only since OpenCV 4.11 the Universal Intrinscs operators have been removed?

I don't understand, I had to [fix some code](https://github.com/lagadic/visp/commit/9ed0300507e13dddd83fd62a799f5039025ea44e) since OpenCV 4.9 release.

https://github.com/opencv/opencv/pull/24371

Comment (asmorkalov) [reply modules/core/include/opencv2/core/hal/intrin_legacy_ops.h:22]: Thanks a lot for the feedback. The operator overload was removed due to problems with RISC-V platform. The header with overloaded operators was added for compatibility on previously supported platforms (we have such issue report). You do not need to touch your code. v_xxx functions is the way to go further.

**Review by asmorkalov — APPROVED** [review]

File: modules/core/include/opencv2/core/hal/intrin_legacy_ops.h (hunk 1 above)
Comment (mshabunin) [reply modules/core/include/opencv2/core/hal/intrin_legacy_ops.h:22]: @s-trinh , you are right. Operators has been removed from AArch64 backend since 4.9 and from other backends since 4.11.
