### PR TITLE
fix for the issue #27456

### LINKED ISSUE #27456: WebPDecoder::readData() potential use of uninitialized variable
### System Information

OpenCV 4.11.0

### Detailed description

In the following code [https://github.com/sturkmen72/opencv/blob/538b99f9f3e3b89cfdc363f8afc7ad4cf21b0ba0/modules/imgcodecs/src/grfmt_webp.cpp](https://github.com/sturkmen72/opencv/blob/538b99f9f3e3b89cfdc363f8afc7ad4cf21b0ba0/modules/imgcodecs/src/grfmt_webp.cpp)

/grfmt_webp.cpp)

```
bool WebPDecoder::readData(Mat &img)
{
    ...
    if (m_has_animation)
    {
        uint8_t* buf;
        int timestamp;

        WebPAnimDecoderGetNext(anim_decoder.get(), &buf, &timestamp);
        Mat tmp(Size(m_width, m_height), CV_8UC4, buf);
        ...
```

`buf` and `timestamp` can remain uninitialized if `WebPAnimDecoderGetNext()` fails.
`buf` should be checked before going any further.

### Steps to reproduce

Compiling with VIsual studio raises a warning about potential use of uninitialized variable

### Issue submission checklist

- [x] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by sturkmen72**
closes #27456
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by chacha21** [comment]
To silent compiler warnings, buf and timestamp could still be initialized to 0.

**Comment by sturkmen72** [comment]
> To silent compiler warnings, buf and timestamp could still be initialized to 0.

(ChatGPT)
✅ Conclusion
No problem with uninitialized variables here.
The variables are correctly assigned before use.
You could optionally zero-initialize them for clarity or to appease static analysis tools, but it's not functionally necessary.

**Comment by vrabaud** [comment]
Thx for fixing this. libwebp should be compiled with -DWEBP_ENABLE_NODISCARD.
Can you please also fix the following lines (the line numbers might be slightly off):
```
modules/imgcodecs/src/grfmt_webp.cpp:158:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  158 |         WebPAnimDecoderOptionsInit(&dec_options);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~
modules/imgcodecs/src/grfmt_webp.cpp:165:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  165 |         WebPAnimDecoderGetInfo(anim_decoder.get(), &anim_info);
      |         ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/imgcodecs/src/grfmt_webp.cpp:219:9: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  219 |         WebPAnimDecoderGetNext(anim_decoder.get(), &buf, &timestamp);
      |         ^~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
modules/imgcodecs/src/grfmt_webp.cpp:449:5: error: ignoring return value of function declared with 'nodiscard' attribute [-Werror,-Wunused-result]
  449 |     WebPEncode(&config, &pic);
```

**Comment by vrabaud** [comment]
LGTM, thx ! @asmorkalov , FYI

**Comment by asmorkalov** [comment]
Hm, the binary check is not enough. It breaks some of existing tests:
```
[ RUN      ] Encode_multi.multi/3, where GetParam() = ".webp"
[ERROR:0@13.871] global loadsave.cpp:1029 imwrite_ imwrite_('test.webp'): can't write data: OpenCV(4.12.0-dev) /home/ci/opencv/modules/imgcodecs/src/grfmt_webp.cpp:453: error: (-3:Internal error) Failed to encode animated WebP frame in function 'writeanimation'

/home/ci/opencv/modules/imgcodecs/perf/perf_decode_encode.cpp:119: Failure
Value of: imwrite("test" + GetParam(), vec)
  Actual: false
Expected: true
[ERROR:0@13.876] global loadsave.cpp:1529 imencode imencode(): can't encode data: OpenCV(4.12.0-dev) /home/ci/opencv/modules/imgcodecs/src/grfmt_webp.cpp:453: error: (-3:Internal error) Failed to encode animated WebP frame in function 'writeanimation'

  Encoded buffer size: 0 bytes, Compression ratio: 0.00%
params    =     ".webp"
termination reason:  reached maximum number of iterations
bytesIn   =          0
bytesOut  =          0
samples   =          1
outliers  =          0
frequency = 1000000000
min       =    4555828 = 4.56ms
median    =    4555828 = 4.56ms
gmean     =    4555828 = 4.56ms
gstddev   = 0.00000000 = 0.00ms for 97% dispersion interval
mean      =    4555828 = 4.56ms
stddev    =          0 = 0.00ms
[  FAILED  ] Encode_multi.multi/3, where GetParam() = ".webp" (59 ms)
```

File: modules/imgcodecs/src/grfmt_webp.cpp [hunk 1]
```diff
@@ -446,7 +449,8 @@ bool WebPEncoder::writeanimation(const Animation& animation, const std::vector<i
     pic.height = height;
     pic.use_argb = 1;
     pic.argb_stride = width;
-    WebPEncode(&config, &pic);
+    if (!WebPEncode(&config, &pic))
```
Comment (vrabaud) [inline modules/imgcodecs/src/grfmt_webp.cpp]: That encode is actually useless right?

**Review by asmorkalov — APPROVED** [review]
