### PR TITLE
added note about BORDER_WRAP in separable filters; fixed SGBMStereo description

### LINKED ISSUE #9392: Reference to non-existent parameter name in documentation of StereoSGBM::create
##### System information (version)
- OpenCV => 3.3
- Operating System / Platform => -
- Compiler => -

##### Detailed description

The documentation for [StereoSGBM::create](http://docs.opencv.org/3.3.0/d2/d85/classcv_1_1StereoSGBM.html#adb7a50ef5f200ad9559e9b0e976cfa59) mentions `SADWindowSize` which is not a parameter of the constructor:

> See stereo_match.cpp sample where some reasonably good P1 and P2 values are shown (like 8\*number_of_image_channels\*SADWindowSize\*SADWindowSize and 32\*number_of_image_channels\*SADWindowSize\*SADWindowSize , respectively).

I suppose that is due to the fact that the parameter `blockSize` was called `SADWindowSize` in OpenCV 2.4.0 (cf. http://docs.opencv.org/2.4.0/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#stereosgbm-stereosgbm). Maybe the documentation in the current version should be updated to avoid confusion. This seems to have been introduced with OpenCV 3.0.

##### Steps to reproduce

Replace `SADWindowSize` with `blocksize` in the documentation of `StereoSGBM::create`.

### LINKED ISSUE #13602: GaussianBlur does not support border type wrap
##### System information (version)

- OpenCV => 4.0.1
- Operating System / Platform => All
- Compiler => All

##### Detailed description

In the documentation for GaussianBlur() it is stated that one should use one of the options in BorderTypes. However, the WRAP option is not supported and will lead to an exception. 

##### Steps to reproduce

Run GaussianBlur with border type WRAP

### PR DESCRIPTION
**Pull request by vpisarev**
resolves #13602
resolves #9392

### CODE REVIEW

File: modules/imgproc/include/opencv2/imgproc.hpp [hunk 1]
```diff
@@ -1409,7 +1409,7 @@ equal to sigmaX, if both sigmas are zeros, they are computed from ksize.width an
 respectively (see #getGaussianKernel for details); to fully control the result regardless of
 possible future modifications of all this semantics, it is recommended to specify all of ksize,
 sigmaX, and sigmaY.
-@param borderType pixel extrapolation method, see #BorderTypes
+@param borderType pixel extrapolation method, see #BorderTypes. BORDER_WRAP is not supported.
```
Comment (alalek) [inline modules/imgproc/include/opencv2/imgproc.hpp]: Please use `#` to force links generation.
