### PR TITLE
Fixed issue in ORB detection if firstLevel property is set above 0

### LINKED ISSUE #10561: `ORB::setFirstLevel(i>0)` causes a crash
##### System information (version)
- OpenCV => 3.4.0-dev
- Operating System / Platform => ALL
- Compiler => ALL

##### Detailed description
Cannot set the first level in the ORB detector to any value other than zero.
Setting it to any positive number `i` is supposed to make all octaves below `i` enlarged, rather than 
the usual shrinkage (similar to SIFT negative octaves).

##### Steps to reproduce
```.c++
vector<KeyPoint> kps;
Mat img = imread("any_image.png"), descs;
Ptr<ORB> orb = ORB::create();

orb->setFirstLevel(1); // <- Crash ahead!
orb->detectAndCompute(img, noArray(), kps, descs);
```

##### Actual result
CRASH!

### PR DESCRIPTION
**Pull request by terfendail**
resolves #10561

### This pullrequest changes
Fixed pyramid buffer size to allow retaining of upscaled images. Updated pyramid evaluation to perform image upscaling if necessary.

### CODE REVIEW

File: modules/features2d/include/opencv2/features2d.hpp [hunk 1]
```diff
@@ -304,10 +304,11 @@ class CV_EXPORTS_W ORB : public Feature2D
     will mean that to cover certain scale range you will need more pyramid levels and so the speed
     will suffer.
     @param nlevels The number of pyramid levels. The smallest level will have linear size equal to
-    input_image_linear_size/pow(scaleFactor, nlevels).
+    input_image_linear_size/pow(scaleFactor, nlevels - firstLevel).
     @param edgeThreshold This is size of the border where the features are not detected. It should
     roughly match the patchSize parameter.
-    @param firstLevel It should be 0 in the current implementation.
+    @param firstLevel The level of pytramid to put source image to. Previous layers are filled
+    with upscaled source image.
```
Comment (alalek) [inline modules/features2d/include/opencv2/features2d.hpp]: please fix typo here

File: modules/features2d/src/orb.cpp [hunk 2]
```diff
@@ -673,7 +673,7 @@ class ORB_Impl : public ORB
     void setEdgeThreshold(int edgeThreshold_) { edgeThreshold = edgeThreshold_; }
     int getEdgeThreshold() const { return edgeThreshold; }
 
-    void setFirstLevel(int firstLevel_) { firstLevel = firstLevel_; }
+    void setFirstLevel(int firstLevel_) { CV_Assert(firstLevel >= 0);  firstLevel = firstLevel_; }
```
Comment (alalek) [inline modules/features2d/src/orb.cpp]: Parameter name contains underscore: `firstLevel_`, assertion - doesn't.

**Comment by vpisarev** [comment]
:+1:

File: modules/features2d/src/orb.cpp (hunk 2 above)
Comment (alalek) [reply modules/features2d/src/orb.cpp]: @vpisarev This definitely should be fixed.
