### PR TITLE
imgproc: fix minEnclosingCircle O(n^3) worst case by adding Welzl shuffle

### LINKED ISSUE #28546: minEnclosingCircle: missing Welzl randomization causes O(n³) worst case on contour inputs
### System Information

OpenCV version: 4.13.0-dev
Operating System / Platform: Ubuntu 24.04
Compiler & compiler version: GCC 13.3.0

### Detailed description

`minEnclosingCircle` [cites Welzl (1991)](https://github.com/opencv/opencv/blob/4.x/modules/imgproc/src/shapedescr.cpp#L158) but does not implement the **random permutation** that is essential to the algorithm's expected O(n) time guarantee. Without shuffling, adversarial input orderings trigger **O(n³)** behavior.

This is especially relevant because **`findContours()` produces exactly such adversarial orderings** — contour points are returned in sequential order along the boundary. The common pipeline `findContours → minEnclosingCircle` directly triggers worst-case performance.

Welzl's [1991 paper](https://link.springer.com/chapter/10.1007/BFb0038202) proves that if input points are randomly permuted, each point triggers a re-computation with probability at most 3/i, yielding expected O(n) time. The current code processes points in input order without shuffling, so sorted inputs hit O(n³).

**Benchmark with `findContours` output (~5088 contour points, Release build, AVX2):**

| Input | Time/call |
|---|---|
| findContours output | **3.93 ms** |
| Random points (same n) | 0.051 ms |

Adding a Fisher-Yates shuffle (~10 lines) fixes this:

| Input | Before | After |
|---|---|---|
| findContours output | 3.93 ms | **0.033 ms** |
| Random points | 0.051 ms | 0.049 ms |

I have a working fix with all existing tests passing and can submit a PR.

### Steps to reproduce

```cpp
#include <opencv2/imgproc.hpp>
#include <iostream>
#include <chrono>

int main() {
    // findContours → minEnclosingCircle
    cv::Mat img = cv::Mat::zeros(2000, 2000, CV_8UC1);
    cv::circle(img, cv::Point(1000, 1000), 900, cv::Scalar(255), -1);

    std::vector<std::vector<cv::Point>> contours;
    cv::findContours(img, contours, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_NONE);

    cv::Point2f center;
    float radius;

    auto t0 = std::chrono::high_resolution_clock::now();
    for (int r = 0; r < 5; r++)
        cv::minEnclosingCircle(contours[0], center, radius);
    auto t1 = std::chrono::high_resolution_clock::now();

    double ms = std::chrono::duration<double, std::milli>(t1 - t0).count() / 5;
    std::cout << "findContours -> minEnclosingCircle: " << ms << " ms/call" << std::endl;
}
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by 0AnshuAditya0**
Welzl's algorithm requires random permutation of input points to
achieve expected O(n) time. Without shuffling, sorted inputs such
as those produced by findContours() trigger O(n^3) worst case.

Fix: copy input to std::vector<PT> and apply cv::randShuffle()
before processing. Uses OpenCV's RNG so cv::setRNGSeed() ensures
reproducible behavior.

Original benchmark (5088 contour points, Release, AVX2):
findContours output: 3.93 ms → 0.033 ms (119x speedup)
Random points: 0.051 ms → 0.049 ms (no regression)

Perf test results (this PR, Release, AVX2):
| Input | N | Time |
|-------|---|------|
| Sequential circle points | 10000 | 0.03 ms |
| Sequential circle points | 5000 | 0.01 ms |
| Random points (CV_32F) | 100000 | 1.87 ms |
| Random points (CV_32S) | 100000 | 2.81 ms |

Fixes #28546

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
cc @MaximSmolskiy

**Comment by asmorkalov** [comment]
@0AnshuAditya0 Thanks for the contribution. Could you add simple performance test for the covered function? Synthetic input should be enough IMHO.

**Comment by 0AnshuAditya0** [comment]
Perf test results (, AVX2):

| Input | N | Time |
|-------|---|------|
| Sequential circle points | 10000 | 0.03 ms |
| Sequential circle points | 5000 | 0.01 ms |
| Random points (CV_32F) | 100000 | 1.87 ms |
| Random points (CV_32S) | 100000 | 2.81 ms |

adds performance tests covering both random and adversarial sequential input orderings.

**Comment by asmorkalov** [comment]
The PR improves the function performance a lot in the worst case, but introduce regression in generic cases (CPU: AMD Ryzen 2700):
```
alexander@asmorkalov-pc:~/perf-circles$ python3 ../opencv/modules/ts/misc/summary.py ./4.x-1.xml ./patch-1.xml 

Geometric mean (ms)

                            Name of Test                              4.x-1  patch-1  patch-1  
                                                                                         vs    
                                                                                       4.x-1   
                                                                                     (x-factor)
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 400)             0.010   0.010     0.99   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 1000)            0.026   0.031     0.85   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 10000)           0.368   0.140     2.63   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 100000)          1.247   2.524     0.49   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 400)             0.016   0.025     0.65   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 1000)            0.039   0.018     2.13   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 10000)           0.575   0.205     2.80   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 100000)          2.668   4.137     0.64   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::400   0.039   0.003    11.44   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::1000  0.238   0.008    28.66   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::5000  5.866   0.038    155.03  
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::10000 23.368  0.075    310.86  
alexander@asmorkalov-pc:~/perf-circles$ python3 ../opencv/modules/ts/misc/summary.py ./4.x-2.xml ./patch-2.xml 

Geometric mean (ms)

                            Name of Test                              4.x-2  patch-2  patch-2  
                                                                                         vs    
                                                                                       4.x-2   
                                                                                     (x-factor)
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 400)             0.010   0.010     0.99   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 1000)            0.026   0.031     0.86   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 10000)           0.372   0.139     2.68   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 100000)          1.262   2.513     0.50   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 400)             0.017   0.025     0.66   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 1000)            0.040   0.018     2.16   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 10000)           0.584   0.204     2.86   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 100000)          2.692   4.161     0.65   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::400   0.040   0.003    11.74   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::1000  0.242   0.008    29.54   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::5000  5.927   0.037    159.00  
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::10000 23.620  0.074    319.83  
alexander@asmorkalov-pc:~/perf-circles$ python3 ../opencv/modules/ts/misc/summary.py ./4.x-3.xml ./patch-3.xml 

Geometric mean (ms)

                            Name of Test                              4.x-3  patch-3  patch-3  
                                                                                         vs    
                                                                                       4.x-3   
                                                                                     (x-factor)
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 400)             0.010   0.010     0.99   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 1000)            0.026   0.031     0.85   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 10000)           0.368   0.138     2.66   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32F, 100000)          1.248   2.514     0.50   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 400)             0.016   0.025     0.65   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 1000)            0.039   0.018     2.13   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 10000)           0.575   0.204     2.81   
minEnclosingCircle::TestMinEnclosingCircle::(CV_32S, 100000)          2.668   4.174     0.64   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::400   0.039   0.003    11.61   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::1000  0.238   0.008    29.11   
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::5000  5.863   0.037    157.42  
minEnclosingCircle_sequential::TestMinEnclosingCircleWorstCase::10000 23.347  0.074    316.06  
```

**Comment by 0AnshuAditya0** [comment]
@asmorkalov 
I'm switching to cv::AutoBuffer<PT, 1024> to avoid heap allocation for common contour sizes.
I've added a threshold (count > 10) to skip shuffling for small inputs where the overhead exceeds the algorithmic risk.
I replaced the global RNG call with a local cv::RNG instance to remove the thread-local overhead that slowed down the N=100,000 case.

**Comment by 0AnshuAditya0** [comment]
Local perf results (Windows, Release, AVX2):

| Test | Previous patch | Updated patch | Reviewer's 4.x baseline |
|------|---------------|---------------|--------------------------|
| CV_32F, 400 | 0.02 ms | 0.02 ms | 0.010 ms |
| CV_32F, 1000 | 0.06 ms | 0.14 ms | 0.026 ms |
| CV_32F, 10000 | 0.17 ms | 0.58 ms | 0.368 ms |
| CV_32F, 100000 | 7.56 ms | 2.14 ms | 1.248 ms |
| CV_32S, 100000 | 11.97 ms | 4.70 ms | 2.668 ms |
| Sequential, 1000 | 0.01 ms | 0.01 ms | 0.238 ms |
| Sequential, 5000 | 0.05 ms | 0.05 ms | 5.863 ms |
| Sequential, 10000 | 0.10 ms | 0.10 ms | 23.347 ms |

The local RNG reduced the 100k regression.
The worst-case fix remains intact.

File: modules/imgproc/src/shapedescr.cpp [hunk 1]
```diff
@@ -130,26 +130,42 @@ void findSecondPoint(const PT *pts, int i, Point2f &center, float &radius)
...
+    // Without shuffling, sorted inputs trigger O(n^3) worst case.
+    cv::AutoBuffer<PT, 1024> pts_buf(count);
+    std::copy(pts_in, pts_in + count, pts_buf.data());
+    PT* pts = pts_buf.data();
+    if (count > 10)
+    {
+        cv::RNG rng(cv::theRNG().next());
+        for (int i = count - 1; i > 0; --i)
+        {
+            int j = (unsigned int)rng % (i + 1);
```
Comment (jaysran) [inline modules/imgproc/src/shapedescr.cpp]: can we use `int j = rng.uniform(0, i + 1);` ? to remove modulo bias? biased shuffles can slightly increase collision risk.

File: modules/imgproc/src/shapedescr.cpp [hunk 2]
```diff
@@ -130,26 +130,42 @@ void findSecondPoint(const PT *pts, int i, Point2f &center, float &radius)
...
-    float dx = (float)(pts[0].x - pts[1].x);
-    float dy = (float)(pts[0].y - pts[1].y);
+    // Welzl's algorithm requires random permutation for expected O(n) time.
+    // Without shuffling, sorted inputs trigger O(n^3) worst case.
+    cv::AutoBuffer<PT, 1024> pts_buf(count);
+    std::copy(pts_in, pts_in + count, pts_buf.data());
+    PT* pts = pts_buf.data();
+    if (count > 10)
+    {
+        cv::RNG rng(cv::theRNG().next());
```
Comment (vpisarev) [inline modules/imgproc/src/shapedescr.cpp]: do not initialize rng from theRNG. This will make function behavior non-deterministic (the subsequent runs of the same function on the same data must provide the same results). Instead, use some fixed seed, like 0x12345.

File: modules/imgproc/src/shapedescr.cpp [hunk 3]
```diff
@@ -130,26 +130,42 @@ void findSecondPoint(const PT *pts, int i, Point2f &center, float &radius)
...
+        for (int i = count - 1; i > 0; --i)
+        {
+            int j = (unsigned int)rng % (i + 1);
+            std::swap(pts[i], pts[j]);
+        }
+    }
+    const PT *pts_ptr = pts;
```
Comment (vpisarev) [inline modules/imgproc/src/shapedescr.cpp]: please, remove this assignment and revert `pts_ptr` to `pts` in the code below — this way we reduce the patch size.

File: modules/imgproc/src/shapedescr.cpp (hunk 1 above)
Comment (vpisarev) [reply modules/imgproc/src/shapedescr.cpp]: rng.uniform(0, i+1) does the same thing internally, but it looks cleaner, so, please, use rng.uniform.

**Comment by 0AnshuAditya0** [comment]
@vpisarev @asmorkalov 

- Compute seed from first 8 points using memcpy
- Use cv::RNG::uniform() instead of modulo
- Remove pts_ptr

Test | 4.x | This Patch | Status
-- | -- | -- | --
CV_32F, 400 | 0.010 ms | 0.01 ms | ok
CV_32F, 1000 | 0.026 ms | 0.04 ms | slower
CV_32F, 10000 | 0.368 ms | 0.31 ms | faster
CV_32F, 100000 | 1.248 ms | 3.31 ms | slower
CV_32S, 100000 | 2.668 ms | 6.67 ms | slower
Sequential, 1000 | 0.238 ms | 0.01 ms | faster
Sequential, 5000 | 5.863 ms | 0.05 ms | faster
Sequential, 10000 | 23.347 ms | 0.10 ms | faster

Is the 2.5x regression on 100k *random* inputs acceptable given the 300x speedup on 10k sequential inputs?
Can we do this -----
Skip shuffle for count > 50k = eliminates regression, but 100k sequential inputs stay slow
Adaptive stride shuffle for large N = partial shuffle.

something like 
```cpp
if (count > 10)
{
    int effective_count = (count > 20000) ? 20000 : count;
    
    uint64_t seed = (uint64_t)count;
    int sample = std::min(count, 8);
    for(int k = 0; k < sample; k++) { /* hash */ }
    
    cv::RNG rng((uint32_t)seed);
    
    int stride = (count > 20000) ? (count / 20000) : 1;
    for (int i = count - 1; i > 0; i -= stride)
    {
        int j = rng.uniform(0, i + 1);
        std::swap(pts[i], pts[j]);
    }
}
```

File: modules/imgproc/src/shapedescr.cpp [hunk 4]
```diff
@@ -130,8 +130,35 @@ void findSecondPoint(const PT *pts, int i, Point2f &center, float &radius)
...
+static void findMinEnclosingCircle(const PT *pts_in, int count, Point2f &center, float &radius)
 {
+    // Welzl's algorithm requires random permutation for expected O(n) time.
+    // Without shuffling, sorted inputs trigger O(n^3) worst case.
+    cv::AutoBuffer<PT, 1024> pts_buf(count);
+    std::copy(pts_in, pts_in + count, pts_buf.data());
+    PT* pts = pts_buf.data();
+    if (count > 10)
+    {
+        uint64_t seed = (uint64_t)count;
```
Comment (mshabunin) [inline modules/imgproc/src/shapedescr.cpp]: Do we really need random seed to depend on data?

**Comment by akretz** [comment]
> Is the 2.5x regression on 100k _random_ inputs acceptable given the 300x speedup on 10k sequential inputs?

That huge slowdown in the random case seems very odd to me. It means that the shuffling takes more time than the actual algorithm.

Can you check the runtime when you reverse the shuffling loop? I.e. going from 0 to `count - 1` instead of the reverse. That memory access pattern should be more friendly to the CPU cache I believe.

**Comment by 0AnshuAditya0** [comment]
Test | Before | After | Status
-- | -- | -- | --
CV_32S, 100000 | 6.67 ms | 5.08 ms | faster
CV_32F, 100000 | 3.31 ms | 1.53 ms | faster


Switching to a forward loop (i = 1 to count-1).

The regression likely comes from the copy overhead + shuffle overhead combined. 
The forward loop should help reduce it.

File: modules/imgproc/src/shapedescr.cpp [hunk 5]
```diff
@@ -130,8 +130,31 @@ void findSecondPoint(const PT *pts, int i, Point2f &center, float &radius)
...
+static void findMinEnclosingCircle(const PT *pts_in, int count, Point2f &center, float &radius)
 {
+    // Welzl's algorithm requires random permutation for expected O(n) time.
+    // Without shuffling, sorted inputs trigger O(n^3) worst case.
+    cv::AutoBuffer<PT, 1024> pts_buf(count);
+    std::copy(pts_in, pts_in + count, pts_buf.data());
+    PT* pts = pts_buf.data();
+    if (count > 10)
+    {
+        uint32_t x0 = 0, y0 = 0, xn = 0, yn = 0;
```
Comment (vpisarev) [inline modules/imgproc/src/shapedescr.cpp]: please use Cv32suf unions instead of this very verbose trick with memcpy.

**Comment by 0AnshuAditya0** [comment]
Done! Switched to Cv32suf union.

**Review by vpisarev — APPROVED** [review]
