### PR TITLE
DNN: ARMv7 compatible fastConv

### LINKED ISSUE #22188: Compilation problems on Pi Gen 2 with Distribution Bullseye Full (32 bit)
##### System information (version)

- OpenCV => newest 04.07.2022
- Operating System / Platform => Raspberry Pi OS Full (32bit) A Port of Debian Bullseye with desktop environment and recommended applications
- Compiler => gnu cc1plus

##### Detailed description
During compilation of opencv a compiler errror occurs at about 44% of compiling
The error message reads:
/home/pi/opencv/modules/dnn/src/layers/fast_convolution/fast_convolution.simd.hpp:176:18 error: 'vfmaq_laneq_f32' was not declared in this scope; did you mean 'vmlaq_lane_f32'?

cause is that the following header file is missing " opencv2/core/hal/intrin.hpp"

So this might be a building issue, because the header was not build previous to fast_convolution.

##### Steps to reproduce

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \
    -D ENABLE_NEON=ON \
    -D ENABLE_VFPV3=ON \
    -D BUILD_TESTS=OFF \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D OPENCV_ENABLE_NONFREE=ON \
    -D CMAKE_SHARED_LINKER_FLAGS=-latomic \
    -D BUILD_EXAMPLES=OFF ..

   make -f$(nproc)

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc
   <!--
   The best reproducer -- test case for OpenCV that we can add to the library.
   Recommendations for media files and binary files:
   * Try to reproduce the issue with images and videos in opencv_extra repository
     to reduce attachment size
   * Use PNG for images, if you report some CV related bug, but not image reader
     issue
   * Attach the image as an archive to the ticket, if you report some reader issue.
     Image hosting services compress images and it breaks the repro code.
   * Provide ONNX file for some public model or ONNX file with random weights,
     if you report ONNX parsing or handling issue. Architecture details diagram
     from netron tool can be very useful too. See https://lutzroeder.github.io/netron/

### PR DESCRIPTION
**Pull request by zihaomu**
This PR is compatible `fastConv` and `winogradConv` with ARMv7.
The previous #21910 PR only supported AARCH64 or ARMv8. And it has [bugs on ARMv7](https://github.com/opencv/opencv/pull/21910#issuecomment-1172772375)
 as @asenyaev reported. 

closes #22188

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/dnn/test/test_darknet_importer.cpp [hunk 1]
```diff
@@ -353,7 +353,7 @@ TEST_P(Test_Darknet_nets, YoloVoc)
                                     1, 6,  0.844947f, 0.637058f, 0.460398f, 0.828508f, 0.66427f);  // a car
 
     double nmsThreshold = (target == DNN_TARGET_MYRIAD) ? 0.397 : 0.4;
-    double scoreDiff = 8e-5, iouDiff = 3e-4;
+    double scoreDiff = 1e-4, iouDiff = 3e-4;
```
Comment (zihaomu) [inline modules/dnn/test/test_darknet_importer.cpp:356]: The arm instruction `vfmaq_laneq_f32` is only supported at ARMv8. So I use the `vmlaq_n_f32` instead. I adjusted the thresholds here and below because I found the `vmlaq_n_f32` will generate very little different results than `vmlaq_n_f32`.

File: modules/dnn/test/test_model.cpp [hunk 2]
```diff
@@ -331,7 +331,7 @@ TEST_P(Test_Model, DetectRegion)
 
     double confThreshold = 0.24;
     double nmsThreshold = (target == DNN_TARGET_MYRIAD) ? 0.397 : 0.4;
-    double scoreDiff = 8e-5, iouDiff = 1e-5;
+    double scoreDiff = 1e-4, iouDiff = 1e-5;
```
Comment (zihaomu) [inline modules/dnn/test/test_model.cpp:334]: The arm instruction `vfmaq_laneq_f32` is only supported at ARMv8. So I use the `vmlaq_n_f32` instead. I adjusted the thresholds here and below because I found the `vmlaq_n_f32` will generate very little different results than `vmlaq_n_f32`.

Comment (zihaomu) [reply modules/dnn/test/test_model.cpp:334]: On my M1 chip, the `vmlaq_n_f32 ` will be parsed as follows:
```
+0x198	fmul.4s             v24, v22, v20[0]
+0x19c	fadd.4s             v3, v3, v24
```
And the `vfmaq_laneq_f32 ` will be parsed as follows:
```
fmla.4s             v16, v2, v14[3]
```

**Comment by zihaomu** [comment]
Hi @alalek, I can't pass the ARMv7 CI. And from the [CI's log](https://pullrequest.opencv.org/buildbot/builders/precommit_armv7/builds/100001/steps/init/logs/stdio), I have no idea how to fix it. Any advice?

**Comment by alalek** [comment]
@zihaomu Please ignore (ARMv7 configuration is not working on BuildBot)

File: modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp [hunk 3]
```diff
@@ -1093,59 +1092,63 @@ int runWinograd63(InputArray _input, OutputArray _output, const Ptr<FastConv2d>&
 #else // ARMv7 16 registers.
 
                         // init 16 registers. FMA/load ratio = 32/12
-                        float32x4_t r00 = vdupq_n_f32(0.0f), r01 = r00, r02 = r00, r03 = r00;
-                        float32x4_t r04 = r00, r05 = r00, r06 = r00, r07 = r00;
-                        float32x4_t r08 = r00, r09 = r00, r10 = r00, r11 = r00;
-                        float32x4_t r12 = r00, r13 = r00, r14 = r00, r15 = r00;
+                        float32x2_t q00 = vdup_n_f32(0.0f), q01 = q00, q02 = q00, q03 = q00,
```
Comment (vpisarev) [inline modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp:1095]: could you please explain why you use halves of NEON registers on ARMv7? ARMv7 still has 128-bit NEON registers, I don't see why not use all of them

Comment (zihaomu) [reply modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp:1095]: Thanks for code reviewing. As @nihui's commented, `vmlaq_lane_f32 ` is the best substitute for `vfmaq_laneq_f32 ` under the ARMv7 platform.
Another option is `vmlaq_n_f32`, it will be parsed into two arm assembly code `fmul.4s             v24, v22, v20[0]` and `fadd.4s v3, v3, v24`. And `vmlaq_lane_f32` will be parsed into only one arm assembly code `vmla.f32 q8, q5, d0[1]` on ARMv7. 
At the same time, two consecutive half-length register loads will be converted into a 128bit load during loading data to register, so the data load time is the same.

**Review by vpisarev — APPROVED** [review]

**Comment by vpisarev** [comment]
:+1:

**Comment by vpisarev** [comment]
@nihui, btw, let me use this opportunity to thank you for ncnn, which we took some code from. ncnn is a real piece of art :+1:
