### PR TITLE
py_samples: fix digits.py

### LINKED ISSUE #8714: Python digits.py sample bad indices.
##### System information (version)
- OpenCV => 3.2.0-3
- Operating System / Platform => Arch 4.10
- Compiler => Python 3.6.1

##### Detailed description

Testing the digits.py example produces this error:

```
Traceback (most recent call last):
  File "digits.py", line 178, in <module>
    vis = evaluate_model(model, digits_test, samples_test, labels_test)
  File "digits.py", line 115, in evaluate_model
    confusion[i, j] += 1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Changing the line to  `confusion[i, int(j)] += 1` corrects the error by converting j from float to int.

### PR DESCRIPTION
**Pull request by berak**
resolves #8714

samples/python/digits.py:   add a cast to int when accessing the confusion matrix

### CODE REVIEW

File: modules/videoio/src/cap_dshow.cpp [hunk 1]
```diff
@@ -96,6 +96,7 @@ Thanks to:
 #ifdef __MINGW32__
 // MinGW does not understand COM interfaces
 #pragma GCC diagnostic ignored "-Wnon-virtual-dtor"
+#define STRSAFE_NO_DEPRECATE
```
Comment (sovrasov) [inline modules/videoio/src/cap_dshow.cpp]: This change seems to be not related to this PR.

Comment (berak) [inline modules/videoio/src/cap_dshow.cpp]: ouch, right.

**Comment by sovrasov** [comment]
:+1:
