### PR TITLE
flann/kmeans: Fix non-determinism of KMeans index

### LINKED ISSUE #9179: Nightly test failure: Features2d_FLANN_Auto.regression
[Win32 without IPP](http://pullrequest.opencv.org/buildbot/builders/master_noICV-win32-vc14/builds/10160):
```
[ RUN      ] Features2d_FLANN_Auto.regression
C:\build\master_noICV-win32-vc14\opencv\modules\ts\src\ts.cpp(541): error: Failed

	failure reason: Bad accuracy
	test case #-1
	seed: ffffffffffffffff
-----------------------------------
	LOG:
correct_perc = -1580547965
bad accuracy of Find 

-----------------------------------

[  FAILED  ] Features2d_FLANN_Auto.regression (52716 ms)
```

[20170728](http://pullrequest.opencv.org/buildbot/builders/master_noOCL-win32-vc14/builds/10169)
[20170820](http://pullrequest.opencv.org/buildbot/builders/master_noOCL-win32-vc14/builds/10195)

### PR DESCRIPTION
**Pull request by mattismyname**
When running with >1 OpenCV thread, KMeans index generation was
non-deterministic. Issue is resolved by protecting each radius variable
with a mutex.

resolves #9179
relates #3458

### CODE REVIEW

**Comment by alalek** [comment]
Nice catch!

Using of multiple mutexes has huge overhead here.

I believe we can move out post-processing from parallel_for body (it is simple enough).
Lets calculate these values in parallel:
- `new_centroid`
- `sq_dist`
for each `indices_length`

```
// pre-allocate buffers
std::vector<int> new_centroid(indices_length);
std::vector<DistanceType> sq_dist(indices_length);

...

KMeansDistanceComputer invoker(...);
parallel_for_(cv::Range(0, (int)indices_length), invoker);

... post processing loop: i=[0..indices_length) ...
- update `radiuses[new_centroid[i]]`
- update `belongs_to[i]` and `count[belongs_to[i]]`
- update `converged`
```

**Comment by alalek** [comment]
As a "bugfix" this patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by mattismyname** [comment]
ok please take a look now.

File: modules/flann/include/opencv2/flann/kmeans_index.h [hunk 1]
```diff
@@ -297,24 +295,15 @@ class KMeansIndex : public NNIndex<Distance>
...
+                sq_dists[i] = distance(dataset[indices[i]], dcenters[0], veclen);
+                new_centroids[i] = 0;
                 for (int j=1; j<branching; ++j) {
                     DistanceType new_sq_dist = distance(dataset[indices[i]], dcenters[j], veclen);
-                    if (sq_dist>new_sq_dist) {
-                        new_centroid = j;
-                        sq_dist = new_sq_dist;
+                    if (sq_dists[i]>new_sq_dist) {
+                        new_centroids[i] = j;
+                        sq_dists[i] = new_sq_dist;
```
Comment (alalek) [inline modules/flann/include/opencv2/flann/kmeans_index.h]: It is better to make calculations using local variables and save them in global memory in the end.

```
for( int i = begin; i<end; ++i)
{
    DistanceType sq_dist = ...
    int new_centroid = 0;
    ...
    sq_dists[i] = sq_dist;
    new_centroids[i] = new_centroid;
}
```

File: modules/flann/include/opencv2/flann/kmeans_index.h [hunk 2]
```diff
@@ -796,10 +783,25 @@ class KMeansIndex : public NNIndex<Distance>
...
+            std::vector<int> new_centroids(indices_length);
+            std::vector<DistanceType> sq_dists(indices_length);
+
             // reassign points to clusters
-            KMeansDistanceComputer invoker(distance_, dataset_, branching, indices, dcenters, veclen_, count, belongs_to, radiuses, converged);
+            KMeansDistanceComputer invoker(distance_, dataset_, branching, indices, dcenters, veclen_, new_centroids, sq_dists);
             parallel_for_(cv::Range(0, (int)indices_length), invoker);
 
+            for (int i=0; i < (int)indices_length; ++i) {
+                if (sq_dists[i] > radiuses[new_centroids[i]]) {
```
Comment (alalek) [inline modules/flann/include/opencv2/flann/kmeans_index.h]: Similar, fetch values into local variables and use them below:
```
DistanceType sq_dist = sq_dists[i];
int new_centroid = new_centroids[i];
```

**Comment by alalek** [comment]
Perhaps this patch should resolve these sporadic failures: #9179

File: modules/flann/include/opencv2/flann/kmeans_index.h (hunk 1 above)
Comment (mattismyname) [reply modules/flann/include/opencv2/flann/kmeans_index.h]: Honestly I thought compilers could do this optimization automatically. I guess not...
