### PR TITLE
DNN: Make MatMul layer support 3D or 4D operation with const input

### LINKED ISSUE #22713: BUG ONNXImporter::handleNode MatMul
### System Information

OpenCV version: current Master branch 
Operating System / Platform: Windows 11
Compiler & compiler version: MSVC 16

### Detailed description

When trying to parse the onnx file (exported from https://github.com/baudm/parseq and simplified with https://github.com/daquexian/onnx-simplifier as recommended in the opencv doku) i get following error:

> ERROR:0@0.145] global X:\ThirdPartySource\opencv_cuda\opencv\modules\dnn\src\onnx\onnx_importer.cpp (1050) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [MatMul]:(onnx_node!MatMul_859) from domain='ai.onnx'
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.6.0-dev) Error: Unspecified error (> Node [MatMul@ai.onnx]:(onnx_node!MatMul_859) parse error: OpenCV(4.6.0-dev) X:\ThirdPartySource\opencv_cuda\opencv\modules\core\src\matrix_transform.cpp:245: error: (-215:Assertion failed) _src.dims() <= 2 && esz <= 32 in function 'cv::transpose'
> ) in cv::dnn::dnn4_v20220524::ONNXImporter::handleNode, file X:\ThirdPartySource\opencv_cuda\opencv\modules\dnn\src\onnx\onnx_importer.cpp, line 1069

The onnx it self is valid and can be used with the onnx runtime itself.
i also checked it via https://netron.app/

there seems to be 2 issues in MatMul_859 first i think opencv expect another order of the inputs.
But even if i change them i get another error here i am :)

### Steps to reproduce

auto detector = cv::dnn::readNetFromONNX("ocr-sim.onnx");

weetransfer for the onnx file:

https://wetransfer.com/downloads/46d0dc6287c0d1ed000924a036400bbe20221028095359/f7770d3acc028f8006a96bced82790c920221028095418/e4e0a6

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by WanliZhong**
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1015

This PR is a temporary solution to fix #22713.

When 3D or 4D `MatMul` with a const input, it will create a virtual layer to ensure it can be run correctly. Later I will create a new PR to optimize the parsing of `MatMul` so that 3D or 4D operations can also use SIMD and multi-thread acceleration like 2D `MatMul`.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 1]
```diff
@@ -2031,8 +2031,9 @@ void ONNXImporter::parseGemm(LayerParams& layerParams, const opencv_onnx::NodePr
     addLayer(layerParams, node_proto);
 }
 
-void ONNXImporter::parseMatMul(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
+void ONNXImporter::parseMatMul(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto_)
 {
+    opencv_onnx::NodeProto node_proto = node_proto_;
```
Comment (asmorkalov) [inline modules/dnn/src/onnx/onnx_importer.cpp:2036]: const reference in signature and copy call on the first line looks very strange. I propose to pass `node_proto` as value, or, better, make a copy in else branch only to not degrade existing branch performance.

Comment (zihaomu) [reply modules/dnn/src/onnx/onnx_importer.cpp:2036]: Agree, this `const reference` exists in many onnx op codes.

**Review by zihaomu — APPROVED** [review]
LGTM! 👍

**Review by rogday — APPROVED** [review]
LGTM :+1:
