### PR TITLE
Fix multichannel warping with BORDER_CONSTANT

### LINKED ISSUE #8400: Wrong borders for warping with channels > 4 and BORDER_CONSTANT
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => ubuntu 14.04
- Compiler => GCC 4.8.2

##### Detailed description
When using warpPerspective with images with more than 4 channels, using BORDER_CONSTANT and one of the interpolation methods INTER_NEAREST, INTER_CUBIC or INTER_LANCZOS4, the borders are wrong.
##### Steps to reproduce
Call the following function using BORDER_CONSTANT and one of the interpolation methods above, pass at least one grayscale image and a nonunit transform:
```.cpp
void test(const std::vector<cv::Mat> &src_images, const cv::Matx33d &transform,
          cv::Size img_size, int num_channels = 100, int interpolation = cv::INTER_NEAREST, 
          int border = cv::BORDER_CONSTANT, const cv::Scalar &value = cv::Scalar(255, 170, 85, 0))
{
    std::vector<cv::Mat> channels(num_channels), channels_true(num_channels);

    for (int i = 0; i < num_channels; ++i) {
        int num = std::rand() % src_images.size();
        channels[i] = src_images[num].clone();
        channels_true[i] = channels[i].clone();
    }
    cv::Mat multichannel;
    cv::merge(channels, multichannel);

    for (size_t i = 0; i < channels_true.size(); ++i) {
        cv::Scalar val = value[i % 4];
        auto ch = channels_true[i];
        cv::warpPerspective(ch, ch, transform, img_size, interpolation, border,
                            val);
    }
    cv::warpPerspective(multichannel, multichannel, transform,
                    img_size, interpolation, border, value);
    cv::split(multichannel, channels);
    for (size_t i = 0; i < channels.size(); ++i) {
        double s = cv::sum(channels[i] != channels_true[i])[0];
        if (s > 0.0) {
            cv::imshow("Error", channels[i]);
            cv::imshow("Should be", channels_true[i]);
            cv::waitKey(0);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by avartenkov**
resolves #8400
### This pullrequest changes
The behavior of filling borders with constant value for the methods above to be similar to that of INTER_LINEAR.

### CODE REVIEW

File: modules/imgproc/src/imgwarp.cpp [hunk 1]
```diff
@@ -3533,15 +3533,15 @@ static void remapNearest( const Mat& _src, Mat& _dst, const Mat& _xy,
                           int borderType, const Scalar& _borderValue )
 {
     Size ssize = _src.size(), dsize = _dst.size();
-    int cn = _src.channels();
+    int k, cn = _src.channels();
```
Comment (sovrasov) [inline modules/imgproc/src/imgwarp.cpp]: Please get rid of the global declarations of `k`, `dx` and `dy`.

**Comment by sovrasov** [comment]
:+1:
