### PR TITLE
Fix occuring artifacts in fillPoly

### LINKED ISSUE #22012: Artifacts in image generated with cv::fillPoly
##### System information (version)
- OpenCV => 3.4.1, 4.5.5
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017

##### Detailed description

Result image of cv::fillPoly contains artifacts at the corner of the polygon. In the following image there are small black dots at the right top of the white area.
BadFilledPolygon
It seems like this mostly happenes if some of the polygon coordinates are outside of the image, but only in rare cases. ~~And it seems that it doesn't happen with line mode cv::LineTypes::LINE_4~~

##### Steps to reproduce

UnitTest to reproduce and to generate the image shown above.
```
TEST(OpenCVTests, CvFillPolyCheckForArtifacts)
{
	unsigned imageWidth = 256;
	unsigned imageHeight = 256;
	for (int y = imageHeight/2; y > -50; y -= 1)
	{
                // define polygon
		std::vector<cv::Point> polygonPoints;
		polygonPoints.push_back(cv::Point(100, imageHeight - y));
		polygonPoints.push_back(cv::Point(imageWidth, imageHeight));
		polygonPoints.push_back(cv::Point(imageWidth, 0));

                // convert data
		std::vector<const cv::Point*> polygonPointPointers(polygonPoints.size());
		for (size_t i = 0; i < polygonPoints.size(); ++i)
		{
			polygonPointPointers[i] = &polygonPoints[i];
		}

		auto data = &polygonPointPointers.front();
		int size = (int)polygonPoints.size();
		const int* npts = &size;
		int ncontours = 1;
		cv::Mat img(imageWidth, imageHeight, CV_8UC1);
		img = 0;
		int lineType = cv::LineTypes::LINE_8;
		int shift = 0;
		cv::Point offset(0, 0);

                // generate image
		cv::fillPoly(img, data, npts, ncontours, 255, lineType, shift, offset);
	
                // check for artifacts
		cv::Mat binary = img < 128;
		cv::Mat labelImage(binary.size(), CV_32S);
		cv::Mat labelStats;
		cv::Mat labelCentroids;
		auto labels = cv::connectedComponents(binary, labelImage, 4);
		EXPECT_EQ(2, labels);
		if (labels > 2)
		{
			cv::imwrite("C:\\temp\\BadFilledPolygon.png", img);
		}
	}
	for (int x = imageWidth / 2; x > -50; x -= 1)
	{
		// define polygon
		std::vector<cv::Point> polygonPoints;
		polygonPoints.push_back(cv::Point(imageWidth-x, 100));
		polygonPoints.push_back(cv::Point(imageWidth, imageHeight));
		polygonPoints.push_back(cv::Point(0, imageHeight));
		
		// convert data
		std::vector<const cv::Point*> polygonPointPointers(polygonPoints.size());
		for (size_t i = 0; i < polygonPoints.size(); ++i)
		{
			polygonPointPointers[i] = &polygonPoints[i];
		}

		auto data = &polygonPointPointers.front();
		int size = (int)polygonPoints.size();
		const int* npts = &size;
		int ncontours = 1;
		cv::Mat img(imageWidth, imageHeight, CV_8UC1);
		img = 0;
		int lineType = cv::LineTypes::LINE_4;
		int shift = 0;
		cv::Point offset(0, 0);
		
		// generate image
		cv::fillPoly(img, data, npts, ncontours, 255, lineType, shift, offset);

		// check for artifacts
		cv::Mat binary = img < 128;

		cv::Mat labelImage(binary.size(), CV_32S);
		cv::Mat labelStats;
		cv::Mat labelCentroids;
		auto labels = cv::connectedComponents(binary, labelImage, 4);
		EXPECT_EQ(2, labels);
		if (labels > 2)
		{
			cv::imwrite("C:\\temp\\BadFilledPolygon.png", img);
		}
	}

}
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by inayd**
Fixes #22012
Fixing the bug described in https://github.com/opencv/opencv/issues/22012

The artifacts can occur when corners of a polygon are outside of the image. To be more precise, the outline of the polygon is being drawn using clipped endpoints of an edge, while the borders of the area to be filled are determined using unclipped points of an edge. This can introduce a small offset between the outline and the filled area in polygons which have corner points outside of the image.

The issue is fixed by correcting the edges when lines are clipped.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work

### CODE REVIEW

File: modules/imgproc/src/drawing.cpp [hunk 1]
```diff
@@ -1259,37 +1259,56 @@ CollectPolyEdges( Mat& img, const Point2l* v, int count, std::vector<PolyEdge>&
...
+        Point2l pt0c(pt0), pt1c(pt1);
+
+        if (line_type < CV_AA)
         {
             t0.y = pt0.y; t1.y = pt1.y;
-            t0.x = (pt0.x + (XY_ONE >> 1)) >> XY_SHIFT;
-            t1.x = (pt1.x + (XY_ONE >> 1)) >> XY_SHIFT;
-            Line( img, t0, t1, color, line_type );
+            t0.x = (pt0.x >> XY_SHIFT);
+            t1.x = (pt1.x >> XY_SHIFT);
```
Comment (alalek) [inline modules/imgproc/src/drawing.cpp:1268]: Rounding mode has been changed. This should not happen.

File: modules/imgproc/src/drawing.cpp [hunk 2]
```diff
@@ -1259,37 +1259,56 @@ CollectPolyEdges( Mat& img, const Point2l* v, int count, std::vector<PolyEdge>&
...
+
+            // use clipped endpoints to create a more accurate PolyEdge
+            if ((unsigned)t0.x >= (unsigned)(img.cols) ||
```
Comment (alalek) [inline modules/imgproc/src/drawing.cpp:1271]: Why is this applied for `line_type < CV_AA` only?

**Comment by inayd** [comment]
I adjusted the code after the review. Could you take another look? 🙂

**Review by alalek — APPROVED** [review]
LGTM :+1: Thank you for contribution!

**Comment by dan-masek** [comment]
Today I ran across this question: https://stackoverflow.com/questions/78955298/python-opencv-draws-polygons-outside-of-lines

Looks like it started to appear between 4.7 and 4.8 which leads me to believe it's related to this patch.

```
import cv2
import numpy as np
    
points = np.array([[[44, 27], [7, 37], [7, 19],[38, 19]]], np.int32).reshape((-1, 1, 2))
img = np.zeros((50, 50, 3), dtype=np.uint8)

cv2.fillPoly(img, [pts], (0, 0, 255))
cv2.polylines(img, [pts], True, (255, 0, 0), 1)

cv2.imwrite("output_v" + str(cv2.__version__) + ".png", img)
```

In 4.7 and older:
output_v4 7 0

In 4.8 and younger:
output_v4 8 0

Is that expected?
