### PR TITLE
Fix for SGBM compute() buffer allocation failure on big images

### LINKED ISSUE #8038: StereoSGBM compute() fails with exception
##### System information (version)
- OpenCV => 3.2.0
- Operating System / Platform => Windows 7 64 bit, 8 GiB RAM, MSYS2 MinGW64 64 bit 
- Compiler => gcc 6.3.0

##### Detailed description

A call to StereoSGBM::compute() with the parameters shown in the code example fails with an exception:

> user@user-PC MINGW64 ~/opencv_stereo_sgbm_testcase
> $ ./opencv_stereo_sgbm_testcase.exe
> OpenCV Error: Assertion failed (s >= 0) in setSize, file C:/msys64/home/user/MINGW-packages-master/mingw-w64-opencv/src/opencv-3.2.0/modules/core/src/matrix.cpp, line 307
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> terminate called after throwing an instance of 'cv::Exception'
>   what():  C:/msys64/home/user/MINGW-packages-master/mingw-w64-opencv/src/opencv-3.2.0/modules/core/src/matrix.cpp:307: error: (-215) s >= 0 in function setSize
> 
> 
> user@user-PC MINGW64 ~/opencv_stereo_sgbm_testcase
> $
> 

The compute() call succeeds with StereoSGBM::MODE_SGBM and StereoSGBM::MODE_SGBM_3WAY, but fails with StereoSGBM::MODE_HH.
The size of the input images affects this behaviour. It seems that compute() works fine when its memory consumption stays below 2 GiB.
Please note that all components involved are using a 64 bit address space, creating a 80000x80000 Mat<uint8_t> works without a problem and makes the process use 6.4 GB as expected.

##### Steps to reproduce

```.cpp
#include <opencv2/core/core.hpp>
#include <opencv2/calib3d/calib3d.hpp>

int main(void)
{
	cv::Mat src1, src0, disparity;

	src0.create(cv::Size(1812, 1737), CV_8U);
	src1.create(cv::Size(1812, 1737), CV_8U);

	cv::Ptr<cv::StereoSGBM> stereoSGBM = cv::StereoSGBM::create(0, 14*16, 3, 0, 10000, 72, 2, 1, 14, 1, 1);

	stereoSGBM->compute(src0, src1, disparity);

	return 0;
}
```

### PR DESCRIPTION
**Pull request by terfendail**
resolves #8038 

### This pullrequest changes
Fixed buffer allocation for sizes over 2GB in SGBM compute() necessary for processing of big images

### CODE REVIEW

File: modules/core/src/matrix.cpp [hunk 1]
```diff
@@ -830,6 +830,26 @@ void Mat::reserve(size_t nelems)
     dataend = data + step.p[0]*r;
 }
 
+void Mat::reserveBuffer(size_t nbytes)
+{
+    if (!isSubmatrix() && data + nbytes <= dataend)//Should it be datalimit?
+        return;
+
+    size_t nelems = (nbytes - 1) / (elemSize()?elemSize():1) + 1;
```
Comment (alalek) [inline modules/core/src/matrix.cpp]: `elemSize()` is undefined for empty Mat, so you shouldn't use it.

File: modules/core/src/matrix.cpp [hunk 2]
```diff
@@ -830,6 +830,26 @@ void Mat::reserve(size_t nelems)
...
+
+    CV_Assert(nelems <= size_t(INT_MAX)*0x3FFFffffUL);//INT_MAX*2^30
```
Comment (alalek) [inline modules/core/src/matrix.cpp]: Why?

File: modules/core/src/matrix.cpp [hunk 3]
```diff
@@ -830,6 +830,26 @@ void Mat::reserve(size_t nelems)
...
+
+    int newrows = 1, newcols = (int)nelems;
+
+    while (nelems > (size_t(INT_MAX) * newrows))
+    {
+        newrows *= 1024;
+        newcols = (int)((nelems - 1) / newrows + 1);
+    }
+
+    create(newrows, newcols, type());
```
Comment (alalek) [inline modules/core/src/matrix.cpp]: `type()` is undefined for empty Mat, so you shouldn't use it.

File: modules/core/src/matrix.cpp [hunk 4]
```diff
@@ -830,6 +830,26 @@ void Mat::reserve(size_t nelems)
     dataend = data + step.p[0]*r;
 }
 
+void Mat::reserveBuffer(size_t nbytes)
+{
+    if (!isSubmatrix() && data + nbytes <= dataend)//Should it be datalimit?
```
Comment (alalek) [inline modules/core/src/matrix.cpp]: `isSubmatrix()` is undefined for empty Mat, so you shouldn't use it.

File: modules/core/src/matrix.cpp [hunk 5]
```diff
@@ -830,6 +830,28 @@ void Mat::reserve(size_t nelems)
...
+    {
+        if (!isSubmatrix() && data + nbytes <= dataend)//Should it be datalimit?
+            return;
+        esz = elemSize();
+        mtype = type();
+    }
+
+    size_t nelems = (nbytes - 1) / esz + 1;
+
+    CV_Assert(nelems <= size_t(INT_MAX)*size_t(INT_MAX));
```
Comment (vpisarev) [inline modules/core/src/matrix.cpp]: this is incorrect assert in 32-bit case

**Comment by vpisarev** [comment]
@terfendail, thanks! can you please make yet another change, i.e. add:

<pre>
if( isContinuous() && total() >= nbytes )
    return;
</pre>

prior to computing `newrows` and `newcols`? This will make the function a bit more intelligent when user allocates buffer by himself using some different formula.

**Comment by terfendail** [comment]
There already is a check at line 839 that prevent reallocation in case matrix has enough space.
I think it shouldn't make much sense to ensure the space is addressable by standard Mat methods if user just asks for a certain amount of bytes.

**Comment by vpisarev** [comment]
ok :+1:
