### PR TITLE
Fixing dnn Resize layer for variable input size

### LINKED ISSUE #18695: onnx 12: Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'
I'm working on a Unet model and the upsampling layers will trigger an exception when infering on an image with a different size than the training dataset: `Inconsistent shape for ConcatLayer in function 'cv::dnn::ConcatLayerImpl::getMemoryShapes'`
When exporting to onnx opset 9, inference work for any input size. The upsampling layer is defined as `Upsample`
image

When exporting to onnx opset >9, inference work on 256² only. The upsampling layer is defined as `Resize`
image

I can provide both onnx by email if needed

### PR DESCRIPTION
**Pull request by JulienMaille**
my previous PR  #18708 closed itself!

resolves #18695
merge with extra https://github.com/opencv/opencv_extra/pull/816

<cut/>

```
opencv_extra=patch-1
force_builders_only=linux,docs
test_modules=dnn,python2,python3,java

Xforce_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2021.1.0:20.04
build_image:Custom Win=openvino-2021.1.0
build_image:Custom Mac=openvino-2021.1.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by JulienMaille** [comment]
So if I understand @l-bat @sl-sergei correctly, some of the new test onnx like [dynamic_resize_scale_10.onnx](https://github.com/opencv/opencv_extra/blob/f3013bd2b0dec4db5cc3e3c6e75dd0fe955e65a4/testdata/dnn/onnx/models/dynamic_resize_scale_10.onnx)  do not pass the scales as a constant input. But if the scales are a variable input, then I don't know how we can proceed. I'm not even sure it makes sense.

That explains why I get this error:
```
[ERROR:0] onnx_importer.cpp (1798) handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 1 outputs: [Upsample]:(10)
[ INFO:0] onnx_importer.cpp (1801) handleNode     Input[0] = 'input'
[ INFO:0] onnx_importer.cpp (1801) handleNode     Input[1] = '16'
[ INFO:0] onnx_importer.cpp (1805) handleNode     Output[0] = '10'
unknown file: Failure
C++ exception with description "OpenCV(4.5.0-dev) onnx_importer.cpp:1807: error: (-2:Unspecified error) in function 'handleNode'
> Node [Upsample]:(10) parse error: OpenCV(4.5.0-dev) onnx_importer.cpp:330: error: (-5:Bad argument) Blob 16 not found in const blobs in function 'getBlob'
```

**Comment by JulienMaille** [comment]
@alalek I suppose all of you are extremely busy but could someone show me the right way the case when scales are not passed as a constant input? Maybe an example of another layer dealing with that. Thanks in advance!

**Comment by JulienMaille** [comment]
Ok, I believe the exported onnx are invalid, because the default mode doesn't export parameters!

**Comment by JulienMaille** [comment]
@alalek Yeah, finally, with the right models, all tests do pass! I've rebased, cleaned up and squashe commits.

**Comment by l-bat** [comment]
@JulienMaille Why did you delete the CI config in PR description?

File: modules/dnn/test/test_onnx_importer.cpp [hunk 1]
```diff
@@ -516,9 +516,34 @@ TEST_P(Test_ONNX_layers, Broadcast)
...
+
+TEST_P(Test_ONNX_layers, DynamicResizeScaleOpset10)
+{
+    testONNXModels("dynamic_resize_scale_10", npy, 0, 0, false, true, 2);
+}
+
+TEST_P(Test_ONNX_layers, DynamicResizeScaleOpset11)
+{
+    testONNXModels("dynamic_resize_scale_11", npy, 0, 0, false, true, 2);
 }
```
Comment (l-bat) [inline modules/dnn/test/test_onnx_importer.cpp:547]: I think it's better to combine all the tests into one

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 2]
```diff
@@ -1746,43 +1746,63 @@ void ONNXImporter::handleNode(const opencv_onnx::NodeProto& node_proto_)
...
+                layerParams.set("zoom_factor_x", shapes.at<int>(3));
+                foundScales = true;
+            }
+            else if (node_proto.input_size() > 1)
+            {
+                const std::string& inputS = node_proto.input(node_proto.input_size() > 2 ? 2 : 1);
+                if (constBlobs.find(inputS) != constBlobs.end())
+                {
+                    Mat scales = getBlob(inputS);
+                    if (scales.total() == 4)
```
Comment (l-bat) [inline modules/dnn/src/onnx/onnx_importer.cpp:1783]: Can we replace this condition with a check: `CV_CheckEQ(scales.total(), 4, ""); `?

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 3]
```diff
@@ -1746,43 +1746,63 @@ void ONNXImporter::handleNode(const opencv_onnx::NodeProto& node_proto_)
...
+                if (shapes.depth() == CV_32F)
+                    shapes.convertTo(shapes, CV_32S);
+                layerParams.set("zoom_factor_y", shapes.at<int>(2));
+                layerParams.set("zoom_factor_x", shapes.at<int>(3));
+                foundScales = true;
+            }
+            else if (node_proto.input_size() > 1)
+            {
+                const std::string& inputS = node_proto.input(node_proto.input_size() > 2 ? 2 : 1);
+                if (constBlobs.find(inputS) != constBlobs.end())
```
Comment (l-bat) [inline modules/dnn/src/onnx/onnx_importer.cpp:1780]: It seems that this condition is always true, because we have a similar check above
```cpp
for (int i = 1; i < node_proto.input_size(); i++)
     CV_Assert(layer_id.find(node_proto.input(i)) == layer_id.end());
```

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 4]
```diff
@@ -1746,43 +1746,63 @@ void ONNXImporter::handleNode(const opencv_onnx::NodeProto& node_proto_)
...
+            bool foundScales = false;
+            if (hasDynamicShapes)
             {
-                if (node_proto.input_size() == 3) {
-                    IterShape_t shapeIt = outShapes.find(node_proto.input(0));
-                    CV_Assert(shapeIt != outShapes.end());
-                    MatShape scales = shapeIt->second;
-                    height *= scales[2];
-                    width *= scales[3];
+                Mat shapes = getBlob(node_proto, node_proto.input_size() - 1);
```
Comment (l-bat) [inline modules/dnn/src/onnx/onnx_importer.cpp:1767]:
```suggestion
                Mat scales = getBlob(node_proto, node_proto.input_size() - 1);
```

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 5]
```diff
@@ -1746,43 +1746,63 @@ void ONNXImporter::handleNode(const opencv_onnx::NodeProto& node_proto_)
...
+                    }
                 }
-                layerParams.set("width", width);
-                layerParams.set("height", height);
             }
 
-            if (layerParams.get<String>("mode") == "linear") {
-                layerParams.set("mode", interp_mode == "pytorch_half_pixel" ?
-                                        "opencv_linear" : "bilinear");
+            if( !foundScales )
```
Comment (l-bat) [inline modules/dnn/src/onnx/onnx_importer.cpp:1792]: Code in this block very similar to code in `if (hasDynamicShapes)` block. Can you try to combine them? Using condition only to determine we have scales or shapes.

**Comment by JulienMaille** [comment]
> @JulienMaille Why did you delete the CI config in PR description?

Because I intially copy pasted it from anyother PR without understanding what it does :)

File: modules/dnn/test/test_onnx_importer.cpp (hunk 1 above)
Comment (alalek) [reply modules/dnn/test/test_onnx_importer.cpp:547]: Usually it is very hard to investigate and debug combined tests.

Each test should be simple enough.

Comment (JulienMaille) [reply modules/dnn/test/test_onnx_importer.cpp]: mmhh I just grouped them before seeing your comment @alalek

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 5 above)
Comment (JulienMaille) [reply modules/dnn/src/onnx/onnx_importer.cpp:1787]: I see what I can do, it may hurt readability of the code, though

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 2 above)
Comment (JulienMaille) [reply modules/dnn/src/onnx/onnx_importer.cpp]: If I do so, we have 2 failing tests:
```
[ RUN      ] Test_ONNX_layers.ResizeUnfusedTwoInputs/0, where GetParam() = OCV/CPU
[ERROR:0] DNN/ONNX: ERROR during processing node with 4 inputs and 1 outputs: [Resize]:(25)
unknown file: Failure
C++ exception with description "OpenCV(3.4.13-pre) /build/precommit_linux64/3.4/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1897: error: (-2:Unspecified error) in function 'handleNode'
> Node [Resize]:(25) parse error: OpenCV(3.4.13-pre) /build/precommit_linux64/3.4/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1781: error: (-215:Assertion failed) scales.total() == 4 in function 'handleNode'
> " thrown in the test body.
```

**Comment by JulienMaille** [comment]
thanks to all reviewers! @l-bat are you ok with the changes?

**Review by l-bat — APPROVED** [review]
Thank you for valuable contribution! :+1:
