### PR TITLE
Fix OBS Virtual Camera capture.

### LINKED ISSUE #19746: DirectShow: VideoCapture returns blank frames for OBS Virtual Camera on Windows
##### System information (version)
- OpenCV => 4.5.1.48 (opencv-python)
- Operating System / Platform => Windows 10 64 Bit

##### Detailed description

[OBS](https://obsproject.com/) installs a DirectShow virtual camera which works fine in Zoom etc. but not in OpenCV via VideoCapture, all frames are either zeros or a bit of garbage at the top of the frame. I also checked it against the [CommandCam](https://github.com/mrihtar/CommandCam) tool which is a simple C++ frame grabber written in a single straight-forward file. No problems there as well. This is what `commandcam.exe /details` shows:

```
  2. OBS Virtual Camera
     Pin: Video Output, 6 caps
       Cap  0: FORMAT_VideoInfo, NV12, 12 bits, 1920x1080 @ 30 fps
       Cap  1: FORMAT_VideoInfo, I420, 12 bits, 1920x1080 @ 30 fps
       Cap  2: FORMAT_VideoInfo, YUY2, 16 bits, 1920x1080 @ 30 fps
       Cap  3: FORMAT_VideoInfo, NV12, 12 bits, 1280x720 @ 20 fps
       Cap  4: FORMAT_VideoInfo, I420, 12 bits, 1280x720 @ 20 fps
       Cap  5: FORMAT_VideoInfo, YUY2, 16 bits, 1280x720 @ 20 fps
```

I tried all pixel formats and resolutions (with the tool) and it worked for all combinations.

##### Steps to reproduce

First, install OBS. The virtual camera always streams a dummy picture.
Then, grab a frame with OpenCV.

```py
def decode_fourcc(fourcc):
    return chr((fourcc & 0xff)) + chr((fourcc & 0xff00) >> 8) + chr((fourcc & 0xff0000) >> 16) + chr((fourcc & 0xff000000) >> 24)

vc = cv2.VideoCapture(2, cv2.CAP_DSHOW)
assert vc.isOpened()

fourcc = decode_fourcc(int(vc.get(cv2.CAP_PROP_FOURCC)))
print(f'fourcc: {fourcc}') # fourcc: }ë6ä  --> with my real webcam this is YUY2

for _ in range(1000):
    ret, frame_captured = vc.read()
    assert ret
    print(frame_captured.min(), frame_captured.max())
    # 0 0
```

I should also mention that I set the environment variable `OPENCV_DSHOW_SAVEGRAPH_FILENAME=graph.grf` and [GraphEdit](https://docs.microsoft.com/en-us/windows/win32/directshow/using-graphedit) cannot open the file. It can open the file when I capture something from my real webcam device however. So somehow the filter graph must be broken.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by gottagofaster236**
Fixes #19746
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work

### CODE REVIEW

File: modules/videoio/src/cap_dshow.cpp [hunk 1]
```diff
@@ -2869,7 +2884,9 @@ int videoInput::start(int deviceID, videoDevice *VD){
     mt.majortype     = MEDIATYPE_Video;
 
     // Disable format conversion if using 8/16-bit data (e-Con systems)
-    if (checkSingleByteFormat(VD->pAmMediaType->subtype) || (VD->pAmMediaType->subtype == MEDIASUBTYPE_Y16)) {
+    if (checkSingleByteFormat(VD->pAmMediaType->subtype) ||
+        (VD->pAmMediaType->subtype == MEDIASUBTYPE_Y16 || VD->pAmMediaType->subtype == MEDIASUBTYPE_YUY2))
+    {
```
Comment (gottagofaster236) [inline modules/videoio/src/cap_dshow.cpp:2889]: Converting the YUY2 to BGR manually instead of using DirectShow helps with making the OBS Virtual Camera work. But I am not sure whether it is a bug in the OBS Virtual Camera or in the capture implementation.

**Comment by asmorkalov** [comment]
@mshabunin Could you take a look and comment?

**Review by opencv-alalek — APPROVED** [review]
- [x] Validated with OBS

Thank you for the contribution! LGTM :+1:
