### PR TITLE
Fixed getCPUCount | Issue #16268

### LINKED ISSUE #16183: Memory leak on K8S
##### System information (version)

- OpenCV => 4.1.0.25
- Operating System / Platform => ubuntu 18.04 image on k8s (host: centos 7.6)
- Docker version 19.03.4, build 9013bf583a
- K8S v1.15.3
- Compiler => installed with python pip

##### Detailed description

I have a tornado web service container using `cv2.imdecode`, and it causes memory leaking when I deployed the image to k8s, but it would not happen on the same machine with native docker rather than k8s.

I can reproduce the problem with the below code.

I used gdb `info threads` to find out that there were a lot of threads not collected:

```
(gdb) info threads
  Id   Target Id         Frame
* 1    Thread 0x7f78a8376580 (LWP 5991) "python" 0x00007f78a7c85603 in select () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x7f789ed93700 (LWP 5992) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f789e592700 (LWP 5993) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f789dd91700 (LWP 5994) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f7899590700 (LWP 5995) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7f7896d8f700 (LWP 5996) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f789458e700 (LWP 5997) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f7891d8d700 (LWP 5998) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7f788f58c700 (LWP 5999) "python" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
...more
```

when I tried to look into the thread, it seems my gdb is not well set:

```
(gdb) thread 5
[Switching to thread 5 (Thread 0x7fe775e0a700 (LWP 6052))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
```

The comparison I run with the native docker,  it just display:

```
(gdb) info threads
No threads.
```
It proves that threads were not properly collected on k8s.

##### Steps to reproduce

```python
import time
import cv2
import numpy as np

if __name__ == "__main__":
    with open("test.jpeg", "rb") as f:
        image = f.read()
        image_arr = np.fromstring(image, np.uint8)
        image_dec = cv2.imdecode(image_arr, cv2.IMREAD_COLOR)
        print(f"Image shape is {image_dec.shape}")

    while True:
        print("Sleep start")
        time.sleep(3)
        print("Sleep end")
```

### LINKED ISSUE #16268: cv::getCPUCount returns number of CPUs instead of available CPUs on Linux
On a system using the kernel argument `isolcpu`, or when using `taskset` to limit the CPUs available to the process OpenCV continues to allocate threads for all cores on the system even if they are not available to it. This causes OpenCV to create far more threads then is optimal for the target system.

https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/modules/core/src/parallel.cpp#L816

To obtain the actual number of cores available to the process one should use `sched_getaffinity` as such:

```
#include <sched.h>

int getCPUs()
{
  cpu_set_t cpu_set;
  sched_getaffinity(0, sizeof(cpu_set), &cpu_set);
  return CPU_COUNT(&cpu_set);
}
```

To workaround this bad behavior one can do the following:

```
cpu_set_t cpu_set;
sched_getaffinity(0, sizeof(cpu_set_t), &cpu_set);
cv::setNumThreads(std::max(1, CPU_COUNT(&cpu_set)-1));
```

### PR DESCRIPTION
**Pull request by ganesh-k13**
#### This pullrequest changes

Fixed getCPUCount to account for cgroups.
Added common code to parse CPU files into a generic function for android and Linux
Tested on Linux VMs, docker images, Kubernetes pods.

resolves #16268
resolves #16183

### CODE REVIEW

**Comment by ganesh-k13** [comment]
Hey @alalek, I do not have the environments of the failing builds, any idea how to solve?

**Comment by ganesh-k13** [comment]
In `org.opencv.test.core.CoreTest.testGetNumberOfCPUUs(CoreTest.java:637)` this line:
https://github.com/opencv/opencv/blob/223790e6fc5fb09d62b10d5616c2902fdc223579/modules/core/misc/java/test/CoreTest.java#L637

I'm not sure if it is true.

**Comment by ganesh-k13** [comment]
Checks pass now, open to suggestions.

**Comment by alalek** [comment]
Thank you for contribution!

Could you please squash commits and rebase onto 3.4 branch?

**Comment by ganesh-k13** [comment]
Thanks @alalek, done.

File: modules/core/src/parallel.cpp [hunk 1]
```diff
@@ -779,8 +773,51 @@ static inline int getNumberOfCPUsImpl()
...
+      return 1;
+
+   return getNumberOfCPUsImplFromFileStr(pbuf);
+}
+#endif
+
+#if (defined __linux__ || defined __GLIBC__ || defined __HAIKU__ || defined __EMSCRIPTEN__) && !defined __ANDROID__
+static inline unsigned getNumberOfCPUsImplLinux()
+{
+   FILE* cpuPossible = fopen("/sys/fs/cgroup/cpuset/cpuset.cpus", "r");
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp]: This is cgroup v1 files, for v2 it will be different:
http://man7.org/linux/man-pages/man7/cgroups.7.html
https://wiki.archlinux.org/index.php/cgroups

Shouldn't we first determine cgroup of current process and then use it in the path?

Comment (mshabunin) [reply modules/core/src/parallel.cpp]: Does HAIKU and EMSCRIPTEN have cgroups at all?

Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Thanks for the review @mshabunin, As per [this](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#mounting), they are backward compatible and we get the info we need from v1 itself. Open to change if required as I do not know much about it. 


> Does HAIKU and EMSCRIPTEN have cgroups at all?

I am not sure about this, but if the file does not exist, we handle that case by returning 0. Again open to removing it if needed, did not find much data on this.

File: modules/core/src/parallel.cpp [hunk 2]
```diff
@@ -779,8 +773,51 @@ static inline int getNumberOfCPUsImpl()
...
+   if(!cpuPossible)
+       return 0;
+
+   char buf[2000]; /* big enough for 1000 CPUs in worst possible configuration */
+   char *contents = fgets(buf, sizeof(buf), cpuPossible);
+   fclose(cpuPossible);
+
+   int cpusAvailable = strchr(contents, '-') == NULL ? atoi(contents) : getNumberOfCPUsImplFromFileStr(contents); /* In dockers, this file is a single number, can be (, -) seperated as well*/
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp]: > In dockers, this file is a single number

It can be anything:
```
docker run -it  --cpuset-cpus 1-2,5 ubuntu:18.04
# cat /sys/fs/cgroup/cpuset/cpuset.cpus 
1-2,5
```

File: modules/core/src/parallel.cpp [hunk 3]
```diff
@@ -789,12 +826,31 @@ int cv::getNumberOfCPUs(void)
...
+    }
+
+    /* Cases:
+     * 1. Both are zero return 1
+     * 2. Logical xor of ncpus_cgroup and ncpus_cpu_set is True:
+     *  2.1. ncpus_cgroup is 0, return ncpus_cpu_set
+     *  2.2. ncpus_cpu_set is 0, return ncpus_cgroup
+     * 3. Return min of zoth
+     */
+    static unsigned ncpus = ncpus_cgroup == 0 && ncpus_cpu_set == 0 ? 1 : (!ncpus_cgroup != !ncpus_cpu_set ? ncpus_cgroup | ncpus_cpu_set : (ncpus_cgroup < ncpus_cpu_set ? ncpus_cgroup : ncpus_cpu_set));
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp]: Please refactor very long lines like this one. We have soft limitation of 100 columns.

File: modules/core/src/parallel.cpp (hunk 1 above)
Comment (mshabunin) [reply modules/core/src/parallel.cpp]: I think it is better to restore previous behavior for HAIKU and EMSCRIPTEN cases.

File: modules/core/src/parallel.cpp (hunk 2 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Yeah, I noticed two types:
1. Just `3` or `4`, etc,  it can be interpreted as CPU 4 or 4 CPUs. If one number it means 4 CPUs
2. Next is `1-2,5`. here I just realized I look only for `-`, I'll look for `,` also, thanks

File: modules/core/src/parallel.cpp (hunk 3 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Sure

File: modules/core/src/parallel.cpp (hunk 1 above)
Comment (mshabunin) [reply modules/core/src/parallel.cpp]: I've rebooted with `cgroup_no_v1=all` option and this path is not available anymore:
```
$ ls /sys/fs/cgroup/
blkio        cpuset   freezer  memory            perf_event  rdma     unified
cpu,cpuacct  devices  hugetlb  net_cls,net_prio  pids        systemd
```
I think we should have fallback to previous method if it is not readable.

File: modules/core/src/parallel.cpp (hunk 2 above)
Comment (mshabunin) [reply modules/core/src/parallel.cpp]: I thought just `3` or `4` means one CPU with this id.

File: modules/core/src/parallel.cpp (hunk 1 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Oh cool, sounds good. I'll remove HAIKU and EMSCRIPTEN. I'll return 0 if the file is absent and handle.

File: modules/core/src/parallel.cpp (hunk 2 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Exactly what I thought too, you can try alpine, it gives count, surprised me as well.

Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]:
```
docker run -v $PWD:/var/tmp --cpuset-cpus=3 -it alpine sh
/ # cat /sys/fs/cgroup/cpuset/cpuset.cpus
3
```

```
docker run -v $PWD:/var/tmp --cpuset-cpus=4 -it alpine sh
/ # cat /sys/fs/cgroup/cpuset/cpuset.cpus
4
```

Comment (mshabunin) [reply modules/core/src/parallel.cpp]: What does it show? You set cpuset-cpus and get exactly what you've passed.
```
      --cpus decimal                   Number of CPUs
      --cpuset-cpus string             CPUs in which to allow execution (0-3, 0,1)
```
Docker image does not matter, kernel from the host system is used in containers.

Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Ohh I get what you are saying, ok I thought that was number of CPUs, thanks for the explanation, I'll fix that and the documentation error.

File: modules/core/src/parallel.cpp (hunk 1 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: I haven't removed Haiku and emscripten to avoid extra # ifs and a possibility of the file existing, but handled it logically.

**Comment by ganesh-k13** [comment]
@mshabunin, I have combined some of the android and linux code to reduce duplicates, I have also fixed the logic of cpus-sets by reusing android code.

**Comment by mshabunin** [comment]
Looks like this approach not work with `--cpus` Docker option, because it does not change cpuset-cpus. As I understand K8S mainly use this option to limit cpu load.

Perhaps we need to handle this case too by dividing cfs_quota to cfs_period and rounding the value, because this parameter supports fractional numbers.
```
$ docker run --cpus 2 -it ubuntu:18.04
# cat /sys/fs/cgroup/cpu/cpu.cfs_period_us 
100000
# cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us 
200000

$ docker run --cpus 1.3 -it ubuntu:18.04
# cat /sys/fs/cgroup/cpu/cpu.cfs_period_us
100000
# cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us
130000
```

**Comment by ganesh-k13** [comment]
Oh, thanks @mshabunin for finding this, I'll read up on this and get back to you

**Comment by ganesh-k13** [comment]
@mshabunin, I've handled `--cpus` case. I tested it on docker and a k8s pod as well.

File: modules/core/src/parallel.cpp [hunk 4]
```diff
@@ -789,12 +838,37 @@ int cv::getNumberOfCPUs(void)
...
+        if(ncpus_impl_cpuset == 0 && ncpus_impl_cfs == 0)
+            ncpus_impl = 1;
+        else if(!ncpus_impl_cpuset != !ncpus_impl_cfs)          /* One of them is zero */
+            ncpus_impl = ncpus_impl_cpuset | ncpus_impl_cfs;    /* Take non zero value */
+        else                                                    /* Both non zero, so take min*/
+            ncpus_impl = ncpus_impl_cpuset < ncpus_impl_cfs ? ncpus_impl_cpuset : ncpus_impl_cfs;
+
+        if(concurentThreadsSupported == 0) { /* somehow hardware_concurrency failed or c++ version < 11 */
+            cpu_set_t cpu_set;
+            sched_getaffinity(0, sizeof(cpu_set), &cpu_set);
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp]: Looks like this API is only available on Linux and only in case when `_GNU_SOURCE` is enabled: https://linux.die.net/man/2/sched_getaffinity

Function call should be checked for errors.

On my platform `std::thread::hardware_concurrency` returns 8, thus affinity check is effectively disabled.

File: modules/core/src/parallel.cpp [hunk 5]
```diff
@@ -775,12 +791,45 @@ static inline int getNumberOfCPUsImpl()
...
+    ss_quota >> cfs_period;
+    delete[] file_contents;
+
+    return (unsigned) cfs_quota/cfs_period;
 }
 #endif
 
 int cv::getNumberOfCPUs(void)
 {
+#if __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1900)
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp]: Wouldn't `CV_CXX11` macro work here?

**Comment by ganesh-k13** [comment]
Thanks for the review @mshabunin, I'll address them. As for priority, I think we can take minimum most value if we have many options as that is always the most probable value.

**Comment by mshabunin** [comment]
@ganesh-k13 , yes minimum should be good. Maybe something like this will be more clear (variables and functions should have meaningful names ofc):
```.cpp
int result = 0;

#if CV_HAVE_METHOD_1
static const int m1 = getCPUS_method1();
if (result > 0 && m1 > 0 && result > m1)
    result = m1;
#endif

#if CV_HAVE_METHOD_2
...
#endif

return result > 0 ? result : 1;
```

**Comment by ganesh-k13** [comment]
Yes, that is much clearer @mshabunin, I'll do like that. Thanks.

File: modules/core/src/parallel.cpp (hunk 4 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: I seem to have missed this, I'll add it

**Comment by ganesh-k13** [comment]
@mshabunin, can you please review the changes.

File: modules/core/src/parallel.cpp [hunk 6]
```diff
@@ -816,9 +897,10 @@ int cv::getNumberOfCPUs(void)
             numCPU = 1;
     }
 
-    return (int)numCPU;
+    unsigned ncpus = min_non_zero(concurentThreadsSupported, (unsigned)numCPU);
+    return ncpus != 0 ? ncpus : 1;
 #else
-    return 1;
+    return concurentThreadsSupported != 0 ? concurentThreadsSupported : 1;
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: > return ncpus != 0 ? ncpus : 1;
> return ncpus != 0 ? ncpus : 1;
> return ncpus != 0 ? ncpus : 1;
> return ncpus != 0 ? ncpus : 1;
> return concurentThreadsSupported != 0 ? concurentThreadsSupported : 1;

There are 5 similar returns above.
Please make return once.
Rename `concurentThreadsSupported` => `ncpus` to reduce code.

File: modules/core/src/parallel.cpp [hunk 7]
```diff
@@ -775,26 +796,86 @@ static inline int getNumberOfCPUsImpl()
...
+#endif
+
+#if defined CV_HAVE_CGROUP
+static inline unsigned getNumberOfCPUsCFS(void)
+{
+    std::string file_contents = getFileContents("/sys/fs/cgroup/cpu/cpu.cfs_quota_us");
+    if(file_contents.empty())
+        return 0;
+
+    std::stringstream ss_period(file_contents);
```
Comment (alalek) [inline modules/core/src/parallel.cpp]:
```.diff
-std::stringstream
+std::istringstream
```

File: modules/core/src/parallel.cpp [hunk 8]
```diff
@@ -77,6 +86,10 @@
     #define HAVE_CONCURRENCY
 #endif
 
+#if defined __linux__ || defined __GLIBC__ || defined __HAIKU__ || defined __EMSCRIPTEN__
+   #define CV_HAVE_CGROUP
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: `__EMSCRIPTEN__` doesn't have cgroups.

File: modules/core/src/parallel.cpp [hunk 9]
```diff
@@ -45,6 +45,10 @@
 #include <opencv2/core/utils/configuration.private.hpp>
 #include <opencv2/core/utils/trace.private.hpp>
 
+#define min_non_zero(val_1, val_2)                                                    \
+   (((val_1 > 0) && (val_2 > 0) && (val_1 > val_2)) || ((val_1 == 0) && (val_2 > 0))) \
+   ? val_2 : val_1
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: Please implement this as `static inline` function near `getNumberOfCPUs()` (line 830)

File: modules/core/src/parallel.cpp [hunk 10]
```diff
@@ -775,26 +796,86 @@ static inline int getNumberOfCPUsImpl()
...
+        return 0;
+
+    std::stringstream ss_quota(file_contents);
+    int cfs_period;
+    ss_quota >> cfs_period;
+
+    if(cfs_period < 1)
+        return 0;
+
+    return (unsigned) cfs_quota/cfs_period;
```
[the remark this answers is not in the document]
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: This gets taken care of in the return, if 0.

File: modules/core/src/parallel.cpp (hunk 6 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Oh ok, thanks, will do

File: modules/core/src/parallel.cpp (hunk 8 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Can you suggest another name :) ? I think it's easier if we include  __EMSCRIPTEN__

File: modules/core/src/parallel.cpp (hunk 9 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Sure

**Comment by ganesh-k13** [comment]
Thanks @alalek, I'll address them.

File: modules/core/src/parallel.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (alalek) [reply modules/core/src/parallel.cpp]: I'm about the case with CPU=0.5

File: modules/core/src/parallel.cpp [hunk 11]
```diff
@@ -775,26 +796,86 @@ static inline int getNumberOfCPUsImpl()
...
 
-    return (int)sysinfo.dwNumberOfProcessors;
+    return ncpus != 0 ? ncpus : 1;
 #elif defined __ANDROID__
-    static int ncpus = getNumberOfCPUsImpl();
-    return ncpus;
-#elif defined __linux__ || defined __GLIBC__ || defined __HAIKU__ || defined __EMSCRIPTEN__
-    return (int)sysconf( _SC_NPROCESSORS_ONLN );
+    unsigned ncpus = concurentThreadsSupported;
+    static unsigned ncpus_impl = (unsigned)getNumberOfCPUsImpl("/sys/devices/system/cpu/possible");
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: > /sys/devices/system/cpu/possible

This is valid on regular Linux too.

File: modules/core/src/parallel.cpp [hunk 12]
```diff
@@ -775,26 +796,86 @@ static inline int getNumberOfCPUsImpl()
...
+    #if defined _GNU_SOURCE
+        cpu_set_t cpu_set;
+        if(!sched_getaffinity(0, sizeof(cpu_set), &cpu_set)) {
+            unsigned cpu_count_cpu_set = CPU_COUNT(&cpu_set);
+            ncpus = min_non_zero(ncpus, cpu_count_cpu_set);
+        }
+    #endif
+
+    static unsigned cpu_count_sysconf = (unsigned)sysconf( _SC_NPROCESSORS_ONLN );
+    ncpus = min_non_zero(ncpus, cpu_count_sysconf);
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: Just split this block on 4 cases through sequence (moving "return" to the end would allow that).

`sched_getaffinity()` is applicable on Android too.

File: modules/core/src/parallel.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Oh, I assumed we take floor so we return 0. Should I take ceil?

[the remark this answers is not in the document]
Comment (alalek) [reply modules/core/src/parallel.cpp]: Rounding with truncation is fine except range (0, 1). I believe this should work better:
```
max(1u, (unsigned)cfs_quota/cfs_period);
```

[the remark this answers is not in the document]
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Oh ok that makes sense, 0.5 makes 1 the valid count, since we take min_non_zero, we might end up taking a bigger value like 8 from other methods cause this is 0. Thanks for explaining.

File: modules/core/src/parallel.cpp (hunk 12 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: @alalek, can I check cgroups for android as well?

**Comment by ganesh-k13** [comment]
Ok so Andriod is just hard when it comes to `sched_getaffinity`, seems like it's not directly supported due to missing `cpu_set_t`. Any pointers on how to proceed and should we even include this in Andriod code path? Open to other review comments as well. @alalek.

**Comment by asmorkalov** [comment]
@ganesh-k13 I propose to preserve original implementation for Andoird and do not use cgroups option there.

**Comment by ganesh-k13** [comment]
Sure @asmorkalov, will do.

**Comment by ganesh-k13** [comment]
@alalek / @asmorkalov / @mshabunin , can you please review?

File: modules/core/src/parallel.cpp [hunk 13]
```diff
@@ -77,6 +84,14 @@
     #define HAVE_CONCURRENCY
 #endif
 
+#if (defined __linux__ || defined __GLIBC__ || defined __HAIKU__ || defined __EMSCRIPTEN__) && !defined __ANDROID__
+   #define CV_LINUX_GROUPS
+#endif
+
+#if (defined __linux__ || defined __GLIBC__ || defined __HAIKU__) && !defined __ANDROID__
```
Comment (asmorkalov) [inline modules/core/src/parallel.cpp]: HAIKU is not Linux distribution, it's OSS BeOS implementation with it's own kernel and it does not support CGroups. GLIBC is not requirement for it too. I propose to stay with condition `#if (defined __linux__ && !defined __ANDROID__)`

File: modules/core/src/parallel.cpp [hunk 14]
```diff
@@ -775,26 +798,102 @@ static inline int getNumberOfCPUsImpl()
       }
 
    }
-   return cpusAvailable ? cpusAvailable : 1;
+   return cpusAvailable;
+}
+#endif
+
+#if defined CV_LINUX_GROUPS
```
Comment (asmorkalov) [inline modules/core/src/parallel.cpp]: It should be `CV_HAVE_CGROUPS`

File: modules/core/src/parallel.cpp [hunk 15]
```diff
@@ -775,26 +798,102 @@ static inline int getNumberOfCPUsImpl()
...
+#elif defined CV_LINUX_GROUPS
+    #if defined CV_HAVE_CGROUPS
+        static unsigned ncpus_impl_cpuset = (unsigned)getNumberOfCPUsImpl("/sys/fs/cgroup/cpuset/cpuset.cpus");
+        ncpus = minNonZero(ncpus, ncpus_impl_cpuset);
+
+        static unsigned ncpus_impl_cfs = getNumberOfCPUsCFS();
+        ncpus = minNonZero(ncpus, ncpus_impl_cfs);
+    #endif
+
+    static unsigned ncpus_impl_devices = (unsigned)getNumberOfCPUsImpl("/sys/devices/system/cpu/possible");
```
Comment (alalek) [inline modules/core/src/parallel.cpp]: BTW, Why is `/possible` here? (I know that it was here before patch)

See https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu:

> online: cpus that are online and being scheduled.
> possible: cpus that have been allocated resources and can be brought online if they are present.

I believe we should use `/online` instead:
```
# cat /sys/devices/system/cpu/online /sys/devices/system/cpu/possible 
0-3
0-3
root ~# echo 0 > /sys/devices/system/cpu/cpu3/online
root ~# cat /sys/devices/system/cpu/online /sys/devices/system/cpu/possible 
0-2
0-3
```

or even both: https://devtalk.nvidia.com/default/topic/1042662/jetson-tx1/-sys-devices-system-cpu-cpu-online-missing-in-the-latest-jetpack-l4t-release/ and select minimal as regular

Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Thanks for the info, I'll read up more on it.

File: modules/core/src/parallel.cpp (hunk 13 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: Yeah, I think I'll restructure the way we handle Linux, probably just split up the Linux group as there are many uncommon blocks

File: modules/core/src/parallel.cpp (hunk 15 above)
Comment (ganesh-k13) [reply modules/core/src/parallel.cpp]: This is very true, `/possible` is showing the hardware count, 128 in my case over just `6` for the VM. I saw a few more options and `online` seems to be right. But Android also has CGroups apparently, Can I add it to CGroups list?

Comment (alalek) [reply modules/core/src/parallel.cpp]: > Android
> Can I add it to CGroups list?

I believe - yes. It is harmless (just a check for missing files in worst case)

**Comment by ganesh-k13** [comment]
@alalek and @asmorkalov, I have made some changes. Open to any changes, this was just my first thoughts on handling Linux and Andriod based stuff. Let me know what needs to be done.

File: modules/core/src/parallel.cpp [hunk 16]
```diff
@@ -77,6 +84,17 @@
     #define HAVE_CONCURRENCY
 #endif
 
+#if defined __linux__ || defined __GLIBC__ || defined __EMSCRIPTEN__ || defined __HAIKU__
+   #define CV_CPU_GROUPS_1
+   #if defined __ANDROID__
```
Comment (asmorkalov) [inline modules/core/src/parallel.cpp]: You can remove the condition, it's already handled in line 94.
