### PR TITLE
cuda::GpuMat::convertTo - fix for in-place arguments

### LINKED ISSUE #13092: cv::cuda::GpuMat.convertTo() seems not to support in-place, while cv::Mat does
Visual Studio 2017, Windows 7 64 bits, OpenCV 3.4.3
Cuda 10

the following code raises an exception :

```
  cv::cuda::GpuMat m(cv::Size(1280, 1024), CV_32FC1);
  cv::cuda::Stream stream;
  m.convertTo(m, CV_8UC1, 1, 0, stream);
  cv::cuda::threshold(m, m, 128, 255, cv::THRESH_BINARY, stream);
```

> OpenCV(3.4.3) Error: Gpu API call (an illegal memory access was encountered) in
> cv::cudev::grid_transform_detail::TransformDispatcher<true, Policy>::call, file
> e:\opencv-3.4.3\opencv\sources\modules\cudev\include\opencv2\cudev\grid\detail/t
> ransform.hpp, line 318

Using a second matrix as a destination for the convertTo() gets rid of the problem.

So it seems that convertTo() is no safe to use *in-place* with cuda::GpuMat, while the same code with cv::Mat would be ok.
Is it a bug or a missing documentation ?

### PR DESCRIPTION
**Pull request by nglee**
Resolves #13092

If given in-place arguments to `GpuMat::convertTo`, `*this` and `dst` refers to the same newly allocated GpuMat after these two lines:
```
_dst.create(size(), rtype);
GpuMat dst = _dst.getGpuMat();
```

<cut/>

In consequence, `*this` refers to a different GpuMat from which `src` refers to.

Before this PR, in the following line:
```
funcs[sdepth][ddepth](reshape(1), dst.reshape(1), stream);
```
the first argument derives from `*this` which refers to the same data as `dst`.

So it should be fixed as the following line to make the first argument derive from `src`:
```
funcs[sdepth][ddepth](src.reshape(1), dst.reshape(1), stream);
                      ^^^^
```

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4
build_image:Custom=ubuntu-cuda:18.04

allow_multiple_commits=1
```

### CODE REVIEW

**Comment by mshabunin** [comment]
@nglee , could you please add a small test for this scenario or extend one of existing tests?

**Comment by nglee** [comment]
@mshabunin There's some tests included in this PR(https://github.com/opencv/opencv/pull/17982/commits/11ac26bfb43ad6e10c2bd50bbba0489e2bc26a79). Should I add more?

**Comment by mshabunin** [comment]
>  There are some tests included in this PR

Oh, I see now, perhaps I was reviewing only first commit.

File: modules/cudaarithm/test/test_gpumat.cpp [hunk 1]
```diff
@@ -320,6 +320,65 @@ CUDA_TEST_P(GpuMat_ConvertTo, WithScaling)
...
+    }
+    else
+    {
+        cv::cuda::GpuMat d_srcDst = loadMat(src, useRoi);
+        d_srcDst.convertTo(d_srcDst, depth2, a, b);
+
+        cv::Mat dst_gold;
+        src.convertTo(dst_gold, depth2, a, b);
+
+        EXPECT_MAT_NEAR(dst_gold, d_srcDst, depth2 < CV_32F ? 1.0 : 1e-4);
```
Comment (asmorkalov) [inline modules/cudaarithm/test/test_gpumat.cpp:378]: Why 1.0 for integer types? Where do you have troubles with it?

**Comment by asmorkalov** [comment]
@alalek Could you look at it? I'm not sure that convertTo is suitable for in-place processing in general case.

File: modules/cudaarithm/test/test_gpumat.cpp (hunk 1 above)
Comment (nglee) [reply modules/cudaarithm/test/test_gpumat.cpp:378]: The values(`1.0`, `1e-4`) are equal to existing non-in-place tests, which these in-place tests are copied from:
https://github.com/opencv/opencv/blob/11ac26bfb43ad6e10c2bd50bbba0489e2bc26a79/modules/cudaarithm/test/test_gpumat.cpp#L287

Comment (nglee) [reply modules/cudaarithm/test/test_gpumat.cpp:378]: For these tests:
`CUDA_TEST_P(GpuMat_ConvertTo, WithOutScaling)`
`CUDA_TEST_P(GpuMat_ConvertTo, InplaceWithOutScaling)`
we can set the tolerance to `0.0`.

But for tests that include scaling:
`CUDA_TEST_P(GpuMat_ConvertTo, WithScaling)`
`CUDA_TEST_P(GpuMat_ConvertTo, InplaceWithScaling)`
some tests fail when tolerance is `0.0`, but pass for `1.0`.
Maybe this is acceptable since scaling includes multiplication?

**Comment by nglee** [comment]
@alalek @asmorkalov Would you take a look at this comment: https://github.com/opencv/opencv/pull/17982#discussion_r463705873

**Comment by nglee** [comment]
To justify why this fix is needed, other codes get the source matrix from `src`, not `*this` such as here:
https://github.com/opencv/opencv/blob/793e7c0d9fdb70d7b9f758322d1a59ee585bdc93/modules/core/src/cuda/gpu_mat.cu#L626

@asmorkalov 
> I'm not sure that convertTo is suitable for in-place processing in general case.

Even if arguments to `converTo` are given in an in-place manner if the destination `GpuMat` type differs from the source `GpuMat` type, it allocates new GPU memory. So in essence, it is not an in-place conversion internally.
