### PR TITLE
Unhandled Objective-C exception when playing video

### LINKED ISSUE #8305: Python quit unexpectedly while using the libopencv_highgui.2.4.dylib plug-in
##### System information (version)

- OpenCV => 2.4.13.2
- Operating System / Platform => OS X El Capitan
- Language: Python

##### Detailed description

OpenCv library with python client works perfectly for the image processing. However, it throws up error when I try to use VideoCapture method.

##### Steps to reproduce

 ```.py
import numpy as np
import cv2
import sys

cap = cv2.VideoCapture("peopleCounter.avi")

w = cap.get(3) #get width
h = cap.get(4) #get height

mx = int(w/2)
my = int(h/2)

count = 0
ret, frame = cap.read()
while(cap.isOpened()):
    ret, frame = cap.read() #read a frame
    try:
        count = count + 1
        text = "Hello World " + str(count)
        cv2.putText(frame, text ,(mx,my),cv2.FONT_HERSHEY_SIMPLEX
                    ,1,(255,255,255),1,cv2.LINE_AA)
        cv2.imshow('Frame',frame)
    except:
        #if there are no more frames to show...
        print('EOF')
        break

    #Abort and exit with 'Q' or ESC
    k = cv2.waitKey(1000) & 0xff
    if k == 27:
        break

cap.release() #release video file
cv2.destroyAllWindows() #close all openCV windows
````
##### Error messsage
screen shot 2017-03-02 at 3 44 18 am

### PR DESCRIPTION
**Pull request by sabzo**
Resolves #8305 

### This pullrequest changes

Out of bound array unhandled exception in Objective C when playing a video in C, C++, Python>

### CODE REVIEW

**Comment by alalek** [comment]
:+1:

File: modules/highgui/src/cap_avfoundation_mac.mm [hunk 1]
```diff
@@ -697,7 +697,15 @@ -(int) updateImage {
         return;
     }
 
-    mAssetTrack = [[mAsset tracksWithMediaType: AVMediaTypeVideo][0] retain];
+    NSArray *tracks = [mAsset tracksWithMediaType:AVMediaTypeAudio];
```
Comment (alalek) [inline modules/highgui/src/cap_avfoundation_mac.mm]: Typo is here: "Audio"
Fixed #8980
