### PR TITLE
`VideoCapture`: change `CAP_PROP_FOURCC` to fix #22876

### LINKED ISSUE #22876: VideoCapture (CAP_FFMPEG) returns the incorrect fourcc codec due to codec_tag representing the underlying stream type
### System Information

OpenCV version: 4.6.0
Operating System / Platform: Windows 11
Compiler & compiler version: Visual Studio 2022

### Detailed description

VideoCapture with the FFmpeg back end returns the incorrect codec fourcc when the codec_tag represents the underlying stream type.

The existing logic is to return the `codec_tag` if it exists and igored the `codec_id`
https://github.com/opencv/opencv/blob/bc6544c0bcfa9ca5db5e0d0551edf5c8e7da3852/modules/videoio/src/cap_ffmpeg_impl.hpp#L1725

This is fine if the `codec_tag` is valid but, if it is invalid and the `codec_id` is valid this logic fails.

For example [this](https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/)  MPEG-TS video has a valid
`codec_id== AV_CODEC_ID_HEVC (173)`
and invalid
`codec_tag ==36` 
the MPEG-TS stream type.

Additonaly because the [`codec_tag`](https://github.com/opencv/opencv/blob/e3e1f704a4c59a38747102d586925e05de1729aa/modules/videoio/src/cap_ffmpeg_impl.hpp#L1717) is
```
/**
 * Additional information about the codec (corresponds to the AVI FOURCC).
 */
uint32_t         codec_tag;
```
the fourcc returned for the three test video's below is `mp4v`
> highgui/video/big_buck_bunny.mp4
> highgui/video/sample_322x242_15frames.yuv420p.mpeg2video.mp4
> highgui/video/sample_322x242_15frames.yuv420p.mjpeg.mp4

when they use MPEG-4, MPEG-2 and MJPG respectively.

I can think of easy fixes:
1) Only use the `codec_tag` if the `codec_id` is unavaliable.  This may pass all the test cases but break existing user code.
2) Add an additional property, i.e. `CAP_PROP_CODEC_ID_FOURCC` or similar, which a user can fall back on if the fourcc returned from `CAP_PROP_FOURCC `is garbage.  This is clunky but it is guaranteed not to break any existing user code.

### Steps to reproduce

Video from https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/
```
VideoCapture cap("LG New York HDR UHD 4K Demo.ts",CAP_FFMPEG);
const double fourcc = cap.get(CAP_PROP_FOURCC);
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by cudawarped**
Address #22876 by adding a `CAP_PROP_CODEC_FOURCC` to the `VideoCapture` FFmpeg backend.
Merge with https://github.com/opencv/opencv_contrib/pull/3488

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/videoio/include/opencv2/videoio.hpp [hunk 1]
```diff
@@ -211,6 +211,7 @@ enum VideoCaptureProperties {
        CAP_PROP_CODEC_EXTRADATA_INDEX = 68, //!< Positive index indicates that returning extra data is supported by the video back end.  This can be retrieved as cap.retrieve(data, <returned index>).  E.g. When reading from a h264 encoded RTSP stream, the FFmpeg backend could return the SPS and/or PPS if available (if sent in reply to a DESCRIBE request), from calls to cap.retrieve(data, <returned index>).
        CAP_PROP_FRAME_TYPE = 69, //!< (read-only) FFmpeg back-end only - Frame type ascii code (73 = 'I', 80 = 'P', 66 = 'B' or 63 = '?' if unknown) of the most recently read frame.
        CAP_PROP_N_THREADS = 70, //!< (**open-only**) Set the maximum number of threads to use. Use 0 to use as many threads as CPU cores (applicable for FFmpeg back-end only).
+       CAP_PROP_CODEC_FOURCC = 71, //!< 4-character code representing type of the encoded data (the codec used).  This differs from CAP_PROP_FOURCC which can represent additional  information about the codec. e.g. CAP_PROP_FOURCC can return divx, xvid, mp4v etc. for an MPEG-4 video where CAP_PROP_CODEC_FOURCC would return only FMP4 (applicable for FFmpeg back-end only).
```
Comment (opencv-alalek) [inline modules/videoio/include/opencv2/videoio.hpp:214]: There is some mess with:

```
CAP_PROP_FOURCC         =6, //!< 4-character code of codec. see VideoWriter::fourcc .
```

Both describes the "codec".
We could deprecate the old one, but we need robust and clear solution.

BTW, there are 3 different FOURCC could be used in some pipelines: camera firmware/device level(MJPEG compression), codec(YUV), output of VideoCapture(BGR24).

Comment (cudawarped) [reply modules/videoio/include/opencv2/videoio.hpp]: @opencv-alalek updated to translate `codec_id` to fourcc and fallback to `codec_tag` if this doesn't exist.  This seems like a robust solution, the returned value will now "always" (apart from when the `codec_id` field doesn't exist) be the `4-character code of codec`.

**Comment by cudawarped** [comment]
@opencv-alalek I know your reworking this but I added a PR with the chages I made inside `cudacodec::VideoReader` to use the new codec value for consistency.

**Comment by cudawarped** [comment]
@opencv-alalek Are you happy with the approach in this PR?  Forcing `CAP_PROP_FOURCC` to be the codec if there is a `codec_id` to be consistent with the property description?

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by asmorkalov** [comment]
The issue is still there:
```
[ RUN      ] CUDA_Codec/Video.Reader/8, where GetParam() = (NVIDIA GeForce GTX 1080, "highgui/video/sample_322x242_15frames.yuv420p.libaom-av1.mp4")
[ERROR:0@1.303] global cap_ffmpeg_impl.hpp:1237 open Could not find decoder for codec_id=32797
[ERROR:0@1.303] global cap_ffmpeg_impl.hpp:1286 open VIDEOIO/FFMPEG: Failed to initialize VideoCapture
[ WARN:0@1.303] global cap.cpp:206 open VIDEOIO(FFMPEG): backend is generally available but can't be used to capture by name
[ERROR:1@1.307] global video_decoder.cpp:127 create Video source is not supported by hardware video decoder.
[ERROR:1@1.307] global video_parser.cpp:169 HandleVideoSequence Attempt to configure Nvidia decoder failed!
[ERROR:1@1.307] global video_parser.cpp:83 parseVideoData Call to cuvidParseVideoData failed!
unknown file: Failure
C++ exception with description "OpenCV(4.7.0-dev) /home/alexander/Projects/OpenCV/opencv_contrib/modules/cudacodec/src/video_reader.cpp:212: error: (-2:Unspecified error) Parsing/Decoding video source failed, check GPU memory is available and GPU supports hardware decoding. in function 'internalGrab'
" thrown in the test body.
[  FAILED  ] CUDA_Codec/Video.Reader/8, where GetParam() = (NVIDIA GeForce GTX 1080, "highgui/video/sample_322x242_15frames.yuv420p.libaom-av1.mp4") (66 ms)
[ RUN      ] CUDA_Codec/Video.Reader/9, where GetParam() = (NVIDIA GeForce GTX 1080, "cv/tracking/faceocc2/data/faceocc2.webm")
[       OK ] CUDA_Codec/Video.Reader/9 (145 ms)
[ RUN      ] CUDA_Codec/Video.Reader/10, where GetParam() = (NVIDIA GeForce GTX 1080, "highgui/video/sample_322x242_15frames.yuv420p.mpeg2video.mp4")
Ошибка сегментирования (стек памяти сброшен на диск)
```
