### PR TITLE
pyrDown: offset HAL added, IPP removed

### LINKED ISSUE #25976: IPP implementation for cv::pyrDown is incorrect
### System Information

OpenCV version: 4.10 and earlier

### Detailed description

Current IPP implementation for `cv::pyrDown` is actually a copypaste of a code from IPP's wrapper for `cv::pyrUp`
Although it's turned off because of accuracy, I propose to remove this code since it's completely incorrect and cannot be easily fixed without rewriting it from scratch.

### Steps to reproduce

See the code [here](https://github.com/opencv/opencv/blob/2a333a6c86b7fd88bd21fd92e8d828aa6a0b595c/modules/imgproc/src/pyramids.cpp#L1272) and [here](https://github.com/opencv/opencv/blob/2a333a6c86b7fd88bd21fd92e8d828aa6a0b595c/modules/imgproc/src/pyramids.cpp#L1460)

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by savuor**
Resolves #25976

### Changes
* HAL added for offset support so that border pixels can be fetched from outside of the image ROI (see `BORDER_ISOLATED` parameter)
* IPP removed since there is `pyrUp` instead of `pyrDown` and there's no easy way to fix this other than rewriting it from scratch
* replaced old C call by modern `cv::pyrDown`

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/src/pyramids.cpp [hunk 1]
```diff
@@ -1266,6 +1266,8 @@ static bool ocl_pyrUp( InputArray _src, OutputArray _dst, const Size& _dsz, int
 
 }
 
+// TODO: enable it when the corresponding IPP code is fixed
```
Comment (asmorkalov) [inline modules/imgproc/src/pyramids.cpp:1269]: Need to describe the issue, or, better, create a ticket and add link here.

File: modules/imgproc/src/pyramids.cpp [hunk 2]
```diff
@@ -1266,6 +1266,8 @@ static bool ocl_pyrUp( InputArray _src, OutputArray _dst, const Size& _dsz, int
...
+#if 0
```
Comment (asmorkalov) [inline modules/imgproc/src/pyramids.cpp:1270]: It's already disabled.
modules/core/include/opencv2/core/private.hpp:198:#define IPP_DISABLE_PYRAMIDS_DOWN       1 // Different results

File: modules/imgproc/src/pyramids.cpp (hunk 1 above)
Comment (savuor) [reply modules/imgproc/src/pyramids.cpp:1269]: Opened an issue: #25976
Since there's no corresponding functions in ippicv, I propose to remove this implementation.
It's easier to write it from scratch than fixing this code that looks like it's in a middle of refactoring.

File: modules/imgproc/src/pyramids.cpp [hunk 3]
```diff
@@ -1426,15 +1363,21 @@ void cv::pyrDown( InputArray _src, OutputArray _dst, const Size& _dsz, int borde
...
-
-#ifdef HAVE_IPP
-    bool isolated = (borderType & BORDER_ISOLATED) != 0;
-    int borderTypeNI = borderType & ~BORDER_ISOLATED;
-#endif
-    CV_IPP_RUN(borderTypeNI == BORDER_DEFAULT && (!_src.isSubmatrix() || isolated) && dsz == Size((_src.cols() + 1)/2, (_src.rows() + 1)/2),
-        ipp_pyrdown( _src,  _dst,  _dsz,  borderType));
+    Point ofs;
+    Size wsz(src.cols, src.rows);
+    if(!(borderType & BORDER_ISOLATED))
```
Comment (opencv-alalek) [inline modules/imgproc/src/pyramids.cpp:1368]: submat check should be used too.

File: modules/imgproc/src/pyramids.cpp [hunk 4]
```diff
@@ -1426,15 +1363,21 @@ void cv::pyrDown( InputArray _src, OutputArray _dst, const Size& _dsz, int borde
...
+        CALL_HAL(pyrDown, cv_hal_pyrdown_offset, src.data, src.step, src.cols, src.rows,
+                 dst.data, dst.step, dst.cols, dst.rows, depth, src.channels(),
+                 ofs.x, ofs.y, wsz.width - src.cols - ofs.x, wsz.height - src.rows - ofs.y, borderType & (~BORDER_ISOLATED));
+    }
+    else
+    {
+        CALL_HAL(pyrDown, cv_hal_pyrdown, src.data, src.step, src.cols, src.rows, dst.data, dst.step, dst.cols, dst.rows, depth, src.channels(), borderType);
+    }
 
+    // IPP code was incorrect, removed
```
Comment (asmorkalov) [inline modules/imgproc/src/pyramids.cpp:1380]: Please remove the comment too. It's not relevant any more.

**Review by asmorkalov — APPROVED** [review]

File: modules/imgproc/src/pyramids.cpp [hunk 5]
```diff
@@ -1426,15 +1363,19 @@ void cv::pyrDown( InputArray _src, OutputArray _dst, const Size& _dsz, int borde
...
-    CALL_HAL(pyrDown, cv_hal_pyrdown, src.data, src.step, src.cols, src.rows, dst.data, dst.step, dst.cols, dst.rows, depth, src.channels(), borderType);
-
-#ifdef HAVE_IPP
-    bool isolated = (borderType & BORDER_ISOLATED) != 0;
-    int borderTypeNI = borderType & ~BORDER_ISOLATED;
-#endif
-    CV_IPP_RUN(borderTypeNI == BORDER_DEFAULT && (!_src.isSubmatrix() || isolated) && dsz == Size((_src.cols() + 1)/2, (_src.rows() + 1)/2),
-        ipp_pyrdown( _src,  _dst,  _dsz,  borderType));
-
+    Point ofs;
```
Comment (opencv-alalek) [inline modules/imgproc/src/pyramids.cpp:1366]: Scope of this variable could be reduced.

File: modules/imgproc/src/pyramids.cpp [hunk 6]
```diff
@@ -1426,15 +1363,19 @@ void cv::pyrDown( InputArray _src, OutputArray _dst, const Size& _dsz, int borde
...
+    Size wsz(src.cols, src.rows);
```
Comment (opencv-alalek) [inline modules/imgproc/src/pyramids.cpp:1367]: the same.

**Review by vpisarev — APPROVED** [review]

File: modules/imgproc/src/hal_replacement.hpp [hunk 7]
```diff
@@ -1049,6 +1049,33 @@ inline int hal_ni_pyrdown(const uchar* src_data, size_t src_step, int src_width,
...
+   @param dst_height Destination image height
+   @param depth Depths of source and destination image
+   @param cn Number of channels
+   @param margin_left Left margins for source image
+   @param margin_top Top margins for source image
+   @param margin_right Right margins for source image
+   @param margin_bottom Bottom margins for source image
+   @param border_type Border type
+*/
+inline int hal_ni_pyrdown_offset(const uchar* src_data, size_t src_step, int src_width, int src_height,
```
Comment (vpisarev) [inline modules/imgproc/src/hal_replacement.hpp:1070]: What is our plan to enable such feature in all filters. Starting with the name - shall we use _roi in the name? And pass the whole image size and roi inside?

How to make it python-compatible? (Numpy does not have a notion of roi)

Comment (asmorkalov) [reply modules/imgproc/src/hal_replacement.hpp:1070]: 1. It's already done in current HAL API for filters.
2. Python and Numpy is not related here. Unfortunately we do not have solution for it.

Comment (savuor) [reply modules/imgproc/src/hal_replacement.hpp:1070]: * Numpy supports array slicing (though I am not sure if the slices can be passed outside of the Python)
* Taking the ROI from source image then applying filter should produce the same result as doing it vice versa (i.e. applying filter then taking the ROI of the result).
  We can recommend Python users to stick to the second option at cost of performance.
