### PR TITLE
Fix double definitions, correct comment.

### LINKED ISSUE #9925: minor - double definition of CALC_SUM_, CALC_SUM in cascadedetect.hpp
##### System information (version)
- OpenCV => 3.3

##### Detailed description
In the file:
../modules/objdetect/src/cascadedetect.hpp

    ## minor 1:
    CALC_SUM_ is defined twice: line 282, 308
    CALC_SUM   is defined twice: line 285, 311

    ## minor 2:
    line 266:
    /* (x + w, y) */ 
    change to: 
    /* (x, y + h) */

### PR DESCRIPTION
**Pull request by catree**
### This pullrequest changes
resolves #9925 
Remove double definitions and fix comment.

### CODE REVIEW

File: modules/objdetect/src/cascadedetect.hpp [hunk 1]
```diff
@@ -263,7 +263,7 @@ class CascadeClassifierImpl : public BaseCascadeClassifier
     (p0) = sum + (rect).x + (step) * (rect).y,                            \
     /* (x + w, y) */                                                      \
     (p1) = sum + (rect).x + (rect).width + (step) * (rect).y,             \
-    /* (x + w, y) */                                                      \
+    /* (x, y + h) */                                                      \
```
Comment (alalek) [inline modules/objdetect/src/cascadedetect.hpp]: One more is on the line 292

Comment (catree) [reply modules/objdetect/src/cascadedetect.hpp]: Done.

**Comment by alalek** [comment]
Thank you! :+1:
