### PR TITLE
RFC: Jpeg2000 OpenJPEG port

### LINKED ISSUE #5849: Application crashed when imdecode() is called for .jp2 image
**[alalek]**: Solution is to replace jasper (stalled development) to modern OpenJPEG library.

---

Hi,

i am working on application that uses opencv for images.
We have a crash when calling imdecode() function in our code for jpeg2000 images.
(attached example of the image that causes crash)
[example1.zip](https://github.com/Itseez/opencv/files/68480/example1.zip)

i have a dump file for this crash, related stack trace is following:

FAULTING_IP: 
ContactService!jas_image_chclrspc+2ee
0978353e 8b4018          mov     eax,dword ptr [eax+18h]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 0978353e (ContactService!jas_image_chclrspc+0x000002ee)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 88000027
Attempt to read from address 88000027

PROCESS_NAME:  CiscoJabber.exe
ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.
EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.
EXCEPTION_PARAMETER1:  00000000
EXCEPTION_PARAMETER2:  88000027
READ_ADDRESS:  88000027 
FOLLOWUP_IP: 
ContactService!jas_image_chclrspc+2ee
0978353e 8b4018          mov     eax,dword ptr [eax+18h]
MOD_LIST: <ANALYSIS/>
NTGLOBALFLAG:  0
APPLICATION_VERIFIER_FLAGS:  0
FAULTING_THREAD:  000027fc
BUGCHECK_STR:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_ffffffff
PRIMARY_PROBLEM_CLASS:  INVALID_POINTER_READ_FILL_PATTERN_ffffffff
DEFAULT_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_ffffffff
LAST_CONTROL_TRANSFER:  from 096cfb68 to 0978353e

STACK_TEXT:  
1409f14c 096cfb68 19f381d0 104dd9d0 00000001 ContactService!jas_image_chclrspc+0x2ee
1409f1a8 096c5329 1409f4d4 dd9bc1dc 00000000 ContactService!cv::Jpeg2KDecoder::readData+0xa8
1409f330 096c4d4e 1409f358 00000001 00000002 ContactService!cv::imdecode+0x5a9
1409f3a0 09522026 1409f4d4 1409f45c 00000001 ContactService!cv::imdecode+0x6e 
// Application related details
...

SYMBOL_STACK_INDEX:  0
SYMBOL_NAME:  contactservice!jas_image_chclrspc+2ee
FOLLOWUP_NAME:  MachineOwner
MODULE_NAME: ContactService
IMAGE_NAME:  ContactService.dll
DEBUG_FLR_IMAGE_TIMESTAMP:  55c239be
STACK_COMMAND:  ~62s; .ecxr ; kb
FAILURE_BUCKET_ID:  INVALID_POINTER_READ_FILL_PATTERN_ffffffff_c0000005_ContactService.dll!jas_image_chclrspc
BUCKET_ID:  APPLICATION_FAULT_INVALID_POINTER_READ_FILL_PATTERN_ffffffff_contactservice!jas_image_chclrspc+2ee
WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/CiscoJabber_exe/11_0_1_19000/55c23a85/ContactService_dll/9_0_0_3829/55c239be/c0000005/0032353e.htm?Retriage=1

Please contact me for more information if needed.

### PR DESCRIPTION
**Pull request by StefanBruens**
resolves #5849

Currently missing/incomplete:

- [x] Write support
- [ ] Reading of "signed" components
- [ ] Reading of precision > 16
- [ ] Reading of > 4 components
- [x] Color conversion e.g. YUV -> BGR

<cut/>

```
ci_branch=pr16494
buildworker:Linux x64=linux-4
buildworker:Linux OpenCL=linux-2
```

### CODE REVIEW

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 1]
```diff
@@ -0,0 +1,343 @@
+/*M///////////////////////////////////////////////////////////////////////////////////////
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: Could you please use [short license header](https://github.com/opencv/opencv/wiki/Coding_Style_Guide#file-structure)?

```
// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.
//
// Copyright (C) 2020, Stefan Brüns <stefan.bruens@rwth-aachen.de>
```

File: cmake/OpenCVFindLibsGrfmt.cmake [hunk 2]
```diff
@@ -153,8 +153,20 @@ if(NOT WEBP_VERSION AND WEBP_INCLUDE_DIR)
...
 
+# --- libopenjp2 (optional, check before libjasper) ---
+if(WITH_OPENJPEG)
+  find_package(OpenJPEG QUIET)
+
+  if(OpenJPEG_FOUND)
+    message(STATUS "Found OpenJPEG: ${OPENJPEG_LIBRARIES} (found version \"${OPENJPEG_MAJOR_VERSION}.${OPENJPEG_MINOR_VERSION}.${OPENJPEG_BUILD_VERSION}\")")
+    set(HAVE_OPENJPEG YES)
+  else()
+    message(STATUS "Could NOT find OpenJPEG")
```
Comment (alalek) [inline cmake/OpenCVFindLibsGrfmt.cmake]: > find_package(OpenJPEG QUIET)
> message(...)
> message(...)

What if we remove QUIET and following `message()` lines? What is the difference?

Comment (StefanBruens) [reply cmake/OpenCVFindLibsGrfmt.cmake]: The QUIET actually has no effect, OpenJPEGConfig.cmake has no message()s at all.

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp (hunk 1 above)
Comment (StefanBruens) [reply modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: done

File: cmake/OpenCVFindLibsGrfmt.cmake (hunk 2 above)
Comment (StefanBruens) [reply cmake/OpenCVFindLibsGrfmt.cmake]: Removed the "QUIET"

**Comment by asmorkalov** [comment]
@StefanBruens Great job! Could you make `find_package` for new format silent. See CI bot warnings: https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/24663/steps/cmake/logs/stdio.
Also Imgcodecs module contains some tests for image IO in Jpeg2000 format that are guarded by `defined(HAVE_JASPER) && defined(OPENCV_IMGCODECS_ENABLE_JASPER_TESTS)` macros. Could you enable them for OpenJPEG too to have automated regression testing with CI bot too.

**Comment by alalek** [comment]
Please ignore CMake warnings for now. I need to upgrade builders and their configurations first.

Let enable tests for OpenJPEG first.

File: cmake/OpenCVFindLibsGrfmt.cmake (hunk 2 above)
Comment (alalek) [reply cmake/OpenCVFindLibsGrfmt.cmake]: Please return "QUIET" and messages back (OpenJPEG is not a regular CMake module, so large warning are showed if it is not available)

File: modules/imgcodecs/test/test_grfmt.cpp [hunk 3]
```diff
@@ -71,7 +71,7 @@ TEST_P(Imgcodecs_FileMode, regression)
 
 const string all_images[] =
 {
-#if defined(HAVE_JASPER) && defined(OPENCV_IMGCODECS_ENABLE_JASPER_TESTS)
```
Comment (alalek) [inline modules/imgcodecs/test/test_grfmt.cpp]: Please use:
```
#if (defined(HAVE_JASPER) && defined(OPENCV_IMGCODECS_ENABLE_JASPER_TESTS)) \
    || HAVE_OPENJPEG
```

and revert related changes in CMake file.

File: modules/imgcodecs/test/test_read_write.cpp [hunk 4]
```diff
@@ -194,7 +194,7 @@ const string exts[] = {
 #ifdef HAVE_JPEG
     "jpg",
 #endif
-#if defined(HAVE_JASPER) && defined(OPENCV_IMGCODECS_ENABLE_JASPER_TESTS)
+#if defined(OPENCV_IMGCODECS_ENABLE_JPEG2K_TESTS)
```
Comment (alalek) [inline modules/imgcodecs/test/test_read_write.cpp]: Lets revert this condition until we will have encoder implementation.

File: CMakeLists.txt [hunk 5]
```diff
@@ -1236,8 +1239,16 @@ if(WITH_TIFF OR HAVE_TIFF)
...
+if(HAVE_OPENJPEG)
+  status("    JPEG 2000:" "OpenJPEG (ver ${OPENJPEG_MAJOR_VERSION}.${OPENJPEG_MINOR_VERSION}.${OPENJPEG_BUILD_VERSION})")
+endif()
+
+if(HAVE_JASPER)
+  status("    JPEG 2000:" JASPER_FOUND THEN "${JASPER_LIBRARY} (ver ${JASPER_VERSION_STRING})" ELSE "build Jasper (ver ${JASPER_VERSION_STRING})")
+endif()
+
+if((WITH_OPENJPEG OR WITH_JASPER) AND NOT (HAVE_OPENJPEG OR HAVE_JASPER))
+  status("    JPEG 2000:" "NO")
```
Comment (alalek) [inline CMakeLists.txt]: Let use this scheme:
```
if(HAVE_OPENJPEG)
  ...
elseif(HAVE_JASPER)
  ...
elseif(WITH_OPENJPEG OR WITH_JASPER)
  status("    JPEG 2000:" "NO")
endif()
```

File: modules/imgcodecs/src/loadsave.cpp [hunk 6]
```diff
@@ -176,6 +176,9 @@ struct ImageCodecInitializer
         decoders.push_back( makePtr<Jpeg2KDecoder>() );
         encoders.push_back( makePtr<Jpeg2KEncoder>() );
     #endif
+    #ifdef HAVE_OPENJPEG
+        decoders.push_back( makePtr<Jpeg2KDecoder>() );
```
Comment (alalek) [inline modules/imgcodecs/src/loadsave.cpp]: To avoid confusion (for example, in stacktraces) it makes sense to use different name, like `OpenJpegDecoder`.

File: CMakeLists.txt (hunk 5 above)
Comment (StefanBruens) [reply CMakeLists.txt]: done

File: modules/imgcodecs/src/loadsave.cpp (hunk 6 above)
Comment (StefanBruens) [reply modules/imgcodecs/src/loadsave.cpp]: how about `Jpeg2KOpjDecoder`?

File: modules/imgcodecs/test/test_grfmt.cpp (hunk 3 above)
Comment (alalek) [reply modules/imgcodecs/test/test_grfmt.cpp]: You need to use `\` with multi-line directives.

Comment (StefanBruens) [reply modules/imgcodecs/test/test_grfmt.cpp]: CI already told me ;-)

**Comment by StefanBruens** [comment]
The Mac build already uses the OpenJPEG path.

It fails due to the unimplemented RGB->gray conversion when IMREAD_GRAY is used.

Should this just use cv::cvtColor, or fail?

File: modules/imgcodecs/src/loadsave.cpp (hunk 6 above)
Comment (StefanBruens) [reply modules/imgcodecs/src/loadsave.cpp]: its Jpeg2KOpjDecoder now

File: modules/imgcodecs/test/test_read_write.cpp (hunk 4 above)
Comment (StefanBruens) [reply modules/imgcodecs/test/test_read_write.cpp]: started an encoder branch on top of this one and moved it there
https://github.com/StefanBruens/opencv/tree/jpeg2000_openjpeg_encoder

File: modules/imgcodecs/test/test_grfmt.cpp (hunk 3 above)
Comment (StefanBruens) [reply modules/imgcodecs/test/test_grfmt.cpp]: done

**Comment by alalek** [comment]
`cvtColor` call is allowed in `imgcodecs` module. Yes, you can use it.

**Comment by StefanBruens** [comment]
Last remaining error:

```
CMake Warning at /build/precommit_linux64/ci/cmake_checks/cmake_checks.cmake:105 (message):
  Manual validation is requied.  Variable is not defined: HAVE_OPENJPEG
Call Stack (most recent call first):
  /build/precommit_linux64/ci/cmake_checks/precommit_linux64/POST_FINALIZE.cmake:115 (build_validate_enabled_flag)
  cmake/OpenCVUtils.cmake:52 (include)
  CMakeLists.txt:1596 (ocv_cmake_hook)
```

**Comment by alalek** [comment]
> HAVE_OPENJPEG

Please ignore this for now (this issue is related to infrastructure which will be updated before merge).

There are several packages of OpenJPEG on Ubuntu 16.04:
- [`libopenjpeg-dev`](https://packages.ubuntu.com/xenial/libopenjpeg-dev)
- [`libopenjp2-7-dev`](https://packages.ubuntu.com/xenial/libopenjp2-7-dev)

Looks like they have different versions of OpenJPEG: 1.5 vs 2.1

Please adapt CMake to check applicable version of OpenJPEG (perhaps >= 2.0).
Try something like this
```
find_package(OpenJPEG 2.0 QUIET)
```
or check version after that:
```
if(NOT OPENJPEG_MAJOR_VERSION VERSION_LESS "2")
  ... use OpenJPEG ...
endif()
```

**Comment by StefanBruens** [comment]
> ```
> find_package(OpenJPEG 2.0 QUIET)
> ```

No OpenJPEGVersion.cmake -> manual check required.

**Comment by asmorkalov** [comment]
@StefanBruens Do you have a chance to finish your patch? it brings a lot of value to the library.

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 7]
```diff
@@ -37,49 +39,233 @@ const String colorspaceName(COLOR_SPACE colorspace)
 }
 
 
-template<typename OutT, bool doShift, typename InT, std::size_t N>
-void copy_data_(Mat& out, const std::array<InT*, N>& data, uint8_t shift) {
+template<typename OutT, typename InT>
```
Comment (StefanBruens) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: doShift is a template parameter for a reason ... do not evaluate it for every pixel

Comment (VadimLevin) [reply modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: Actually it is evaluated once per image, basically it is possible to split functions to not evaluate `isShiftRequered` every *row*, but for continueus mat it is evaluated once at all

**Comment by VadimLevin** [comment]
@alalek I've fixed all issues with the memory management in this PR and cherry-picked changes from #16524. Can you proceed with the review?

The only thing that makes this PR red is CMake warning about `HAVE_OPENJPEG`

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 8]
```diff
@@ -0,0 +1,694 @@
...
+        copyFromMatImpl<uint16_t>(in, std::move(out));
+        break;
+    default:
+        CV_Error(Error::StsNotImplemented, "only depth CV_8U and CV16_U are supported");
+    }
+}
+
+void errorLogCallback(const char* msg, void* /* userData */)
+{
+    CV_LOG_ERROR(nullptr, cv::format("OpenJPEG2000: %s", msg));
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: > CV_LOG_ERROR(nullptr

Please use `NULL` for logger tags. It is designed as a part of identifier (`nullptr` would be broken in the future).

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 9]
```diff
@@ -0,0 +1,694 @@
...
+    opj_cparameters parameters;
+    opj_set_default_encoder_parameters(&parameters);
+    for (size_t i = 0; i < params.size(); i += 2)
+    {
+        switch (params[i])
+        {
+        case cv::IMWRITE_JPEG2000_COMPRESSION_X1000:
+            parameters.tcp_rates[0] = 1000.f / std::min(std::max(params[i + 1], 1), 1000);
+            break;
+        }
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]:
```
default:
    CV_LOG_WARNING(NULL, "OpenJPEG2000(encoder): skip unsupported parameter: " << params[i])
```
?

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 10]
```diff
@@ -0,0 +1,694 @@
...
+        CV_Error(Error::StsNotImplemented,
+                 cv::format("OpenJPEG2000: Unsupported number of output channels. IN: %d OUT: 2", image_->numcomps));
+    }
+
+    DecodeFunc decode = nullptr;
+    switch (image_->color_space)
+    {
+    case OPJ_CLRSPC_UNKNOWN:
+        CV_LOG_WARNING(nullptr, "OpenJPEG2000: Image has unknown color space, SRGB is assumed");
+    case OPJ_CLRSPC_SRGB:
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: Add `falltru` comment to avoid compiler warnings:

```
        CV_LOG_WARNING(nullptr, "OpenJPEG2000: Image has unknown color space, SRGB is assumed");
        // fallthru
    case OPJ_CLRSPC_SRGB:
```

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 11]
```diff
@@ -0,0 +1,694 @@
...
+{
+    return depth == CV_8U || depth == CV_16U;
+}
+
+bool Jpeg2KOpjEncoder::write(const Mat& img, const std::vector<int>& params)
+{
+    CV_Assert(params.size() % 2 == 0);
+
+    const int channels = img.channels();
+    if (channels > 4)
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: `CV_DbgAssert(channels > 0);   // passed matrix is not empty`

File: modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp [hunk 12]
```diff
@@ -0,0 +1,694 @@
...
+
+
+ImageDecoder Jpeg2KOpjDecoder::newDecoder() const
+{
+    return makePtr<Jpeg2KOpjDecoder>();
+}
+
+bool Jpeg2KOpjDecoder::readHeader()
+{
+    stream_.reset(opj_stream_create_default_file_stream(m_filename.c_str(), OPJ_STREAM_READ));
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: > m_filename.c_str()

Looks like `imdecode()` from in-memory buffers is not supported at this moment.

Comment (VadimLevin) [reply modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp]: Added support, based on the following PR:
 * [PR 583](https://github.com/uclouvain/openjpeg/pull/583)
 * [PR 1212](https://github.com/uclouvain/openjpeg/pull/1212)

**Comment by alalek** [comment]
Updated I/O tests (#16922) show large output from OpenJPEG encoding process. Looks like lossless compression is applied.

We need to tune default compression parameters. PSNR 30-35 threshold on mentioned tests should be enough for default compression values.

**Comment by arogozhnikov** [comment]
I see this is very recent change (only 4 days ago), but I'm interested in testing openjpeg for my case (uint16 grayscale) to read/write from python. 
When should I expect this functionality available in distribution?

**Comment by asmorkalov** [comment]
OpenCV 4.3.0 is coming soon.
