### PR TITLE
Java VideoCapture buffered stream constructor

### LINKED ISSUE #26809: No way to initialize the IStreamReader class in the Java wrapper.
### System Information

OpenCV version: 4.11.0
Operating System / Platform: Windows 10 22H2
Compiler & compiler version: 3.18.1

### Detailed description

In the Java wrapper of OpenCV, there is currently no way to initialize the IStreamReader class. While the class is exposed in the Java bindings, no constructor or factory method is implemented, making it impossible to create an instance.

Specifically, the following constructor in the Videoio module of the Videoio class requires an instance of the IStreamReader class, but since there is no way to initialize IStreamReader, this functionality is unusable:

`public VideoCapture(IStreamReader source, int apiPreference, MatOfInt params)`

As a result, even though the IStreamReader class is supported in the native C++ implementation, it cannot be used in Java applications.

### Steps to reproduce

Build with the BUILD_opencv_java_bindings_generator flag ON.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by dkurt**
### Pull Request Readiness Checklist

resolves #26809

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/videoio/misc/java/src/java/videoio+IStreamReader.java [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package org.opencv.videoio;
+
+public interface IStreamReader {
+    public long read(byte[] buffer, long size);
```
Comment (dkurt) [inline modules/videoio/misc/java/src/java/videoio+IStreamReader.java:4]: Open question is to keep `size` as a parameter or `buffer.length` is enough (array is initialized). Examples in Java:

https://docs.oracle.com/javase/8/docs/api/java/io/BufferedInputStream.html#read-byte:A-int-int-
https://docs.oracle.com/javase/6/docs/api/java/io/RandomAccessFile.html#read(byte[])
https://docs.oracle.com/javase/6/docs/api/java/io/RandomAccessFile.html#read(byte[],%20int,%20int)

File: modules/videoio/include/opencv2/videoio.hpp [hunk 2]
```diff
@@ -721,7 +721,7 @@ enum VideoCaptureOBSensorProperties{
 
 /** @brief Read data stream interface
  */
-class CV_EXPORTS_W IStreamReader
+class CV_EXPORTS IStreamReader
```
Comment (dkurt) [inline modules/videoio/include/opencv2/videoio.hpp:724]: I don't know if it may break ObjC bindings introduced in https://github.com/opencv/opencv/pull/25584

Comment (opencv-alalek) [reply modules/videoio/include/opencv2/videoio.hpp:724]: IMHO, It should be kept wrapped as arguments of binding functions rely on this type.

What is the error?
Can we override behavior in java/gen_dict.json?

Comment (asmorkalov) [reply modules/videoio/include/opencv2/videoio.hpp:724]: Without  `CV_EXPORTS_W` we also loose Python type hints.

Comment (dkurt) [reply modules/videoio/include/opencv2/videoio.hpp:724]: There is a minor error in gen_java but I were able to fix it. Let me try use a generated bindings again.

File: modules/videoio/misc/java/test/VideoCaptureTest.java [hunk 3]
```diff
@@ -61,4 +75,69 @@ public void testConstructorWithIndexAndExplicitlySpecifiedAPI() {
...
+            break;
+        }
+        if (apiPref == Videoio.CAP_ANY)
+        {
+            throw new TestSkipException();
+        }
+
+        RandomAccessFile f = new RandomAccessFile(new File(testDataPath, "cv/video/768x576.avi"), "r");
+
+        IStreamReader stream = new IStreamReader(0)
```
[the remark this answers is not in the document]
Comment (dkurt) [reply modules/videoio/misc/java/test/VideoCaptureTest.java:102]: Native object address, not used actually. Shall we hide it?

File: modules/videoio/misc/java/src/cpp/videoio_converters.hpp [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+#include <jni.h>
+#include "opencv_java.hpp"
+#include "opencv2/core.hpp"
+#include "opencv2/videoio/videoio.hpp"
+
+class JavaStreamReader : public cv::IStreamReader
+{
+public:
+    JavaStreamReader(JNIEnv* env, jobject obj);
```
Comment (asmorkalov) [inline modules/videoio/misc/java/src/cpp/videoio_converters.hpp:12]: > The JNIEnv is used for thread-local storage. For this reason, you cannot share a JNIEnv between threads. If a piece of code has no other way to get its JNIEnv, you should share the JavaVM, and use GetEnv to discover the thread's JNIEnv. (Assuming it has one; see AttachCurrentThread below.)

Source: https://developer.android.com/training/articles/perf-jni?hl=en

Looks like the adapter should handle the threading model in smarter way.

File: modules/videoio/misc/java/test/VideoCaptureTest.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (dkurt) [reply modules/videoio/misc/java/test/VideoCaptureTest.java]: Fixed by `ManualFuncs`

File: modules/videoio/misc/java/test/VideoCaptureTest.java [hunk 5]
```diff
@@ -61,4 +75,69 @@ public void testConstructorWithIndexAndExplicitlySpecifiedAPI() {
...
+        {
+            @Override
+            public long read(byte[] buffer, long size)
+            {
```
[the remark this answers is not in the document]
Comment (dkurt) [reply modules/videoio/misc/java/test/VideoCaptureTest.java:106]: Sure. Also make sense to highlight in docstring that it's pre-allocated

**Comment by asmorkalov** [comment]
Great job!

File: modules/videoio/misc/java/src/cpp/videoio_converters.cpp [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+    env->DeleteGlobalRef(obj);
+}
+
+long long JavaStreamReader::read(char* buffer, long long size)
+{
+    if (!m_read)
+        return 0;
+    JNIEnv* env;
+    if (vm->GetEnv((void**)&env, JNI_VERSION_1_6) != JNI_OK)
+        return 0;
```
Comment (opencv-alalek) [inline modules/videoio/misc/java/src/cpp/videoio_converters.cpp:26]: In general these callbacks are called from FFmpeg non-Java threads.

`JNIEnv` may be not available for native threads.

Should we use `AttachCurrentThread` in that case instead of `return 0` ?

Docs:

> For example, a thread started with pthread_create() or std::thread can be attached using the AttachCurrentThread() or AttachCurrentThreadAsDaemon() functions. Until a thread is attached, it has no JNIEnv, and cannot make JNI calls.

But there is dedicated issue with detaching of such threads.

Comment (dkurt) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:41]: Added `AttachCurrentThread` if `GetEnv` returns specific `JNI_EDETACHED` error.

Comment (dkurt) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:41]: > But there is dedicated issue with detaching of such threads.

Do you mean there is some bug in JNI or we also responsible for `DetachCurrentThread` call?

**Comment by asmorkalov** [comment]
Android build error:
```
 ccache /opt/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --sysroot=/opt/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DCVAPI_EXPORTS -D_USE_MATH_DEFINES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/ci/opencv/modules/core/misc/java/src/cpp -I/home/ci/opencv/modules/imgproc/misc/java/src/cpp -I/home/ci/opencv/modules/ml/misc/java/src/cpp -I/home/ci/opencv/modules/photo/misc/java/src/cpp -I/home/ci/opencv/modules/dnn/misc/java/src/cpp -I/home/ci/opencv/modules/features2d/misc/java/src/cpp -I/home/ci/opencv/modules/imgcodecs/misc/java/src/cpp -I/home/ci/opencv/modules/videoio/misc/java/src/cpp -I/home/ci/opencv/modules/calib3d/misc/java/src/cpp -I/home/ci/opencv/modules/objdetect/misc/java/src/cpp -I/home/ci/opencv/modules/video/misc/java/src/cpp -I/home/ci/opencv/modules/java/generator/src/cpp -I/home/ci/build/o4a/modules/java_bindings_generator/gen/cpp -I/home/ci/opencv/modules/core/include -I/home/ci/opencv/modules/flann/include -I/home/ci/opencv/modules/imgproc/include -I/home/ci/opencv/modules/ml/include -I/home/ci/opencv/modules/photo/include -I/home/ci/opencv/modules/dnn/include -I/home/ci/opencv/modules/features2d/include -I/home/ci/opencv/modules/imgcodecs/include -I/home/ci/opencv/modules/videoio/include -I/home/ci/opencv/modules/calib3d/include -I/home/ci/opencv/modules/objdetect/include -I/home/ci/opencv/modules/video/include -isystem /home/ci/build/o4a -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security     -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -fdiagnostics-show-option -Qunused-arguments  -fvisibility=hidden -fvisibility-inlines-hidden  -Wno-deprecated-declarations -O3 -DNDEBUG   -DNDEBUG -fPIC -std=c++11 -MD -MT modules/java/jni/CMakeFiles/opencv_java.dir/__/__/videoio/misc/java/src/cpp/videoio_converters.cpp.o -MF modules/java/jni/CMakeFiles/opencv_java.dir/__/__/videoio/misc/java/src/cpp/videoio_converters.cpp.o.d -o modules/java/jni/CMakeFiles/opencv_java.dir/__/__/videoio/misc/java/src/cpp/videoio_converters.cpp.o -c /home/ci/opencv/modules/videoio/misc/java/src/cpp/videoio_converters.cpp
/home/ci/opencv/modules/videoio/misc/java/src/cpp/videoio_converters.cpp:11:39: error: cannot initialize a parameter of type 'JNIEnv **' (aka '_JNIEnv **') with an rvalue of type 'void **'
        res = vm->AttachCurrentThread((void**)&env, NULL);
                                      ^~~~~~~~~~~~
/opt/android-sdk/ndk/26.3.11579264/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/jni.h:1057:39: note: passing argument to parameter 'p_env' here
    jint AttachCurrentThread(JNIEnv** p_env, void* thr_args)
                                      ^
1 error generated.
```

File: modules/videoio/misc/java/src/cpp/videoio_converters.cpp (hunk 6 above)
Comment (opencv-alalek) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:58]: > we also responsible

this.

File: modules/videoio/misc/java/src/cpp/videoio_converters.cpp [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+#endif // __ANDROID__
+            detach = true;
+        }
+    }
+
+    ~JNIEnvHandler()
+    {
+        if (env && detach)
+        {
+            vm->DetachCurrentThread();
```
Comment (opencv-alalek) [inline modules/videoio/misc/java/src/cpp/videoio_converters.cpp:24]: BTW, this could significantly slowdown execution through attach-detach on each callback call.

File: modules/videoio/misc/java/src/cpp/videoio_converters.cpp (hunk 6 above)
Comment (dkurt) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:58]: Added in the latest commit for every read/seek call

File: modules/videoio/misc/java/src/cpp/videoio_converters.cpp (hunk 7 above)
Comment (dkurt) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:24]: I can move it to the wrapper class, just few minute

Comment (opencv-alalek) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:24]: There is no guarantee that wrapper class uses the same thread,

Comment (dkurt) [reply modules/videoio/misc/java/src/cpp/videoio_converters.cpp:24]: Agree, actually, I have concern that even if read/seek were used in the thread that requires `AttachCurrentThread`, the destructor of `JavaStreamReader` might be called in the main thread

**Comment by asmorkalov** [comment]
@opencv-alalek Do you have other remarks? Is it ready for merge?
