### PR TITLE
Restored function to rescale pixel values before imshow

### LINKED ISSUE #13216: highgui: imshow can only show CV_8U images
- OpenCV => master
- Operating System / Platform => Windows 64 Bit
- Compiler => mingw64 / 7.2.0

##### Detailed description
regression after: https://github.com/opencv/opencv/commit/11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e

the `cvConvertImage()` calls [were removed](https://github.com/opencv/opencv/commit/11eafca3e2a4cbc62f1309d25db0ea3ed9a6ea8e#diff-baec79d9f6cf2a8b605a5d9aad326540L1214). 
while code was added to adapt the colorspace, there is no more depth conversion to CV_8U

##### Steps to reproduce
```
//Mat m(400,400,CV_32FC3,Scalar(1.0));
Mat m(400,400,CV_16U,Scalar(255));
imshow("win",m);
waitKey();
```
leading to:

```
OpenCV(4.0.0-pre) Error: Assertion failed (dst.data == (uchar*)dst_ptr) in cvShowImage, file C:\p\opencv\modules\highgui\src\window_w32.cpp, line 1230
```
apart from the windows version (tried here), others will be affected: 
- [X] window_w32.cpp 
- [ ] window_cocoa.mm 
- [ ] window_gtk.cpp
- [x] window_QT.cpp

### PR DESCRIPTION
**Pull request by mshabunin**
resolves #13216
related #13184

### This pullrequest changes

* adds a single function similar to removed one to rescale pixel values and swap B and R channels before showing image in the window
* rewrote highgui test to cover different image types passed to `imshow`

### CODE REVIEW

File: modules/highgui/src/precomp.hpp [hunk 1]
```diff
@@ -123,4 +123,39 @@ double cvGetOpenGlProp_QT(const char* name);
...
+        break;
+    case CV_16U:
+        cv::convertScaleAbs(src, tmp, 1/255.);
+        break;
+    case CV_32F:
+    case CV_64F: // assuming image has values in range [0, 1)
+        cv::convertScaleAbs(src, tmp, 256.);
+        break;
+    }
+    cv::cvtColor(tmp, dst, cv::COLOR_BGR2RGB, dst.channels());
```
Comment (berak) [inline modules/highgui/src/precomp.hpp]: unfortunately, windows needs BGR pixel order

**Comment by mshabunin** [comment]
I've added BGR image and verified all 4 backends (GTK and Qt on Linux, Mac, Win) visually. Separated trackbar test and disabled it on Mac: callback does not get called in the test while sample apps work fine.
