### PR TITLE
DNN: supports Scatter and ScatterND from ONNX

### LINKED ISSUE #22528: (-2:Unspecified error) Can't create layer "onnx_node!ScatterND_274" of type "ScatterND" in function 'getLayerInstance'
##### System information (version)

- OpenCV => 4.6
- Operating System / Platform =>Ububtu 20.04

##### Steps to reproduce

link to my onnx model https://drive.google.com/file/d/1oP3TrtYfn42SZ0JrDTd9tYhi8bGnmOe1/view?usp=sharing

##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [ ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [ ] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by fengyuentau**
Fixes #22528 

Merge with: https://github.com/opencv/opencv_extra/pull/1009

Checklist:
- [x] Scatter impl
- [x] Scatter impl for negative indices
- [x] Test data for Scatter
- [x] ScatterND impl
- [x] ScatterND impl for negative indices
- [x] Test data for ScatterND
- [x] Disable the perf test to save CI server resources before merge

ONNX operator doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Scatter

## Benchmark

Benchmark was done on M1 Macbook Air (16G mem). Time is in milliseconds.

*: Shapes of input, indices, updates are all [8, 256, 128, 100].

| Version | Operation | mean | median | min |
| - | - | - | - | - |
| intial | Scatter | 223.53 | 223.44 | 220.77 |
| initial | Scatter-add | 241.19 | 241.86 | 238.11 |
| + passing_mat | Scatter | 228.51 | 228.36 | 226.45 |
| + passing_mat | Scatter-add | 249.08 | 249.20 | 247.54 |
| current impl: + optm + pm | Scatter | 154.62 | 153.80 | 153.38 |
| current impl: + optm + pm | Scatter-add | 169.39 | 169.63 | 168.20 |

*: Shapes of input, indices, updates are [8, 256, 128, 100], [8, 256, 128, 100, 4], [8, 256, 128, 100] respectively.

| Version | Operation | mean | median | min |
| - | - | - | - | - |
| intial | ScatterND | 465.92 | 465.25 | 464.78 |
| initial | ScatterND-add | 475.01 | 473.86 | 473.13 |
| + passing_mat | ScatterND | 464.59 | 464.40 | 464.13 |
| + passing_mat | ScatterND-add | 473.80 | 470.24 | 465.80 |
| + pm + ng index | ScatterND | 511.17 | 508.44 | 507.73 |
| + pm + ng index | ScatterND-add | 518.91 | 518.56 | 510.94 |
| + optm1 + pm + ng index | ScatterND | 227.04 | 226.29 | 225.21 |
| + optm1 + pm + ng index | ScatterND-add | 218.58 | 218.37 | 217.26 |
| current impl: + optm2 + optm1 + pm + ng index | ScatterND | 132.87 | 132.94 | 132.09 |
| current impl: + optm2 + optm1 + pm + ng index | ScatterND-add | 135.17 | 135.05 | 133.93 |

## Potential issue

ScatterND should support duplicate indices if reduction is not none. Also ScatterND permits negative indices. See [here](https://github.com/onnx/onnx/issues/4548) for more details.

***Notice***: Current impl does not check for duplicate indices if reduction is none.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 1]
```diff
@@ -3106,6 +3108,106 @@ void ONNXImporter::parseRange(LayerParams& layerParams, const opencv_onnx::NodeP
     constBlobsExtraInfo.insert(std::make_pair(node_proto.output(0), TensorInfo(1)));
 }
 
+void ONNXImporter::parseScatter(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
+{
+    CV_CheckEQ(node_proto.input_size(), 3, "Scatter: 3 three inputs are required.");
```
Comment (asmorkalov) [inline modules/dnn/src/onnx/onnx_importer.cpp:3113]: `3 three` - it's most probably a typo.

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 2]
```diff
@@ -3106,6 +3108,106 @@ void ONNXImporter::parseRange(LayerParams& layerParams, const opencv_onnx::NodeP
...
+            }
+        }
+    }
+
+    addLayer(layerParams, node_proto);
+}
+
+void ONNXImporter::parseScatterND(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
+{
+    CV_CheckEQ(node_proto.input_size(), 3, "Scatter: 3 three inputs are required.");
```
Comment (asmorkalov) [inline modules/dnn/src/onnx/onnx_importer.cpp:3163]: the same.

File: modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp [hunk 3]
```diff
@@ -1588,6 +1588,10 @@ CASE(test_scatter_elements_with_duplicate_indices)
     // no filter
 CASE(test_scatter_elements_with_negative_indices)
     // no filter
+CASE(test_scatter_elements_with_reduction_max)
```
Comment (asmorkalov) [inline modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp:1591]: Most probably the tests for scatter should be disabled for CUDA, Vulcan, OpenCL back-ends too. Also it's not clear, if it works works with Tim-VX.

File: modules/dnn/src/layers/scatterND_layer.cpp [hunk 4]
```diff
@@ -0,0 +1,263 @@
...
+            for (int j = 0; j < ind_ndims - 1; j++)
+            {
+                upd_current_indices[j] = update_indices[j];
+            }
+
+            upd_start_offset = 0;
+            for (int j = 0; j < upd_ndims; j++)
+            {
+                upd_start_offset += upd_current_indices[j] * upd_step[j];
+            }
```
Comment (rogday) [inline modules/dnn/src/layers/scatterND_layer.cpp:181]: Do extra dimensions of indices matter?(not related to index tuple)
I'm not sure I got the docs correctly, but it seems that we can interpret like array of indices and then we have 1 loop for data index restoration and 1 loop for update?
I seem to be missing something, point me to the docs, please.

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 5]
```diff
@@ -3106,6 +3108,106 @@ void ONNXImporter::parseRange(LayerParams& layerParams, const opencv_onnx::NodeP
...
+                proto.add_output(constParams.name);
+                addLayer(constParams, proto);
+            }
+        }
+    }
+
+    addLayer(layerParams, node_proto);
+}
+
+void ONNXImporter::parseScatterND(LayerParams& layerParams, const opencv_onnx::NodeProto& node_proto)
```
Comment (rogday) [inline modules/dnn/src/onnx/onnx_importer.cpp:3161]: Looks like a duplicate of the function above.

**Review by rogday — CHANGES_REQUESTED** [review]
Thank you for contribution!
Comments about the algorithm are valid only for the case of continuous matrices.

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 1 above)
Comment (fengyuentau) [reply modules/dnn/src/onnx/onnx_importer.cpp]: fixed.

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 2 above)
Comment (fengyuentau) [reply modules/dnn/src/onnx/onnx_importer.cpp]: fixed.

File: modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp (hunk 3 above)
Comment (fengyuentau) [reply modules/dnn/test/test_onnx_conformance_layer_filter__openvino.inl.hpp:1591]: Added into the deny lists of cuda, halide, vulkan and opencl. As for TIM-VX, it does not have a deny list yet and this could be done in a separate pull request.

File: modules/dnn/src/layers/scatter_layer.cpp [hunk 6]
```diff
@@ -0,0 +1,217 @@
...
+        const size_t* step = data.step.p;
+
+        const int* ind_shape = indices.size.p;
+        const size_t* ind_step = indices.step.p;
+
+        typeDispatch(outputs[0].type(), ndims, shape, step, data.ptr<char>(), ind_shape, ind_step, indices.ptr<char>(), updates.ptr<char>(), out.ptr<char>());
+    }
+
+    template<typename T, typename Functor>
+    void forward_impl(const Functor& rd, int ndims, const int* shape, const size_t* step, const char* input, const int* ind_shape, const size_t* ind_step, const char* indices, const char* updates, char* out)
```
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatter_layer.cpp]: It went much slower (from ~220ms to ~290ms) if passing mat. You could have a look at `forward_impl_mat` in case I did something inefficient.

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 5 above)
Comment (fengyuentau) [reply modules/dnn/src/onnx/onnx_importer.cpp:3118]: It is now calling `parseScatterND` in `parseScatter` to remove duplicate.

File: modules/dnn/src/layers/scatter_layer.cpp [hunk 7]
```diff
@@ -0,0 +1,217 @@
...
+
+            // get index and overwrite current indices
+            const T* p_index = (const T*)(indices + ind_offset);
+            int index = (int)(*p_index);
+            CV_Assert(index < shape[axis] && index > -shape[axis]);
+            current_indices[axis] = (index + shape[axis]) % shape[axis];
+
+            inp_offset = 0;
+            for (int j = 0; j < ndims; j++)
+                inp_offset += current_indices[j] * step[j];
```
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatter_layer.cpp:182]: > if we have current indices_offset, we can get input_offset by replacing the 'axis' dimension in indices_offset

IIUC, It is true if shape(input) === shape(indices). However, it is allowed to have mismatched shapes like the following:
```python
data = np.array([[1.0, 2.0, 3.0, 4.0, 5.0]], dtype=np.float32) # (1, 5)
indices = np.array([[1, 3]], dtype=np.int64) # (1, 2)
updates = np.array([[1.1, 2.1]], dtype=np.float32) # (1, 2)

y = scatter_elements(data, indices, updates, axis)
# print(y) produces
# [[1.0, 1.1, 3.0, 2.1, 5.0]]
```

In this case, I am not sure whether getting rid of loops can still work.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 4 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp:181]: The extra dimensions of indices are used to index indices (to index output) and updates. Do you mean flattening extra dimensions of indices. If yes, the extra dimensions of both indices and updates need to be flattened.

File: modules/dnn/src/layers/scatterND_layer.cpp [hunk 8]
```diff
@@ -0,0 +1,263 @@
...
+
+            const T* p_updates = (const T*)(updates + upd_start_offset);
+            T* p_out = (T*)(out + inp_start_offset);
+            for (int j = 0; j < updates_size; j++)
+            {
+                p_out[j] = rd(p_out[j], p_updates[j]);
+            }
```
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp:188]: If no-op rd is special-cased, I think this for loop needs to be moved into those lambda expressions (rd).

File: modules/dnn/src/layers/scatter_layer.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (rogday) [reply modules/dnn/src/layers/scatter_layer.cpp]: 1. It might be a call to `total()` inside each iteration of for loop - let's try to cache it and see if it improves.
2. As for signature, it can be reduced to `void forward_impl(const Functor& rd, const Mat& input, const Mat& indices, const Mat& updates, Mat& out)`
3. What hardware are you testing on? My AMD Ryzen 5 5600H manages to run in 800ms(!), not 200ms.

File: modules/dnn/src/layers/scatter_layer.cpp (hunk 7 above)
[the remark this answers is not in the document]
Comment (rogday) [reply modules/dnn/src/layers/scatter_layer.cpp:182]: Oh, yes, you're right, sorry for misleading.

File: modules/dnn/src/onnx/onnx_importer.cpp (hunk 5 above)
Comment (rogday) [reply modules/dnn/src/onnx/onnx_importer.cpp:3118]: If you look at other layer handlers, it typically implemented inside one handler with `if node_proto.op_type() == ... {layerParams.type = ...; } else {}`

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 4 above)
Comment (rogday) [reply modules/dnn/src/layers/scatterND_layer.cpp:181]: Yes, do you think that's possible?

File: modules/dnn/src/layers/scatter_layer.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatter_layer.cpp]: Cached `total()` and it did improve a lot, but still a little slower than the initial version. Also tried to restore current_indices with:
```cpp
current_indices[ndims - 1] += 1;
for (int j = ndims - 1; j > 0; j--)
{
    current_indices[j - 1] += int(current_indices[j] / ind_shape[j]);
    current_indices[j] %= ind_shape[j];
}
```
, and this went way slower (+100ms). Code is updated and you could take a look if you want.

> I still think it's a little bit too much, isn't it?

It depends on the indices shape. The shape of indices in the perf test I set is 8x256x128x100, which is kind of stressful. I checked the models which require ScatterND, and the shapes of indices are like 1x3x80x80x6x5 (1/45 of the stress test) from https://github.com/opencv/opencv/issues/22528, 1x168x2 from https://github.com/opencv/opencv/issues/22541#issuecomment-1252268440. I could not say we can never reach a scale like the stress test, but maybe the current implementation satisfies most use cases, not to mention that a model containing scatter or scatterND is quite rare. We could improve it latter if there is a great demand on the speed of scatter & scatterND.

[the remark this answers is not in the document]
Comment (rogday) [reply modules/dnn/src/layers/scatter_layer.cpp]: I think +0.5% is negligible. Does caching step_ and indices_step_ improve the performance?
Everything looks good, so please make the same changes to scatterND to be consistent and it will be merged.

[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatter_layer.cpp]: > Does caching step_ and indices_step_ improve the performance?

Minor improvement like -2ms. I think we dont cache step_ and indices_step_ to save mem and keep the code clean and simple.

> so please make the same changes to scatterND

Sure, will do.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp:188]: tried with `std::memcpy` instead of `std::copy`, since latter one only works with iterators and what I got are pointers not vectors. It went slower with `std::memcpy` like +100ms.

File: modules/dnn/src/layers/scatterND_layer.cpp [hunk 9]
```diff
@@ -0,0 +1,263 @@
...
+                     upd_ndims, upd_shape, upd_step, updates.ptr<char>(),
+                     out.ptr<char>());
+    }
+
+    template<typename T, typename Functor>
+    void forward_impl(const Functor& rd,
+                      int ndims, const int* shape, const size_t* step, const char* input,
+                      int ind_ndims, const int* ind_shape, const size_t* ind_step, const char* indices,
+                      int upd_ndims, const int* upd_shape, const size_t* upd_step, const char* updates,
+                      char* out)
```
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp:124]: Done.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 4 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp]: I need to think of it carefully. Will reach back asap.

Comment (rogday) [reply modules/dnn/src/layers/scatterND_layer.cpp]: I would further suggest to merge this as is, but open a ticket for a potential improvement, so that this PR doesn't block anyone.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (rogday) [reply modules/dnn/src/layers/scatterND_layer.cpp]: Well that was unexpected.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 4 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp]: I prefer to keep current impl. I mean we can always index `indices` without `idx`, but I dont figure how to index `updates` without `idx`.

```python
# ScatterND impl in python
output = np.copy(data)
  update_indices = indices.shape[:-1]
  for idx in np.ndindex(update_indices):
      output[indices[idx]] = f(output[indices[idx]], updates[idx]) // how to index updates without idx?
```

Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp]: Thank you for your very insightful suggestion! Now the time of ScatterND has decreased half.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp]: Also tested with the latest optimized impl. It is just slower (+80ms) with `std::memcpy`.

**Comment by fengyuentau** [comment]
Commits are squashed.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 4 above)
Comment (rogday) [reply modules/dnn/src/layers/scatterND_layer.cpp]: Yay!

File: modules/dnn/src/layers/scatterND_layer.cpp [hunk 10]
```diff
@@ -0,0 +1,220 @@
...
+            for (int j = 0; j < k; j++)
+            {
+                CV_Assert(tmp_p_indices[j] < shape[j] && tmp_p_indices[j] > -shape[j]);
+                inp_current_indices[j] = ((int)tmp_p_indices[j] + shape[j]) % shape[j];
+            }
+
+            inp_start_offset = 0;
+            for (int j = 0; j < ndims; j++)
+                inp_start_offset += inp_current_indices[j] * step[j];
+            inp_start_offset /= sizeof(T);
```
Comment (rogday) [inline modules/dnn/src/layers/scatterND_layer.cpp:142]: I think we can get rid of `inp_current_indices` and `finalize()`:
```cpp
const T* tmp_p_indices = p_indices + ind_start_offset;
inp_start_offset = 0;
for (int j = 0; j < k; j++)
{
    CV_Assert(tmp_p_indices[j] < shape[j] && tmp_p_indices[j] > -shape[j]);
    inp_start_offset += (((int)tmp_p_indices[j] + shape[j]) % shape[j]) * step[j];
}
inp_start_offset /= sizeof(T);
```
It shows another 2x speedup on my machine.

File: modules/dnn/src/layers/scatter_layer.cpp [hunk 11]
```diff
@@ -0,0 +1,218 @@
...
+            // get index and overwrite current indices
+            const T* tmp_p_index = p_index + ind_offset;
+            index = (int)(*tmp_p_index);
+            CV_Assert(index < shape[axis] && index > -shape[axis]);
+            current_indices[axis] = (index + shape[axis]) % shape[axis];
+
+            inp_offset = 0;
+            for (j = 0; j < ndims; j++)
+                inp_offset += current_indices[j] * step[j];
+            inp_offset /= sizeof(T);
```
Comment (rogday) [inline modules/dnn/src/layers/scatter_layer.cpp:139]: Seems like here we can also get rid of `current_indices` and `finalize()` and also get 2x speedup:

```cpp
t = i;
int at_axis_val = 0;
ind_offset = 0;
inp_offset = 0;
for (j = ndims - 1; j >= 0; j--)
{
    idx = t / ind_shape[j];
    offset_at_idx = (int)(t - idx * ind_shape[j]);
    ind_offset += offset_at_idx * ind_step[j];
    inp_offset += offset_at_idx * step[j];
    t = idx;
    if (j == axis)
    {
        at_axis_val = offset_at_idx * step[j];
    }
}

ind_offset /= sizeof(T);

// get index and overwrite current indices
const T* tmp_p_index = p_index + ind_offset;
index = (int)(*tmp_p_index);
CV_Assert(index < shape[axis] && index > -shape[axis]);
inp_offset = inp_offset - at_axis_val + ((index + shape[axis]) % shape[axis]) * step[axis];
inp_offset /= sizeof(T);
```

**Review by rogday — COMMENTED** [review]
I had a few ideas for speeding this up further, if you don't mind. The code should be behave exactly the same. I ran tests, but might've missed something. Please take a look.

File: modules/dnn/src/layers/scatterND_layer.cpp (hunk 10 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/scatterND_layer.cpp:142]: It is indeed ~2X speedup getting rid of `inp_current_indices`

File: modules/dnn/src/layers/scatter_layer.cpp (hunk 11 above)
Comment (fengyuentau) [reply modules/dnn/src/layers/scatter_layer.cpp:139]: Yes, another speedup of ~1.5X.

**Review by rogday — APPROVED** [review]
LGTM! :+1:

**Review by asmorkalov — APPROVED** [review]
