### PR TITLE
Fixed bug with the last 4 bytes in MJPEG encoder

### LINKED ISSUE #19634: Out of bound access in cap_mjpeg_encoder.cpp
**Workaround**: OpenCV 3.4.14: disabled parallel MJPEG encoder

---

##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 20.04
- Compiler => gcc 9.3.0

##### Detailed description

While using the `cv::VideoWriter` to write a MJPEG video, I sometimes get an error that causes an out of memory write/read in `cap_mjpeg_encoder.cpp`.
Tracking it down with valgrind, I got the following :
```
==27350== Thread 3:
==27350== Invalid write of size 4
==27350==    at 0x586AA3D: get_data (cap_mjpeg_encoder.cpp:533)
==27350==    by 0x586AA3D: cv::mjpeg::MotionJpegWriter::writeFrameData(unsigned char const*, int, int, int) (cap_mjpeg_encoder.cpp:1867)
==27350==    by 0x586D5A9: cv::mjpeg::MotionJpegWriter::write(cv::_InputArray const&) (cap_mjpeg_encoder.cpp:843)
==27350==    by 0x5866DD8: cv::VideoWriter::write(cv::Mat const&) (cap.cpp:776)
```

Looking at the code, there is even a warning : 
```
        //bits == 0 means that last element shouldn't be used.
        m_output_buffer[m_data_len++] = currval;
```
And indeed, patching the code with : 
```
        //bits == 0 means that last element shouldn't be used.
        if (bits != 0) m_output_buffer[m_data_len++] = currval;
```
I don't get the issue anymore.

##### Steps to reproduce

If needed, I could try to produce a MWE.

##### Issue submission checklist

 - [X] I report the issue, it's not a question
   
 - [X] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found solution
   
 - [X] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

### LINKED ISSUE #24171: cv::VideoWriter with CAP_OPENCV_MJPEG api creates broken (or just unfinished) video file.
### System Information

OpenCV version: 4.8.0
Windows 11
Microsoft Visual Studio 2022 64bit

### Detailed description

If I create a certain video using cv::VideoWriter with CAP_OPENCV_MJPEG api, I can load the video correctly using cv::VideoCapture, but I get an error message during loading.
```
[mjpeg @ 0000015a20f1df00] error count: 268435456
[mjpeg @ 0000015a20f1df00] error y=0 x=0
```
Also I can watch the created video using Windows Media Player without any errors.
If I create the same video using CAP_FFMPEG api, I don't get error messages.
The error reproduces only on a certain video content, so I can create a different video with the same size without error messages.

### Steps to reproduce

```
#include <opencv2/highgui.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

#include <iostream>

int w = 16;
int h = 16;
int num_frames = 1;

void saveVideo(std::string filename, cv::VideoCaptureAPIs api, long base_color) {
    cv::VideoWriter writer(filename, api, cv::VideoWriter::fourcc('M', 'J', 'P', 'G'), 30, cv::Size(w, h), true);
    for (long i = 0; i < num_frames; ++i) {
        cv::Mat frame1(h, w, CV_8UC3);
        for (long x = 0; x < w; x++) {
            for (long y = 0; y < h; y++) {
                frame1.at<cv::Vec3b>(y, x) = cv::Vec3b((base_color * x) % 256, base_color + 2, base_color + 3);
            }
        }
        writer.write(frame1);
    }
    writer.release();
}

void loadVideo(std::string filename) {
    std::cout << "===== loading " << filename << std::endl << std::flush;
    cv::VideoCapture cap(filename, cv::CAP_FFMPEG);
    if (!cap.isOpened()) {
        std::cout << "No video stream detected" << std::endl;
        return;
    }
    cv::Mat frame;
    uint32_t frame_cnt = 0;
    while (true) {
        cap >> frame;
        if (frame.empty()) {
            break;
        }

    }
    cap.release();
    std::cout << "===== loaded " << filename << std::endl << std::flush;
}

int main(int argc, char* argv[]) {
    saveVideo("out1.avi", cv::CAP_FFMPEG, 147);
    saveVideo("out2.avi", cv::CAP_FFMPEG, 146);
    saveVideo("out3.avi", cv::CAP_OPENCV_MJPEG, 147);
    saveVideo("out4.avi", cv::CAP_OPENCV_MJPEG, 146);

    loadVideo("out1.avi");
    loadVideo("out2.avi");
    loadVideo("out3.avi");
    loadVideo("out4.avi"); // prints error message
}
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by alexlyulkov**
resolves #19634
resolves #24171
Enabled parallel processing, that was temporary disabled in #19812 because of the issue #19634

### CODE REVIEW

File: modules/videoio/src/cap_mjpeg_encoder.cpp [hunk 1]
```diff
@@ -268,7 +268,7 @@ class mjpeg_buffer_keeper
             m_buffer_list[0].finish();
 
             m_data_len = m_buffer_list[0].get_len();
-            m_last_bit_len = m_buffer_list[0].get_bits_free() ? 32 - m_buffer_list[0].get_bits_free() : 0;
+            m_last_bit_len = 32 - m_buffer_list[0].get_bits_free();
```
Comment (alexlyulkov) [inline modules/videoio/src/cap_mjpeg_encoder.cpp:271]: see https://github.com/opencv/opencv/blob/b3c896370cb6b61f9a45a1fa4dc2483a50d3097d/modules/videoio/src/cap_mjpeg_encoder.cpp#L192

Comment (alexlyulkov) [reply modules/videoio/src/cap_mjpeg_encoder.cpp:271]: if you call mjpeg_buffer::finish() than mjpeg_buffer::get_len() returns the number of occupied integers and mjpeg_buffer::get_bits_free() returns the number of free bits in the last integer (from 0 to 31)

File: modules/videoio/src/cap_mjpeg_encoder.cpp [hunk 2]
```diff
@@ -331,9 +331,14 @@ class mjpeg_buffer_keeper
         }
 
         //bits == 0 means that last element shouldn't be used.
-        m_output_buffer[m_data_len++] = currval;
-
-        m_last_bit_len = -bits;
+        if (bits != 0) {
```
Comment (alexlyulkov) [inline modules/videoio/src/cap_mjpeg_encoder.cpp:334]: If bits != 0 than currval contains some useful bits. We need to increase m_data_len and add the bits to the last item of m_output_buffer.
If bits == 0 than currval doesn't contain useful bits

**Review by asmorkalov — APPROVED** [review]
:+1: Thanks a lot for the patch! I removed the guard by myself.
