### PR TITLE
Fixed segfault at ORB::compute() near image's border

### LINKED ISSUE #5031: ORB feature detector crashes with AccessViolationException
Transferred from http://code.opencv.org/issues/4423

```
|| Robert Schwede on 2015-06-19 07:40
|| Priority: Normal
|| Affected: branch 'master' (3.0-dev)
|| Category: features2d
|| Tracker: Bug
|| Difficulty: 
|| PR: 
|| Platform: x64 / Windows
```
## ORB feature detector crashes with AccessViolationException 

```
When trying to to detect features on a large number of images, Orb::detectAndCompute() crashes from time to time with an AccessViolationException.
All my images are of the same size (256x256 pixels), it makes no difference if they contain random data or meaningful images.

I use Emgu.CV to call opencv from my c# program.

For the ORB detector, I use the following parameters:

nfeatures=1000, scaleFactor=1.2f, *nlevels=1*, edgeThreshold=0, firstLevel=0, WTA_K=2, scoreType=ORB::HARRIS_SCORE, *patchSize=32*

I was not able to reproduce the crash when I changed the patchSize to 31.

The crash happens after processing ~1000 images when processing the images in a sequential for-loop, but much faster (~20 images) when I try to process several images in parallel.

I was able to catch the exception in the VisualStudio debugger, but i have no experience in debugging unmanaged code. Please give me instructions how to extract additional information from the debugger, if neccessary.
Attached are screenshots from the debugger, showing the part of the code where the exception happens, and the local variables.
```
##### Robert Schwede on 2015-06-19 07:41

```
-   Assignee deleted (Maria Dimashova)
```

### PR DESCRIPTION
**Pull request by savuor**
resolves #5031
fixes fails of ORB tests if they are run in random order

### CODE REVIEW

File: modules/features2d/test/test_rotation_and_scale_invariance.cpp [hunk 1]
```diff
@@ -200,6 +200,8 @@ class DetectorRotationInvarianceTest : public cvtest::BaseTest
 
     void run(int)
     {
+        cv::ocl::setUseOpenCL(false);
```
Comment (alalek) [inline modules/features2d/test/test_rotation_and_scale_invariance.cpp]: Why?
#7787 should help here.

**Comment by alalek** [comment]
Patch has been updated (removed OpenCL related code).
:+1:
