### PR TITLE
Fix api preferences changed

### LINKED ISSUE #7268: Consolidate VideoCapture methods vs apiPreference param
##### System information
- OpenCV => 3.1

It would be useful to consolidate `VideoCapture` constructors and `open` methods regards to `apiPreference` parameter. 

In 3.1 we have:

``` cpp
//from file
VideoCapture (const String &filename);
VideoCapture (const String &filename, int apiPreference);
open(const String & filename);
open(const String & filename, int apiPreference);
//from device
VideoCapture (int index)
open(int index)
```

where `index=camera_id + domain_offset (CAP_*)`

Proposal:

``` cpp
//from file
VideoCapture (const String &filename, int apiPreference=CAP_ANY);
open(const String & filename, int apiPreference=CAP_ANY);
//from device
VideoCapture (int index, int apiPreference=CAP_ANY);
open(int index, int apiPreference=CAP_ANY);
```
### Note

removing methods will break binary compatibility (ABI). Changes should be considered for next major release.
### Detailed description

**Capture from file:** Proposed changes just expose [the internal way](https://github.com/opencv/opencv/blob/3.1.0/modules/videoio/src/cap.cpp#L589)

**Capture from device:** Currently  `index=camera_id + domain_offset (CAP_*)` but we could have same scheme as capture from file just adding a bit of code in the `open` [method](https://github.com/opencv/opencv/blob/3.1.0/modules/videoio/src/cap.cpp#L592) to manage old style syntax calls index+pref... something like  this:

``` cpp
VideoCapture::VideoCapture(int index,int apiPreference)
{ open(index,apiPreference); }

bool VideoCapture::open(int index, int apiPreference)
{
    // manage old style calls index+pref
    // if both are present the apiPreference param will won
    int pref = (index / 100) * 100; //no pref => 0
    if (apiPreference == pref)
        pref = 0;
    else if (apiPreference == CAP_ANY)
        apiPreference = pref;
    index = index + apiPreference - pref;
    //old code
    if (isOpened()) release();
    icap = IVideoCapture_create(index);
    ...
```

even if changes in `IVideoCapture_create` and `cvCreateCameraCapture` should be considered

### PR DESCRIPTION
**Pull request by souch55**
### This pullrequest changes

resolves #7268

### CODE REVIEW

**Comment by alalek** [comment]
Why you create a new PR? You should continue to work in existed, especially if you received some comments where.

**Comment by souch55** [comment]
Hi alalek there was some issue with my old PR,which was not able to rebase or modify,as the review comments i have tried to create an new PR,the suggestion was as use same cvCreateCameraCapture sun with out replicating it,so i have improved this in new PR.But i can see now ABI related error is coming.

**Comment by alalek** [comment]
> some issue

I believe "force" push should help in your case (`git push -f origin <branch_name>`).

Also your "base" commit of your branch is still too old: d06bdd5bf6e11b73c46cb7281cceb013d938cc8b so that creates inappropriate git history.
You need to follow this:
- commit/stash all pending changes
- configure git remote with "upstream" name: https://help.github.com/articles/configuring-a-remote-for-a-fork/
- `git pull --rebase upstream master` (in case of conflicts resolve them, add files to index, and continue via `git rebase --continue`)
- to update PR make "force" push of your changes
- optionally you can update you master: `git branch -f master upstream/master`

File: modules/videoio/src/cap.cpp [hunk 1]
```diff
@@ -589,6 +594,22 @@ bool VideoCapture::open(int index)
     return isOpened();
 }
 
+bool VideoCapture::open(int index,int apiPreference)//added
```
Comment (paroj) [inline modules/videoio/src/cap.cpp]: as said in the bug report. this should be just
`return open(camera + apiPreference);`

**Comment by souch55** [comment]
Hi paroj any review comments or suggestion how this pr can be improved as ABI related things are coming,have improved this pr changes as per urs last suggestion ,still ABI related things are breaking.

File: modules/videoio/include/opencv2/videoio.hpp [hunk 2]
```diff
@@ -650,6 +650,12 @@ class CV_EXPORTS_W VideoCapture
     */
     CV_WRAP virtual bool open(int index);
 
+    /**@overload
+
+    Parameters are open(int index,int apiPreference)
+    */
+    CV_WRAP virtual bool open(int index,int apiPreference);
```
Comment (paroj) [inline modules/videoio/include/opencv2/videoio.hpp]: do not make this function virtual to pass the ABI checks.

Comment (paroj) [inline modules/videoio/include/opencv2/videoio.hpp]: also change the argument `index` to `cameraNum` as it has different semantics.

File: modules/videoio/include/opencv2/videoio.hpp [hunk 3]
```diff
@@ -650,6 +650,12 @@ class CV_EXPORTS_W VideoCapture
     */
     CV_WRAP virtual bool open(int index);
 
+    /**@overload
+
+    Parameters are open(int cameraNum,int apiPreference)
```
Comment (alalek) [inline modules/videoio/include/opencv2/videoio.hpp]: Looks good to me except missing space after comma (3 locations):
> int cameraNum,<**space**>int apiPreference

And we will merge it.

File: modules/videoio/include/opencv2/videoio.hpp [hunk 4]
```diff
@@ -650,6 +650,14 @@ class CV_EXPORTS_W VideoCapture
     */
     CV_WRAP virtual bool open(int index);
 
+    /** @brief  Open a camera for video capturing
+
+    @overload
+
+    Parameters of the methods are open(int cameraNum, int apiPreference),@return open(cameraNum + apiPreference).
```
Comment (alalek) [inline modules/videoio/include/opencv2/videoio.hpp]: Please place `@return` on a separate line and remove comma before that, because it is visible in [documentation](http://pullrequest.opencv.org/buildbot/export/pr/7625/docs/d8/dfe/classcv_1_1VideoCapture.html#a128a4457358fb7dccb9a9a686e56e344).

Comment (alalek) [inline modules/videoio/include/opencv2/videoio.hpp]: Also link should be on constructor VideoCapture instead this function itself. Use method above as an example.

**Comment by alalek** [comment]
Thank you! :+1:

File: modules/videoio/include/opencv2/videoio.hpp [hunk 5]
```diff
@@ -650,6 +650,16 @@ class CV_EXPORTS_W VideoCapture
     */
     CV_WRAP virtual bool open(int index);
 
+   /** @brief  Open a camera for video capturing
+
+    @overload
+
+    This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
```
Comment (PkLab) [inline modules/videoio/include/opencv2/videoio.hpp]: The sentence "_This is an overloaded member function..._" should be removed because it's added automatically by doxygen due to the `overload` tag

**Comment by PkLab** [comment]
In the comment for `open(int cameraNum, int apiPreference);` the sentence _This is an overloaded member function..._ should be removed because it's added automatically by doxygen due to the `overload` tag
