### PR TITLE
displayOverlay doesn't disappear after timeout

### LINKED ISSUE #26555: python binding: displayOverlay doesn't disappear from the display unless a mouse move event happens over the image
### System Information

opencv: 4.10.0
os: debian 12
python 3.12.7

### Detailed description

Expected behaviour: 
an overlay should be displayed atop an image and then disappear after delayms has timed out but doesn't.

Also, displayStatusBar doesn't appear to set any text on the window.

Actual:
the overlay appears but doesn't disappear unless a mouse move event happens on the image

Workaround / fix

I have to send a flag to `namedWindow`, either `cv2.WINDOW_GUI_EXPANDED` or `cv2.WINDOW_NORMAL` and call displayStatus bar and set the same timeout value, to get the overlay to disappear without the mouse move event needed. 

Presumably this method must be calling something that displayOverlay doesn't. 

If I use different timeout values in the two method calls, the overlay doesn't disappear.

### Steps to reproduce

For example, this code should display an image, display an overlay for 1.5s and then disappear.
```python
import cv2

im = cv2.imread('foo.png')
cv2.namedWindow('asdf', cv2.WINDOW_GUI_EXPANDED)
cv2.imshow('asdf', im)
cv2.displayOverlay('asdf', 'look at this overlay!', 1500)

cv2.waitKey(0)
```

The overlay appears but doesn't vanish unless I move the mouse cursor across the image.

The overlay disappears with the addition of the displayStatusBar call:

```python
import cv2

im = cv2.imread('foo.png')
cv2.namedWindow('asdf', cv2.WINDOW_GUI_EXPANDED)
cv2.imshow('asdf', im)
cv2.displayOverlay('asdf', 'look at this overlay!', 1500) # the timeout values must be the same between the two calls
cv2.displayStatusBar('asdf', 'asdf', 1500) # doesn't appear to set any text in status bar neither

cv2.waitKey(0)
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by iiiuhuy**
Fixes #26555

### Expected Behaviour
An overlay should be displayed atop an image and then disappear after `delayms` has timed out, but it doesn't. Also, `displayStatusBar` doesn't appear to set any text on the window.

### Actual Behaviour
The overlay appears but doesn't disappear unless a mouse move event happens on the image.

### Changes
- Fixed the issue with `displayOverlay` not disappearing after the timeout.

### Checklist
- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV.
- [x] The PR is proposed to the proper branch.
- [x] There is a reference to the original bug report and related work.
- [ ] There is accuracy test, performance test, and test data in the opencv_extra repository, if applicable.
- [ ] The feature is well documented, and sample code can be built with the project CMake.

### CODE REVIEW

File: modules/highgui/src/window_QT.cpp [hunk 1]
```diff
@@ -299,6 +299,13 @@ CV_IMPL void cvDisplayOverlay(const char* name, const char* text, int delayms)
         Q_ARG(QString, QString(name)),
         Q_ARG(QString, QString(text)),
         Q_ARG(int, delayms));
+
+    if (delayms > 0)
+    {
+        QTimer::singleShot(delayms, [name]() {
+            cvUpdateWindow(name);  // Force redraw
+        });
+    }
```
Comment (asmorkalov) [inline modules/highgui/src/window_QT.cpp:308]: What if just add "update" to the end of `DefaultViewPort::stopDisplayInfo()`? The method is involed by existing timer. No need to create a new one.

File: modules/highgui/src/window_QT.cpp [hunk 2]
```diff
@@ -2655,7 +2662,10 @@ void DefaultViewPort::startDisplayInfo(QString text, int delayms)
         stopDisplayInfo();
 
     infoText = text;
-    if (delayms > 0) timerDisplay->start(delayms);
+    if (delayms > 0)  {
+        timerDisplay->start(delayms);
+        QTimer::singleShot(delayms, this, SLOT(update())); //force referesh
```
Comment (asmorkalov) [inline modules/highgui/src/window_QT.cpp:2667]: The same idea.

**Review by asmorkalov — CHANGES_REQUESTED** [review]

**Comment by asmorkalov** [comment]
The cvUpdateWindow designed for OpenGL integration:
```
CV_IMPL void cvUpdateWindow(const char*)
{
    CV_Error(cv::Error::OpenGlNotSupported, "The library is compiled without OpenGL support");
}
```
I got the error in my build without OpenGL support.

**Review by asmorkalov — APPROVED** [review]
