### PR TITLE
imgcodecs: fix integer overflow in BMP and SunRaster decoders

### LINKED ISSUE #28350: Integer overflow in BMP and SunRaster decoders may cause heap buffer over-read
### System Information

OpenCV version: 4.x (current master)
Operating System / Platform: macOS
Compiler & compiler version: Apple Clang (Xcode default)

### Detailed description

BmpDecoder::readData and SunRasterDecoder::readData compute `src_pitch`
using width × bits-per-pixel arithmetic without sufficient overflow checks.

For large crafted image widths, these calculations can overflow 32-bit
integers, resulting in insufficient buffer allocation. Subsequent decoding
logic (e.g. row copy operations) may then read beyond the allocated buffer,
causing a heap buffer over-read.

### Affected code
- modules/imgcodecs/src/grfmt_bmp.cpp
- modules/imgcodecs/src/grfmt_sunras.cpp

### Impact
A malformed BMP or SunRaster image may trigger out-of-bounds memory access
during decoding via `cv::imdecode`.

### Root cause
- Missing overflow checks for width × bpp calculations
- Missing bounds checks for width × channel count

### Reproduction
The issue can be triggered by decoding a crafted BMP or SunRaster image
with very large width values that cause width × bpp arithmetic to overflow.

Example parameters:
- Width: 134217731
- Height: 1
- Bits per pixel: 32

When decoded, the computed `src_pitch` overflows and results in insufficient
buffer allocation.

A minimal reproducer can be constructed by crafting an image header with
the above values and passing it to `cv::imdecode`.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by raimbekovm**
### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

Fixes #28350

### Description

This PR fixes integer overflow vulnerabilities in BMP and SunRaster image decoders that could cause heap buffer over-read when decoding malformed images.

### Root Cause

The `src_pitch` and `width3` calculations in `BmpDecoder::readData()` and `SunRasterDecoder::readData()` used `int` arithmetic:

```cpp
int src_pitch = ((m_width * m_bpp + 7) / 8 + 3) & -4;
int width3 = m_width * nch;
```

When `m_width` or `m_bpp` are large values from a crafted malicious file, the multiplication overflows, resulting in a small or negative value. This leads to insufficient buffer allocation, causing heap buffer over-read during subsequent decoding operations.

### Fix

1. **Use `size_t` arithmetic**: Cast operands to `size_t` before multiplication:
   ```cpp
   const size_t bits_per_row = static_cast<size_t>(m_width) * static_cast<size_t>(m_bpp);
   const size_t src_pitch_size = ((bits_per_row + 7) / 8 + 3) & ~static_cast<size_t>(3);
   ```

2. **Add size validation**: Added `CV_CheckLT` to reject images requiring buffers larger than 256MB:
   ```cpp
   const size_t MAX_SRC_PITCH = static_cast<size_t>(1) << 28;
   CV_CheckLT(src_pitch_size, MAX_SRC_PITCH, "BMP: src_pitch exceeds maximum allowed size");
   ```

3. **Safe conversion**: Use `validateToInt()` for safe conversion back to `int`.

### Files Changed

- `modules/imgcodecs/src/grfmt_bmp.cpp` - BmpDecoder::readData()
- `modules/imgcodecs/src/grfmt_sunras.cpp` - SunRasterDecoder::readData()

### Testing

- Code compiles without warnings
- Basic BMP and SunRaster encode/decode tests pass
- Overflow conditions are now properly rejected with CV_CheckLT

### CODE REVIEW

**Comment by asmorkalov** [comment]
@vrabaud Could you take a look on the patch?

File: modules/imgcodecs/src/grfmt_sunras.cpp [hunk 1]
```diff
@@ -133,10 +133,19 @@ bool  SunRasterDecoder::readData( Mat& img )
     size_t step = img.step;
     uchar  gray_palette[256] = {0};
     bool   result = false;
-    int  src_pitch = ((m_width*m_bpp + 7)/8 + 1) & -2;
     int  nch = color ? 3 : 1;
-    int  width3 = m_width*nch;
-    int  y;
+
+    const size_t bits_per_row = static_cast<size_t>(m_width) * static_cast<size_t>(m_bpp);
```
Comment (vrabaud) [inline modules/imgcodecs/src/grfmt_sunras.cpp]: This seems like heavy logic that would be worth not duplicating. Can you please make that a function that you export in modules/imgcodecs/src/grfmt_bmp.h ? Thx.

**Comment by raimbekovm** [comment]
Done. I moved the shared logic to `utils.hpp/cpp` instead of `grfmt_bmp.hpp` for a few reasons:

1. `utils.hpp` already has `validateToInt()` which both decoders use
2. Both BMP and SunRaster include `utils.hpp` through `grfmt_base.hpp`, so no new includes needed
3. Keeps SunRaster independent from BMP (would be weird to have sunras depend on bmp header)

Added two functions:
- `calculateRowPitch(width, bpp, alignment, format_name)` - returns aligned pitch + raw bytes_per_row (SunRaster needs it for RLE)
- `calculateRowSize(width, nch, format_name)` - for width*channels calculation

Both use the same 256MB limit and throw `cv::Error` with format-specific message on overflow.
