### PR TITLE
Use the YV12 format in the Android emulator to avoid image issues

### LINKED ISSUE #8166: Wrong format returned on CvCameraViewFrame.rgba() in Android emulator
##### System information (version)
- OpenCV => 3.2
- Operating System / Platform => Android
- Compiler => Android Studio 2.2

##### Detailed description

Images captured from the camera do not look fine when using the Android emulator. It looks as though there is some wrong color conversion.

More information: http://stackoverflow.com/questions/27083097/opencv-android-color-issue-using-camerabridgeviewbase

Other platforms might also be affected from this wrong color conversion.

##### Steps to reproduce

- Open the FaceDetect sample in the Android emulator

### PR DESCRIPTION
**Pull request by jmgomezpoveda**
resolves #8166 

### This pullrequest changes

This change forces the Android emulator to use the YV12 format to avoid image issues.

### CODE REVIEW

File: modules/java/generator/src/java/android+JavaCameraView.java [hunk 1]
```diff
@@ -303,7 +311,10 @@ public Mat gray() {
 
         @Override
         public Mat rgba() {
-            Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21, 4);
+            if (mPreviewFormat == ImageFormat.NV21)
+                Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGBA_NV21, 4);
+            else if (mPreviewFormat == ImageFormat.YV12)
+                Imgproc.cvtColor(mYuvFrameData, mRgba, Imgproc.COLOR_YUV2RGB_I420, 4);  // COLOR_YUV2RGBA_YV12 produces inverted colors
```
Comment (vpisarev) [inline modules/java/generator/src/java/android+JavaCameraView.java]: what about the "else" branch?

Comment (jmgomezpoveda) [inline modules/java/generator/src/java/android+JavaCameraView.java]: Is there a need for an else branch? On initialisation, the previewFormat is always set to NV21 or YV12:

```
if (Build.BRAND.equalsIgnoreCase("generic") || Build.BRAND.equalsIgnoreCase("Android"))
    params.setPreviewFormat(ImageFormat.YV12);  // "generic" or "android" = android emulator
else
    params.setPreviewFormat(ImageFormat.NV21);
```

I still kept the " if (mPreviewFormat == ImageFormat.YV12)" condition because I thought it looked more informative, but that part can be safely removed.

Comment (alalek) [inline modules/java/generator/src/java/android+JavaCameraView.java]: Al least we need here `else` branch with exception for non-implemented support.

Comment (vpisarev) [inline modules/java/generator/src/java/android+JavaCameraView.java]: the purpose of having "else" branch and "default" case in switch statement is to add some protection for possible mistakes during further modifcations, refactoring.

Comment (jmgomezpoveda) [inline modules/java/generator/src/java/android+JavaCameraView.java]: Ok

**Comment by alalek** [comment]
Could you please squash commits into one to eliminate "fixup" changes from Git history?

**Comment by jmgomezpoveda** [comment]
@alalek sorry, I just saw your message. For some reason I am not getting notifications.
