### PR TITLE
Fixed mask reduction in seamless_clone

### LINKED ISSUE #10627: seamless_cloning.cpp off-by-1
##### System information (version)
- OpenCV => master
- Operating System / Platform => Any
- Compiler => Any

##### Detailed description

I think the seamless_cloning.cpp code is off by one pixel: In the loop, maxx and maxy are set as the last pixels that should be included (since they are white).

```
    for(int i=0;i<h;i++)
    {
        for(int j=0;j<w;j++)
        {
            if(gray.at<uchar>(i,j) == 255)
            {
                minx = std::min(minx,i);
                maxx = std::max(maxx,i);
                miny = std::min(miny,j);
                maxy = std::max(maxy,j);
            }
        }
    }
```
However, later-on, the length of the ROI is defined as  `int lenx = maxx - minx;`, thus excluding the` maxx` pixel.

##### Steps to reproduce

For example, having a pixel at x-positions 203 and 206 will generate a `lenx` of `206 - 203 = 3` pixels, while the actual length should be `4` _(pixels at 203, 204, 205 and 206)_.

### PR DESCRIPTION
**Pull request by terfendail**
resolves #10627
### This pullrequest changes
Fixed mask reduction in seamless_clone.
Renamed a few variables to make the code more obvious.

### CODE REVIEW

File: modules/photo/src/seamless_cloning.cpp [hunk 1]
```diff
@@ -75,30 +75,30 @@ void cv::seamlessClone(InputArray _src, InputArray _dst, InputArray _mask, Point
...
 
-    Rect roi_d(minyd,minxd,leny,lenx);
-    Rect roi_s(miny,minx,leny,lenx);
+    Rect roi_d(minxd,minyd,lenx,leny);
+    Rect roi_s(minx,miny,lenx,leny);
 
     Mat destinationROI = dest(roi_d).clone();
 
-    Mat sourceROI = Mat::zeros(leny, lenx, src.type());
+    Mat sourceROI = Mat::zeros(lenx, leny, src.type());
```
Comment (alalek) [inline modules/photo/src/seamless_cloning.cpp]: Parameters order doesn't look correct:

> static MatExpr zeros(int rows, int cols, int type);

**Comment by vpisarev** [comment]
looks good! :+1:
