### PR TITLE
Fix truncated sentenced in boxPoints documentation #22975

### LINKED ISSUE #22975: Truncated sentenced in boxPoints documentation
### Descripe the doc issue

There is a truncated sentence in [boxPoints](https://docs.opencv.org/4.6.0/d3/dc0/group__imgproc__shape.html#gaf78d467e024b4d7936cf9397185d2f5c).
The `box` parameter says `The input rotated rectangle. It may be the output of`.

### Fix suggestion

It could be `It may be the output of minAreaRect.`

### PR DESCRIPTION
**Pull request by akormous**
Resolves #22975

Completed the sentence as per the suggestion given in the issue #22975
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/include/opencv2/imgproc.hpp [hunk 1]
```diff
@@ -4086,7 +4086,7 @@ The function finds the four vertices of a rotated rectangle. This function is us
 rectangle. In C++, instead of using this function, you can directly use RotatedRect::points method. Please
 visit the @ref tutorial_bounding_rotated_ellipses "tutorial on Creating Bounding rotated boxes and ellipses for contours" for more information.
 
-@param box The input rotated rectangle. It may be the output of
+@param box The input rotated rectangle. It may be the output of minAreaRect.
```
Comment (dkurt) [inline modules/imgproc/include/opencv2/imgproc.hpp:4089]:
```suggestion
@param box The input rotated rectangle. It may be the output of @ref minAreaRect.
```

**Review by asmorkalov — APPROVED** [review]

**Review by dkurt — APPROVED** [review]
