### PR TITLE
Edited on tag '4.3.0-openvino' to support HDDL

### LINKED ISSUE #17727: OpenCV with OpenVINO - dual MYRIAD mPCIe
##### System information (version)

- OpenCV => 4.3.0-openvino
- Operating System / Platform => ubuntu 18.04
- Compiler => python 3.6.9

##### Detailed description

When I try to run my model using `cv2.dnn.DNN_TARGET_MYRIAD` while having the intel neural compute stick 2 (NCS2) connected, everything runs completely fine. However, when I insert the mPCIe 'vega-330' which has two Movidius MYRIAD cores, I get the following error.

```cv2.error: OpenCV(4.3.0-openvino) ../opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Can not init Myriad device: NC_ERROR in function 'initPlugin'```

When I use the demo files in the openvino directory '/opt/intel/openvino/deployment_tools/demo/', both the NCS2 and the mPCIe work though sometimes I face some issues with the mPCIe

The option used to run the demo using the mPCIe is `-d HDDL` while the option used to run it on the NCS2 is `-d MYRIAD`

In opencv, there is only the option `cv2.dnn.DNN_TARGET_MYRIAD`.

My question is: How do I run my opencv model (python) on the mPCIe?

### PR DESCRIPTION
**Pull request by Omar-AE**
This pull request is not ready to be merged. I still have an issue and I created this pull request to seek assistance as suggested by @dkurt . @mshabunin

<cut/>

First, I am trying to create this pull request to be compared with the tag **4.3.0-openvino**. However, I could only compare it to master, and I would like to merge it to the tag 4.3.0-openvino. I know that a tag is different from a branch but I edited the code starting from the tag 4.3.0-openvino.

Second, I am getting the following exception when I try to use the newly added directive `cv2.dnn.DNN_TARGET_HDDL` instead of `cv2.dnn.DNN_TARGET_MYRIAD`:
```
AttributeError: module 'cv2.dnn' has no attribute 'DNN_TARGET_HDDL'
```
I am not sure where should I edit to let python3 be able to have the new constant `DNN_TARGET_HDDL`.

closes #17727 

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2020.4.0:16.04
build_image:Custom Win=openvino-2020.4.0
build_image:Custom Mac=openvino-2020.4.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Comment by Omar-AE** [comment]
> Hi!
> 
> Please start with the latest master branch to resolve the conflicts.
> 
> > AttributeError: module 'cv2.dnn' has no attribute 'DNN_TARGET_HDDL'
> 
> Check `python3 -c "import cv2 as cv; print(cv.__file__)"` - it should point to build directory. Is not, specify `PYTHONPATH=/path/to/opencv/build/lib/python3`

Thank you for your reply.

Adding the python path you mentioned worked.

I started again from the latest master branch and moved my commit to it. How can I change the branch I would like to requrest a merge from? Should I open a new PR?

**Comment by dkurt** [comment]
@Omar-AE, you can just rename the branches and force push actual changes:
```
git branch -m hddl-supported old-hddl-supported
git branch -m new_branch hddl-supported
git push <fork_name> -f hddl-supported
```

**Comment by Omar-AE** [comment]
I accidentally deleted the branch `hddl-supported`. Can I reopen the PR?

File: modules/dnn/src/op_inf_engine.cpp [hunk 1]
```diff
@@ -1140,14 +1148,15 @@ void resetMyriadDevice()
 {
 #ifdef HAVE_INF_ENGINE
     AutoLock lock(getInitializationMutex());
+    std::string device = detectMyriadX_("MYRIAD") ? "MYRIAD" : "HDDL";
```
Comment (dkurt) [inline modules/dnn/src/op_inf_engine.cpp:1151]: Please add a default argument with device type:
```cpp
void resetMyriadDevice(const std::string& device = "MYRIAD")
```

File: modules/dnn/src/op_inf_engine.cpp [hunk 2]
```diff
@@ -1156,9 +1165,9 @@ void resetMyriadDevice()
 }
 
 #ifdef HAVE_INF_ENGINE
-bool isMyriadX()
+bool isMyriadX(std::string device)
```
Comment (dkurt) [inline modules/dnn/src/op_inf_engine.cpp:1168]: Not sure that we really need this. MyriadX is MyriadX even on HDDL

**Comment by Omar-AE** [comment]
I successfully built the last changes on my Ubuntu 18.04.5 LTS machine. Any idea how to resolve the remaining failed builds?

File: modules/dnn/src/op_inf_engine.cpp [hunk 3]
```diff
@@ -652,20 +656,24 @@ InferenceEngine::Core& getCore(const std::string& id)
...
+        if (i->find(device) != std::string::npos)
         {
             const std::string name = ie.GetMetric(*i, METRIC_KEY(FULL_DEVICE_NAME)).as<std::string>();
             CV_LOG_INFO(NULL, "Myriad device: " << name);
-            return name.find("MyriadX") != std::string::npos  || name.find("Myriad X") != std::string::npos;
+
+            if (device == "MYRIAD")
+                return name.find("MyriadX") != std::string::npos  || name.find("Myriad X") != std::string::npos;
+            else if (device == "HDDL")
+                return name.find("HDDL") != std::string::npos;
```
Comment (dkurt) [inline modules/dnn/src/op_inf_engine.cpp:676]: What is a full name for MyriadX based HDDL? I mean that there is also FPGA HDDL so we can distinguish them

Comment (Omar-AE) [reply modules/dnn/src/op_inf_engine.cpp:676]: It is only 'HDDL'.
```
$ python3 /opt/intel/openvino/deployment_tools/inference_engine/samples/python/hello_query_device/hello_query_device.py
.
.
.
	Device: HDDL
	Metrics:
		AVAILABLE_DEVICES: 
		SUPPORTED_METRICS: AVAILABLE_DEVICES, SUPPORTED_METRICS, SUPPORTED_CONFIG_KEYS, FULL_DEVICE_NAME, OPTIMIZATION_CAPABILITIES, RANGE_FOR_ASYNC_INFER_REQUESTS, VPU_HDDL_DEVICE_NUM, VPU_HDDL_DEVICE_NAME, VPU_HDDL_DEVICE_THERMAL, VPU_HDDL_DEVICE_ID, VPU_HDDL_DEVICE_SUBCLASS, VPU_HDDL_DEVICE_MEMORY_TOTAL, VPU_HDDL_DEVICE_MEMORY_USED, VPU_HDDL_DEVICE_UTILIZATION, VPU_HDDL_DEVICE_TAG, VPU_HDDL_STREAM_ID
		SUPPORTED_CONFIG_KEYS: PERF_COUNT, VPU_INPUT_NORM, VPU_INPUT_BIAS, VPU_HDDL_GRAPH_TAG, VPU_HDDL_STREAM_ID, VPU_HDDL_DEVICE_TAG, VPU_HDDL_BIND_DEVICE, VPU_HDDL_RUNTIME_PRIORITY, VPU_HDDL_USE_SGAD, VPU_COPY_OPTIMIZATION, LOG_LEVEL, VPU_IGNORE_UNKNOWN_LAYERS, VPU_HW_STAGES_OPTIMIZATION, VPU_NONE_LAYERS, VPU_NUMBER_OF_SHAVES, VPU_NUMBER_OF_CMX_SLICES, VPU_HW_INJECT_STAGES, VPU_HW_POOL_CONV_MERGE, VPU_HW_STAGES_OPTIMIZATION, EXCLUSIVE_ASYNC_REQUESTS
		FULL_DEVICE_NAME: Intel Vision Accelerator Design with Intel Movidius VPUs
		OPTIMIZATION_CAPABILITIES: FP16
[16:36:35.6871][2839]I[ClientManager.cpp:159] client(id:2) registered: clientName=HDDLPluginForQuery socket=2
		RANGE_FOR_ASYNC_INFER_REQUESTS: 8, 150, 1
		VPU_HDDL_DEVICE_NUM: 2
		VPU_HDDL_DEVICE_NAME: 3.1, 3.2
		VPU_HDDL_DEVICE_THERMAL: 61.891929626464844, 62.51952362060547
		VPU_HDDL_DEVICE_ID: 224, 225
		VPU_HDDL_DEVICE_SUBCLASS: 0, 0
		VPU_HDDL_DEVICE_MEMORY_TOTAL: 483, 483
		VPU_HDDL_DEVICE_MEMORY_USED: 0, 0
		VPU_HDDL_DEVICE_UTILIZATION: 0.0, 0.0
		VPU_HDDL_DEVICE_TAG: , 
		VPU_HDDL_STREAM_ID: , 

	Default values for device configuration keys:
		PERF_COUNT: 
		VPU_INPUT_NORM: 
		VPU_INPUT_BIAS: 
		VPU_HDDL_GRAPH_TAG: 
		VPU_HDDL_STREAM_ID: 
		VPU_HDDL_DEVICE_TAG: 
		VPU_HDDL_BIND_DEVICE: 
		VPU_HDDL_RUNTIME_PRIORITY: 
		VPU_HDDL_USE_SGAD: 
		VPU_COPY_OPTIMIZATION: 
		LOG_LEVEL: 
		VPU_IGNORE_UNKNOWN_LAYERS: 
		VPU_HW_STAGES_OPTIMIZATION: 
		VPU_NONE_LAYERS: 
		VPU_NUMBER_OF_SHAVES: 
		VPU_NUMBER_OF_CMX_SLICES: 
		VPU_HW_INJECT_STAGES: 
		VPU_HW_POOL_CONV_MERGE: 
		VPU_HW_STAGES_OPTIMIZATION: 
		EXCLUSIVE_ASYNC_REQUESTS: 
```
When I insert the NCS2, I get
```
$ python3 /opt/intel/openvino/deployment_tools/inference_engine/samples/python/hello_query_device/hello_query_device.py
.
.
.
	Device: MYRIAD
	Metrics:
		RANGE_FOR_ASYNC_INFER_REQUESTS: 3, 6, 1
		OPTIMIZATION_CAPABILITIES: FP16
		DEVICE_THERMAL: UNSUPPORTED TYPE
		SUPPORTED_CONFIG_KEYS: PERF_COUNT, EXCLUSIVE_ASYNC_REQUESTS, DEVICE_ID, VPU_MYRIAD_PLATFORM, VPU_IGNORE_IR_STATISTIC, VPU_CUSTOM_LAYERS, CONFIG_FILE, VPU_MYRIAD_FORCE_RESET, VPU_PRINT_RECEIVE_TENSOR_TIME, LOG_LEVEL, VPU_HW_STAGES_OPTIMIZATION
		SUPPORTED_METRICS: RANGE_FOR_ASYNC_INFER_REQUESTS, OPTIMIZATION_CAPABILITIES, DEVICE_THERMAL, SUPPORTED_CONFIG_KEYS, SUPPORTED_METRICS, FULL_DEVICE_NAME, AVAILABLE_DEVICES
		FULL_DEVICE_NAME: Intel Movidius Myriad X VPU
		AVAILABLE_DEVICES: 1.1.2-ma2480

	Default values for device configuration keys:
		PERF_COUNT: OFF
		EXCLUSIVE_ASYNC_REQUESTS: OFF
		DEVICE_ID: 
		VPU_MYRIAD_PLATFORM: 
		VPU_IGNORE_IR_STATISTIC: OFF
		VPU_CUSTOM_LAYERS: 
		CONFIG_FILE: 
		VPU_MYRIAD_FORCE_RESET: OFF
		VPU_PRINT_RECEIVE_TENSOR_TIME: OFF
		LOG_LEVEL: LOG_NONE
		VPU_HW_STAGES_OPTIMIZATION: ON
```

Comment (dkurt) [reply modules/dnn/src/op_inf_engine.cpp:676]: Got it. So, do you mind if `detectMyriadX_` will just return true in this way?
```cpp
return name.find("MyriadX") != std::string::npos  ||
       name.find("Myriad X") != std::string::npos ||
       name.find("HDDL") != std::string::npos;
```
because we use it only as 
```cpp
bool isMyriadX_ = detectMyriadX_("MYRIAD");
bool isHDDL_ = detectMyriadX_("HDDL");
if (isMyriadX_ || isHDDL_)
```

Comment (Omar-AE) [reply modules/dnn/src/op_inf_engine.cpp:676]: Sure, sounds perfect. But why do you think this would resolve the failed builds?

Comment (dkurt) [reply modules/dnn/src/op_inf_engine.cpp:676]: I have not checked failed builds - it just a part of code review. Let me see

Comment (dkurt) [reply modules/dnn/src/op_inf_engine.cpp:676]: please apply the changes and let's see how ABI tests will go

File: modules/dnn/include/opencv2/dnn/utils/inference_engine.hpp [hunk 4]
```diff
@@ -40,7 +40,7 @@ CV_EXPORTS_W cv::String setInferenceEngineBackendType(const cv::String& newBacke
  * Single Myriad device cannot be shared across multiple processes which uses
  * Inference Engine's Myriad plugin.
  */
-CV_EXPORTS_W void resetMyriadDevice();
+CV_EXPORTS_W void resetMyriadDevice(const std::string& device = "MYRIAD");
```
Comment (dkurt) [inline modules/dnn/include/opencv2/dnn/utils/inference_engine.hpp:43]: @alalek, can you suggest a new version number for `#define OPENCV_DNN_API_VERSION 20200908`?

**Comment by Omar-AE** [comment]
> I successfully built the last changes on my Ubuntu 18.04.5 LTS machine. Any idea how to resolve the remaining failed builds (on Linux x64 and iOS)?

Any update regarding this?

File: modules/dnn/include/opencv2/dnn/utils/inference_engine.hpp (hunk 4 above)
Comment (alalek) [reply modules/dnn/include/opencv2/dnn/utils/inference_engine.hpp:43]: I would prefer to add dedicated `resetHDDLDevice()` API for that.

File: modules/dnn/src/layers/convolution_layer.cpp [hunk 5]
```diff
@@ -314,9 +314,9 @@ class ConvolutionLayerImpl CV_FINAL : public BaseConvolutionLayerImpl
         {
             if (kernel_size.size() == 3)
                 return preferableTarget == DNN_TARGET_CPU;
-            if ((backendId == DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_2019 || preferableTarget != DNN_TARGET_MYRIAD) && blobs.empty())
+            if ((backendId == DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_2019 || preferableTarget != DNN_TARGET_MYRIAD && preferableTarget != DNN_TARGET_HDDL) && blobs.empty())
                 return false;
-            return (preferableTarget != DNN_TARGET_MYRIAD || dilation.width == dilation.height);
+            return (preferableTarget != DNN_TARGET_MYRIAD && preferableTarget != DNN_TARGET_HDDL || dilation.width == dilation.height);
```
Comment (alalek) [inline modules/dnn/src/layers/convolution_layer.cpp:319]: Obfuscated conditions.

**Review by alalek — APPROVED** [review]
LGTM
