### PR TITLE
objdetect: Properly check for C++11 as it's done in the matching .cpp…

### LINKED ISSUE #7623: Build fails with C++11 enabled in MinGW-w64 5.3.0 - Different conditionals in Detection Based Tracker
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => Windows 32 Bit
- Compiler => MinGW-w64 5.3.0 (as shipped with Qt 5.7)

##### Detailed description

In an attempt to compile OpenCV 3.1 with the Qt 5.7-bundled 32-Bit MinGW-w64 5.3.0 compiler and proper Qt GUI bindings, I needed to do "set CXXFLAGS=-std=gnu++11" prior to compiling. Otherwise, build fails at the Qt bindings, because latest Qt 5.7 can only be built with C++11 enabled.

With this option though, build fails at 74% in detection_based_tracker.cpp.
This code is only conditionally compiled and while I cannot totally figure out what platforms you want to exclude, the conditions should at least be the same in detection_based_tracker.cpp and detection_based_tracker.hpp. Currently, detection_based_tracker.cpp checks for __cplusplus > 199711L and detection_based_tracker.hpp wants __cplusplus > 201103L. In my opinion, this needs to be changed to > 199711L in the .hpp file. It fixes the problem for me.

##### Steps to reproduce

mkdir mingw_build
cd mingw_build
set CXXFLAGS=-std=gnu++11
cmake -D WITH_QT=ON -D WITH_OPENGL=ON -G "MinGW Makefiles" ../sources
mingw32-make

### PR DESCRIPTION
**Pull request by ColinFinck**
resolves #7623

### This pullrequest changes

Fixes #7623

### CODE REVIEW

File: modules/objdetect/include/opencv2/objdetect/detection_based_tracker.hpp [hunk 1]
```diff
@@ -46,7 +46,7 @@
 
 // After this condition removal update blacklist for bindings: modules/python/common.cmake
 #if defined(__linux__) || defined(LINUX) || defined(__APPLE__) || defined(__ANDROID__) || \
-  (defined(__cplusplus) &&  __cplusplus > 201103L) || (defined(_MSC_VER) && _MSC_VER >= 1700)
+  (defined(__cplusplus) &&  __cplusplus > 199711L) || (defined(_MSC_VER) && _MSC_VER >= 1700)
```
Comment (alalek) [inline modules/objdetect/include/opencv2/objdetect/detection_based_tracker.hpp]: I believe it should be (`>` --> `>=`):
```
__cplusplus >= 201103L
```

Comment (ColinFinck) [inline modules/objdetect/include/opencv2/objdetect/detection_based_tracker.hpp]: Doesn't matter as there is no valid value in between. My proposal only requires change to a single file and fixes the problem.

**Comment by vpisarev** [comment]
:+1:
