### PR TITLE
Fix #9363

### LINKED ISSUE #9363: lsd.cpp debug
hello, I find that the codes attached here in lsd.cpp in opencv3.2 is useless. The codes aim to make the list starts by the larger bin, howerer ,it doesn't works.

    // Sort
    int idx = n_bins - 1;
    for(;idx > 0 && !range_s[idx]; --idx);
    coorlist* start = range_s[idx];
    coorlist* end = range_e[idx];
    if(start)
    {
        while(idx > 0)
        {
            --idx;
            if(range_s[idx])
            {
                end->next = range_s[idx];
                end = range_e[idx];
            }
        }
    }

### PR DESCRIPTION
**Pull request by take1014**
resolves #9363 

### This pullrequest changes
Fixed as list was not sorted as intended based on norm value.

### CODE REVIEW

File: modules/imgproc/src/lsd.cpp [hunk 1]
```diff
@@ -75,6 +75,12 @@ struct edge
     bool taken;
 };
 
+struct coorlist
+{
+    cv::Point2i p;
+    int norm;
```
Comment (alalek) [inline modules/imgproc/src/lsd.cpp]: Looks like this struct is misnamed ("list" part should be removed after removing "next" entry - something like PointEntry).

File: modules/imgproc/src/lsd.cpp [hunk 2]
```diff
@@ -156,6 +162,12 @@ inline double log_gamma_lanczos(const double& x)
     }
     return a + log(b);
 }
+
+// Compare norm
+inline bool compare_norm(const coorlist& n1, const coorlist& n2)
```
Comment (alalek) [inline modules/imgproc/src/lsd.cpp]: You can put this in class `LineSegmentDetectorImpl` as **static** member function.

File: modules/imgproc/src/lsd.cpp (hunk 1 above)
Comment (take1014) [reply modules/imgproc/src/lsd.cpp]: Thanks for your comment.
I think to change the structure name from "coorlist" to "coorPoint", what do you think?
In addition, since the member variable "list" does not already have a list structure, I'd like to change the name of "list" to "ordered_points", what do you think?

Comment (alalek) [reply modules/imgproc/src/lsd.cpp]: "coor" here is a just "typo" for "coordinate". "coordinatePoint" is redundant name.

> ordered_points

Sounds good.

File: modules/imgproc/src/lsd.cpp (hunk 2 above)
Comment (take1014) [reply modules/imgproc/src/lsd.cpp]: I added this function in LineSegmentDetectorImpl class as static member function of public member.
