### PR TITLE
DNN: Let Slice layer support non-sequential and negative axes

### LINKED ISSUE #22355: dnn module: problem when importing ONNX model
##### Detailed description

I am trying to import an ONNX model exportet from standard keras applications (NASNet)
but the import always fails with exceptions.

[ERROR:0@2.754] global C:\QtProjects\LIB\opencv-4.6.0\modules\dnn\src\onnx\onnx_importer.cpp (1021) cv::dnn::dnn4_v20220524::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 4 inputs and 1 outputs: [Slice]:(onnx_node!model_41/NASNet/cropping2d_29/strided_slice) from domain='ai.onnx'
exception caught: OpenCV(4.6.0) C:\QtProjects\LIB\opencv-4.6.0\modules\dnn\src\onnx\onnx_importer.cpp:1040: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20220524::ONNXImporter::handleNode'
> Node [Slice@ai.onnx]:(onnx_node!model_41/NASNet/cropping2d_29/strided_slice) parse error: OpenCV(4.6.0) C:\QtProjects\LIB\opencv-4.6.0\modules\dnn\src\onnx\onnx_importer.cpp:1345: error: (-215:Assertion failed) axes[i - 1] == axes[i] - 1 in function 'cv::dnn::dnn4_v20220524::ONNXImporter::parseSlice'

changeing opset to a lower number fixed a previous import error but for this problem there was no helping it....I tried using opset 1-16, with down to 9 yieling same error, below a similar
 axes.get<int>(i - 1) == axes.get<int>(i) - 1 

##### Steps to reproduce

export default keras application NASNet to ONNX, try to import in cv:dnn: readNetFromONNX

##### Issue submission checklist

 - [x ] I report the issue, it's not a question
  
 - [x ] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
  
 - [x ] I updated to the latest OpenCV version and the issue is still there
  
  

   * Provide ONNX file for some public model or ONNX file with random weights,
     if you report ONNX parsing or handling issue. Architecture details diagram
     from netron tool can be very useful too. See https://lutzroeder.github.io/netron/
   -->

the model has more than 750 layers, i  suspect this strided_slice node is the culprit...

grafik
[stripe14.onnx.txt](https://github.com/opencv/opencv/files/9281957/stripe14.onnx.txt)

### PR DESCRIPTION
**Pull request by WanliZhong**
**Merge with extra:** https://github.com/opencv/opencv_extra/pull/1008

This PR try to fix #22355.
ONNX operator doc: https://github.com/onnx/onnx/blob/main/docs/Operators.md#Slice
- [x] Support non-sequential axes input
- [x] Support negative number of axes

TODO:
- [x] Reduce duplicated code
- [x] Add test for this enhancement

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@fengyuentau friendly reminder.

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 1]
```diff
@@ -1326,72 +1326,57 @@ void ONNXImporter::parseReduce(LayerParams& layerParams, const opencv_onnx::Node
...
+    int dims = inpShape.size();
+    std::vector<int> begin(dims, 0);
+    std::vector<int> end(dims, INT_MAX);
     std::vector<int> steps;
     int inp_size = node_proto.input_size();
+    int axis = 0;
+    bool has_axes = false;
+    DictValue starts_, ends_, axes_, steps_;
 
     if (inp_size == 1)
```
Comment (fengyuentau) [inline modules/dnn/src/onnx/onnx_importer.cpp:1339]: I propose to add a comment to explain this condition: // opset-1

File: modules/dnn/src/onnx/onnx_importer.cpp [hunk 2]
```diff
@@ -1326,72 +1326,57 @@ void ONNXImporter::parseReduce(LayerParams& layerParams, const opencv_onnx::Node
...
-            begin.push_back(starts.get<int>(i));
-            end.push_back(ends.get<int>(i));
+            axes_ = layerParams.get("axes");
+            CV_Assert(axes_.size() == starts_.size());
+            axis = axes_.getIntValue(0) < 0 ? axes_.getIntValue(0) + dims : axes_.getIntValue(0);
+            has_axes = true;
         }
-    } else { // inp_size > 1
+    }
+    else
```
Comment (fengyuentau) [inline modules/dnn/src/onnx/onnx_importer.cpp:1352]: I propose to add a comment to explain this condition: // opset > 1

**Review by fengyuentau — APPROVED** [review]
👍

**Review by rogday — APPROVED** [review]
Thank you! Looks good.

**Comment by asmorkalov** [comment]
@WanliZhong please squash commits before merge.

**Comment by WanliZhong** [comment]
@asmorkalov I've done and this pr is ready to be merged. Thanks!

**Comment by asmorkalov** [comment]
@WanliZhong Thanks! The PR looks good to me and is ready for merge. Please fix issues in related extra PR. I need to merge them together.
