### PR TITLE
imgproc: use double to determine whether the corners points are within src

### LINKED ISSUE #26016: cv2.error: in function 'cv::cornerSubPix'
### System Information

Python version: 3.8.18 
OpenCV python version: 4.10.0
Operating System / Platform: Windows-10-10.0.19045-SP0

### Detailed description

```
cv2.error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\cornersubpix.cpp:99: error: (-215:Assertion failed) Rect(0, 0, src.cols, src.rows).contains(cT) in function 'cv::cornerSubPix'
```

### Steps to reproduce

```
import cv2
import numpy as np

src = np.zeros((500, 500), dtype=np.uint8)

corners = np.array([
    [63.23869, 233.98373],
    [24.23986, 21.29863],
    [123.34534, 499.52298],
    [225.45345, 56.35624],
    [32.87236, 217.28916],
    [124.59836, 166.02876],
], dtype=np.float32).reshape(-1, 1, 2)

winSize = (3, 3)
zeroZone = (-1, -1)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 0.1)

refined_corners = cv2.cornerSubPix(src, corners, winSize, zeroZone, criteria)
```
In this case, in array, if there is some number more than 499.5, like 499.52298, the exception would be throw.
If the number smaller than 499.5, like 499.00001, this kind of exception would not be throw.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by Kumataro**
close #26016 
Related https://github.com/opencv/opencv_contrib/pull/3778

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/src/cornersubpix.cpp [hunk 1]
```diff
@@ -96,7 +96,7 @@ void cv::cornerSubPix( InputArray _image, InputOutputArray _corners,
     for( int pt_i = 0; pt_i < count; pt_i++ )
     {
         Point2f cT = corners[pt_i], cI = cT;
-        CV_Assert( Rect(0, 0, src.cols, src.rows).contains(cT) );
+        CV_Assert( Rect2f(0.0f, 0.0f, static_cast<float>(src.cols), static_cast<float>(src.rows)).contains(cT) );
```
Comment (opencv-alalek) [inline modules/imgproc/src/cornersubpix.cpp:99]: Check line 145 too.

Please note that conversion int->float may lead to accuracy errors.

May be we should try to fix `contains` method instead?

**Review by opencv-alalek — COMMENTED** [review]
relates #24527

File: modules/imgproc/src/cornersubpix.cpp (hunk 1 above)
Comment (Kumataro) [reply modules/imgproc/src/cornersubpix.cpp]: Thank you for your comment !

> May be we should try to fix contains method instead?

I believe this will be a better direction, so I tried implementing it.

- Point2f converts to Point2d with Rect_<int>.
- Rect_<int> converts to Rect_<double> only with Point2d.

Comment (Kumataro) [reply modules/imgproc/src/cornersubpix.cpp]: Because keyPoint has float type, various side effects occur(features2d/stiching/...). 

I'll take a bit more time to fix it.

**Comment by Kumataro** [comment]
It seems that CI doesn't work well.  Is there anything I can help ?

I had been tried to re-run CI/CD with new git commit and push,
CI For Linux64 ( https://pullrequest.opencv.org/buildbot/builders/precommit_linux64/builds/108564 ) starts first `init` step, but doest not finished and does not conitue to next steps.

File: modules/imgproc/src/cornersubpix.cpp (hunk 1 above)
Comment (Kumataro) [reply modules/imgproc/src/cornersubpix.cpp]: I tried to fix it. And this is breaking change, so I add warning on this function.

https://pullrequest.opencv.org/buildbot/export/pr/26022/docs/d2/d44/classcv_1_1Rect__.html#a4506eca68c36d1c68af51489a7ac58a7

**Review by asmorkalov — APPROVED** [review]
