### PR TITLE
stiching: add warpPointBackward to warpers

### LINKED ISSUE #18608: Add warpPointBackward to warpers
##### System information (version)

- OpenCV => latest (4.5)
- Operating System / Platform =>Windows 64 Bit
- Compiler =>Visual Studio 2017

##### Detailed description

Current RotationWarper is missing functionality to reproject points from warped space back to rectilinear space, so for instance constructing homography with fisheye lens or for a panoramic video is not possible. 

PR with proposed functionality: #18607

##### Steps to reproduce
```.cpp
Ptr<WarperCreator> creator = makePtr<PlaneWarper>();
Ptr<detail::RotationWarper> warper = creator->create(1);
Point2f pt(.5,1);
Mat I = Mat::eye(3, 3, CV_32FC1);
Point2f projected_pt = warper->warpPoint(pt, I, I);
Point2f reprojected_pt = warper->warpPointBackward(projected_pt, I, I);  
// reprojected_pt should be close to pt
```
 ##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by zteffi**
resolves #18608 

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is accuracy test, ~~performance test and test data in opencv_extra repository~~,

 Since warpPoint method is not used in stiching_detailed sample, I did not create a separate sample, but I'd say it's self-explanatory

### CODE REVIEW

File: modules/stitching/include/opencv2/stitching/detail/warpers.hpp [hunk 1]
```diff
@@ -70,6 +70,16 @@ class CV_EXPORTS RotationWarper
...
     virtual Point2f warpPoint(const Point2f &pt, InputArray K, InputArray R) = 0;
 
+    /** @brief Projects the image point backward.
+
+    @param pt Projected point
+    @param K Camera intrinsic parameters
+    @param R Camera rotation matrix
+    @return Backward-projected point
+    */
+    virtual Point2f warpPointBackward(const Point2f& pt, InputArray K, InputArray R) = 0;
```
Comment (alalek) [inline modules/stitching/include/opencv2/stitching/detail/warpers.hpp:80]: Please use this approach to bypass ABI check:

https://github.com/opencv/opencv/blob/1729297ef3bb87ea840c9ab7de9f97e03589fa02/modules/ml/include/opencv2/ml.hpp#L1300-L1304

Default implementation can contain `CV_Error(Error::StsNotImplemented, "");`

File: modules/stitching/test/test_reprojection.cpp [hunk 2]
```diff
@@ -0,0 +1,169 @@
+/*M///////////////////////////////////////////////////////////////////////////////////////
```
Comment (alalek) [inline modules/stitching/test/test_reprojection.cpp:1]: Please use short license header: https://github.com/opencv/opencv/wiki/Coding_Style_Guide#file-structure

```
// This file is part of OpenCV project.
// It is subject to the license terms in the LICENSE file found in the top-level directory
// of this distribution and at http://opencv.org/license.html.
```

**Review by alalek — COMMENTED** [review]
Thank you for contribution!

File: modules/stitching/include/opencv2/stitching/detail/warpers.hpp [hunk 3]
```diff
@@ -70,6 +70,20 @@ class CV_EXPORTS RotationWarper
...
+    @param pt Projected point
+    @param K Camera intrinsic parameters
+    @param R Camera rotation matrix
+    @return Backward-projected point
+    */
+#if CV_VERSION_MAJOR == 4
+    CV_WRAP virtual Point2f warpPointBackward(const Point2f& pt, InputArray K, InputArray R)
+    { CV_Error(Error::StsNotImplemented, ""); }
+#else
+    /*CV_WRAP*/ virtual Point2f warpPointBackward(const Point2f& pt, InputArray K, InputArray R) = 0;
```
Comment (alalek) [inline modules/stitching/include/opencv2/stitching/detail/warpers.hpp:84]: `CV_WRAP` is not needed here (both lines).

File: modules/stitching/test/test_reprojection.cpp [hunk 4]
```diff
@@ -0,0 +1,132 @@
+// This file is part of OpenCV project.
+// It is subject to the license terms in the LICENSE file found in the top-level directory
+// of this distribution and at http://opencv.org/license.html.
+
+#include "test_precomp.hpp"
+#include "opencv2/ts/ts_gtest.h"
```
Comment (alalek) [inline modules/stitching/test/test_reprojection.cpp:6]: > opencv2/ts/ts_gtest.h

not needed (included by `test_precomp.hpp` through `ts.hpp`)

**Review by alalek — APPROVED** [review]
