### PR TITLE
core: fix solveCubic numerical instability via coefficient normalization (fixes #27748)

### LINKED ISSUE #27748: The bug fix for the cubic equation solving in cv2.solveCubic has not been fully resolved.
### System Information

https://github.com/opencv/opencv/issues/27323 

This issue was about fixing the solution for solveCubic, which has been optimized and the issue has been closed. 
The bug fix for the cubic equation solving in cv2.solveCubic has not been fully resolved. 

### Detailed description

> I upgraded to version 4.12.0 and retested the issue, but when I input the following code, the solution was still incorrect. 
> 
> @asmorkalov @MaximSmolskiy 
> 
> 
> ```
> import cv2
> import numpy as np
> 
> def solve_polynomial(a, b, c, d):
>     roots = np.zeros(3, dtype=np.float64)
>     cv2.solveCubic(np.array([a, b, c, d], dtype=np.float64), roots)
>     return roots.tolist()
> 
> a = 0.000000000000227373675443232059
> b = 84.5276
> c = -2.79124
> d = -0.1575821794716176
> roots = solve_polynomial(a, b, c, d)
> print("root:", roots)
> ```
> 
> result:
> ```
> -371756316271994.500000000000000 
> 1066096.671875000000000 
> -1066096.500000000000000
> ```
> 
> The correct result
> ```
> -0.029715537326410 
> 0.062737177595388 
> 0.000000000000000 
> ``` 

### Steps to reproduce

python  C++     4.12.0

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by satyam102006**
Summary
This PR fixes numerical instability in `cv::solveCubic` when the leading coefficient `a` is non-zero but extremely small relative to other coefficients (Issue #27748). 

It introduces a **normalization step** that scales all coefficients by their maximum magnitude before solving. This ensures robust detection of when the equation should degenerate to a quadratic solver, without breaking valid cubic equations that happen to have small coefficients (e.g., scaled by 1e-9).

The Problem (Issue #27748)
The previous implementation checked `if (a == 0)` to decide whether to use the cubic or quadratic formula. 
- When `a` is extremely small (e.g., 1e-17) but not exactly zero, and other coefficients are normal (e.g., 5.0), the standard cubic formula suffers from catastrophic cancellation and overflow, producing incorrect roots (e.g., 1e14).

 The Fix
1. Normalization: The solver now finds `max_coeff = max(|a|, |b|, |c|, |d|)` and scales all coefficients by `1.0 / max_coeff`.
2. Relative Threshold: It then checks `if (abs(a) < epsilon)` on the *normalized* coefficients. 

 Why this is better than previous attempts
In a previous attempt (PR #28057), a simple absolute check `abs(a) < epsilon` was proposed. That approach was rejected because it failed for scaled equations . 

Fixes #27748

### CODE REVIEW

**Comment by asmorkalov** [comment]
The PR introduce regression:
```
[ RUN      ] Core_SolveCubicConstant.accuracy
  /home/ci/opencv/modules/core/test/test_math.cpp:2464: Failure
  Expected equality of these values:
    num_roots
      Which is: 0
    -1
  [  FAILED  ] Core_SolveCubicConstant.accuracy (0 ms)
  [ RUN      ] Core_SolveCubicQuadratic.accuracy
  /home/ci/opencv/modules/core/test/test_math.cpp:2503: Failure
  Expected equality of these values:
    roots[0]
      Which is: 2
    2.
      Which is: 2
  /home/ci/opencv/modules/core/test/test_math.cpp:2504: Failure
  Expected equality of these values:
    roots[1]
      Which is: 1
    1.
      Which is: 1
  [  FAILED  ] Core_SolveCubicQuadratic.accuracy (0 ms)
  [ RUN      ] Core_SolveCubic.regression_27323
  /home/ci/opencv/modules/core/test/test_math.cpp:2608: Failure
  Expected equality of these values:
    roots[0]
      Which is: 1
    -5e12 - 2.
      Which is: -5e+12
  /home/ci/opencv/modules/core/test/test_math.cpp:2617: Failure
  Expected equality of these values:
    roots[0]
      Which is: 1
    -5e12 - 2.
      Which is: -5e+12
  [  FAILED  ] Core_SolveCubic.regression_27323 (0 ms)
```
Please also add test case for the issue you are solving.

**Comment by satyam102006** [comment]
> The PR introduce regression:
> 
> ```
> [ RUN      ] Core_SolveCubicConstant.accuracy
>   /home/ci/opencv/modules/core/test/test_math.cpp:2464: Failure
>   Expected equality of these values:
>     num_roots
>       Which is: 0
>     -1
>   [  FAILED  ] Core_SolveCubicConstant.accuracy (0 ms)
>   [ RUN      ] Core_SolveCubicQuadratic.accuracy
>   /home/ci/opencv/modules/core/test/test_math.cpp:2503: Failure
>   Expected equality of these values:
>     roots[0]
>       Which is: 2
>     2.
>       Which is: 2
>   /home/ci/opencv/modules/core/test/test_math.cpp:2504: Failure
>   Expected equality of these values:
>     roots[1]
>       Which is: 1
>     1.
>       Which is: 1
>   [  FAILED  ] Core_SolveCubicQuadratic.accuracy (0 ms)
>   [ RUN      ] Core_SolveCubic.regression_27323
>   /home/ci/opencv/modules/core/test/test_math.cpp:2608: Failure
>   Expected equality of these values:
>     roots[0]
>       Which is: 1
>     -5e12 - 2.
>       Which is: -5e+12
>   /home/ci/opencv/modules/core/test/test_math.cpp:2617: Failure
>   Expected equality of these values:
>     roots[0]
>       Which is: 1
>     -5e12 - 2.
>       Which is: -5e+12
>   [  FAILED  ] Core_SolveCubic.regression_27323 (0 ms)
> ```
> 
> Please also add test case for the issue you are solving.

Thank you for the feedback. 

1.  Fixed Regressions:
    `Core_SolveCubicQuadratic` (Precision):I modified the logic to use the **original (raw) coefficients when falling back to the quadratic solver. This prevents the floating-point rounding errors that were causing the exact-match tests to fail.
  `Core_SolveCubicConstant` (Infinite Roots): Added an explicit check for all-zero coefficients to correctly return `-1` (infinite roots) as expected by the tests.
    `Core_SolveCubic.regression_27323` (Small Valid Cubic):** I updated the threshold logic to use `std::numeric_limits<double>::epsilon()` on normalized coefficients. This ensures that valid cubic equations with small but significant terms are not incorrectly degraded to quadratic.

2.  Test Case Added:
     I have added `TEST(Core_SolveCubic, regression_27748)` to `test_math.cpp`, which specifically targets the numerical instability reported in the issue.

3.  CI Fix:
     Added missing `<algorithm>` and `<cmath>` headers to fix the build failures on Linux/Windows CI agents.

**Comment by asmorkalov** [comment]
CI Warnings:
```
**modules/core/src/mathfuncs.cpp:49: trailing whitespace.
+#include <algorithm> 
modules/core/src/mathfuncs.cpp:50: trailing whitespace.
+#include <cmath>     
modules/core/src/mathfuncs.cpp:1606: trailing whitespace.
+        // CRITICAL: Use RAW coefficients here to avoid rounding errors in trivial cases 
modules/core/src/mathfuncs.cpp:1650: trailing whitespace.
+        double a0 = a0_norm; 
modules/core/src/mathfuncs.cpp:1663: trailing whitespace.
+        
modules/core/test/test_math.cpp:2623: trailing whitespace.
+    
modules/core/test/test_math.cpp:2624: trailing whitespace.
+    // a is extremely small relative to others (approx 1.8e-19 ratio), 
modules/core/test/test_math.cpp:2633: trailing whitespace.
+    
modules/core/test/test_math.cpp:2638: trailing whitespace.
+    
modules/core/test/test_math.cpp:2642: trailing whitespace.
+    
modules/core/test/test_math.cpp:2646: trailing whitespace.
+        EXPECT_NEAR(r, 0.5, 1.0); 
```

**Comment by satyam102006** [comment]
> CI Warnings:
> 
> ```
> **modules/core/src/mathfuncs.cpp:49: trailing whitespace.
> +#include <algorithm> 
> modules/core/src/mathfuncs.cpp:50: trailing whitespace.
> +#include <cmath>     
> modules/core/src/mathfuncs.cpp:1606: trailing whitespace.
> +        // CRITICAL: Use RAW coefficients here to avoid rounding errors in trivial cases 
> modules/core/src/mathfuncs.cpp:1650: trailing whitespace.
> +        double a0 = a0_norm; 
> modules/core/src/mathfuncs.cpp:1663: trailing whitespace.
> +        
> modules/core/test/test_math.cpp:2623: trailing whitespace.
> +    
> modules/core/test/test_math.cpp:2624: trailing whitespace.
> +    // a is extremely small relative to others (approx 1.8e-19 ratio), 
> modules/core/test/test_math.cpp:2633: trailing whitespace.
> +    
> modules/core/test/test_math.cpp:2638: trailing whitespace.
> +    
> modules/core/test/test_math.cpp:2642: trailing whitespace.
> +    
> modules/core/test/test_math.cpp:2646: trailing whitespace.
> +        EXPECT_NEAR(r, 0.5, 1.0); 
> ```

Apologies for the build failures. I will pushed a fix that:
1. Removes trailing whitespace to pass the style check.
2. Adds missing headers (`<algorithm>`, `<cmath>`) for cross-platform compilation.

File: modules/core/src/mathfuncs.cpp [hunk 1]
```diff
@@ -1633,38 +1660,32 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
         double Q = (a1 * a1 - 3 * a2) * (1./9);
         double R = (a1 * (2 * a1 * a1 - 9 * a2) + 27 * a3) * (1./54);
         double Qcubed = Q * Q * Q;
-        /*
-          Here we expand expression `Qcubed - R * R` for `d` variable
-          to reduce common terms `a1^6 / 729` and `-a1^4 * a2 / 81`
-          and thus decrease rounding error (in case of quite big coefficients).
 
-          And then we additionally group terms to further reduce rounding error.
-        */
```
Comment (s-trinh) [inline modules/core/src/mathfuncs.cpp:1642]: **Please, do not remove old comments.**

---

BTW, too much AI code / comments.
No idea if the approach is really valid or not.

**Comment by satyam102006** [comment]
Sorry I used ai for removing whitespace  which occur in docs previous once
again sorry for forward I will make sure of this.    

For inconvenience you can close my PR

File: modules/core/test/test_math.cpp [hunk 2]
```diff
@@ -2618,6 +2618,34 @@ TEST(Core_SolveCubic, regression_27323)
...
+    // Roots approx: 0.156, 0.990
+
+    int n = solveCubic(coeffs, roots);
+
+    EXPECT_GE(n, 2); // Should find at least 2 real roots (as quadratic)
+
+    for(int i = 0; i < n; i++)
+    {
+        double r = roots.at<double>(i);
+        EXPECT_NEAR(r, 0.5, 1.0);
```
Comment (asmorkalov) [inline modules/core/test/test_math.cpp]: It means that roots are validated in +-1 range. It's too much. See documentation: https://google.github.io/googletest/reference/assertions.html#EXPECT_NEAR

File: modules/core/src/mathfuncs.cpp [hunk 3]
```diff
@@ -1633,38 +1660,32 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
...
         double d = (a1 * a1 * (a2 * a2 - 4 * a1 * a3) + 2 * a2 * (9 * a1 * a3 - 2 * a2 * a2) - 27 * a3 * a3) * (1./108);
 
         if( d > 0 )
         {
-            double theta = acos(R / sqrt(Qcubed));
-            double sqrtQ = sqrt(Q);
```
Comment (asmorkalov) [inline modules/core/src/mathfuncs.cpp:1648]: Please do not add `std::` to the code you do not touch. It produces a lot of noise.

**Comment by satyam102006** [comment]
Sure I will remember all these things

File: modules/core/src/mathfuncs.cpp [hunk 4]
```diff
@@ -1563,35 +1565,54 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
     Mat roots = _roots.getMat();
 
     int i = -1, n = 0;
-    double a0 = 1., a1, a2, a3;
+    // We store raw coefficients to preserve precision for the quadratic case
+    double raw_a0 = 1., raw_a1, raw_a2, raw_a3;
```
Comment (vpisarev) [inline modules/core/src/mathfuncs.cpp]: please, don't introduce raw_a0, raw_a1, raw_a2 and raw_a3. Normalization is quite simple operation that can be done in-place. And it will also further reduce the patch size and will make it easier to analyze.

**Review by vpisarev — CHANGES_REQUESTED** [review]
please, reduce the patch size as much as possible, i.e. remove unnecessary changes, makes the comments less verbose, keep the old code and comments where it's possible.

**Comment by satyam102006** [comment]
Ok, I will do that.

File: modules/core/src/mathfuncs.cpp [hunk 5]
```diff
@@ -1586,12 +1588,21 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
         a3 = coeffs.at<double>(i+3);
     }
 
-    if( a0 == 0 )
+    // Fix for Issue #27748: Normalize coefficients to avoid overflow/underflow
+    // and correctly detect negligible cubic terms.
+    double max_coeff = std::max(std::max(std::abs(a0), std::abs(a1)), std::max(std::abs(a2), std::abs(a3)));
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp]: std::max({std::abs(a0),std::abs(a1),std::abs(a2),std::abs(a3)}) is easier to read.

File: modules/core/src/mathfuncs.cpp [hunk 6]
```diff
@@ -1605,10 +1616,10 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
             double d = a2*a2 - 4*a1*a3;
             if( d >= 0 )
             {
-                d = std::sqrt(d);
+                d = sqrt(d);
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp]: please keep std::sqrt to minimize change

File: modules/core/test/test_math.cpp [hunk 7]
```diff
@@ -2618,6 +2618,33 @@ TEST(Core_SolveCubic, regression_27323)
...
+    // Expecting quadratic behavior (2 roots)
+    EXPECT_GE(n, 2);
+
+    // Verify roots satisfy the quadratic part of the equation (since a*x^3 is negligible)
+    for(int i = 0; i < n; i++)
+    {
+        double x = roots.at<double>(i);
+        double val = b*x*x + c*x + d;
+        // Check residual is small
+        EXPECT_LE(std::abs(val), 1e-3) << "Root " << x << " does not satisfy the equation";
```
Comment (vrabaud) [inline modules/core/test/test_math.cpp]: 1e-3 is very high no ?

File: modules/core/src/mathfuncs.cpp [hunk 8]
```diff
@@ -1625,6 +1636,13 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
     else
     {
         // cubic equation
+        // Normalize coefficients in-place to prevent overflow/instability
+        double scale = 1.0 / max_coeff;
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp:1640]: pre-computing the inverse and multiplying by it is probably a bit faster but I doubt it matters compared to the precision loss: you should use a0 /= max_coeff no ?

File: modules/core/src/mathfuncs.cpp [hunk 9]
```diff
@@ -1625,6 +1636,13 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
...
+        a0 *= scale;
+        a1 *= scale;
+        a2 *= scale;
+        a3 *= scale;
+
         a0 = 1./a0;
         a1 *= a0;
         a2 *= a0;
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp:1648]: So at the end of that step, we have: a0 -> max_coeff/a0, a1 -> a1 * 1/max_coeff*  a0 = a1\*1/max_coeff\*max_coeff/original a0 = a1/original a0

Why not simplify the math to that? You would gain in precision. You'd replace 2 divisions and 7 multiplications by 4 divisions. I believe a division used to be roughly 4 times slower than a multiplication so you'd end up with the same complexity.

**Comment by satyam102006** [comment]
@vrabaud Thank you for the detailed review. I have applied all your suggestions:

1. **Math Simplification:** You are absolutely right about the `scale` factor canceling out. I removed the normalization loop and now divide directly by `a0` in the cubic branch. This reduces operations and improves precision as suggested.
2. **Readability:** I updated the `max_coeff` calculation to use `std::max({ ... })`.
3. **Minimizing Diff:** I reverted the changes to `std::sqrt` in the quadratic branch to keep the diff minimal.
4. **Test Accuracy:** I agreed that `1e-3` was too loose. I have tightened the regression test tolerance to `1e-6`.

**Comment by satyam102006** [comment]
@asmorkalov Could you please rerun the CI job 58329113008? It seems to have been cancelled or stalled without logs.

**Comment by satyam102006** [comment]
@asmorkalov  can you rerun 4 failing jobs no logs their . Thankyou

File: modules/core/src/mathfuncs.cpp [hunk 10]
```diff
@@ -1625,14 +1636,15 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
     else
     {
         // cubic equation
-        a0 = 1./a0;
-        a1 *= a0;
-        a2 *= a0;
-        a3 *= a0;
+        // Simplify math: divide directly by a0 to get monic form x^3 + Ax^2 + Bx + C = 0
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp]: This is like the old code. It is a bit more precise but we are dealing with doubles so the old code is fine. It is faster. Please revert.

File: modules/core/src/mathfuncs.cpp [hunk 11]
```diff
@@ -1625,14 +1636,15 @@ int cv::solveCubic( InputArray _coeffs, OutputArray _roots )
...
+        a1 /= a0;
+        a2 /= a0;
+        a3 /= a0;
 
         double Q = (a1 * a1 - 3 * a2) * (1./9);
         double R = (a1 * (2 * a1 * a1 - 9 * a2) + 27 * a3) * (1./54);
         double Qcubed = Q * Q * Q;
+
```
Comment (vrabaud) [inline modules/core/src/mathfuncs.cpp:1654]: Please revert

**Comment by satyam102006** [comment]
ok sure

**Comment by asmorkalov** [comment]
```
Run cd /home/ci/opencv
modules/core/src/mathfuncs.cpp:1641: trailing whitespace.
+        a0 *= scale; 
modules/core/src/mathfuncs.cpp:1642: trailing whitespace.
+        a1 *= scale; 
modules/core/src/mathfuncs.cpp:1643: trailing whitespace.
+        a2 *= scale; 
```

**Comment by satyam102006** [comment]
@asmorkalov can rerun all the jobs failing due connection lost and failed with an infrastructure error

File: modules/core/test/test_math.cpp [hunk 12]
```diff
@@ -2618,6 +2618,33 @@ TEST(Core_SolveCubic, regression_27323)
...
+    int n = solveCubic(coeffs, roots);
+
+    // Expecting quadratic behavior (2 roots)
+    EXPECT_GE(n, 2);
+
+    // Verify roots satisfy the quadratic part of the equation (since a*x^3 is negligible)
+    for(int i = 0; i < n; i++)
+    {
+        double x = roots.at<double>(i);
+        double val = b*x*x + c*x + d;
```
Comment (asmorkalov) [inline modules/core/test/test_math.cpp]: IMHO we should include cubic part too. The minimal impact of it is solver assumption, but not requirement.

**Comment by satyam102006** [comment]
@asmorkalov I will updated the test to verify the full cubic equation (`val = a*x*x*x + ...`) as you suggested.

**Comment by satyam102006** [comment]
@asmorkalov   2 jobs failing , The Windows CI job failed during the checkout step with an internal runner error, can please rerun the jobs

**Comment by satyam102006** [comment]
@asmorkalov 1 job failing , due to Internal server error , can you rerun the job, thank you

**Comment by satyam102006** [comment]
The Windows CI job failed during the 'Set up job' phase with the error: Failed to resolve action download info. This appears to be a transient GitHub Actions infrastructure issue unrelated to the code changes. Could you please re-trigger the @asmorkalov
