### PR TITLE
imgcodecs: fix PNG read on BE platforms (s390x)

### LINKED ISSUE #26913: OpenCV 4.11.0 broken on s390x (big endian) - `cv::imread` returns empty matrix for valid file
### System Information

OpenCV 4.11.0 seems to be broken on s390x (notably, the only big-endian arch we - Fedora - test). When our OpenCV package was updated to 4.11.0, the tests of os-autoinst (part of the openQA test framework) started failing on s390x only. The failure seemed to point to OpenCV, because it looked like the operation that was failing was just reading an image with OpenCV.

### Detailed description

It looks like `img = cv::imread("/var/tmp/bootmenu.test.png", cv::IMREAD_COLOR);` - where that's a perfectly valid PNG file - returns an empty matrix on s390x with OpenCV 4.11.0. On x86_64 (or any other LE arch), it works. On s390x with OpenCV 4.10.0, it works.

### Steps to reproduce

Here's a minimal reproducer I hacked up to prove the point - apologies for any weirdness, I am not really a C++ coder:
```
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/mat.hpp>
#include <iostream>

int main() {
    cv::Mat img;
    img = cv::imread("/var/tmp/bootmenu.test.png", cv::IMREAD_COLOR);
    if (!img.data) {
        std::cout << "Failed\n";
    }
    else {
        std::cout << "Succeeded\n";
    }
}
```
Obviously, you need `/var/tmp/bootmenu.test.png` to be a valid PNG file, in the original test it is [this one](https://github.com/os-autoinst/os-autoinst/blob/821904bebb450093fed0f35976ebbef81f242e78/t/data/bootmenu.test.png). The compile command I used is:
```
g++ -I /usr/include/opencv4 -o cvtest cvtest.cpp /usr/lib64/libopencv_imgcodecs.so.4.11.0 /usr/lib64/libopencv_core.so.4.11.0
```
obviously adjust the paths and filenames as appropriate for your test environment (of course the library filenames had 4.10.0 in them when testing 4.10.0).

When I compile and run that test script on s390x with OpenCV 4.11.0 (Fedora Rawhide clean build environment), it prints "Failed". On s390x with OpenCV 4.10.0, and on x86_64 with either version of OpenCV, it prints "Succeeded".

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by mshabunin**
Resolves #26913
Related(?): #25715 #26832

### CODE REVIEW

File: modules/imgcodecs/src/grfmt_png.cpp [hunk 1]
```diff
@@ -732,7 +739,7 @@ uint32_t PngDecoder::read_chunk(Chunk& chunk)
     chunk.p.resize(size);
     memcpy(chunk.p.data(), size_id, 8);
     if (readFromStreamOrBuffer(&chunk.p[8], chunk.p.size() - 8))
-        return id;
+        return isBigEndian() ? id : *((uint32_t*)(&size_id[4]));
```
Comment (AdamWill) [inline modules/imgcodecs/src/grfmt_png.cpp:742]: since we just made `id` correct in both cases, why change the return here? wouldn't just `return id;` now be ok for both?

File: modules/imgcodecs/src/grfmt_png.cpp [hunk 2]
```diff
@@ -699,7 +699,14 @@ uint32_t PngDecoder::read_chunk(Chunk& chunk)
         return 0;
     const size_t size = static_cast<size_t>(png_get_uint_32(size_id)) + 12;
 
-    const uint32_t id = *(uint32_t*)(&size_id[4]);
+    uint32_t id = *((uint32_t*)(&size_id[4]));
```
Comment (vrabaud) [inline modules/imgcodecs/src/grfmt_png.cpp]: Actually the proper way is to use:
```
const uint32_t id = png_get_uint_32(size_d + 4);
```

**Comment by mshabunin** [comment]
If I understand correctly the problem has been introduced here: #25715 with introduction of constants `id_IHDR`, `id_acTL`, etc. which are defined in platform-dependent way, while in the actual file they are always in BE. So perhaps alternatively we can change definition of these constants.

**Comment by vrabaud** [comment]
@mshabunin , you are right. Let's use png_get_uint_32 because it has a constant endianness. We just need to have the chunk constants have the same endianness as what this function does, BE cf https://github.com/pnggroup/libpng/blob/b525503b78392335a43558c6a053e0209140762d/pngrutil.c#L63

**Comment by mshabunin** [comment]
I tried and apparently `png_get_uint_32` does not work for this case, because we actually do not need to swap bytes - we need to just copy them as 4 bytes. Actually something like `strncmp` would fit better in this case:
```.cpp
const uint8_t * id_IHDR = "IHDR";
...
if (0  == strncmp(size_id + 4, id_IHDR, 4))
...

```
Maybe we could even switch to `std::string` to use operator==`...

**Comment by mshabunin** [comment]
OK, the last variant should work :face_exhaling:

**Comment by vrabaud** [comment]
Perfect, LGTM ! @asmorkalov , ready to go.

**Comment by asmorkalov** [comment]
@vrabaud please put formal approve.

**Comment by vrabaud** [comment]
@asmorkalov , how do I do that? (we LGTM internally :) )

**Comment by AdamWill** [comment]
thanks a lot, I will test this and see if I can confirm the fix.

**Comment by AdamWill** [comment]
Oh, er, but...worryingly...it makes the test *fail* on x86_64, here.

**Comment by mshabunin** [comment]
@AdamWill which test fails? Our CI had passed. Did you use the latest variant of the patch?

**Comment by AdamWill** [comment]
OK yeah, so I instead backported every change to the PNG code since 4.11.0, including this PR, and the test script passes on both x86_64 and s390x. Yay. Thanks.
