### PR TITLE
resolves 10507

### LINKED ISSUE #10507: Multi channel 32F Mat setTo NaN is not setting to NaN
##### System information (version)
- OpenCV => 3.3.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2017 (15.5.2)

##### Detailed description

Setting 3 or 4 channel 32F Mat to NaN using mask actually sets the value to 3.40282347e+38.
1 or 2 channels works fine.
64F works fine.
No mask works fine.
Problem is not reproduced in opencv 3.2.0

##### Steps to reproduce
```.cpp
#include <opencv2/opencv.hpp>
#include <iostream>

int main(void)
{
    for (int chans = 1; chans <= 4; chans++)
    {
        cv::Mat A(1, 1, CV_MAKE_TYPE(CV_32F, chans), cv::Scalar::all(0));
        A.setTo(cv::Scalar::all(std::numeric_limits<float>::quiet_NaN()), cv::Mat(1, 1, CV_8UC1, cv::Scalar::all(255)));
        std::cout << "Number of NaN pixels in " << chans << " channels image is " << (cv::countNonZero((A == A) == 0)) << " (should be 1)" << std::endl;
    }
}
```

output:
Number of NaN pixels in 1 channels image is 1 (should be 1)
Number of NaN pixels in 2 channels image is 1 (should be 1)
Number of NaN pixels in 3 channels image is 0 (should be 1)
Number of NaN pixels in 4 channels image is 0 (should be 1)

### PR DESCRIPTION
**Pull request by take1014**
resolves #10507

### CODE REVIEW

File: modules/core/test/test_mat.cpp [hunk 1]
```diff
@@ -1612,6 +1612,20 @@ TEST(Mat, regression_7873_mat_vector_initialize)
...
+{
+    for(int chans = 1; chans <= 4; chans++)
+    {
+        cv::Mat A(1, 1, CV_MAKE_TYPE(CV_32F, chans), cv::Scalar::all(0));
+        A.setTo(cv::Scalar::all(std::numeric_limits<float>::quiet_NaN()), cv::Mat(1, 1, CV_8UC1, cv::Scalar::all(255)));
+        int nonzero = 0;
+        float* _data = (float*)&A.data[0];
+        for( int n = 0; n < chans; n++ )
+            nonzero += (std::isnan(_data[n])) ? 1 : 0;
+        EXPECT_EQ(nonzero, 1);
```
Comment (alalek) [inline modules/core/test/test_mat.cpp]: Check condition is wrong: all `chans` channels must have NaN values.

**Comment by alalek** [comment]
I pushed the updates for `setTo()` check / test.

**Comment by take1014** [comment]
@alalek 
There is nothing I can say. I think that this is perfect answer.
