### PR TITLE
ARM: add new comparison to tolerate with rounding error

### LINKED ISSUE #10871: OpenCL: some test seems too strict
##### Abstract
- Some OpenCL tests fail on TinkerBoard
- Rather than the implementation, I think the threshold is too strict

##### System information (version)

- OpenCV => recent master ( 252e871a8 )
- Operating System / Platform => Debian 9.3 (32bit) Tinker Board
- Compiler => gcc 6.3.0
- OpenCL => 1.2

##### Detailed description
- I got some test failure on TinkerBoard
- Each of them were test on kernel of OpenCL
- [```opencv_test_video```](https://gist.github.com/tomoaki0705/e8553518a98a0bb1437593ee21a3c5f5)
```
[  PASSED  ] 55 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OCL_Video/PyrLKOpticalFlow.Mat/4, where GetParam() = (21, 3)
```
- [```opencv_test_core```](https://gist.github.com/tomoaki0705/94d77ed5e7e7c84f2b33c440bfd3f50b)
```
[  PASSED  ] 10500 tests.
[  FAILED  ] 32 tests, listed below:
[  FAILED  ] OCL_Arithm/Mul.Mat_Scale/40, where GetParam() = (CV_32F, Channels(1), false)
(snip)
[  FAILED  ] OCL_Arithm/Mul.Mat_Scale/47, where GetParam() = (CV_32F, Channels(4), true)
[  FAILED  ] OCL_Arithm/AddWeighted.Mat/8, where GetParam() = (CV_8S, Channels(1), false)
(snip)
[  FAILED  ] OCL_Arithm/AddWeighted.Mat/39, where GetParam() = (CV_32S, Channels(4), true)
```
- [```opencv_test_imgproc```](https://gist.github.com/tomoaki0705/31f8528bfcc479b26410b977606e3dc1)
```
[  PASSED  ] 9585 tests.
[  FAILED  ] 110 tests, listed below:
[  FAILED  ] OCL_ImgProc/CvtColor.RGB2YCrCb/0, where GetParam() = (CV_8U, false)
(snip)
```
- Since these tests pass on other test platform on build farm, I suspected that the threshold is too tight.
- For instance, one of the test ```OCL_Video/PyrLKOpticalFlow.Mat/4``` were [comparing the difference in fixed value](https://github.com/opencv/opencv/blob/cff79609c8723d062851fa43d732c57ac375eef8/modules/video/test/ocl/test_optflowpyrlk.cpp#L139)
```
    // cpuErr and err are the result from CPU and GPU respectively
    eq = std::abs(cpuErr[i] - err[i]) < 0.01;
```
  - Tracing back the err, [it was computed based on Eigen value of the matrix](https://github.com/opencv/opencv/blob/cff79609c8723d062851fa43d732c57ac375eef8/modules/video/src/lkpyramid.cpp#L446-L450) (as shown below)
  - Thus, if the platform hires ```FMA```, the result won't be "bit-exact"
  - Back to the comparison, I think the threshold has to be "relative" rather than "absolute value"

```
        float minEig = (A22 + A11 - std::sqrt((A11-A22)*(A11-A22) +
                        4.f*A12*A12))/(2*winSize.width*winSize.height);

        if( err && (flags & OPTFLOW_LK_GET_MIN_EIGENVALS) != 0 )
        err[ptidx] = (float)minEig;
```
- [Here's my fix ](https://github.com/opencv/opencv/compare/master...tomoaki0705:fixTinkerBoardOpenCL?expand=1)(W.I.P)

- Still, I'm in the middle of investigation, so these problem might not be caused by a single issue.
- From my point of view, the comparison seems too strict.
- Before writing a patch, I'd like to hear some opinion before I go this way

##### Steps to reproduce
- Build OpenCV on TInkerBoard
- run either one of the test
  - ```opencv_test_core```
  - ```opencv_test_video```
  - ```opencv_test_imgproc```

### PR DESCRIPTION
**Pull request by tomoaki0705**
* clean up the source code
  * remove unused variable (eps)
  * remove unused member function (Near)
  * restore resize of carotene
  * resolves #10871 

### This pullrequest changes
  * As mainly described in #10871, ```opencv_test_imgproc``` was failing on ARM + GPU OpenCL platform.
    * TinkerBoard (Arm Cortex A17 + Mali-T760)
    * ODROID-XU4 (Arm Cortex A15 + A7 + Mali-T628)
    * Firefly RK3399 (Arm Cortex A53 + Mali-T860)
  * This was due to the rounding error, and the difference was relatively small, yet going over the ```eps```
  * This PR adds comparison macro ```OCL_EXPECT_MAT_N_DIFF``` which counts the number of pixel which differs more than ```eps```
   * Carotene implementation can now be stored back.

### CODE REVIEW

File: modules/ts/include/opencv2/ts/ocl_test.hpp [hunk 1]
```diff
@@ -122,6 +122,18 @@ do \
...
 
+#define OCL_EXPECT_MAT_N_DIFF(name, eps) \
+do \
+{ \
+    ASSERT_EQ(name ## _roi.type(), u ## name ## _roi.type()); \
+    ASSERT_EQ(name ## _roi.size(), u ## name ## _roi.size()); \
+    Mat diff, binary; \
+    absdiff(name ## _roi, u ## name ## _roi, diff); \
+    cv::threshold(diff, binary, (double)eps, 255, cv::THRESH_BINARY); \
+    EXPECT_LE(countNonZero(binary.reshape(1)), (int)(binary.cols*binary.rows*5/1000)) \
```
Comment (alalek) [inline modules/ts/include/opencv2/ts/ocl_test.hpp]: Number of pixels on border (`O(rows+cols)`) is much less than total number of pixels (`rows*cols`).
So this condition may not detect problems with incorrect processing of border pixels.

BTW, What kind of source images for failed tests? If processed images are just "noise", then it is probably better to replace of these inputs (I can help to prepare some synthetic images).

Comment (tomoaki0705) [reply modules/ts/include/opencv2/ts/ocl_test.hpp]: The error happens not only the edge, it happens all over the image.
I already explained in [this comment](https://github.com/opencv/opencv/pull/11169#issuecomment-376818533) that it's about the pixel **coordinate** rather than the pixel **value** itself which become malfunction.

So, answering your question, this evaluation is **NOT** about the border. It happens everywhere.


Answering your second question, the test is based on a random generated image.  The pixel next to each other are very less correlative.

Now, I already uploaded an error log from Tinker Board (Arm Cortex A17 + Mali T760) [here](https://gist.githubusercontent.com/tomoaki0705/4f047b5502b231ccc3bca4f3829b1ba9/raw/563300af194500349f45407c1812814ffbaea4a8/opencv_test_imgproc_tinkerboard.log)
I've extraceted some tests which are still failing.

```
[  FAILED  ] 54 tests, listed below:
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/4, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/5, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/6, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/7, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/8, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/9, where GetParam() = (CV_8U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/34, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/35, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/36, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/37, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/38, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/39, where GetParam() = (CV_8U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/64, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/65, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/66, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/67, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/68, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/69, where GetParam() = (CV_8U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/94, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/95, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/96, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/97, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/98, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/99, where GetParam() = (CV_16U, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/124, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/125, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/126, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/127, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/128, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/129, where GetParam() = (CV_16U, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/154, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/155, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/156, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/157, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/158, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/159, where GetParam() = (CV_16U, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/184, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/185, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/186, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/187, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/188, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/189, where GetParam() = (CV_32F, Channels(1), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/214, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/215, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/216, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/217, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/218, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/219, where GetParam() = (CV_32F, Channels(3), (32FC1, 32FC1), BORDER_REFLECT_101, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/244, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_WRAP, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/245, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_WRAP, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/246, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/247, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_REFLECT, true)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/248, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, false)
[  FAILED  ] OCL_ImgprocWarp/Remap_INTER_LINEAR.Mat/249, where GetParam() = (CV_32F, Channels(4), (32FC1, 32FC1), BORDER_REFLECT_101, true)
```

Question from me, is it realistic to replace the input ?
I can imagine 2,3 alternative solution, but I think it could still happen even if we replace the input image.
How should we fix this test failure ?

Comment (tomoaki0705) [reply modules/ts/include/opencv2/ts/ocl_test.hpp]: Right, now I'm on the same page.
I'll add another ```EXPECT_LE``` just to check the border.
This time by comparing with 
```
(int)((binary.cols + binary.rows)/100)
```
or something similar

File: modules/ts/include/opencv2/ts/ocl_test.hpp [hunk 2]
```diff
@@ -127,11 +127,20 @@ do \
...
     ASSERT_EQ(name ## _roi.size(), u ## name ## _roi.size()); \
-    Mat diff, binary; \
+    Mat diff, binary, mask; \
     absdiff(name ## _roi, u ## name ## _roi, diff); \
+    mask = cv::Mat::zeros(diff.size(), diff.type()); \
+    Scalar color(0xff); \
+    line(mask, Point(0, 0),                 Point(mask.cols, 0),         color); \
+    line(mask, Point(mask.cols, 0),         Point(mask.cols, mask.rows), color); \
+    line(mask, Point(mask.cols, mask.rows), Point(0, mask.rows),         color); \
+    line(mask, Point(0, mask.rows),         Point(0, 0),                 color); \
```
Comment (alalek) [inline modules/ts/include/opencv2/ts/ocl_test.hpp]:
```
Mat mask(diff.size(), CV_8UC1, cv::Scallar::all(255));
if (mask.cols > 2 && mask.rows > 2)
    mask(cv::Rect(1, 1, mask.cols - 2, mask.rows - 2)).setTo(0);
```
