### PR TITLE
fix #7833

### LINKED ISSUE #7833: Cocoa Application VideoCapture crashes on release() using AVFoundation
##### System information (version)
- OpenCV => Dec 7th HEAD (2341222672a24d143ae08b8ccaa0c030bc728db9)
- Operating System / Platform => Mac 10.11 / 10.12
- Compiler => Xcode

##### Detailed description
We are trying to use an AVFoundation build of opencv_videoio in our macOS app. 
It is able to open the webcam and read from it, but once release is called, a EXC_BAD_ACCESS Error is thrown. Here are stack traces caught by Zombies. I wasn't sure exactly what is relevant in the zombie report. Here's a screenshot. 

screen shot 2016-12-09 at 3 16 07 pm

Stepping through the code, It successfully turns the camera off, exits release(), and continue program flow, and another thread crashes the program each time. 

It does NOT crash on a blank c++ command line project, only happens in a cocoa app. 

We have tried running both on Sierra and El Capitan.
We chose to use AVFoundation to support Sierra, and chose to not use FFMpeg. Are there any other build options to consider?

##### Steps to reproduce
Build openCV with 
```
WITH_AVFOUNDATION=YES
WITH_FFMPEG=NO
WITH_QT=NO
WITH_QUICKTIME=NO
```

Create an empty Cocoa Project, 
and in ApplicationDidFinishLaunching put basic VideoIO capture calls in 
```
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
  cv::VideoCapture cap(0);
  cap.release();
}
```

### PR DESCRIPTION
**Pull request by abratchik**
### This pullrequest changes

resolves #7833

removed "mCaptureDevice release"

### CODE REVIEW

**Comment by abratchik** [comment]
Please help with the failed test - it shows perf_stich.cpp issue but this fix has no relation to it.

File: modules/videoio/src/cap_avfoundation_mac.mm [hunk 1]
```diff
@@ -293,7 +293,7 @@ - (IplImage*)getOutput;
 
     [mCaptureSession release];
     [mCaptureDeviceInput release];
-    [mCaptureDevice release];
+    // [mCaptureDevice release]; fix #7833
```
Comment (alalek) [inline modules/videoio/src/cap_avfoundation_mac.mm]: Probably we need `mCaptureDevice = nil;` here at least.

And the same fix [here](https://github.com/opencv/opencv/blob/3.2.0/modules/videoio/src/cap_avfoundation.mm#L306).

Comment (abratchik) [inline modules/videoio/src/cap_avfoundation_mac.mm]: Hi @alalek 

Sorry I did not know that this was already fixed as no traces on the issue. Please let know what I need to do? Just need this issue fixed as it is pretty annoying.

Regards.

Alex

Comment (alalek) [inline modules/videoio/src/cap_avfoundation_mac.mm]: It is not fixed yet.
I'm asking to replace this line to `mCaptureDevice = nil;` and to make similar change in file "cap_avfoundation.mm".

BTW, Are you able to reproduce this problem on your side (and to validate fix)?

Comment (abratchik) [inline modules/videoio/src/cap_avfoundation_mac.mm]: sure, will do, no problem. The issue existed on the latest commit from the master  - java was crashing after VideoCapture.release(). With this fix all works like a charm - tried to switch on/switch off the camera many times and no issues at all. @jbyu is awesome, I owe him some beer :)

Comment (abratchik) [inline modules/videoio/src/cap_avfoundation_mac.mm]: Hi @alalek, I tried to do as you suggested  (mCaptureDevice = nil;) and it leads to internal opencv crush although it is different in this case. Also cap_avfoundation.mm doesn't have [mCaptureDevice release] and I assume it works well as is, without any changes. 
So may be it makes sense to merge as is because additional changes are causing problems.

**Comment by alalek** [comment]
Thank you! :+1:
