### PR TITLE
dnn: fix OpenCL implementation of Slice layer

### LINKED ISSUE #17762: DNN: YOLOv4-tiny no detections for OpenCV/OpenCL target
see #17743

```
[ RUN      ] Test_Darknet_nets.YOLOv4_tiny/0, where GetParam() = OCV/OCL
/build/precommit_opencl_linux/3.4/opencv/modules/dnn/test/test_common.impl.hpp:99: Failure
Value of: testClassIds.empty()
  Actual: true
Expected: false
No detections
Google Test trace:
/build/precommit_opencl_linux/3.4/opencv/modules/dnn/test/test_darknet_importer.cpp:616: batch size 1
```

### PR DESCRIPTION
**Pull request by alalek**
resolves #17762
relates #17743

TODO:
- [x] performance test
- [x] optimizations w/o regressions
- [x] drop debug code

<cut/>

```
**WIP**
test_modules=dnn

Xbuild_image:Custom=ubuntu:18.04
Xbuildworker:Custom=linux-5
Xtest_opencl:Custom=ON

build_image:Linux AVX2=ubuntu:18.04
buildworker:Linux AVX2=linux-3
test_opencl:Linux AVX2=ON

build_image:Custom=ubuntu-openvino-2020.3.0:16.04
build_image:Custom Win=openvino-2020.3.0
Xbuild_image:Custom Win=openvino-2019r3.0
build_image:Custom Mac=openvino-2020.3.0

Xtest_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=ON
test_bigdata:Custom=1
test_filter:Custom=*lice*:*plit*

test_opencl:Custom Win=ON
test_bigdata:Custom Win=1
test_filter:Custom Win=*lice*:*plit*

```

### CODE REVIEW

File: modules/dnn/src/layers/slice_layer.cpp [hunk 1]
```diff
@@ -205,44 +205,43 @@ class SliceLayerImpl : public SliceLayer
...
+            MatShape outputShape = shape(outputs[i]);
+            if (total(outputShape, 2) != inputPlaneSz && outputShape[1] != 1)
                 return false;
         }
 
+        for (size_t i = 0; i < outputs.size(); i++)
+        {
+            UMat& output = outputs[i];
+#if 0  // TODO: core - support non-contiguous ND layouts
+            input(finalSliceRanges[i]).copyTo(output);
```
Comment (dkurt) [inline modules/dnn/src/layers/slice_layer.cpp:230]: Seems strange why input is not contiguous.

Comment (alalek) [reply modules/dnn/src/layers/slice_layer.cpp:230]: Input is contiguous, but ROI/slice is not.

**Comment by alalek** [comment]
:+1:
