### PR TITLE
Convolutional padding parsing modified

### LINKED ISSUE #16259: darknet importer: padding is parsed incorrectly for convolutional layers
### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04
- Compiler => g++ 7.4

##### Detailed description

It appears that the `pad` value in darknet configuration files indicates the padding mode and not the padding value itself. I think `pad` being one implies same padding and `pad` being zero implies manual padding (which is specified in the `padding` parameter).

https://github.com/AlexeyAB/darknet/blob/dcfeea30f195e0ca1210d580cac8b91b6beaf3f7/src/parser.c#L180-L182

The OpenCV darknet parser treats the pad value as the actual padding value. There is also a comment which shows that the original author of the parser was stunned by the weird `pad=1` and sets it to zero. It's actually zero because `pad=1` would imply a padding of `kernel_size//2` which would anyway give zero.

https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/modules/dnn/src/darknet/darknet_io.cpp#L566-L567

### PR DESCRIPTION
**Pull request by ashishkrshrivastava**
**Merge with extra**:  https://github.com/opencv/opencv_extra/pull/698

This PR modifies the parsing of 'padding' for convolutional layers in darknet importer.

resolves #16259

```
opencv_extra=3.4modified
```

### CODE REVIEW

File: modules/dnn/test/test_darknet_importer.cpp [hunk 1]
```diff
@@ -106,7 +106,7 @@ class Test_Darknet_layers : public DNNTestLayer
         std::string cfg = findDataFile("dnn/darknet/" + name + ".cfg");
         std::string model = "";
         if (hasWeights)
-            model = findDataFile("dnn/darknet/" + name + ".weights", false);
+            model = findDataFile("dnn/darknet/" + name + ".weights", required);
```
Comment (alalek) [inline modules/dnn/test/test_darknet_importer.cpp]: Lets remove unclear `required` parameter (with meaning of `requiredWeights`).
Just remove `", false"` from here (weights are not "optional" testdata - they are stored in "opencv_extra").

Comment (dkurt) [reply modules/dnn/test/test_darknet_importer.cpp]: I agree, lest just emit the last argument (so make it `true` by default value):

```
            model = findDataFile("dnn/darknet/" + name + ".weights");
```

File: modules/dnn/src/darknet/darknet_io.cpp [hunk 2]
```diff
@@ -556,20 +556,21 @@ namespace cv {
...
                         int stride = getParam<int>(layer_params, "stride", 1);
                         int filters = getParam<int>(layer_params, "filters", -1);
                         bool batch_normalize = getParam<int>(layer_params, "batch_normalize", 0) == 1;
                         int flipped = getParam<int>(layer_params, "flipped", 0);
                         if (flipped == 1)
                             CV_Error(cv::Error::StsNotImplemented, "Transpose the convolutional weights is not implemented");
 
-                        // correct the strange value of pad=1 for kernel_size=1 in the Darknet cfg-file
-                        if (kernel_size < 3) pad = 0;
+                        if (pad == 1)
```
Comment (dkurt) [inline modules/dnn/src/darknet/darknet_io.cpp]: What if user specified non zero value of `pad` different from `1`? So let's keep `if (pad)`

**Comment by ashishkrshrivastava** [comment]
> Well done!

Thanks
