### PR TITLE
cuda::flip - Use in-place npp function for inplace arguments

### LINKED ISSUE #17840: In-place flip of GpuMat produces image artifacs
##### System information (version)

- OpenCV => 4.3.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019/NVCC

##### Detailed description

When uploading an `Mat` to a `GpuMat` called `x`, using `cv::cuda::resize` to downscale `x` into a new `GpuMat` called `y`, and finally flipping that image along the vertical axis by passing `y` as both the `src` and `dst` argument of `cv::cuda::flip`, major image fragmentation is produced on the right side of the `y`. 

Here's a code example:

```.cpp
#include <opencv2/opencv.hpp>
#include <opencv2/cudaarithm.hpp>
#include <opencv2/cudawarping.hpp>
#include <iostream>

using namespace cv;

const int kDownscaleFactor = 3;

int main(int argc, char** argv) {
	Mat image;
	image = imread("img.jpg", IMREAD_COLOR);

	cuda::GpuMat downscaled;
	cuda::GpuMat flipped;
	downscaled.upload(image);
	cuda::resize(downscaled, flipped, Size(image.size[0] / kDownscaleFactor, image.size[1] / kDownscaleFactor));
	cuda::flip(flipped, flipped, 1);
	flipped.download(image);

	namedWindow("Glitchy Image", WINDOW_AUTOSIZE);
	imshow("Glitchy Image", image);
	waitKey(0);

	return 0;
}
```

Capture

However, using a new `GpuMat` variable as the argument for the `dst` parameter of `cv::cuda::flip` (not the same one as `src`), this error is not produced.

[Here](https://github.com/opencv/opencv/files/4920841/cvCudaFlip.zip) is a zip file containing an executable demonstrating this error and the source code needed to reproduce it.

##### Steps to reproduce

1. Upload a `Mat` object to the GPU into a `GpuMat x`.
2. Downscale `x` into a `GpuMat y` by calling `cv::cuda::resize(x, y, Size(...));`
3. Flip `y` along the vertical axis by calling `cv::cuda::flip(y, y, 1);` noting that `y` is passed as both the source and destination matrix to `cv::cuda::flip`.
4. Calling `y.download(...)` and displaying the results demonstrates significant image fragmentation.

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
 - [x] I updated to latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by nglee**
Resolves #17840 

https://github.com/opencv/opencv/pull/17863#issuecomment-661536808

~~`cv::cuda::GpuMat::create` does not allocate a new GpuMat if required size and type equals existing size and type.~~
https://github.com/opencv/opencv/blob/bf8136eaa68d8f17edba929622ddba05f95c89d8/modules/core/src/cuda/gpu_mat.cu#L160-L161

~~This PR implements `cv::cuda::detachOutput` to allocate a new GpuMat in such cases. Unfortunately, `_dst` is const so assignment is not possible. Instead, this implementation clones `src`.~~

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/core/src/cuda_gpu_mat.cpp [hunk 1]
```diff
@@ -407,6 +407,22 @@ void cv::cuda::syncOutput(const GpuMat& dst, OutputArray _dst, Stream& stream)
...
+#ifndef HAVE_CUDA
+    CV_UNUSED(src);
+    CV_UNUSED(dst);
+    CV_UNUSED(stream);
+    throw_no_cuda();
+#else
+    CV_UNUSED(stream);
+    if (src.refcount == dst.refcount)
+    {
+        src = src.clone();
```
Comment (alalek) [inline modules/core/src/cuda_gpu_mat.cpp:421]: IMHO, Performance warning must be emitted. Users can see it and update application code.

You may use this "once" emitter: `CV_LOG_ONCE_WARNING()`
Also caller function name should be used in the message.

File: modules/core/include/opencv2/core/private.cuda.hpp [hunk 2]
```diff
@@ -99,6 +99,7 @@ namespace cv { namespace cuda {
     }
 
     CV_EXPORTS void syncOutput(const GpuMat& dst, OutputArray _dst, Stream& stream);
+    CV_EXPORTS void detachOutput(GpuMat& src, const GpuMat& dst, Stream& stream);
```
Comment (alalek) [inline modules/core/include/opencv2/core/private.cuda.hpp:102]: I believe it should be a macro (to keep called function name and line in emitted warnings)

File: modules/core/src/cuda_gpu_mat.cpp [hunk 3]
```diff
@@ -407,6 +407,22 @@ void cv::cuda::syncOutput(const GpuMat& dst, OutputArray _dst, Stream& stream)
...
 
+void cv::cuda::detachOutput(GpuMat& src, const GpuMat& dst, Stream& stream)
+{
+#ifndef HAVE_CUDA
+    CV_UNUSED(src);
+    CV_UNUSED(dst);
+    CV_UNUSED(stream);
+    throw_no_cuda();
+#else
+    CV_UNUSED(stream);
```
Comment (alalek) [inline modules/core/src/cuda_gpu_mat.cpp:418]: Unused `stream` may prevent correct data synchronization.

**Comment by nglee** [comment]
@alalek 
The updated code referred to the following lines.
https://github.com/opencv/opencv/blob/3.4/modules/imgproc/src/filter.dispatch.cpp#L918-L924

Consulting [this issue comment](https://github.com/opencv/opencv/issues/17840#issuecomment-659946149), should we raise an exception instead?

**Comment by nglee** [comment]
https://github.com/opencv/opencv/issues/17840#issuecomment-660757791

Instead of copying the source matrix, this code calls in-place npp function if given in-place arguments.

File: modules/core/src/cuda_gpu_mat.cpp (hunk 1 above)
Comment (nglee) [reply modules/core/src/cuda_gpu_mat.cpp]: https://github.com/opencv/opencv/commit/58dcd52e37783bc310e5b607cba08c0cb662da62 tried to resolve this review comment, however: https://github.com/opencv/opencv/pull/17863#issuecomment-661536808

File: modules/core/include/opencv2/core/private.cuda.hpp (hunk 2 above)
Comment (nglee) [reply modules/core/include/opencv2/core/private.cuda.hpp]: https://github.com/opencv/opencv/commit/58dcd52e37783bc310e5b607cba08c0cb662da62 tried to resolve this review comment, however: https://github.com/opencv/opencv/pull/17863#issuecomment-661536808

File: modules/core/src/cuda_gpu_mat.cpp (hunk 3 above)
Comment (nglee) [reply modules/core/src/cuda_gpu_mat.cpp]: https://github.com/opencv/opencv/commit/58dcd52e37783bc310e5b607cba08c0cb662da62 tried to resolve this review comment, however: https://github.com/opencv/opencv/pull/17863#issuecomment-661536808

**Comment by asmorkalov** [comment]
Looks good to me. Passed test on Ubuntu 18.04 with CUDA 10.2 and GPU 1080Ti.

**Comment by asmorkalov** [comment]
@nglee The same issue is reproducible with master branch too, but the code for master is moved to opencv_contrib repo. Could you propose yet another PR to contrib repository too?

**Comment by nglee** [comment]
@asmorkalov 
I've opened one: https://github.com/opencv/opencv_contrib/pull/2612

**Comment by tomoaki0705** [comment]
> nglee The same issue is reproducible with master branch too, but the code for master is moved to opencv_contrib repo. Could you propose yet another PR to contrib repository too?

@asmorkalov Once in the past, I was pointed from @alalek that this is not necessary, porting one PR from opencv to opencv_contrib.

https://github.com/opencv/opencv/pull/12666#pullrequestreview-160086288

> > once this modification is approved, I'll open a PR for opencv_contrib, too.

> It is not necessary. I will merge these changes during next regular "Merge 3.4" PRs.

And alalek also did the same recently
[original](https://github.com/opencv/opencv/pull/17527/commits/d4af89781b81cdc2ffa93af2a04a26370575d230)
[ported](https://github.com/opencv/opencv_contrib/pull/2573/commits/bab3d66c715ff8afacee1d066f65166a894ded38)

Was there any special reason for this PR to be ported to opencv_contrib ?
I'm just curious.

**Comment by asmorkalov** [comment]
It's good idea to have CUDA implementations aligned between branches, especially if the patch could be ported as is without serious modifications.

**Comment by tomoaki0705** [comment]
@asmorkalov , my point is not "why", but "who".
If I make modification for CUDA stuff in 3.4 branch, should "I" port it to contrib, or can I keep it untouched so "alalek" can port it ?

**Comment by asmorkalov** [comment]
General approach is to merge 3.4 to master weekly or so. Alalek does it and you usually hould not worry about it. Cuda changes cannot be just merged to contrib with git and some manual work is required. I usually ask the PR author to do porting as soon as author is in context can can do it faster.
