### PR TITLE
GAPI: fix Clang warning for dangling references in for loop variable

### LINKED ISSUE #18928: G-API: "range for" result reference warning near ade::util::indexed()
Xcode 12.2:

```
modules/gapi/src/backends/ocl/goclbackend.cpp:234:26: warning:
loop variable 'out_it' is always a copy because the range of type 
'decltype(zip(iota<std::size_t>(), std::forward<const std::__1::vector<cv::gimpl::RcDesc, std::__1::allocator<cv::gimpl::RcDesc> > &>(conts)))' (aka 'ZipRange<ade::util::Range::IotaRange<unsigned long, 1>, const std::__1::vector<cv::gimpl::RcDesc, std::__1::allocator<cv::gimpl::RcDesc> > &>')
does not return a reference [-Wrange-loop-analysis]
        for (const auto &out_it : ade::util::indexed(op.outs))
                         ^
modules/gapi/src/backends/ocl/goclbackend.cpp:234:14: note:
use non-reference type 'std::__1::tuple<const unsigned long &, const cv::gimpl::RcDesc &>'
        for (const auto &out_it : ade::util::indexed(op.outs))
             ^~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by anton-potapov**
Clang complains that the code in question binds a temporary value (returned by `indexed`) to a (`const`) reference.  While technically assigning a temporary value to `const` reference is OK (as it extends a lifetime of the temporary to lifetime of the reference), let\s please the compiler :)   

resolves #18928

<cut/>

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

```
buildworker:Mac=macosx-1
buildworker:iOS=macosx-1

force_builders=Custom,Custom Win,Custom Mac
build_gapi_standalone:Linux x64=ade-0.1.1f
build_gapi_standalone:Win64=ade-0.1.1f
build_gapi_standalone:Mac=ade-0.1.1f
build_gapi_standalone:Linux x64 Debug=ade-0.1.1f

build_image:Custom=centos:7
buildworker:Custom=linux-1
build_gapi_standalone:Custom=ade-0.1.1f

test_modules:Custom=gapi
test_modules:Custom Win=gapi
test_modules:Custom Mac=gapi

buildworker:Custom=linux-1
# disabled due high memory usage: test_opencl:Custom=ON
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

**Review by alalek — APPROVED** [review]
Looks good to me :+1:

**Comment by anton-potapov** [comment]
@dmatveev, could you please take a look ?

File: modules/gapi/src/backends/common/gcompoundkernel.cpp [hunk 1]
```diff
@@ -16,7 +16,7 @@
 cv::detail::GCompoundContext::GCompoundContext(const cv::GArgs& in_args)
 {
     m_args.resize(in_args.size());
-    for (const auto& it : ade::util::indexed(in_args))
+    for (const auto it : ade::util::indexed(in_args))
```
Comment (dmatveev) [inline modules/gapi/src/backends/common/gcompoundkernel.cpp:19]: out of curiosity: y not `auto && it` ?

**Review by dmatveev — APPROVED** [review]

File: modules/gapi/src/backends/common/gcompoundkernel.cpp (hunk 1 above)
Comment (alalek) [reply modules/gapi/src/backends/common/gcompoundkernel.cpp:19]: details about that approach: https://stackoverflow.com/questions/13130708/what-is-the-advantage-of-using-forwarding-references-in-range-based-for-loops

Comment (dmatveev) [reply modules/gapi/src/backends/common/gcompoundkernel.cpp:19]: @anton-potapov ?

Comment (anton-potapov) [reply modules/gapi/src/backends/common/gcompoundkernel.cpp:19]: In this context both versions are equal and correct, however "plain copy" version put less stress on the reader  (IMHO) more explicitly describing the intent

**Comment by anton-potapov** [comment]
@alalek could you please merge it ?
