### PR TITLE
core: Add cgroupsv2 support to parallel.cpp

### LINKED ISSUE #25284: cv::getCPUCount has no support for Linux cgroups v2
### System Information

OpenCV version: 4.9.0
Operating System / Platform: Fedora 38

### Detailed description

Code was added in #16457 (bug #16268) to inspect `/sys/fs/cgroup/` under Linux to see if opencv is running in a constrained environment and cannot use all the CPUs of the system. But cgroups in the Linux kernel now has v2 which changes the underlying file structure (see https://github.com/torvalds/linux/commit/0d5936344f30aba0f6ddb92b030cb6a05168efe6).

This means that under cgroups v2 opencv incorrectly counts the CPUs and ends up opening far too any threads.

### Steps to reproduce

Expected behaviour (this is seen when run under cgroups v1).

```
docker run --cpu-quota=300000 --cpu-period=100000  ...

$ opencv_version --threads
Parallel framework: pthreads (nthreads=3)
```

But under cgroups v2 this gives the wrong answer (8 is number of cores on my system)

```
docker run --cpu-quota=300000 --cpu-period=100000 ...

$ opencv_version --threads
Parallel framework: pthreads (nthreads=8)
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by johnteslade**
The parallel code works out how many CPUs are on the system by checking the quota it has been assigned in the Linux cgroup. The existing code works under cgroups v1 but the file structure changed in cgroups v2. From [1]:

    "cpu.cfs_quota_us" and "cpu.cfs_period_us" are replaced by "cpu.max"
  which contains both quota and period.

This commit add support to parallel so it will read from the cgroups v2 location. v1 support is still retained.

Resolves #25284

[1] https://github.com/torvalds/linux/commit/0d5936344f30aba0f6ddb92b030cb6a05168efe6

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by johnteslade** [comment]
I've build and tested this locally on my Linux system (Fedora 38) running cgroups v2 and the opencv is now reporting the expected number of threads when running in a container with a quota.

```
$ mount -l | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)

$ docker run --cpu-quota=300000 --cpu-period=100000 ...

$ opencv_version --threads
Parallel framework: pthreads (nthreads=3)
```

File: modules/core/src/parallel.cpp [hunk 1]
```diff
@@ -966,8 +981,11 @@ int getNumberOfCPUs_()
     static unsigned ncpus_impl_cpuset = (unsigned)getNumberOfCPUsImpl("/sys/fs/cgroup/cpuset/cpuset.cpus");
```
Comment (mshabunin) [inline modules/core/src/parallel.cpp:981]: What about cpuset? Apparently on my system with cgroups2 (Ubuntu 22.04 - based) it has changed location to `/sys/fs/cgroup/cpuset.cpus` or `cpuset/cpus.effective` (idk which is right).

```
$ docker run --cpuset-cpus 1-3,8 -it ubuntu:22.04
root@f0e45a761cea:/# cat /sys/fs/cgroup/cpuset.cpus
1-3,8
```

Comment (opencv-alalek) [reply modules/core/src/parallel.cpp:981]: It is a workaround for callers.

Because we could assign CPUs and also limit their usage:

```
docker run --rm --cpuset-cpus 1-3,8 --cpu-quota=300000 --cpu-period=100000 -it ubuntu:22.04
root@d4db947e6eba:/# cat /sys/fs/cgroup/cpuset.cpus
1-3,8
root@d4db947e6eba:/# cat /sys/fs/cgroup/cpu.max    
300000 100000
```

**Review by opencv-alalek — APPROVED** [review]
LGTM :+1: Thank you for contribution!
