### PR TITLE
calib3d(usac): do not crash on empty models

### LINKED ISSUE #19639: version 4.5.1 findFundamentalMat Magsac algorithm SegmentFault across platforms on specific keypoint input
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => both on ubuntu 18.04 and macbook catalina
- Compiler => installed using pip

##### Detailed description

Magsac in cv2.findFundamentalMat() crashes on a specific pair of input points

##### Steps to reproduce

```
>>> import cv2
>>> cv2.__version__
'4.5.1'
>>> import numpy as np
>>> x = np.array([[941, 890],
...        [596, 940],
...        [898, 941],
...        [894, 933],
...        [586, 938],
...        [902, 933],
...        [887, 935]])
>>> y = np.array([[1416,  806],
...        [1157,  852],
...        [1380,  855],
...        [1378,  843],
...        [1145,  849],
...        [1378,  843],
...        [1378,  843]])
>>> cv2.findFundamentalMat(x, y, cv2.USAC_MAGSAC, 3, 0.99)
```

<details>

<summary>Python .py code</summary>

```.py
import numpy as np
import cv2 as cv

x = np.array([[941, 890],
        [596, 940],
        [898, 941],
        [894, 933],
        [586, 938],
        [902, 933],
        [887, 935]])

y = np.array([[1416,  806],
        [1157,  852],
        [1380,  855],
        [1378,  843],
        [1145,  849],
        [1378,  843],
        [1378,  843]])

res = cv.findFundamentalMat(x, y, cv.USAC_MAGSAC, 3, 0.99)

print(res)
```

</details>

### PR DESCRIPTION
**Pull request by alalek**
resolves #19639
relates #17683

### CODE REVIEW

File: modules/calib3d/src/usac/quality.cpp [hunk 1]
```diff
@@ -421,7 +421,11 @@ class SPRTImpl : public SPRT {
      * @current_hypothesis: current RANSAC iteration
      * Return: true if model is good, false - otherwise.
      */
-    inline bool isModelGood (const Mat &model) override {
+    inline bool isModelGood(const Mat& model) override
+    {
+        if (model.empty())
+            return false;
```
Comment (alalek) [inline modules/calib3d/src/usac/quality.cpp:427]: @ivashmak @vpisarev Is it valid?

Comment (ivashmak) [reply modules/calib3d/src/usac/quality.cpp:427]: Yes it is. However, the situation that model comes empty to SPRT should not have happened in general. Maybe there is a problem somewhere else, I'll check it. For function setModelParameters CV_CheckTypeEQ(model.depth(), CV_64F, ""); it is a bit redundant because the model will always be in double format. It comes from solver.

**Review by ivashmak — APPROVED** [review]

**Comment by alalek** [comment]
:+1:
