### PR TITLE
cuda4dnn(build): add basic support for cuDNN 8

### LINKED ISSUE #17747: opencv_dnn compilation error caused by using deprecated cuDNN functions
##### System information (version)

- OpenCV => master
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- NVIDIA CUDA => ver 11.0 *(latest)*, CUFFT CUBLAS FAST_MATH enabled
- cuDNN  => ver 8.0.1.13 *(latest)*

##### Detailed description

According to [cuDNN Developer Guide](https://docs.nvidia.com/deeplearning/sdk/cudnn-api/index.html#api-changes),  functions invoked in [convolution.hpp](https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp) and [transpose_convolution.hpp](https://github.com/opencv/opencv/blob/7b12cbd7dcbb025c31e7630c9ae709493a8f3d62/modules/dnn/src/cuda4dnn/csl/cudnn/transpose_convolution.hpp) like  `cudnnGetConvolutionBackwardDataAlgorithm()` and `cudnnGetConvolutionForwardAlgorithm()`, as well as their input parameters `cudnnConvolutionFwdPreference_t` and ` cudnnConvolutionBwdDataPreference_t` have been deprecated as of cuDNN 8.0. Therefore, building the current opencv_dnn module with CUDA could raise compilation errors. 

##### Steps to reproduce
- Compile the latest OpenCV with the above configurations

##### Current workaround
For **convolution.hpp**: 
| Line | Revision |
| ------ | ------ |
| 263 | `cudnnGetConvolutionForwardAlgorithm(` => `cudnnFindConvolutionForwardAlgorithm(` |
| 266 | `CUDNN_CONVOLUTION_FWD_PREFER_FASTEST,` => `CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM,` |
| 268 | `&algo` => `&perf` |
| 276 | `algo, &workspace_size` => `perf.algo, &workspace_size` |
| 284 | `cudnnConvolutionFwdAlgo_t get() const noexcept { return algo; }` => |
|       | `cudnnConvolutionFwdAlgo_t get() const noexcept { return perf.algo; }` |
| 290 | `cudnnConvolutionFwdAlgo_t algo;` => `cudnnConvolutionFwdAlgoPerf_t perf;` |

For **transpose_convolution.hpp**:
| Line | Revision |
| ------ | ------ |
| 39 | `cudnnGetConvolutionBackwardDataAlgorithm(` => `cudnnFindConvolutionBackwardDataAlgorithm(` |
| 42 | `CUDNN_CONVOLUTION_BWD_DATA_PREFER_FASTEST,` => `CUDNN_CONVOLUTION_BWD_DATA_ALGO_1` |
| 44 | `&dalgo` => `&perf` |
| 52 | `dalgo, &workspace_size` => `perf.algo, &workspace_size` |
| 60 | `cudnnConvolutionBwdDataAlgo_t get() const noexcept { return dalgo; }` |
|      | `cudnnConvolutionBwdDataAlgo_t get() const noexcept { return perf.algo; }` |
| 65 | `cudnnConvolutionBwdDataAlgo_t dalgo;` => `cudnnConvolutionBwdDataAlgoPerf_t perf;` |

(can make a pull request if this seems reasonable)

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by YashasSamaga**
There are five tests failing on GTX 1050 which are not fixable (no convolution algorithm found). These might be limited to 6.1 devices or devices that don't support good FP16 performance.

```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_layers.PoolConv3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_nets.Resnet34_kinetics/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.concat_3d/1, where GetParam() = CUDA/CUDA_FP16
```

Related #17496
fixes #17747 

**Pending:**
- test on CUDA11

<cut/>

# Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

```
force_builders=Custom
buildworker:Custom=linux-4
Xbuild_image:Custom=ubuntu-cuda:18.04
build_image:Custom=ubuntu-cuda11:18.04
build_image:Custom Win=cuda11
```

### CODE REVIEW

File: modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp [hunk 1]
```diff
@@ -225,6 +225,14 @@ namespace cv { namespace dnn { namespace cuda4dnn { namespace csl { namespace cu
                     );
                 }
                 CUDA4DNN_CHECK_CUDNN(cudnnSetConvolutionGroupCount(descriptor, group_count));
+
+#if CUDNN_MAJOR >= 8
+                /* cuDNN 7 and below use FMA math by default. cuDNN 8 includes TF32 Tensor Ops
+                 * in the default setting. TF32 convolutions have lower precision than FP32.
+                 * Hence, we set the math type to CUDNN_FMA_MATH to reproduce old behavior.
+                 */
+                CUDA4DNN_CHECK_CUDNN(cudnnSetConvolutionMathType(descriptor, CUDNN_FMA_MATH));
```
Comment (YashasSamaga) [inline modules/dnn/src/cuda4dnn/csl/cudnn/convolution.hpp:234]: > On pre-NVIDIA A100 GPU devices, CUDNN_DEFAULT_MATH and CUDNN_FMA_MATH have the same behavior: Tensor Core kernels will not be selected. With NVIDIA Ampere GPU architecture and CUDA Toolkit 11, CUDNN_DEFAULT_MATH permits TF32 Tensor Core operation and CUDNN_FMA_MATH does not. The TF32 behavior for CUDNN_DEFAULT_MATH can be explicitly disabled by the environment variable NVIDIA_TF32_OVERRIDE=0.
>
> [Source](https://docs.nvidia.com/deeplearning/sdk/cudnn-api/index.html#cudnnMathType_t)

TF32 format is stored as FP32 in memory but uses a 10-bit mantissa during convolution. Hence, it's less precise. This affects only the new CC 8.x GPUs.

Some models like YOLOv4 do not suffer an accuracy drop in FP16. So TF32 might work without issues and give faster performance but it's still not the same as FP32.

**Comment by alalek** [comment]
@YashasSamaga Thank you!

Please add removal of lines 24-26 and line 31 from [CMake file](https://github.com/opencv/opencv/blame/master/modules/dnn/CMakeLists.txt#L24) too.

File: modules/dnn/CMakeLists.txt [hunk 2]
```diff
@@ -21,14 +21,11 @@ if(OPENCV_DNN_OPENCL AND HAVE_OPENCL)
...
 
-if(NOT DEFINED OPENCV_DNN_CUDA AND HAVE_CUDNN AND CUDNN_VERSION VERSION_LESS 8.0)
-  message(STATUS "DNN: CUDNN 8.0 is not supported yes. Details: https://github.com/opencv/opencv/issues/17496")
-endif()
 ocv_option(OPENCV_DNN_CUDA "Build with CUDA support"
     HAVE_CUDA
     AND HAVE_CUBLAS
     AND HAVE_CUDNN
-    AND CUDNN_VERSION VERSION_LESS 8.0
+    AND CUDNN_VERSION
```
Comment (alalek) [inline modules/dnn/CMakeLists.txt:28]: We can just remove this line (`HAVE_CUDNN` is already here)

**Comment by alalek** [comment]
@YashasSamaga BTW, Which CUDA version are you using for experiments? CUDNN 8 is available for both CUDA 10.2 and 11.0

**Comment by rafale77** [comment]
I would vote for CUDA11... might as well go all the way....

**Comment by YashasSamaga** [comment]
@alalek I am using 10.2.

**Comment by YashasSamaga** [comment]
I tried to use `cudnnGetConvolutionForwardAlgorithm_v7` instead of `cudnnGetConvolutionForwardAlgorithm` (which has been removed in cuDNN 8) in cuDNN 7. This caused some tests to fail in cuDNN 7.

```
[  FAILED  ] Test_Model.Keypoints_face/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.pooling_max_pool_odd_same/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.fp16_weights_fp16_max_pool_odd_same/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.fp16_weights_fp16_max_pool_even/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.fp16_weights_fp16_max_pool_odd_valid/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_nets.EfficientDet/1, where GetParam() = CUDA/CUDA_FP16
```

So with this, we can say that the best algorithm returned by the two APIs are not the same. I printed the algorithms where mismatches occurred. The `cudnnGetConvolutionForwardAlgorithm_v7` and `cudnnGetConvolutionForwardAlgorithm` disagree in mainly in one way: the v7 API returns `WINOGRAD_NONFUSED` in place of other algorithms in some situations.

Comparing the heuristic returned by cuDNN with the stats obtained generated by #16900, it appears like the v7 API is correct if we want the fastest algorithm. But `WINOGRAD_NONFUSED` is one of the numerically inaccurate algorithms for convolutions. All the tests that failed by switching to v7 API in cuDNN 7 can be corrected by updating the thresholds (some 5x-10x higher than before though). Maybe this is why TF ignores it?

**Comment by YashasSamaga** [comment]
Removing `WINOGRAD_NONFUSED` from the list of algorithms returned by the _v7 API and then picking the best algorithm appears to give identical results as the non-v7 API. The accuracy regressions have all disappeared. The tests that are failing are because of non-availability of convolution algorithms for certain configurations. I am not sure if it's because of testing on a 6.1 device (which has bad FP16 performance). Maybe they work in other devices which actually have goog FP16 perfromance.

These are the tests that are failing with cuDNN 8.

```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] Test_ONNX_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_layers.PoolConv3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_ONNX_nets.Resnet34_kinetics/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.Convolution3D/1, where GetParam() = CUDA/CUDA_FP16
[  FAILED  ] Test_TensorFlow_layers.concat_3d/1, where GetParam() = CUDA/CUDA_FP16
```

File: modules/dnn/CMakeLists.txt (hunk 2 above)
Comment (YashasSamaga) [reply modules/dnn/CMakeLists.txt]: I have removed `CUDNN_VERSION` line (no idea why I even left it there). Do you want `opencv_dnn: filter out cuda4dnn source code` to be removed too?

Comment (alalek) [reply modules/dnn/CMakeLists.txt]: > to be removed too

No.
This message just shows that condition for `OPENCV_DNN_CUDA` is false.
Removal of `CUDNN_VERSION` fixes that.

**Comment by rafale77** [comment]
There is actually even a version 8.0.1 RC2 of Cudnn which got released last week...

**Comment by YashasSamaga** [comment]
I asked about  `WINOGRAD_NONFUSED` at NVIDIA's developer forums: https://forums.developer.nvidia.com/t/variations-in-heuristics-for-selecting-conv-algorithm-in-different-apis/139730/2

> the reason some framework choose to remove “WINOGRAD_NONFUSED” is because sometimes it does not produce very good numerical precision. However we have not head it causing huge convergence problems either. It’s a per-framework decision to skip it or not.

> For general usage, it would be safer to imitate the old TF behavior and skip it to avoid any surprise in existing working scripts. if you want performance and has more tolerance on convergence issues, you can choose to allow it.

So it's just a tradeoff between numerical accuracy and performance. The tests that fail by enabling `WINOGRAD_NONFUSED` require 3x-8x higher thresholds. The small errors in the convolution probably get amplified by the remaining part of the networks.
