### PR TITLE
videoio: obsensor: remove OB_EXT_CMD10 to suppress warning

### LINKED ISSUE #25522: videoio: obsensor: OB_EXT_CMD10 is defined, but unused.
### System Information

OpenCV version: 4.x ( b5cf4f1483cb3a3884bbec08f289ba8f7b582b91 )
Operating System / Platform: Ubuntu 24.04
Compiler & compiler version: clang++ 18.1.3

### Detailed description

With clang++-18, there is a comile warning in videoio.
OB_EXT_CMD10 seems to be no longer to use.

```
[985/1550] Building CXX object modules/videoio/CMakeFiles...io.dir/src/cap_obsensor/obsensor_uvc_stream_channel.cpp.
/home/kmtr/work/opencv4/modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp:48:15: warning: unused variable 'OB_EXT_CMD10' [-Wunused-const-variable]
   48 | const uint8_t OB_EXT_CMD10[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfa, 0x13, 0x3f, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00 };
      |               ^~~~~~~~~~~~
1 warning generated.
```

### Steps to reproduce

```
$ cmake -S opencv4 -B build4-main_clang18 -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18 -GNinja
$ cmake --build build4-main_clang18
[985/1550] Building CXX object modules/videoio/CMakeFiles...io.dir/src/cap_obsensor/obsensor_uvc_stream_channel.cpp.
/home/kmtr/work/opencv4/modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp:48:15: warning: unused variable 'OB_EXT_CMD10' [-Wunused-const-variable]
   48 | const uint8_t OB_EXT_CMD10[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfa, 0x13, 0x3f, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00 };
      |               ^~~~~~~~~~~~
1 warning generated.
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by Kumataro**
Close #25522 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp [hunk 1]
```diff
@@ -45,7 +45,7 @@ const uint8_t OB_EXT_CMD6[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0x7c, 0x00
 const uint8_t OB_EXT_CMD7[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfe, 0x12, 0x55, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00 };
 const uint8_t OB_EXT_CMD8[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfe, 0x13, 0x3f, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00 };
 const uint8_t OB_EXT_CMD9[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfa, 0x13, 0x4b, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00 };
-const uint8_t OB_EXT_CMD10[16] = { 0x47, 0x4d, 0x04, 0x00, 0x02, 0x00, 0xfa, 0x13, 0x3f, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00 };
```
Comment (asmorkalov) [inline modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp:48]: I propose to presume array values in comment or remove the line at all. In current version the command cannot be restored with `//` removal.

**Review by asmorkalov — APPROVED** [review]
:+1:

File: modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp (hunk 1 above)
Comment (Kumataro) [reply modules/videoio/src/cap_obsensor/obsensor_uvc_stream_channel.cpp:48]: Thank you for your review !

As first, I reserved CMD10 so that I would not reuse only CMD10 identifier for other array in the future. 
However, it didn't seem to cause any problems, so I deleted it completely.
