### PR TITLE
changed names of permutations if Reshpe is in NHWC

### LINKED ISSUE #21290: Lost support of tf nhwc models
- OpenCV => 4.5.5-pre
- Operating System / Platform => Ubuntu 20.04 LTS
- Compiler => gcc 8.4.0

##### Detailed description

While I switched to version 4.5.4 and later after version 4.5.1, tensorflow models, that use NHWC-type layers, stopped working. I ran dnn tests on actual version and all was fun with tf. After I use forward, there's an error:
```
  what():  OpenCV(4.5.5-pre) /home/user/libs/opencv_19_12_master/src/opencv-4.x/modules/dnn/src/layers/[convolution_layer.cpp:405](https://github.com/opencv/opencv/blame/80492d663e3fcdaf84f1edf234e563d2a5c81951/modules/dnn/src/layers/convolution_layer.cpp#L402-L405): error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 224 in function 'getMemoryShapes'.
```
Before I also tried to make input of my model NCHW, then permutate tensor's dims so, that after it would be NHWC and I wouldn't have to change architectures to NCHW-style.

So, I see there are 2 problems:
1). There are lots of tf NHWC models on my project and rewriting architectures of each of them(to NCHW format) and retraining them will be a huge waste of time. And, I think, there are also lots of people, who are using models of NHWC-type and are using OpenCV for inference purposes. So, wouldn't it be too rough to break the support of NHWC?
2). If support of NHWC layers was canceled, shouldn't be there any exception, that will be threw, when you load a model, that contains NHWC-style layers?

##### Steps to reproduce
Just load NHWC-style tf model:
```
    const std::string imgPath{"test_img.png"};
    const std::string pbModelPath = "opencv_graph.pb";

    auto net = cv::dnn::readNetFromTensorflow(pbModelPath);
    cv::Mat img = cv::imread(imgPath, 1);
    auto blob = cv::dnn::blobFromImage(img, 1.0, cv::Size(224, 224));
    net.setInput(blob);
    auto outputs = net.forward();
```

### PR DESCRIPTION
**Pull request by Ichini24**
Fixes #21290 
opencv_extra: https://github.com/opencv/opencv_extra/pull/1004

### Pull Request Readiness Checklist

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

Original issue:
https://github.com/opencv/opencv/issues/21290

Found out, why my tf models wasn't supported by latest version of OpenCV. The problem was, that in graph layers with their id's were looking like:
0: input
1: reshape
2: conv

But while building graph in OpenCV it was looking like:
0: input
1: reshape//nhwc
2: reshape
3: reshape/nchw
4: conv

The problem is while getting memory shapes and connecting nodes with each other, the algorithm is connecting them by names, so the chain of layers ids was not: 0 -> 1 -> 2 -> 3 -> 4, but 0 -> 1 -> 2 -> 4.
There's 2 ways of solving this issue:

1. Place the original name as the latest in this permutation chain, which may be not 100% correct, but it fixes bug.
2. Change the input layer name on conv layer(see above in example). But there's no interface for such a fix.

### CODE REVIEW

**Comment by fengyuentau** [comment]
Thank you for your contribution. Could you provide a test for this patch?

**Comment by antonmiliutsin** [comment]
@fengyuentau sure, but how do I do it? Should I place small pb graph to opencv_extra and write test for this patch in dnn module?

**Comment by Ichini24** [comment]
@fengyuentau sure, but how do I do it? Should I place small pb graph to opencv_extra and write test for this patch in dnn module?

**Comment by asmorkalov** [comment]
@Ichini24 Yes, you are right. You need to create small model with several layers to reproduce the issue, submit PR with the same branch name to extra and add test case to DNN test set. Extra patch should include input and expected output tensors for check. You can use on of onnx tests as reference.

**Comment by Ichini24** [comment]
Sorry for the delay, tried to understand, how there's all work. So, I prepared little model with 28x28x3 input shape, so the graph size is 19.2 kB. on the disk. I have several questions about test.

1. Cause the model is small, not sure, that it would be correct to await for any output result to compare it with predefined tensor. In my fix, not getting an exception is already the prove, that fix is working. You can see the original issue, everything is covered there. Will it be ok just to Assert that output is not empty?
2. I've watched the test_tf_importer.cpp and placed my test there. Can I use Test_TensorFlow_layers class for my issue?

**Comment by fengyuentau** [comment]
Since the issue happens in forwarding, I suggest you should provide the reference data for output checking as well, especially when you want to reuse `Test_TensorFlow_layers` which needs reference data.

File: modules/dnn/src/tensorflow/tf_importer.cpp [hunk 1]
```diff
@@ -1110,23 +1113,28 @@ void TFImporter::parseReshape(tensorflow::GraphDef& net, const tensorflow::NodeD
...
+        inpId = Pin(setName);
 
         if ((inpLayout == DATA_LAYOUT_NHWC || inpLayout == DATA_LAYOUT_UNKNOWN || inpLayout == DATA_LAYOUT_PLANAR) &&
             newShapeSize == 4 && !hasSwap)
         {
             int order[] = {0, 3, 1, 2};  // Transform back to OpenCV's NCHW.
-            addPermuteLayer(order, name + "/nchw", inpId);
+
+            setName = changedType ? name : name + "/nchw";
+            addPermuteLayer(order, setName, inpId);
```
Comment (fengyuentau) [inline modules/dnn/src/tensorflow/tf_importer.cpp:1137]: ***For reviewers***:
This issue is triggered when this if condition is entered. `addPermuteLayer` sets the output name to `name + "/nchw"`, leading to the incorrect input fetched by the next layer.

**Review by fengyuentau — COMMENTED** [review]
Thank you for the fix. Your changes look good to me. We can move on when you provide the test case.

**Comment by Ichini24** [comment]
Done everything like you said. Here's the link to the opencv-extra pr:
https://github.com/opencv/opencv_extra/pull/1004

**Comment by fengyuentau** [comment]
I checked the model you provided. I think you should add a shape-sensitive layer after realdiv, such as conv in your original model, since realdiv is elementwise and it runs no matter what the input shape is.

**Comment by Ichini24** [comment]
Updated pb graph with the convolution layer at the end and updated output array. Please, check.

**Review by fengyuentau — APPROVED** [review]
Please squash commits into one. Others look good to me 👍

**Comment by Ichini24** [comment]
I've squashed opencv and opencv_extra commits, please check.

**Review by zihaomu — APPROVED** [review]
Thanks for your contribution! 👍 
It's a workaround for me.

File: modules/dnn/src/tensorflow/tf_importer.cpp (hunk 1 above)
Comment (rogday) [reply modules/dnn/src/tensorflow/tf_importer.cpp:1137]: Why do we need `name + "/nchw"` node at the end? I don't think other layers know this node by name.

Comment (fengyuentau) [reply modules/dnn/src/tensorflow/tf_importer.cpp:1137]: @rogday It was introduced by you in a pull request a year ago: https://github.com/opencv/opencv/pull/20190/files#diff-f5872c76075aa1f06f357d1dc27448bf1a02a28b79e62d92e8b7aa47311b57dfR1007

Comment (rogday) [reply modules/dnn/src/tensorflow/tf_importer.cpp:1137]: @fengyuentau, it's a refactoring PR that broke history a little bit.

Comment (rogday) [reply modules/dnn/src/tensorflow/tf_importer.cpp:1137]: Heh, I was investigating it [already](https://github.com/opencv/opencv/pull/19641#issuecomment-892756609), but didn't get the answer.

**Comment by rogday** [comment]
Could you check if this fixes https://github.com/opencv/opencv/issues/20433? And link it to this PR, if it does?

File: modules/dnn/src/tensorflow/tf_importer.cpp (hunk 1 above)
Comment (Ichini24) [reply modules/dnn/src/tensorflow/tf_importer.cpp:1137]: @rogday I've investigated this. So, there's a sample in tests, where the next condition is not met:
https://github.com/opencv/opencv/pull/22448/files#diff-f5872c76075aa1f06f357d1dc27448bf1a02a28b79e62d92e8b7aa47311b57dfR1105

It's not met cause newShape has values: [1, 2, 4, 3].
So, there will not be permutation before the actual Reshape node.
The test sample is: reshape_layer with the dnn/tensorflow/reshape_layer_net.pb graph. Which has only input and Reshape layer(look at the screenshot).
Screenshot from 2022-09-06 19-20-01

The reference output has shape: output shape: (1, 3, 2, 4).
So, the loaded graph in opencv will look like:
input->Reshape->Reshape/nchw.

Also this behaviour can be observed in not_implemented_layer_net.pb graph, which has 2 inputs, 1 is going to not_implemented_layer, the 2nd is going to reshape, after that outputs from this layers are multiplied.

So, the problem, that you've covered may be defined like:
1). Input layer of reshape has NHWC layout.
2). By some reason(the question here is why don't we reshape, if condition newShape.at<int>(1) == 1 is not met) the permutation from HNWC to NCHW layouts is not performed.
3). Next Reshape is performed only with NCHW data layout.
4). Data is always permuted from NCHW to NHWC data format at the end if the source of Reshape in original graph is NHWC/ Even if it wasn't permuted from NHWC to NCHW at input.

I don't see any reasons, why there's no permutation at the start. Cause usually when you have graph, where all layers have 1 data layout.
I can investigate it lately, but this is not what this PR is about. Also the changing of naming the original node name to last permutation layer breaks several tests.
