### PR TITLE
fix charuco checkBoard

### LINKED ISSUE #23905: Detection of multiple ChArUco boards with different IDs in one image broken in 4.8.0
### System Information

OpenCV 4.8.0
Ubuntu 22.04
Python 3.10.6

### Detailed description

In OpenCV 4.7.0 you could separately detect two ChArUco boards visible in a single image:

```python
dict_type = aruco.DICT_6X6_250
squares = (5, 7)
square_length_mm = 20.0
marker_length_mm = 10.0
aruco_dict = aruco.getPredefinedDictionary(dict_type)

board0 = aruco.CharucoBoard(squares, square_length_mm,
    marker_length_mm, aruco_dict, np.arange(17)) # There are 17 white squares, provide 17 markers with ids [0..16]
detector = aruco.CharucoDetector(board0)
charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(image)
aruco.drawDetectedCornersCharuco(image, charuco_corners, charuco_ids, (255, 0, 0))

board1 = aruco.CharucoBoard(squares, square_length_mm,
    marker_length_mm, aruco_dict, np.arange(17) + 17) # 17 markers with ids  [17..33]
detector = aruco.CharucoDetector(board1)
charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(image)
aruco.drawDetectedCornersCharuco(image, charuco_corners, charuco_ids, (0, 255, 0))
```
Screenshot from 2023-07-02 14-04-06

In OpenCV 4.8.0, the second `detectBoard` does not return any ChArUco corners. `charuco_corners`and `charuco_ids` are both `None`.

The markers are still returned, so it is not a detection issue.

Sample code and sample image (see below) return under 4.7.0:

```
Running OpenCV 4.7.0
board0
  charuco ids 0..23 (24)
  marker ids 0..33 (34)
board1
  charuco ids 0..23 (24)
  marker ids 0..33 (23)
```

and SAME code under OpenCV 4.8.0:

```
Running OpenCV 4.8.0
board0
  charuco ids 0..23 (24)
  marker ids 0..33 (34)
board1
  no charuco ids
  marker ids 0..33 (23)
```

### Steps to reproduce

```python
import numpy as np
import cv2
import cv2.aruco as aruco

if __name__ == '__main__':

    # Load image
    image = cv2.imread('image.png')

    # Generate Aruco boards
    dict_type = aruco.DICT_6X6_250
    squares = (5, 7)
    square_length_mm = 20.0
    marker_length_mm = 10.0
    aruco_dict = aruco.getPredefinedDictionary(dict_type)
    board0 = aruco.CharucoBoard(squares, square_length_mm,
        marker_length_mm, aruco_dict, np.arange(17))
    board1 = aruco.CharucoBoard(squares, square_length_mm,
        marker_length_mm, aruco_dict, np.arange(17) + 17)

    print(f'Running OpenCV {cv2.__version__}')

    detector = aruco.CharucoDetector(board0)
    charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(image)
    print('board0')
    if charuco_ids is None:
        print('  no charuco ids')
    else:
        print(f'  charuco ids {np.min(charuco_ids)}..{np.max(charuco_ids)} ({len(charuco_ids)})')
        aruco.drawDetectedCornersCharuco(image, charuco_corners, charuco_ids, (255, 0, 0))
    print(f'  marker ids {np.min(marker_ids)}..{np.max(marker_ids)} ({len(marker_ids)})')

    detector = aruco.CharucoDetector(board1)
    charuco_corners, charuco_ids, marker_corners, marker_ids = detector.detectBoard(image)
    print('board1')
    if charuco_ids is None:
        print('  no charuco ids')
    else:
        print(f'  charuco ids {np.min(charuco_ids)}..{np.max(charuco_ids)} ({len(charuco_ids)})')
        aruco.drawDetectedCornersCharuco(image, charuco_corners, charuco_ids, (0, 255, 0))
    print(f'  marker ids {np.min(marker_ids)}..{np.max(marker_ids)} ({len(marker_ids)})')

    cv2.imshow(f'charuco ids with OpenCV {cv2.__version__}', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```

image

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by AleksandrPanov**
Fixes #23905

checkBoard() is an internal function that checks that the found board has the correct structure

1. fixed a bug with checking extraneous markers:
```
                if (find(boardIds.begin(), boardIds.end(), idMaker) == boardIds.end())
                    continue;
```
2. fixed an indexing bug:
```
                const int nearestMarkerId1 = boardIds[nearestMarkerIdx[chId][0]];
                const int nearestMarkerId2 = boardIds[nearestMarkerIdx[chId][1]];
```
3. updated docs for getNearestMarkerIdx()/getNearestMarkerCorners()
4. added `checkBoardStructure` flag, this flag allows you to return the old behavior or use your custom board structure check.
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp [hunk 1]
```diff
@@ -16,6 +16,7 @@ struct CV_EXPORTS_W_SIMPLE CharucoParameters {
     CV_WRAP CharucoParameters() {
         minMarkers = 2;
         tryRefineMarkers = false;
+        checkBoardStructure = true;
```
Comment (asmorkalov) [inline modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp:19]: Why do you need extra flag?

File: modules/objdetect/src/aruco/charuco_detector.cpp [hunk 2]
```diff
@@ -362,7 +366,9 @@ void CharucoDetector::setRefineParameters(const RefineParameters& refineParamete
 void CharucoDetector::detectBoard(InputArray image, OutputArray charucoCorners, OutputArray charucoIds,
                                   InputOutputArrayOfArrays markerCorners, InputOutputArray markerIds) const {
     charucoDetectorImpl->detectBoard(image, charucoCorners, charucoIds, markerCorners, markerIds);
-    if (charucoDetectorImpl->checkBoard(markerCorners, markerIds, charucoCorners, charucoIds) == false) {
+    if (charucoDetectorImpl->charucoParameters.checkBoardStructure &&
+        charucoDetectorImpl->checkBoard(markerCorners, markerIds, charucoCorners, charucoIds) == false) {
+        CV_LOG_DEBUG(NULL, "ChArUco board is built incorrectly, you can disable checkBoardStructure flag");
```
Comment (asmorkalov) [inline modules/objdetect/src/aruco/charuco_detector.cpp:371]: It's obvious from the function output. Is not it?

**Review by asmorkalov — APPROVED** [review]

File: modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp (hunk 1 above)
Comment (AleksandrPanov) [reply modules/objdetect/include/opencv2/objdetect/charuco_detector.hpp:19]: this flag allows you to return the old behavior or use your own board structure check.

File: modules/objdetect/src/aruco/charuco_detector.cpp (hunk 2 above)
Comment (AleksandrPanov) [reply modules/objdetect/src/aruco/charuco_detector.cpp:375]: I tell the user that there is a flag disabling the function checkBoard().

**Comment by vrabaud** [comment]
I confirm this fixes some tests on our end.

**Review by asmorkalov — APPROVED** [review]
:+1:

**Comment by vrabaud** [comment]
@AleksandrPanov , @asmorkalov , getMat() builds a mat so you are taking a reference to a temporary, that is problematic and will not compile with certain flags.

https://github.com/opencv/opencv/blob/224dac9427cfa1b3f1ba8787f681a3fe7f253e87/modules/core/include/opencv2/core/mat.hpp#L217  getmat returns a `Mat`, not a `Mat&`.
It should be `const Mat`, simply.
