### PR TITLE
bug fix infinite loop

### LINKED ISSUE #24967: infinite loop in findEssentialMat with 4.9.0 conda
### System Information

OpenCV python from conda-forge 4.9.0
Operation System ubuntu 18.04
python version 3.10.13

### Detailed description

OpenCV get stuck in infinite loop in findEssentialMat for specific input in version 4.9.0/4.8.0 from conda-forge, it doesn't reproduce on earlier versions, works fine with 4.5.5, 4.6.0.
on version 4.7.0 it returns very weird values for the essential mat, looks like uninitialized byes:
running find essential mat:
finished running essential mat [[ 1.51464101e-308  2.35527110e-308  1.04188218e-308]
 [ 6.81533080e-308 -3.01372316e-308  4.63557080e-310]
 [ 0.00000000e+000  6.95334911e-310  6.95328248e-310]]

### Steps to reproduce
download the attached file to reproduce, i created a conda environment like this:

mamba create -n test_opencv_loop python=3.10 opencv=4.9.0 -y

[ess_inputs.txt](https://github.com/opencv/opencv/files/14168469/ess_inputs.txt)
```
import cv2
import numpy as np

with open(<attached text file path>) as npfl:
    pts = np.loadtxt(npfl)
pts1 = pts[:, :2]
pts2 = pts[:, 2:]
fl = 1211.2073974609375
threshold = 5
print("running find essential mat:")
E, _ = cv2.findEssentialMat(pts1, pts2, focal=fl, pp=(0, 0), method=cv2.USAC_MAGSAC, threshold=threshold)
print(f'finished running essential mat {E}')
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by ivashmak**
Fixes #24967

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake
Bugfix to #24967

### CODE REVIEW

File: modules/calib3d/src/usac/utils.cpp [hunk 1]
```diff
@@ -169,6 +169,9 @@ class SolvePoly : public SolverPoly {
     int getRealRoots (const std::vector<double> &coeffs, std::vector<double> &real_roots) override {
         if (coeffs.empty())
             return 0;
+        for (auto c : coeffs)
+            if (std::isnan(c))
```
Comment (opencv-alalek) [inline modules/calib3d/src/usac/utils.cpp:173]: `cvIsNaN` (which properly works in case of `-ffast-math`)

---

Inf?

Comment (ivashmak) [reply modules/calib3d/src/usac/utils.cpp]: fixed

**Comment by asmorkalov** [comment]
The reproducer attached to the issue report works fine now:
```
running find essential mat:
finished running essential mat [[-5.50885294e-03  9.98948807e-01  4.48155013e-02]
 [-9.98882746e-01 -5.49439748e-03  7.84946260e-03]
 [-4.62316065e-02 -8.16087597e-03  8.94246615e-06]]
```

**Review by asmorkalov — APPROVED** [review]
:+1:

**Review by asmorkalov — APPROVED** [review]
:+1:
