### PR TITLE
Fix #25812: Add error handling for invalid nu parameter in SVM NU_SVC

### LINKED ISSUE #25812: SVM train fails with no warning on infeasible nu parameter
### System Information

OpenCV version:  4.6..0 
Operating System / Platform: Ubuntu 24.04
Compiler: GCC  13.2.0

### Detailed description

A value of the ```nu``` parameter to SVM ml algorithm  (type NU_SVC) that is inconsistent with the  distribution of labels of the  training cases triggers a _silent_ failure in the ```train()``` method.  The problem is detected, but no error or warning printed--it just fails. Suggested change would be to replace the "// TODO" line with something like :

```
CV_Error( cv::Error::StsBadArg, "training cases incompatible with nu parameter--try a lower value");
```
The same issue exists in the current source at the time of this submission.

### Steps to reproduce

The dog that did not bark is on line **1462** of module/ml/svm.cpp :

```
                        if( nu*(ci + cj)*0.5 > std::min( ci, cj ) )
                            // TODO: add some diagnostic 
                            return false;
                    }
```
[https://github.com/opencv/opencv/blob/11c69bb1717e2e0f37b2c25c4741aa4b18538788/modules/ml/src/svm.cpp#L1460]()

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by anandkaranubc**
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work [Issue #25812](https://github.com/opencv/opencv/issues/25812)
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/ml/src/svm.cpp [hunk 1]
```diff
@@ -1459,7 +1459,7 @@ class SVMImpl CV_FINAL : public SVM
                     {
                         int cj = class_ranges[j+1] - class_ranges[j];
                         if( nu*(ci + cj)*0.5 > std::min( ci, cj ) )
-                            // TODO: add some diagnostic
```
Comment (asmorkalov) [inline modules/ml/src/svm.cpp:1462]: CV_Error raises exception. The method would interrupt execution here instead of false result.
Alternative solution is just log message like
```
 CV_LOG_ERROR(NULL, "Training cases incompatible with nu parameter—try a lower value.");
```

**Comment by anandkaranubc** [comment]
Apologies for the oversight @asmorkalov. Have made the necessary changes :)

**Review by asmorkalov — APPROVED** [review]
