### PR TITLE
objdetect: qrcode_encoder: fix to missing timing pattern

### LINKED ISSUE #22029: QR Code Encoder: Timing pattern is broken if version >= 7.
##### System information (version)
- OpenCV => 3.4
- Operating System / Platform => ubuntu 22.04
- Compiler => gcc11

##### Detailed description

A part of timing Pattern is broken. (Same as left-bottom parts).

Timing pattern is used to determine version. So QRCodeDetector cannot decode it.

Left image is expected output. Right image is current output.

image

Reason
--------

Version information and timing pattern is overlapped when ( i== 6 or j == 6).

https://github.com/opencv/opencv/blob/3.4/modules/objdetect/src/qrcode_encoder.cpp#L976

```c++
    if (version_level >= 7)
    {
        for (int i = 0; i <= 6; i++) // (1) Version information
        {
            for (int j = version_size - 11; j <= version_size - 8; j++)
            {
                original.at<uint8_t>(i, j) = INVALID_REGION_VALUE;
                original.at<uint8_t>(j, i) = INVALID_REGION_VALUE;
            }
        }
    }
    for (int i = 0; i < version_size; i++) // (2) Timing pattern
    {
        for (int j = 0; j < version_size; j++)
        {
            if (original.at<uint8_t>(i, j) == INVALID_REGION_VALUE)
            {
                continue;
            }
            if ((i == 6 || j == 6))
            {
                original.at<uint8_t>(i, j) = INVALID_REGION_VALUE;
                if (!((i == 6) && (j - 7) % 2 == 0) &&
                    !((j == 6) && ((i - 7) % 2 == 0)))
                {
                    masked_data.at<uint8_t>(i, j) = 0;
                }
            }
```

##### Steps to reproduce

```c++
        expect_msg = "OpenCV";
        Mat qrimg;
        QRCodeEncoder::Params params;
        params.version = 7;
        Ptr<QRCodeEncoder> qrcode_enc = cv::QRCodeEncoder::create(params);
        qrcode_enc->encode(expect_msg, qrimg);

        cv::imwrite("qrimg.png", qrimg);
```

How to fix
------------

I feel changing the version information area is better.

```
-       for (int i = 0; i <= 6; i++)
+       for (int i = 0; i <= 5; i++)
```

##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
 - [X] I updated to the latest OpenCV version and the issue is still there
 - [X] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by Kumataro**
### Pull Request Readiness Checklist

fix #22029 

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- [X] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [X] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/objdetect/test/test_qrcode_encode.cpp [hunk 1]
```diff
@@ -430,4 +430,80 @@ TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, DISABLED_regression)
...
+        const int finder_width = 7;
+
+        const int timing_pos = white_margin + 6;
+        int i;
+
+        // Horizontal Check
+        // (1) White margin(Left)
+        for(i = 0; i < white_margin ; i++ )
+        {
+            CV_Assert( qrimg.at<uint8_t>(i, timing_pos) == 255 ) ;
```
Comment (alalek) [inline modules/objdetect/test/test_qrcode_encode.cpp:457]: > CV_Assert

Please use GoogleTest checks instead:

- `ASSERT_EQ(expected_value, actual_value)` << "i=" << i;

Please note about the order of parameters:
`ASSERT_EQ((uint8_t)255, qrimg.at<uint8_t>(i, timing_pos)) << "i=" << i;`

BTW, `ASSERT_` could be replaced by `EXPECT_` if there number of error messages is limited and small (we should not trash logs in case of failure).

File: modules/objdetect/test/test_qrcode_encode.cpp [hunk 2]
```diff
@@ -430,4 +430,80 @@ TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, DISABLED_regression)
...
 
+TEST(Objdetect_QRCode_Encode_Decode, regression_issue22029)
+{
+    const cv::String expect_msg = "OpenCV";
+    const int min_version = 1;
+    const int max_version = 40;
+
+    for ( int v = min_version ; v <= max_version ; v++ )
+    {
+        Mat qrimg;
```
Comment (alalek) [inline modules/objdetect/test/test_qrcode_encode.cpp:441]: Please add GoogleTest's scope identifier in "for" loop body (used for error messages):

```
SCOPED_TRACE(cv::format("version=%d", v));
```

**Review by alalek — COMMENTED** [review]
Thank you for the fix and especially for the test!

**Comment by Kumataro** [comment]
Thank you for your reviewing and comment. 

I re-pushed commits to fix it.

**Review by alalek — APPROVED** [review]
LGTM :+1:
