### PR TITLE
Fixed Compilation warnings | Issue #16336

### LINKED ISSUE #16336: Compilation warnings in opencv4/opencv2/core/types.hpp
##### System information (version)
- OpenCV = 4.2.0 compiled from source, and installed in /usr/local/
- Operating System / Platform = Linux - debian Buster
- Compiler = g++ 8.3.0

##### Detailed description

A compile warning error pop-ups in the core/types.hpp file
when using -Wdouble-promotion gcc compilation flag.

```
usr/local/include/opencv4/opencv2/core/types.hpp:1419:88:   required from here
/usr/local/include/opencv4/opencv2/core/types.hpp:1218:21: warning: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Wdouble-promotion]
     return (double)x*pt.x + (double)y*pt.y;
            ~~~~~~~~~^~~~~
/usr/local/include/opencv4/opencv2/core/types.hpp:1218:38: warning: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Wdouble-promotion]
     return (double)x*pt.x + (double)y*pt.y;
```

##### How to reproduce

Just compile the following file:
```
#include <opencv2/core/types.hpp>
int main(void)
{
	return 0;
}
```
with : g++ -Wall -Wdouble-promotion -o test test.cc -I/usr/local/include/opencv4/

##### How to fix
The problem is in the ddot template inside core/types.hpp line 1216. 
Code should be changed to:

```
template<typename _Tp> inline
double Point_<_Tp>::ddot(const Point_& pt) const
{
    return (double)x*(double)(pt.x) + (double)y*(double)(pt.y);
}

```

### PR DESCRIPTION
**Pull request by gapry**
### This pullrequest changes
resolves #16336

### Brief
The `main.cpp` will occur the compilation warnings. The reason is at the [modules/core/include/opencv2/core/types.hpp#L1218](https://github.com/opencv/opencv/blob/7fa7fa02264eb2faed638947a5673839da386743/modules/core/include/opencv2/core/types.hpp#L1218)

<cut/>

### Detailed description

Assume a file calls `main.cpp` as below
```
#include <opencv2/core/types.hpp>

int main(void) {
  return 0;
}
```

If the developer enables the `g++` flags `-Wall -Wdouble-promotion` in the compilation, `g++` will output the following warning messages and generate a ELF file.

```
warning: implicit conversion from ‘float’ to ‘double’ to match other operand of binary expression [-Wdouble-promotion]
 1218 |     return (double)x*pt.x + (double)y*pt.y;
      |            ~~~~~~~~~^~~~~

warning: implicit conversion from ‘float’ to ‘double’ to match other operand of binary expression [-Wdouble-promotion]
 1218 |     return (double)x*pt.x + (double)y*pt.y;
      |                             ~~~~~~~~~^~~~~
```

If the developer enables the `g++` flags `-Wall -Werror -Wdouble-promotion` in the compilation, `g++` will output the same warning messages but can't generate a ELF file.

### CODE REVIEW

**Comment by gapry** [comment]
cc @bduclaux

File: modules/core/include/opencv2/core/types.hpp [hunk 1]
```diff
@@ -1215,7 +1215,7 @@ _Tp Point_<_Tp>::dot(const Point_& pt) const
 template<typename _Tp> inline
 double Point_<_Tp>::ddot(const Point_& pt) const
 {
-    return (double)x*pt.x + (double)y*pt.y;
+    return (double)x*(double)(pt.x) + (double)y*(double)(pt.y);
```
Comment (dkurt) [inline modules/core/include/opencv2/core/types.hpp]: Will `(double)pt.x*x` work?

**Comment by bduclaux** [comment]
Sounds good !

File: modules/core/include/opencv2/core/types.hpp (hunk 1 above)
Comment (gapry) [inline modules/core/include/opencv2/core/types.hpp]: Dear @bduclaux 

Although the patch can fix the issue, the casting can achieve with `static_cast`. 

Here, it's the code. 
```
return static_cast<double>(x)*static_cast<double>(pt.x) + 
  static_cast<double>(y)*static_cast<double>(pt.y);
```

I think it's better. Do you agree ?

Comment (bduclaux) [reply modules/core/include/opencv2/core/types.hpp]: Yes, static_cast is indeed much better. 
Btw, there are tons of C-style cast in the code, and it will take months to fully check / rewrite them. Not a problem, unless the compiler emits warnings like above !
Thanks !

**Comment by alalek** [comment]
Thank you for the contribution!

This patch should [go](https://github.com/opencv/opencv/wiki/How_to_contribute#faq) into [3.4 branch](https://github.com/opencv/opencv/wiki/Branches) first. We will merge changes from 3.4 into master regularly (weekly/bi-weekly).

So, please:
- change "base" branch of this PR: master => 3.4 (use "Edit" button near PR title)
- rebase your commits from master onto 3.4 branch. For example:
    `git rebase -i --onto upstream/3.4 upstream/master`
    (check list of your commits, save and quit (Esc + "wq" + Enter)
    where `upstream` is configured by following [this GitHub guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and fetched (`git fetch upstream`).
- push rebased commits into source branch of your fork (with `--force` option)

Note: no needs to re-open PR, apply changes "inplace".

**Comment by gapry** [comment]
@alalek Thank you for your guide. I've done it. 

After that, I notice that all checks have passed but this branch has conflicts that must be resolved. The conflicting files is `modules/objdetect/include/opencv2/objdetect.hpp`

Is it my fault ?

**Comment by gapry** [comment]
@alalek Thank you for your guide. I've done it.
