### PR TITLE
imgcodecs: gif: support animated gif without loop

### LINKED ISSUE #26970: imgcodecs: gif: support animated gif without loop
### System Information

OpenCV version: 4.x
Operating System / Platform: Ubuntu 24.04 
Compiler & compiler version: GCC 13.2.0

### Detailed description

We can expect `IMWRITE_GIF_LOOP=1` means to display all frames only once.
But it will show 2 times in Chromium and Firefox.

This had been discussed in the webkit and chrome bug tracking system.
- https://bugs.webkit.org/show_bug.cgi?id=183153- 
- https://issues.chromium.org/issues/40459899

When we drop the Netscape Application Block(NAB), we can get animated GIF without loop.

### Steps to reproduce

```cpp
typedef testing::TestWithParam<int> Imgcodecs_Gif_GIF_LOOP;
TEST_P(Imgcodecs_Gif_GIF_LOOP, imencode)
{
    int loopCount = GetParam();

    vector<int> param;
    param.push_back(cv::IMWRITE_GIF_LOOP);
    param.push_back(loopCount);

    vector<cv::Mat> src;
    for(int n = 1; n <= 5 ; n ++ )
    {
        cv::Mat frame(64, 64, CV_8UC3, cv::Scalar::all(0));
        cv::putText(frame, cv::format("%d", n), cv::Point(0,64), cv::FONT_HERSHEY_PLAIN, 4.0, cv::Scalar::all(255));
        src.push_back(frame);
    }

    bool ret = false;
    vector<uint8_t> buf;
#if 0
    // To output gif image for test.
    EXPECT_NO_THROW(ret = imwrite(cv::format("gif_loop-%d.gif", loopCount), src, param));
    EXPECT_TRUE(ret);
#endif
    EXPECT_NO_THROW(ret = imencode(".gif", src, buf, param));
    EXPECT_TRUE(ret);

    std::vector<uint8_t> netscape = {'N','E','T','S','C','A','P','E'};
    auto pos = std::search(buf.begin(), buf.end(), netscape.begin(), netscape.end());
    if(loopCount < 0) {
        EXPECT_EQ(pos, buf.end()) << "Netscape Applicatioin Block should not be included if IMWRITE_GIF_LOOP < 0";
    } else {
        EXPECT_NE(pos, buf.end()) << "Netscape Applicatioin Block should be included if IMWRITE_GIF_LOOP >= 0";
    }
}

INSTANTIATE_TEST_CASE_P(/*nothing*/,
    Imgcodecs_Gif_GIF_LOOP,
    testing::Values(
        -2,
        -1, // Minimum Limit, no-loop
         0, // Default, loop-forever
         1, // Positive minimum value
         2,
     65534,
     65535, // Maximum Limit
     65536
    )
);
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by Kumataro**
Close #26970

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@sturkmen72 Is the Looping option relevant to APNG, AVIF, etc? M.b. make it generic.

**Comment by sturkmen72** [comment]
> @sturkmen72 Is the Looping option relevant to APNG, AVIF, etc? M.b. make it generic.
it is possible adding enums
```
IMWRITE_ANIMATION_LOOP = IMWRITE_GIF_LOOP;
IMWRITE_ANIMATION_SPEED =IMWRITE_GIF_SPEED;
```
and add revelant code to other encoders

**Comment by sturkmen72** [comment]
imho
```
enums
IMWRITE_ANIMATION_LOOP = 1024
IMWRITE_ANIMATION_SPEED = ?
```
will be useful if these properties wanted to be write with `imwrite `and `imwritemulti ` functions

up to you dropping `IMWRITE_GIF_LOOP` if `IMWRITE_ANIMATION_LOOP` will be defined instead

**Comment by sturkmen72** [comment]
there is also `IMWRITE_AVIF_SPEED` i should check for what functionality

**Comment by sturkmen72** [comment]
i think IMWRITE_GIF_SPEED is unfunctional now ( overlooked when adopted gif encoder to imwriteanimation )

**Comment by Kumataro** [comment]
IMO, `IMWRITE_GIF_*` should be refactored.

- `IMWRITE_GIF_SPEED` sets duration between frames. however `IMWRITE_AVIF_SPEED` changes blance of  compress time and data size. They have similar enum names, but their purposes are different.
- `IMWRITE_GIF_QUALITY` and `IMWRITE_GIF_DITHER ` are releated quality of output GIFs, It should be merge into one parameter. 
- `IMWRITE_GIF_TRANSPARENCY` is hard to image what it effects. Can we use this parameter ?
- `IMWRITE_GIF_COLORTABLE` is hard to image what it effets too.  Need to introduce parameter specified enum, `GIF_WITHOUT_LOCALTABLE` or `GIF_WITH_LOCALTABLE`. But it also hard to use it ....

**Comment by sturkmen72** [comment]
i vote for 
dropping `IMWRITE_GIF_LOOP `and `IMWRITE_GIF_SPEED ` (use writeanimation)

File: modules/imgcodecs/test/test_gif.cpp [hunk 1]
```diff
@@ -366,6 +366,56 @@ TEST(Imgcodecs_Gif, encode_IMREAD_GRAYSCALE) {
...
+    EXPECT_NO_THROW(ret = imwrite(cv::format("gif_loop-%d.gif", loopCount), src, param));
+    EXPECT_TRUE(ret);
+#endif
+    EXPECT_NO_THROW(ret = imencode(".gif", src, buf, param));
+    EXPECT_TRUE(ret);
+
+    std::vector<uint8_t> netscape = {'N','E','T','S','C','A','P','E'};
+    auto pos = std::search(buf.begin(), buf.end(), netscape.begin(), netscape.end());
+    if(loopCount < 0) {
+        EXPECT_EQ(pos, buf.end()) << "Netscape Applicatioin Block should not be included if IMWRITE_GIF_LOOP < 0";
```
Comment (sturkmen72) [inline modules/imgcodecs/test/test_gif.cpp:399]: Netscape Application

Comment (Kumataro) [reply modules/imgcodecs/test/test_gif.cpp]: I fixed it, thank you for your comment !

**Comment by Kumataro** [comment]
I dropped `IMWRITE_GIF_SPEED` and `IMWRITE_GIF_LOOP`.

**Comment by asmorkalov** [comment]
@Kumataro I restored constants and added warning.
@sturkmen72 @vrabaud please take a look again.

**Comment by Kumataro** [comment]
@asmorkalov Thank you to resolve my worry about  `IMWRITE_GIF_SPEED` and `IMWRITE_GIF_LOOP`. I agree with you !!

File: modules/imgcodecs/include/opencv2/imgcodecs.hpp [hunk 2]
```diff
@@ -248,10 +248,20 @@ It provides support for looping, background color settings, frame timing, and fr
...
+    /*! @note (GIF) When N is set, whether it is displayed N or N+1 times depends on the implementation of the user application.
+              Animated GIF with loop is extended with the Netscape Application Block(NAB), which it not a part of GIF89a specification.
+              See https://en.wikipedia.org/wiki/GIF#Animated_GIF .
+              This loop times behaviour has not been documented clearly.
+     */
     CV_PROP_RW int loop_count;
     //! Background color of the animation in BGRA format.
     CV_PROP_RW Scalar bgcolor;
     //! Duration for each frame in milliseconds.
+    /*! @note (GIF) Due to file format limitation
```
Comment (sturkmen72) [inline modules/imgcodecs/include/opencv2/imgcodecs.hpp:260]: please consider
```
    /*! @note (GIF) Due to file format limitation
     *  - Durations must be multiples of 10 milliseconds. Any provided value will be rounded down to the nearest 10ms (e.g., 88ms → 80ms).
     *  - 0ms(or smaller than expected in user application) duration may cause undefined behavior, e.g. it is handled with default duration.
     *  - Over 65535 milliseconds duration is not supported.
     */
```

Comment (Kumataro) [reply modules/imgcodecs/include/opencv2/imgcodecs.hpp:260]: This example is helpful to know about duration about 10ms unit, thank you for your comment !

> - Over 65535 milliseconds duration is not supported.

For GIF89a specification, I think it seems to have to change from `655350`.

https://www.w3.org/Graphics/GIF/spec-gif89a.txt

> 23. Graphic Control Extension.
> vii) Delay Time - If not 0, this field specifies the number of
> hundredths (1/100) of a second to wait before continuing with the
> processing of the Data Stream. The clock starts ticking immediately
> after the graphic is rendered. This field may be used in
> conjunction with the User Input Flag field.

We can store`Delay Time` value as 16 bit unsigned integer with 10ms unit, so a range from 10ms to 655350ms are valid. 

```diff
        // GIF file stores duration in 10ms unit.
        const int frameDelay10ms = cvRound(frameDelay / 10);
        CV_LOG_IF_WARNING(NULL, (frameDelay10ms == 0),
                          cv::format("frameDelay(%d) is rounded to 0ms, its behaviour is user application depended.", frameDelay));
        CV_CheckLE(frameDelay10ms, 65535, "It requires to be stored in WORD");
```

Both 65535ms(about 1min)  and 655350ms(about 11min) are a very long durations as animation frames. 
So this restriction is not expected to affect user experience.

To make compatibility with other codecs, should I limit with `CV_CheckLE(frameDelay, 65535, "Unsupported duration")` ?

Comment (Kumataro) [reply modules/imgcodecs/include/opencv2/imgcodecs.hpp:272]: Thank you for reply ! I fixed it and to use "milliseconds` instead of `millseconds`.

**Review by asmorkalov — APPROVED** [review]

**Review by asmorkalov — APPROVED** [review]

**Comment by asmorkalov** [comment]
@vrabaud Do you have any notes?

File: modules/imgcodecs/src/grfmt_gif.cpp [hunk 3]
```diff
@@ -436,11 +437,18 @@ bool GifDecoder::getFrameCount_() {
             // Application Extension need to be handled for the loop count
             if (extension == 0xFF) {
                 int len = m_strm.getByte();
+                bool isFoundNetscape = false;
                 while (len) {
-                    // TODO: In strictly, Application Identifier and Authentication Code should be checked.
-                    if (len == 3) {
+                    if (len == 11) {
+                        String app_auth_code(len, ' ');
```
Comment (vrabaud) [inline modules/imgcodecs/src/grfmt_gif.cpp:443]: Please use C++:
```
std::string app_auth_code(len);
m_strm.getBytes(const_cast<void*>(static_cast<const void*>(app_auth_code.c_str())), len);
isFoundNetscape = (app_auth_code == "NETSCAPE2.0");
```

File: modules/imgcodecs/include/opencv2/imgcodecs.hpp [hunk 4]
```diff
@@ -260,10 +260,20 @@ It provides support for looping, background color settings, frame timing, and fr
 struct CV_EXPORTS_W_SIMPLE Animation
 {
     //! Number of times the animation should loop. 0 means infinite looping.
+    /*! @note (GIF) When N is set, whether it is displayed N or N+1 times depends on the implementation of the user application.
+              Animated GIF with loop is extended with the Netscape Application Block(NAB), which it not a part of GIF89a specification.
+              See https://en.wikipedia.org/wiki/GIF#Animated_GIF .
+              This loop times behaviour has not been documented clearly.
```
Comment (vrabaud) [inline modules/imgcodecs/include/opencv2/imgcodecs.hpp:266]: For more context: https://issues.chromium.org/issues/40459899 . WebP had the same problem where 1 loop coould not happen: https://groups.google.com/a/webmproject.org/g/webp-discuss/c/rJ2a0j1BNQI/m/XXqK918ZEQAJ

File: modules/imgcodecs/src/grfmt_gif.cpp [hunk 5]
```diff
@@ -436,11 +437,18 @@ bool GifDecoder::getFrameCount_() {
...
+                        m_strm.getBytes(const_cast<void*>(static_cast<const void*>(app_auth_code.data())), len);
+                        isFoundNetscape = (memcmp(app_auth_code.data(), "NETSCAPE2.0", len) == 0);
+                    }  else if ( (len == 3) && (isFoundNetscape) ) {
```
Comment (vrabaud) [inline modules/imgcodecs/src/grfmt_gif.cpp:446]: Shouldn't there be an interpretation if `!isFoundNetscape` too ?

Comment (Kumataro) [reply modules/imgcodecs/src/grfmt_gif.cpp]: Thank you for comment, I fixed it to show log message when it is unexpected condition.

**Review by vrabaud — APPROVED** [review]
