### PR TITLE
cudaarithm: use only even number for inplace flip

### LINKED ISSUE #18347: cudaarithm: inplace version of NPP flip fails with odd number ROI
##### System information (version)

- OpenCV => recent 3.4 (8cb7eae5c9) / master (3b00ee2afb4176a5a45def7939b816d3a8914c00)
- Operating System / Platform => Jetson Nano/TX1/TX2/XavierNX
- Compiler => GCC 5.4.0, GCC 7.5.0
- CUDA => 10.0 (Nano) 10.2 (XavierNX) 8.0 (TX1,TX2)

##### Detailed description

This issue was originally found by @nglee 
The in-place version of mirror was enabled in #17863 
Unfortunately, the test intermittently fails.

```
./opencv_test_cudaarithm
(snip)
[ RUN      ] CUDA_Arithm/Flip.AccuracyInplace/82, where GetParam() = (NVIDIA Tegra X1, 113x113, 8UC3, FLIP_Y, whole matrix)
/home/nvidia/opencv-fork/modules/cudaarithm/test/test_core.cpp:292: Failure
The max difference between matrices "dst_gold" and "srcDst" is 243 at (56, 102), which exceeds "0.0", where "dst_gold" at (56, 102) evaluates to (84, 129, 2), "srcDst" at (56, 102) evaluates to (147, 171, 245), "0.0" evaluates to 0
[  FAILED  ] CUDA_Arithm/Flip.AccuracyInplace/82, where GetParam() = (NVIDIA Tegra X1, 113x113, 8UC3, FLIP_Y, whole matrix) (2 ms)
(snip)
[  PASSED  ] 11169 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] CUDA_Arithm/Flip.AccuracyInplace/82, where GetParam() = (NVIDIA Tegra X1, 113x113, 8UC3, FLIP_Y, whole matrix)
[  FAILED  ] CUDA_Arithm/Flip.AccuracyInplace/88, where GetParam() = (NVIDIA Tegra X1, 113x113, 8UC4, FLIP_Y, whole matrix)
[  FAILED  ] CUDA_Arithm/Flip.AccuracyInplace/106, where GetParam() = (NVIDIA Tegra X1, 113x113, 16UC4, FLIP_Y, whole matrix)
[  FAILED  ] CUDA_Arithm/Flip.AccuracyInplace/142, where GetParam() = (NVIDIA Tegra X1, 113x113, 32FC4, FLIP_Y, whole matrix)

 4 FAILED TESTS
```

I was able to reproduce it separate from OpenCV, so the cause came from NPP
I contacted with NPP team, and I got reply that
- There was a synchronization issue in in-place version
- The NPP team chose not to fix this, but instead, in the future release, this in-place function will explicitly return an error value `NPP_SIZE_ERROR` when width and/or height is odd number
I think I need to add the same limit in the `cv::cuda::flip`

I'll send a patch shortly

##### Steps to reproduce
run `./opencv_test_cudaarithm`

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [x] I updated to latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by tomoaki0705**
resolves #18347 

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

<cut/>

```
force_builders=Custom
buildworker:Custom=linux-4
build_image:Custom=ubuntu-cuda:18.04
```

### CODE REVIEW

**Review by mshabunin — APPROVED** [review]

File: modules/cudaarithm/test/test_core.cpp [hunk 1]
```diff
@@ -281,6 +281,8 @@ CUDA_TEST_P(Flip, Accuracy)
 
 CUDA_TEST_P(Flip, AccuracyInplace)
 {
+    size.width  = (size.width  >> 1) << 1; // in-place version only accepts even number
+    size.height = (size.height >> 1) << 1; // in-place version only accepts even number
```
Comment (asmorkalov) [inline modules/cudaarithm/test/test_core.cpp:285]: I propose to split tests for in-place and general cases and instantiate in-place cases with even size. It's more obvious behavior.

**Review by asmorkalov — CHANGES_REQUESTED** [review]

File: modules/cudaarithm/test/test_core.cpp (hunk 1 above)
Comment (mshabunin) [reply modules/cudaarithm/test/test_core.cpp:285]: @asmorkalov , do you mean create `DIFFERENT_EVEN_SIZES` list [here](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/ts/include/opencv2/ts/cuda_test.hpp#L212) and instantiate inplace tests separately? I think it would make this test unnecessary complex.

Comment (tomoaki0705) [reply modules/cudaarithm/test/test_core.cpp:285]: That's something debatable.  I first had the same feeling with @asmorkalov , since the log shows `113x113` which is not correct.
Then I saw the [the line](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/ts/include/opencv2/ts/cuda_test.hpp#L212) that @mshabunin pointed, and thought the same thing. "It's only a single test which uses `DIFFERENT_EVEN_SIZES` "
Merging the idea will lead me to add single define in the `test_core.cpp` rather in `cuda_test.hpp`, but I need someone as an arbitor.

Comment (tomoaki0705) [reply modules/cudaarithm/test/test_core.cpp:285]: Sorry, but I again changed my mind.
I thought it would be simple, but it's really making a another copy of flip test code just for the in-place version.
Now, there are one `Flip` test, but asmorkalov suggestion is to create `Flip` and `Flip_inplace` test case, which I don't prefer.
Can I keep the current implementation as-is, since it'll make things much easier ?

File: modules/cudaarithm/src/core.cpp [hunk 2]
```diff
@@ -163,8 +163,10 @@ void cv::cuda::flip(InputArray _src, OutputArray _dst, int flipCode, Stream& str
 
     _dst.create(src.size(), src.type());
     GpuMat dst = getOutputMat(_dst, src.size(), src.type(), stream);
+    if (src.data == dst.data && ((src.cols & 1) == 1 || (src.rows & 1) == 1))
+        CV_Error(Error::BadROISize, "In-place version of flip only accepts even width/height");
 
-    if (src.refcount != dst.refcount)
+    if (src.data != dst.data)
```
Comment (alalek) [inline modules/cudaarithm/src/core.cpp:169]: BTW, `refcount` is a pointer to reference counter which is allocated with underlying buffer/data and it is shared between GpuMats.
At least, it is more reliable check in case of image ROIs.

But it doesn't work if `refcount == NULL` (non-managed buffers).

Better check should compare both values:
```
bool isInplace = (src.data == dst.data) || (src.refcount == dst.refcount);
```
(however there are still some non-covered cases)

**Review by alalek — APPROVED** [review]
Thank you for contribution!

File: modules/cudaarithm/test/test_core.cpp (hunk 1 above)
Comment (mshabunin) [reply modules/cudaarithm/test/test_core.cpp:285]: Another idea is to keep sizes intact but add bad args handling to the test:
```.cpp
if (/* size is not even */)
{
    EXPECT_THROW(...);
    return;
}
// current test body
```
