### PR TITLE
Fix android libc++ build

### LINKED ISSUE #6511: Targeting Android clang/c++stl not possible.
I'm sure the problem is in `android.toolchain.cmake`. I could edit that file to *make* it work, but I don't know the backward compatibility requirements or future plans of this project regarding Android support.

### System information 
- OpenCV version: 3.1.0 6e5e5d87df4212b91839704ff153ec6d8f2549f6
- Host OS: Mac OS 10.11.4
- Target OS: Android 6.0
- Compiler & CMake: clang 3.8 & CMake 3.5.0
- Android SDK: 21
- NDK 12

### Problem area
- Build configuration using clang and c++stl_shared.

### Expected behaviour
Resulting .so files only depend on libc++.so

### Actual behaviour
Cannot link libopencv-core.so because of missing symbols.

Note the inclusion of `libstdc++.a` and `libsupc++.a` at the end of the link command and the omission of `libc++.so`.

### Steps to reproduce the issue
Standalone toolchain command:
```
$ANDROID_NDK/build/tools/make-standalone-toolchain.sh \
--use-llvm \
--stl=libc++ \
--platform=android-21 \
--install-dir=tc_arm64 \
--arch=arm64 \
--toolchain=aarch64-linux-android-clang
```

Cmake command line:
```
cmake \
-DANDROID_TOOLCHAIN_NAME=standalone-clang \
-DANDROID_STANDALONE_TOOLCHAIN=/Users/kg/dev/opencv-3.1.0/build/tc_arm64 \
-DANDROID_ABI=arm64-v8a \
-DBUILD_SHARED_LIBS=ON \
-DANDROID_NATIVE_API_LEVEL=android-21 \
-DANDROID_STL=c++_shared \
-DBUILD_ANDROID_EXAMPLES=OFF \
-DINSTALL_PYTHON_EXAMPLES=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_TESTS=OFF \
-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
-DANDROID_STL_FORCE_FEATURES=ON \
-DCMAKE_TOOLCHAIN_FILE=../../opencv/platforms/android/android.toolchain.cmake $@ ../../opencv
```

The link command and first two errors from `make VERBOSE=1`:
```
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/bin/clang38++  -fPIC -target aarch64-none-linux-android -Qunused-arguments --sysroot=/Users/kg/dev/opencv-3.1.0/build/tc_arm64/sysroot -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Xclang -mnoexecstack    -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Qunused-arguments -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -O3 -DNDEBUG  -DNDEBUG  -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname,libopencv_core.so -o ../../lib/arm64-v8a/libopencv_core.so CMakeFiles/opencv_core.dir/src/algorithm.cpp.o CMakeFiles/opencv_core.dir/src/alloc.cpp.o CMakeFiles/opencv_core.dir/src/arithm.cpp.o CMakeFiles/opencv_core.dir/src/array.cpp.o CMakeFiles/opencv_core.dir/src/command_line_parser.cpp.o CMakeFiles/opencv_core.dir/src/conjugate_gradient.cpp.o CMakeFiles/opencv_core.dir/src/convert.cpp.o CMakeFiles/opencv_core.dir/src/copy.cpp.o CMakeFiles/opencv_core.dir/src/cuda_gpu_mat.cpp.o CMakeFiles/opencv_core.dir/src/cuda_host_mem.cpp.o CMakeFiles/opencv_core.dir/src/cuda_info.cpp.o CMakeFiles/opencv_core.dir/src/cuda_stream.cpp.o CMakeFiles/opencv_core.dir/src/datastructs.cpp.o CMakeFiles/opencv_core.dir/src/directx.cpp.o CMakeFiles/opencv_core.dir/src/downhill_simplex.cpp.o CMakeFiles/opencv_core.dir/src/dxt.cpp.o CMakeFiles/opencv_core.dir/src/gl_core_3_1.cpp.o CMakeFiles/opencv_core.dir/src/glob.cpp.o CMakeFiles/opencv_core.dir/src/kmeans.cpp.o CMakeFiles/opencv_core.dir/src/lapack.cpp.o CMakeFiles/opencv_core.dir/src/lda.cpp.o CMakeFiles/opencv_core.dir/src/lpsolver.cpp.o CMakeFiles/opencv_core.dir/src/mathfuncs.cpp.o CMakeFiles/opencv_core.dir/src/mathfuncs_core.cpp.o CMakeFiles/opencv_core.dir/src/matmul.cpp.o CMakeFiles/opencv_core.dir/src/matop.cpp.o CMakeFiles/opencv_core.dir/src/matrix.cpp.o CMakeFiles/opencv_core.dir/src/matrix_decomp.cpp.o CMakeFiles/opencv_core.dir/src/merge.cpp.o CMakeFiles/opencv_core.dir/src/ocl.cpp.o CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdblas.cpp.o CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_clamdfft.cpp.o CMakeFiles/opencv_core.dir/src/opencl/runtime/opencl_core.cpp.o CMakeFiles/opencv_core.dir/src/opengl.cpp.o CMakeFiles/opencv_core.dir/src/out.cpp.o CMakeFiles/opencv_core.dir/src/parallel.cpp.o CMakeFiles/opencv_core.dir/src/parallel_pthreads.cpp.o CMakeFiles/opencv_core.dir/src/pca.cpp.o CMakeFiles/opencv_core.dir/src/persistence.cpp.o CMakeFiles/opencv_core.dir/src/rand.cpp.o CMakeFiles/opencv_core.dir/src/split.cpp.o CMakeFiles/opencv_core.dir/src/stat.cpp.o CMakeFiles/opencv_core.dir/src/stl.cpp.o CMakeFiles/opencv_core.dir/src/system.cpp.o CMakeFiles/opencv_core.dir/src/tables.cpp.o CMakeFiles/opencv_core.dir/src/types.cpp.o CMakeFiles/opencv_core.dir/src/umatrix.cpp.o CMakeFiles/opencv_core.dir/src/va_intel.cpp.o CMakeFiles/opencv_core.dir/opencl_kernels_core.cpp.o  -L/Users/kg/dev/opencv-3.1.0/build/arm_so/install/libs/arm64-v8a -lz -ldl -lm -llog  "/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libstdc++.a" "/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libsupc++.a"
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libsupc++.a(eh_catch.o): In function `std::uncaught_exception()':
/Volumes/Android/buildbot/src/android/master-ndk/toolchain/gcc/gcc-4.9/libstdc++-v3/libsupc++/eh_catch.cc:138: multiple definition of `std::uncaught_exception()'
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libstdc++.a(exception.o):/Volumes/Android/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/exception.cpp:113: first defined here
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libsupc++.a(new_handler.o):(.rodata._ZSt7nothrow+0x0): multiple definition of `std::nothrow'
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libstdc++.a(new.o):(.rodata+0x0): first defined here
/Users/kg/dev/opencv-3.1.0/build/tc_arm64/aarch64-linux-android/lib/libstdc++.a(locale.o): In function `std::__ndk1::moneypunct_byname<char, false>::init(char const*)':
/Volumes/Android/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/locale.cpp:5928: undefined reference to `typeinfo for std::runtime_error'
/Volumes/Android/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/locale.cpp:5928: undefined reference to `std::runtime_error::~runtime_error()'
/Volumes/Android/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/locale.cpp:5928: undefined reference to `typeinfo for std::runtime_error'
/Volumes/Android/buildbot/src/android/master-ndk/ndk/sources/cxx-stl/llvm-libc++/libcxx/src/locale.cpp:5928: undefined reference to `std::runtime_error::~runtime_error()'
```

### PR DESCRIPTION
**Pull request by guycook**
resolves #6511

### This pullrequest changes

Presently, when using `cmake -DANDROID_STL=c++_shared` the build completes successfully but you can't actually use the generated artefacts in an android project that uses clang + libc++ due to linker errors. The changes in this PR resolve that by using the correct std library headers.

### CODE REVIEW

**Comment by vpisarev** [comment]
@mshabunin, could you please review it?

**Comment by alalek** [comment]
@guycook What Android NDK do you use?

**Comment by guycook** [comment]
@alalek I've tested and got it working with two separate ndk versions:

* **r12_b-1** sourced from https://aur.archlinux.org/packages/android-ndk/
* **r10e-rc4** as bundled with webrtc rev 979c268830 (this is why I need clang/libc++ btw)

To use the built library I'm using Android Studio + gradle-experimental:0.8.0-beta2 and a build script that looks like:

```
model {
    android {
        ndk {
            toolchain "clang"
            stl "c++_shared"
            abiFilters.add("armeabi-v7a")
            cppFlags.add("-std=c++11")
            cppFlags.add("-DNDEBUG")
            cppFlags.add("-DANDROID")
            cppFlags.add("-I" + localProperty('opencv.native') + "/jni/include")
            ldFlags.add("-L" + localProperty('opencv.native') + "/libs/armeabi-v7a")
            ldFlags.add("-L" + localProperty('opencv.native') + "/3rdparty/libs/armeabi-v7a")
            ldLibs.add("opencv_core")
            ldLibs.add("tegra_hal")
            ldLibs.add("tbb")
            ldLibs.add("zlib")
        }
    }
}
```

The relevant cmake flags are:
```
ANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-clang3.5
ANDROID_STL=c++_shared
ANDROID_ABI="armeabi-v7a"
ANDROID_NATIVE_API_LEVEL=21
CMAKE_C_FLAGS_RELEASE="-Os -DNDEBUG -DANDROID -fvisibility=hidden -ffunction-sections -fstack-protector-all"
CMAKE_CXX_FLAGS_RELEASE="-Os -DNDEBUG -DANDROID -fvisibility=hidden -ffunction-sections -fstack-protector-all -fvisibility-inlines-hidden"
ENABLE_PRECOMPILED_HEADERS=OFF
CMAKE_TOOLCHAIN_FILE=platforms/android/android.toolchain.cmake
```

File: 3rdparty/carotene/src/pyramid.cpp [hunk 1]
```diff
@@ -40,6 +40,7 @@
 #include "common.hpp"
 
 #include <vector>
+#include <cstdlib>
```
Comment (mshabunin) [inline 3rdparty/carotene/src/pyramid.cpp]: This statement should be moved to "comon.hpp", because some other source files in Carotene need it too (e.g. _canny.cpp_).

**Comment by mshabunin** [comment]
Thank you! Please squash both commits into one and we will merge it.

**Comment by guycook** [comment]
@mshabunin Cool, I think that's done now (I haven't ever squashed before)

**Comment by mshabunin** [comment]
:+1:
