### PR TITLE
Fix findContours crash for very large images (v2.4)

### LINKED ISSUE #7449: findContours crashes on very large images
##### System information (version)
- OpenCV => 2.4.13 (official binaries)
- Operating System / Platform => Windows, 64-bit
- Compiler => Visual Studio 2013, Update 4

##### Detailed description
Function findContours crashes my program for very large images (e.g. 79925 * 49955), apparently regardless of the image contents.

##### Steps to reproduce
Code:

    cv::Mat largeImage(79925, 49955, CV_8UC1);
    largeImage.setTo(0);
    
    // this is not really even needed to reproduce
    cv::circle(largeImage, cv::Point(largeImage.cols, largeImage.rows), 1000, 255, CV_FILLED);

    std::vector<std::vector<cv::Point>> contours;
    cv::findContours(largeImage, contours, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_SIMPLE);

The last line crashes the program. Works great for smaller images (didn't find the exact limit though).

I don't think I'm running out of memory (have multiple gigabytes left), and even if I was, it'd be better to receive an exception of course.

Can anyone reproduce this?

Haven't tried on version 3 yet.

### PR DESCRIPTION
**Pull request by reunanen**
resolves #7449 in 2.4

Cast step to size_t in order to avoid integer overflow when processing very large images.

### CODE REVIEW

**Comment by sovrasov** [comment]
:+1:

File: modules/imgproc/src/contours.cpp [hunk 1]
```diff
@@ -284,10 +284,13 @@ cvStartFindContours( void* _img, CvMemStorage* storage,
                                           scanner->cinfo_storage );
     }
 
+    assert(step >= 0);
+    assert(size.height >= 1);
```
Comment (alalek) [inline modules/imgproc/src/contours.cpp]: `assert` is not used in OpenCV code, please use CV_Assert instead.

Comment (reunanen) [inline modules/imgproc/src/contours.cpp]: In fact the vanilla `assert` is used, even in this file. But changed mine to `CV_Assert`.

Comment (alalek) [inline modules/imgproc/src/contours.cpp]: Thanks!
Yep, there is still a lot of legacy code.
I hope CV_Assert will become more useful sometimes and will provide more information, like stack traces.
