### PR TITLE
core: exp/log workaround for MSVS

### LINKED ISSUE #7795: Internal compiler error in mathfuncs_core.cpp(1239) when enabling AVX
##### System information (version)
- OpenCV => Newest GitHub master from today
- Operating System / Platform =>Windows 8.1 64 Bit
- Compiler => Visual Studio 2015 Update 3

##### Detailed description
I get an internal compiler error (ICE) when building opencv_core in Release mode, on above system.

> 1>c:\opencv\opencv-git\opencv\modules\core\src\mathfuncs_core.cpp(1239): fatal error C1001: An internal error has occurred in the compiler.

The error appears as soon as you enable `ENABLE_AVX`. Disabling AVX and it works again. Debug build works fine as well.
My CPU supports AVX (i7-4700MQ).

##### Steps to reproduce

Compile opencv_core from GitHub master with `ENABLE_AVX` on VS2015 update 3, 64-bit, Release build.

Disabling IPP didn't help. I tried disabling pretty much everything else too (OpenMP, OpenCL, etc.) and it didn't help.

### PR DESCRIPTION
**Pull request by alalek**
resolves #7795

### CODE REVIEW

File: modules/core/src/mathfuncs_core.cpp [hunk 1]
```diff
@@ -373,6 +373,62 @@ void sqrt64f(const double* src, double* dst, int len)
         dst[i] = std::sqrt(src[i]);
 }
 
+// Workaround for ICE in MSVS 2015 update 3 (issue #7795)
+// CV_AVX is not used here, because generated code is faster in non-AVX mode.
+// (tested with disabled IPP on i5-6300U)
+#if (defined _MSC_VER && _MSC_VER >= 1900)
```
Comment (patrikhuber) [inline modules/core/src/mathfuncs_core.cpp]: I think you can add a `&& _MSC_VER < 1910` since this bug doesn't occur in VS2017RC, it looks like MS fixed the ICE.

Comment (alalek) [inline modules/core/src/mathfuncs_core.cpp]: There is same reason as avoiding "&& CV_AVX": this "workaround" is faster.
You can try to build in MSVS 2017RC OpenCV without IPP/OpenCL and run this perf test with and without workaround:
```
.\bin\Release\opencv_perf_core.exe --gtest_filter=*Exp*/4:*Log*/4
```

Comment (patrikhuber) [inline modules/core/src/mathfuncs_core.cpp]: I managed to run it, but it says zero tests? `Running 0 tests from 0 test cases.`

Comment (alalek) [inline modules/core/src/mathfuncs_core.cpp]: Sorry, you need to build with OpenCL (only "OCL" (read as "UMat") tests measure performance for exp/log and [they are disabled if there no OpenCL](https://github.com/opencv/opencv/blob/300f92397e93fab638944630b37257a4e2f4a616/modules/core/test/ocl/test_arithm.cpp#L47)). You need to disable OpenCL during runtime: set environment variable `OPENCV_OPENCL_DEVICE=disabled`.

Also you can try to replace mentioned line to `#if 1` temporary and build without OpenCL.

Comment (alalek) [inline modules/core/src/mathfuncs_core.cpp]: Sure.

**Comment by alalek** [comment]
:+1:
