### PR TITLE
Core fix mat matx mult

### LINKED ISSUE #13926: Matrix multiplication between Mat and Matx
There is an issue when doing a matrix multiplication between a `Mat` and a `Matx`.

Code:

```
#include <opencv2/opencv.hpp>
using namespace cv;

int main()
{
    Mat M1 = (Mat_<double>(4,4,CV_64FC1) << 1, 2, 3, 4,
                                            5, 6, 7, 8,
                                            9, 10, 11, 12,
                                            13, 14, 15, 16);

    Matx44d M2(1, 2, 3, 4,
               5, 6, 7, 8,
               9, 10, 11, 12,
               13, 14, 15, 16);

    std::cout << "M1*M1:\n" << M1*M1 << std::endl; //OK
    std::cout << "M2*M2:\n" << M2*M2 << std::endl; //OK
    std::cout << "M1*M2:\n" << M1*M2 << std::endl; //NOK
    std::cout << "M2*M1:\n" << M2*M1 << std::endl; //NOK
    std::cout << "M1*Mat(M2):\n" << M1*Mat(M2) << std::endl; //OK

    return 0;
}
```

Output:

```
M1*M1:
[90, 100, 110, 120;
 202, 228, 254, 280;
 314, 356, 398, 440;
 426, 484, 542, 600]
M2*M2:
[90, 100, 110, 120;
 202, 228, 254, 280;
 314, 356, 398, 440;
 426, 484, 542, 600]
M1*M2:
[2, 4, 6, 8;
 10, 12, 14, 16;
 18, 20, 22, 24;
 26, 28, 30, 32]
M2*M1:
[2, 4, 6, 8;
 10, 12, 14, 16;
 18, 20, 22, 24;
 26, 28, 30, 32]
M1*Mat(M2):
[90, 100, 110, 120;
 202, 228, 254, 280;
 314, 356, 398, 440;
 426, 484, 542, 600]
```

### PR DESCRIPTION
**Pull request by berak**
resolves #13926

replace erroneous `+` with `*`  in mat.hpp

### CODE REVIEW

**Comment by alalek** [comment]
Could you please add test for that (use code from issue and add checks for 1-2 result values)?

File: modules/core/test/test_mat.cpp [hunk 1]
```diff
@@ -2001,6 +2001,22 @@ TEST(Core_Vectors, issue_13078_workaround)
...
+                                           9, 10, 11, 12,
+                                           13, 14, 15, 16);
+
+    Matx44d M2(1, 2, 3, 4,
+               5, 6, 7, 8,
+               9, 10, 11, 12,
+               13, 14, 15, 16);
+
+    ASSERT_EQ(0, countNonZero(M1*M2 - M1*M1));
+    ASSERT_EQ(0, countNonZero(M2*M1 - M2*M2));
```
Comment (alalek) [inline modules/core/test/test_mat.cpp]: It is better to avoid using of `countNonZero()`, especially in case of floating-point matrixes.

Consider using this:
```
EXPECT_GE(1e-6, cvtest::norm(M1*M2, M1*M1, NORM_INF)) << Mat(M1*M2) << std::endl << Mat(M1*M1);
```

Comment (berak) [reply modules/core/test/test_mat.cpp]: oh sure, it's float -- my bad, i did not see it.
