### PR TITLE
fix refineDetectedMarkers

### LINKED ISSUE #24127: RefineDetectedMarkers fails if cameraMatrix is given as a param
### System Information

OpenCV python version: 4.8.0
Operating System / Platform: Windows 10
Python version: 3.9.16

### Detailed description

`refineDetectedMarkers `method of `ArucoDetector `fails if optional `cameraMatrix `param is given. 

When running following line, 
```
corners, ids, rejected, _ = aruco_detector.refineDetectedMarkers(
    image=grayscale_image,
    board=charucoboard,
    detectedCorners=aruco_corners,
    detectedIds=aruco_ids,
    rejectedCorners=aruco_rejected,
    cameraMatrix=camera_matrix,
    distCoeffs=dist_coeffs,
)
```
An assertion error is raised: 
```
    corners, ids, rejected, _ = aruco_detector.refineDetectedMarkers(
cv2.error: OpenCV(4.8.0) D:\bld\libopencv_1690022693676\work\modules\objdetect\src\aruco\aruco_board.cpp:460: error: (-215:Assertion failed) (int)detectedCharucoVecMat[i].total() * detectedCharucoVecMat[i].channels() == 2 in function 'cv::aruco::CharucoBoardImpl::matchImagePoints'
```
No error is raised if no `cameraMatrix` is specified. 

### Steps to reproduce

```python 
import imageio.v3 as iio
import numpy as np
import cv2

grayscale_image = iio.imread( r"C:\Users\jnicks\Documents\repositories\camera-characterization\gray_scale_image.png")
camera_matrix = np.array(
    [
        [1.08444638e03, 0.00000000e00, 6.99703945e02],
        [0.00000000e00, 1.08545749e03, 5.24978509e02],
        [0.00000000e00, 0.00000000e00, 1.00000000e00],
    ]
)
dist_coeffs = np.array([0.01183206, 0.01096358, 0.0, 0.0])

charucoboard = cv2.aruco.CharucoBoard(
    (11, 8),
    35,
    26,
    cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50),
)
charucoboard.setLegacyPattern(True)
aruco_detector = cv2.aruco.ArucoDetector(
    dictionary=charucoboard.getDictionary(), detectorParams=cv2.aruco.DetectorParameters()
)
aruco_corners, aruco_ids, aruco_rejected = aruco_detector.detectMarkers(image=grayscale_image)
# following line works
# corners, ids, rejected, _ = aruco_detector.refineDetectedMarkers(
#     image=grayscale_image,
#     board=charucoboard,
#     detectedCorners=aruco_corners,
#     detectedIds=aruco_ids,
#     rejectedCorners=aruco_rejected,
#     distCoeffs=dist_coeffs,
# )
# following line fails
corners, ids, rejected, _ = aruco_detector.refineDetectedMarkers(
    image=grayscale_image,
    board=charucoboard,
    detectedCorners=aruco_corners,
    detectedIds=aruco_ids,
    rejectedCorners=aruco_rejected,
    cameraMatrix=camera_matrix,
    distCoeffs=dist_coeffs,
)

```
Following image is used as input: gray_scale_image

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by AleksandrPanov**
Fixes #24127

To refine corners of ArUco markers we need to call matchImagePoints() from base class Board. The method matchImagePoints() implemented in Pimpl and we need to create temp Board object.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/objdetect/src/aruco/aruco_detector.cpp [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ static inline void _projectUndetectedMarkers(const Board &board, InputOutputArra
                                              OutputArray undetectedMarkersIds) {
     Mat rvec, tvec; // first estimate board pose with the current avaible markers
     Mat objPoints, imgPoints; // object and image points for the solvePnP function
-    board.matchImagePoints(detectedCorners, detectedIds, objPoints, imgPoints);
```
Comment (asmorkalov) [inline modules/objdetect/src/aruco/aruco_detector.cpp:1003]: Why does it change the function behaviour?

**Review by asmorkalov — CHANGES_REQUESTED** [review]

File: modules/objdetect/src/aruco/aruco_detector.cpp (hunk 1 above)
Comment (AleksandrPanov) [reply modules/objdetect/src/aruco/aruco_detector.cpp:1003]: The issue #24127 uses `CharucoBoard` and ChArUco board call `matchImagePoints` for charuco corners, but to refine ArUco markers we need to call `matchImagePoints` for ArUco corners. The method `matchImagePoints` implemented in Pimpl and we need to create `Board` object.

`refineDetectedMarkers` must always call `matchImagePoints` from the base class `Board`.

Comment (asmorkalov) [reply modules/objdetect/src/aruco/aruco_detector.cpp:1003]: It should be added to the implementation as comment.

**Review by VadimLevin — APPROVED** [review]

File: modules/objdetect/src/aruco/aruco_detector.cpp (hunk 1 above)
Comment (asmorkalov) [reply modules/objdetect/src/aruco/aruco_detector.cpp:1003]: @AleksandrPanov Please add this information to the code as comment. Current comment is not informative.

**Review by asmorkalov — APPROVED** [review]
