### PR TITLE
fix #26276: cv::VideoWriter fails writing colorless images

### LINKED ISSUE #26276: cv::VideoWriter fails writing colorless images
### System Information

**Ubuntu 22.04**
OpenCV version: 4.5.4
Compiler & compiler version: Clang 15.0.7

**Ubuntu 24.04 LTS**
OpenCV version: 4.6.0
Compiler & compiler version: GCC 13.2

### Detailed description

If an instance of `cv::VideoWriter` is used to write matrices to a file using the colorless format, the resulting video is empty and cannot be opened with any media player. This is not the case if the instance is set to use colored matrices.\
This problem has been tested and confirmed with the following input material:
1. Using artificially created matrices as shown in the example code below.
2. Loading matrices as images from any video using `cv::VideoCapture`
3. Converted ROS2 `sensor_msgs::msg::Image` messages.

### Steps to reproduce

CPP File:
```
#include <opencv2/videoio.hpp>

#include <iostream>

int main()
{
    cv::Mat mat(480, 640, CV_8UC3, cv::Scalar::all(0));
    mat.setTo(cv::Scalar(255, 0, 0));
    // Setting the last parameter to true will write a blue mat
    auto videoWriter = cv::VideoWriter("../result.mp4", cv::VideoWriter::fourcc('m', 'p', '4', 'v'), 30, mat.size(), false);

    auto frameCount = 1;
    // Write a 3-second-video
    while (frameCount <= 90) {
        std::cout << "Encoding frame " << frameCount << " of 90..." << std::endl;
        videoWriter.write(mat);

        frameCount++;
    }

    return 0;
}
```

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.8)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

project(CVTest LANGUAGES CXX)

find_package(OpenCV REQUIRED)

add_executable(CVTest
    ${CMAKE_CURRENT_LIST_DIR}/main.cpp
)

target_link_libraries(CVTest
    PRIVATE ${OpenCV_LIBS}
)
```

To build:
1. Copy the code into a `main.cpp` and `CMakeLists.txt`, respectively.
2. `mkdir build && cd build`
3. `cmake ..`
4. `make`
5. Start the application with `./CVTest` and check the resulting video.

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by 03kiko**
When writing grayscale images (`isColor=false`), `cv::VideoWriter` failed as FFmpeg backend requires input frames to be in a grayscale format. Unlike other backends, FFmpeg doesn't perform this conversion internally and expects the input to be pre-converted. To fix this, I inserted a check in the `CvVideoWriter_FFMPEG_proxy::write` to convert input frames to grayscale when the input has more than 1 channel. If this is true, then the input is converted to a gray image using `cv::cvtColor` (with `cv::COLOR_BGR2GRAY`).
Additionally, as suggested in the issue comments, I have correctly propagated the return value of `CvVideoWriter_FFMPEG::writeFrame` back to the `CvVideoWriter_FFMPEG_proxy::write`. This return value wasn't being used, and `writeFrame` was always returning false since the FFmeg's return code `AVERROR(EAGAIN)` was mistakenly being treated as an error. Now it's handled as a signal for additional input (current input was successfully written, and a new frame should be sent. [See FFmpeg documentation for  `avcodec_receive_packet`](https://ffmpeg.org/doxygen/6.1/group__lavc__decoding.html)). A warning is displayed if  `CvVideoWriter_FFMPEG::writeFrame` returns false. Alternatively, this could be propagated back up to the user, making cv::VideoWriter::write a boolean.
Finally, I added a test case to verify if the grayscale conversion is being done correctly. 

Fixes #26276

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by asmorkalov** [comment]
@mshabunin @opencv-alalek Could you take a look?

**Comment by mshabunin** [comment]
If I remember correctly there might be issues with building FFmpeg plugin on Windows because of dependency on OpenCV.

**Comment by asmorkalov** [comment]
Looks like VideoWriter behaviour is not consistent here:
- FFmpeg throws exception, if writer config and image does  not match
- GStreamer prints warning and ignores frame, if writer config and image does  not match: https://github.com/opencv/opencv/blob/09c71aed141210bf2b14582974ed9d231c24edd5/modules/videoio/src/cap_gstreamer.cpp#L2694
- MS media foundation just converts input image to target format independently on writer config: https://github.com/opencv/opencv/blob/09c71aed141210bf2b14582974ed9d231c24edd5/modules/videoio/src/cap_msmf.cpp#L2700
- Android writer ignores configuration and just convert data to expected format: https://github.com/opencv/opencv/blob/09c71aed141210bf2b14582974ed9d231c24edd5/modules/videoio/src/cap_android_mediandk.cpp#L565

**Comment by 03kiko** [comment]
@asmorkalov @mshabunin @opencv-alalek

Thank you for the feedback. I agree that consistency across backends is important, and I think the best approach is to convert data/input to the desired format, as done in MS media foundation and Android.

### Key changes:
#### FFmpeg:
- Instead of what I previously suggested in my commit, we should perform the needed conversions in `writeFrame()` in `cap_ffmpeg_impl.hpp` when checking parameters. (See conversion logic below).
- Also, since the only supported formats are `CV_8UC1`/`CV_8UC3`/`CV_16UC1`, we should add a verification for that in `write()` at `cap_ffmpeg.cpp` and do a warning in case of non-supported formats.
- In `writeFrame()`, instead of receiving only the number of channels (cn), we receive the input depth/type to make the conversions easier.

#### GStreamer:
- Implement similar conversion logic.

#### What the conversions would look like in both backends:
```cpp
if (input_pix_fmt == AV_PIX_FMT_BGR24) {
        if (type != CV_8UC3) {
            cv::Mat mat(height, width, type , data, step);
            if (type == CV_16UC1) // CV_16UC1 -> CV_8UC1
            	mat.convertTo(mat, CV_8UC1);
            cv::cvtColor(mat, mat, COLOR_GRAY2BGR); // CV_8UC1 -> CV_8UC3
            data = mat.data;
            step = (int)mat.step;
            type = CV_8UC3;
        }
}
else if (input_pix_fmt == AV_PIX_FMT_GRAY8) {
	if (type != CV_8UC1) {
	    cv::Mat mat(height, width, type , data, step);
            if (type == CV_8UC3) // CV_8UC3 -> CV_8UC1
            	cv::cvtColor(mat, mat, COLOR_BGR2GRAY);
            else // CV_16UC1 -> CV_8UC1
            	mat.convertTo(mat, CV_8UC1);
     	    data = mat.data;
            step = (int)mat.step;
            type = CV_8UC1;
	}
}
else if (input_pix_fmt == AV_PIX_FMT_GRAY16LE) {
	if (type != CV_16UC1) {
	    cv::Mat mat(height, width, type , data, step);
    	    if (type == CV_8UC3)
    	    	cv::cvtColor(mat, mat, COLOR_BGR2GRAY);  // CV_8UC3 -> CV_8UC1
    	    mat.convertTo(mat, CV_16UC1);  // CV_8UC1 -> CV_16UC1
    	    data = mat.data;
            step = (int)mat.step;
            type = CV_16UC1;
	}
}
else {
	CV_LOG_WARNING(NULL, "Input data does not match selected pixel format: "
        	<< av_get_pix_fmt_name(input_pix_fmt)
                << ", depth: " << type);
        CV_Assert(false);
}
```

#### Test Cases to Add:
- `isColor=false` with `CV_8UC3` (already done in my PR)
- `isColor=true` with `CV_8UC1`
- `isColor=true` with `CV_16UC1`
- ...

Does this approach seem reasonable? I'm ready to implement these changes.

**Comment by 03kiko** [comment]
Hi @asmorkalov, is there anything I should address or clarify to help move this PR forward?

In my last message, I suggested aligning the behavior of the FFmpeg and GStreamer backends with that of MS Media Foundation and Android — handling input conversion internally.

Specifically, the idea is to perform the necessary conversions inside the `writeFrame()` function for FFmpeg (and similarly for GStreamer). Since only three input types are supported (`CV_8UC1`, `CV_8UC3`, and `CV_16UC1`), these conversions should be straightforward.

I also plan to add test cases to cover these scenarios and make sure the conversions behave as expected.

Please let me know if anything is unclear or if you’d prefer a different approach. I’m ready to make any needed adjustments and move forward with the implementation.

**Comment by 03kiko** [comment]
Hi @asmorkalov @mshabunin @opencv-alalek,

Since I didn’t hear back, I decided to move forward and implement the changes I previously proposed. The update improves consistency between the FFmpeg backend and others like MS Media Foundation and Android.

Specifically:
- The conversion logic has been moved into CvVideoWriter_FFMPEG::writeFrame().
- All relevant format conversion cases are now handled.
- Test cases were added to cover all supported conversion scenarios.
- The fix for AVERROR(EAGAIN) handling remains, along with a warning when writeFrame returns false.

Please let me know if you’d like any changes or have further feedback.

**Comment by 03kiko** [comment]
@asmorkalov @opencv-alalek @mshabunin friendly reminder

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 1]
```diff
@@ -2512,34 +2512,57 @@ static int icv_av_write_frame_FFMPEG( AVFormatContext * oc, AVStream * video_st,
 }
 
 /// write a frame with FFMPEG
-bool CvVideoWriter_FFMPEG::writeFrame( const unsigned char* data, int step, int width, int height, int cn, int origin )
+bool CvVideoWriter_FFMPEG::writeFrame( const unsigned char* data, int step, int width, int height, int type, int origin )
 {
     if (!encode_video) {
-        CV_Assert(cn == 1 && ((width > 0 && height == 1) || (width == 1 && height > 0 && step == 1)));
+        CV_Assert((type == CV_16UC1 || type == CV_8UC1) && ((width > 0 && height == 1) || (width == 1 && height > 0 && step == 1)));
```
Comment (opencv-alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:2518]: In case of `encode_video = False` we should accept only raw bytes arrays.
So we should have CV_8UC1 data type only.
Expected layout is 1xN or Nx1.

This change must be reverted.

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 2]
```diff
@@ -2512,34 +2512,57 @@ static int icv_av_write_frame_FFMPEG( AVFormatContext * oc, AVStream * video_st,
...
+    // check parameters and do conversions if needed
+    cv::Mat inputMat(height, width, type, (void*)data, step);
+    cv::Mat convertedMat;
+    switch (input_pix_fmt) {
+        case AV_PIX_FMT_BGR24: // expected CV_8UC3
+            if (type == CV_8UC3)
+                convertedMat = inputMat;
+            else {
+                if (type == CV_16UC1) // CV_16UC1 -> CV_8UC1
+                    inputMat.convertTo(inputMat, CV_8UC1, 1.0 / 256);
```
Comment (opencv-alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:2534]: > inputMat ... inputMat

"In-place" ops should not be used in general (causes extra `.clone()` call).

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 3]
```diff
@@ -2512,34 +2512,57 @@ static int icv_av_write_frame_FFMPEG( AVFormatContext * oc, AVStream * video_st,
...
+                cv::cvtColor(inputMat, convertedMat, cv::COLOR_GRAY2BGR); // CV_8UC1 -> CV_8UC3
+            }
```
Comment (opencv-alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:2536]: What is about other cases?

16UC3?

**Review by opencv-alalek — COMMENTED** [review]
Silent ignorance of the error is a design bug.

But implicit data manipulation is an evil too.
There are no safe operations, except may be `COLOR_GRAY2BGR`.
So required conversions should be left on the user side.

`.write()` should fail properly instead if input is not expected.

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 1 above)
Comment (03kiko) [reply modules/videoio/src/cap_ffmpeg_impl.hpp:2518]: Thanks for pointing that out! The original logic only checked if cn == 1, so I mistakenly assumed both CV_8UC1 and CV_16UC1 were acceptable. I’ll revert this logic in the next commit.

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 2 above)
Comment (03kiko) [reply modules/videoio/src/cap_ffmpeg_impl.hpp:2534]: Thanks for the heads-up, I’ll avoid in-place operations moving forward.

File: modules/videoio/src/cap_ffmpeg_impl.hpp (hunk 3 above)
Comment (03kiko) [reply modules/videoio/src/cap_ffmpeg_impl.hpp:2536]: Good point. I had focused only on the explicitly supported types (CV_8UC1, CV_16UC1, CV_8UC3) and overlooked the possibility of unsupported inputs like CV_16UC3. I’ll address this as well.

**Comment by 03kiko** [comment]
> Silent ignorance of the error is a design bug.
> 
> But implicit data manipulation is an evil too. There are no safe operations, except may be `COLOR_GRAY2BGR`. So required conversions should be left on the user side.
> 
> `.write()` should fail properly instead if input is not expected.

Given that there are no safe operations, the best approach is indeed to leave format handling to the user. Since .write() is a void function, changing its return type would require a broader change (though it could be beneficial). Instead, this will be addressed through clearer warnings:
- One when writeFrame() fails to write the frame (already in previous commits)
- Another explicitly reports a mismatch between expected and received input types, similar to the GStreamer backend. (Will add this in the next commit)
This avoids silent failures and makes the frame skipping behaviour more transparent to users.

**Comment by 03kiko** [comment]
Hi @opencv-alalek @mshabunin,

I've pushed a new version addressing @opencv-alalek’s feedback. All required conversions should now be handled by the user. I kept the `type` argument in the `writeFrame()` function to allow for more specific warnings. I’ve also added three test cases to validate that VideoWriter fails in case of mismatched types and that appropriate warnings are logged.

However, on Win64, one test case fails: when the input is `CV_8UC1` and the expected depth is `CV_16UC1`. Despite the mismatch, the writer still successfully writes the video, and the file can be read. I suspect this is because, in this particular case, `encode_video = false`, which skips the input/expected types check and directly encapsulates the frame data.

I would appreciate your input, as the other two test cases behave as expected by failing due to the mismatch. Is this platform-specific behaviour expected, or am I missing something?

Thanks!

**Comment by mshabunin** [comment]
We need to make sure ffmpeg videoio plugin on windows can be built with this patch - see https://github.com/opencv/opencv_3rdparty/tree/ffmpeg/4.x.

File: modules/videoio/src/cap_ffmpeg_impl.hpp [hunk 4]
```diff
@@ -3456,7 +3466,7 @@ void cvReleaseVideoWriter_FFMPEG( CvVideoWriter_FFMPEG** writer )
 
 int cvWriteFrame_FFMPEG( CvVideoWriter_FFMPEG* writer,
                          const unsigned char* data, int step,
-                         int width, int height, int cn, int origin)
```
Comment (opencv-alalek) [inline modules/videoio/src/cap_ffmpeg_impl.hpp:3459]: This is a part of external API (`cap_ffmpeg_legacy_api.hpp`), we can't just change parameters meaning.

Comment (03kiko) [reply modules/videoio/src/cap_ffmpeg_impl.hpp]: I completely missed that detail... As its part of external API, I'm going to revert it back to using the number of channels

**Comment by 03kiko** [comment]
Hi @mshabunin @opencv-alalek,

I've pushed a new version based on your feedback. I also added a set of test cases that cover various combinations of input frame channel counts and depth/isColor configurations. Please let me know if you think these tests are necessary, as the core behaviour remains mostly unchanged compared to the original code (it now just logs warnings).

Let me know if there's anything else you'd like me to adjust.
Thanks!

**Comment by 03kiko** [comment]
@mshabunin @opencv-alalek Friendly reminder

**Comment by 03kiko** [comment]
@asmorkalov @opencv-alalek @mshabunin friendly reminder
