### PR TITLE
Fix 7785: putText garbage

### LINKED ISSUE #7785: cv::putText regression
##### System information (version)
- OpenCV => master
- Operating System / Platform => Win7 x64
- Compiler => **MSVS 2010 32-bit** (MSVS 2012/2015 32/64-bit are fine)

##### Detailed description

Example of generated input data for test: `Videoio_Video.seek_random_synthetic`

OpenCV 3.1.0:
opencv-3 1 0

OpenCV master:
opencv-master

Probably related: #7458 #7161

### PR DESCRIPTION
**Pull request by alalek**
resolves #7785

Reproduced in MSVS2010 Win32 Release build only.
```
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
```

### CODE REVIEW

File: modules/imgproc/src/drawing.cpp [hunk 1]
```diff
@@ -1187,18 +1182,18 @@ FillConvexPoly( Mat& img, const Point2l* v, int npts, const void* color, int lin
...
+                        }
                         xs = v[idx].x;
                         idx += di;
-                        idx -= ((idx < npts) - 1) & npts;   /* idx -= idx >= npts ? npts : 0 */
+                        if (idx >= npts) idx -= npts;
                         edges--;
                     }
 
-                    xs <<= XY_SHIFT - shift;
-                    xe = v[idx].x << (XY_SHIFT - shift);
```
Comment (alalek) [inline modules/imgproc/src/drawing.cpp]: Probably vc10 compiler bug is somewhere here. Adding "printf" statement repairs regression test.

**Comment by alalek** [comment]
:+1:

**Comment by mshabunin** [comment]
:+1:
