### PR TITLE
Load IR model from buffer

### LINKED ISSUE #15578: Read ir model from buffer not implemented
- OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit / Ubuntu 18.04 LTS
- Compiler => Visual Studio 2017 / clang6.0

We are trying to load an IR model from a memory buffer (loaded from a single binary file, not relevant) but `dnn::readNet()` for dldt from buffer is not implemented.

```cpp
 else if (framework == "dldt")
        CV_Error(Error::StsNotImplemented, "Reading Intel's Model Optimizer models from buffers");
```

My colleague is already working on submitting a pull request to implement this.

### PR DESCRIPTION
**Pull request by Quantizs**
resolves #15578

Added implementations to load IR models from buffer

<cut/>

```
force_builders=Custom,Custom Win,Custom Mac
build_image:Custom=ubuntu-openvino-2019r3.0:16.04
build_image:Custom Win=openvino-2019r3.0
build_image:Custom Mac=openvino-2019r3.0

test_modules:Custom=dnn,python2,python3,java
test_modules:Custom Win=dnn,python2,python3,java
test_modules:Custom Mac=dnn,python2,python3,java

buildworker:Custom=linux-1
test_opencl:Custom=OFF
test_bigdata:Custom=1
test_filter:Custom=*
```

### CODE REVIEW

File: modules/dnn/include/opencv2/dnn/dnn.hpp [hunk 1]
```diff
@@ -357,6 +357,8 @@ CV__DNN_EXPERIMENTAL_NS_BEGIN
         virtual ~Layer();
     };
 
+    struct LayerData;
```
Comment (dkurt) [inline modules/dnn/include/opencv2/dnn/dnn.hpp]: This is an internal data structure.

Comment (Quantizs) [reply modules/dnn/include/opencv2/dnn/dnn.hpp]: https://github.com/opencv/opencv/pull/16015#discussion_r351744027
To create a seprate functon from the common parts in the two loading method (file and buffer):
- I have to pass an InferenceEngine::CNNNetReader which can not be included in the dnn.hpp, so i had to use static function
- I need to access the Impl struct of the Net class which is forward declarated in dnn.hpp and this where i can't find a clean solution.

As I see now I have these options here: 
1. Writing a getter to member impl which doesn't seems right because its a private member. 
2. The current solution: writing a getter which can get a layerData from the impl struct by id.
To do this a had to forward declarate the LayerData struct in the header. 
3. Writing setters to layerInstance and backendNodes:
        ld.layerInstance = cvLayer;
        ld.backendNodes[DNN_BACKEND_INFERENCE_ENGINE] = backendNode;
The problem here is the backendNode which is has an InfEngineBackendNet type whisch also can't be included in the dnn.hpp 

If there is an other way please help me to find it.

File: modules/dnn/src/dnn.cpp [hunk 2]
```diff
@@ -4344,7 +4422,7 @@ Net readNet(const String& _framework, const std::vector<uchar>& bufferModel,
     else if (framework == "torch")
         CV_Error(Error::StsNotImplemented, "Reading Torch models from buffers");
     else if (framework == "dldt")
-        CV_Error(Error::StsNotImplemented, "Reading Intel's Model Optimizer models from buffers");
+        return readNetFromModelOptimizerBuffer(bufferConfig, bufferModel);
```
Comment (alalek) [inline modules/dnn/src/dnn.cpp]: @dkurt Please verify parameters order.

Comment (dkurt) [reply modules/dnn/src/dnn.cpp]: Looks fine because of origin

```cpp
CV_WRAP static Net readFromModelOptimizer(const String& xml, const String& bin);
```

File: modules/dnn/src/dnn.cpp [hunk 3]
```diff
@@ -3001,9 +2995,93 @@ Net Net::readFromModelOptimizer(const String& xml, const String& bin)
...
+#ifndef HAVE_INF_ENGINE
+    CV_UNUSED(bufferModelConfigPtr); CV_UNUSED(bufferWeightsPtr);
+    CV_UNUSED(bufferModelConfigSize); CV_UNUSED(bufferModelConfigSize);
+    CV_Error(Error::StsError, "Build OpenCV with Inference Engine to enable loading models from Model Optimizer.");
+#else
+
+#if INF_ENGINE_VER_MAJOR_LE(INF_ENGINE_RELEASE_2019R3)
+    InferenceEngine::CNNNetReader reader;
+
+    InferenceEngine::CNNNetReader reader;
```
Comment (dkurt) [inline modules/dnn/src/dnn.cpp]: please remove duplicated code

File: modules/dnn/include/opencv2/dnn/dnn.hpp [hunk 4]
```diff
@@ -694,7 +713,7 @@ CV__DNN_EXPERIMENTAL_NS_BEGIN
         CV_WRAP int64 getPerfProfile(CV_OUT std::vector<double>& timings);
 
     private:
-        struct Impl;
+        struct Impl; friend struct Impl;
```
Comment (dkurt) [inline modules/dnn/include/opencv2/dnn/dnn.hpp]: It looks like we can remove this as well.

**Comment by alalek** [comment]
> readFromModelOptimizer
> readFromModelOptimizerBuffer
> readFromModelOptimizerBufferPtr

Any objections about these names?

**Comment by dkurt** [comment]
@alalek, sorry. I missed this

File: modules/dnn/include/opencv2/dnn/dnn.hpp [hunk 5]
```diff
@@ -384,14 +384,33 @@ CV__DNN_EXPERIMENTAL_NS_BEGIN
...
          */
         CV_WRAP static Net readFromModelOptimizer(const String& xml, const String& bin);
 
+        /** @brief Create a network from Intel's Model Optimizer in-memory buffers with intermediate representation (IR).
+         *  @param[in] bufferModelConfig buffer with model's configuration.
+         *  @param[in] bufferWeights buffer with model's trained weights.
+         *  @returns Net object.
+         */
+        CV_WRAP static
+        Net readFromModelOptimizerBuffer(const std::vector<uchar>& bufferModelConfig, const std::vector<uchar>& bufferWeights);
```
Comment (dkurt) [inline modules/dnn/include/opencv2/dnn/dnn.hpp]: All the versions should have the same name: readFromModelOptimizer and readNetFromModelOptimizer.

Comment (alalek) [reply modules/dnn/include/opencv2/dnn/dnn.hpp]: The same name is not good and should be avoided.
At least for bindings support.
"String" (bytes array in meaning of UTF-8 file path) and `vector<uchar>` (or other forms of bytes array) is similar things and bindings wrappers may convert between them.

`readFromModelOptimizer` should be called `readFromModelOptimizerFile` but it is too late.

---

What is about prefixes?
- "read" for files ("load" is also used, for example in objdetect module)
- "create" / "build" for buffers

Comment (dkurt) [reply modules/dnn/include/opencv2/dnn/dnn.hpp]: Here an example when bindings work correctly with Darknet model: https://github.com/opencv/opencv/pull/11104#issuecomment-403763020

Comment (alalek) [reply modules/dnn/include/opencv2/dnn/dnn.hpp]: I didn't say that they not working. My concern here is that overused overloading is not reliable.

Feel free to update patch (just keep eyes on documentation).

**Comment by Quantizs** [comment]
Hi,
When will this feature be merged ?

**Comment by dkurt** [comment]
@Quantizs, As we discussed with @alalek, I'd like to recommend to rename methods in the same way: `readNetFromModelOptimizer` because in Python they can work fine (with `bytearray`). So you can fix it.

File: modules/dnn/include/opencv2/dnn/dnn.hpp (hunk 5 above)
Comment (dkurt) [reply modules/dnn/include/opencv2/dnn/dnn.hpp]: @Quantizs, please change `Net::readFromModelOptimizer*` as well.
