### PR TITLE
Fix memory leak in pyopencv_to for path-like objects

### LINKED ISSUE #28046: Python: reference leak in `pyopencv_to` modules/python/src2/cv2_convert.cpp
### System Information

OpenCV python version: 4.11.0.86
Operating System / Platform: Oracle Linux 8 x86_64
Python version: 3.14.0

### Detailed description

The call to `PyOS_FSPath` returns a [new strong reference]( https://docs.python.org/3/c-api/sys.html#c.PyOS_FSPath) but Py_XDECREF is never called on that returned value.

https://github.com/opencv/opencv/blob/f627368ebc1640093717b6046f274f719237cb8b/modules/python/src2/cv2_convert.cpp#L716

### Steps to reproduce

build python with `--with-address-sanitizer` & `--without-pymalloc` to get a working leak sanitiser.

```
from pathlib import Path
import cv2

cv2.imread(Path("image.jpg"))
```

LeakSanitizer will report a leak for a memory block allocated by a call to `PyOS_FSPath`.
Running with a string rather than a Path will report the leak coming from elsewhere (as `PyOS_FSPath` is just a ref count increment in this case)

Any function argument annotated with `CV_WRAP_FILE_PATH` will leak, `cv2.imread` is just one of them.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by 0AnshuAditya0**
This PR fixes a memory leak in pyopencv_to when handling path-like objects (e.g., pathlib.Path).
Problem:
PyOS_FSPath() returns a new strong reference, but the code was not calling Py_XDECREF to decrement it, causing a memory leak on every call with path-like arguments.
Solution:

Store the returned reference from PyOS_FSPath() in a separate variable path_obj
Call Py_XDECREF(path_obj) on all function exit paths (both success and error paths)
This ensures proper reference counting without changing the function's behavior

Testing:
The leak can be reproduced using the steps in issue #28046 with Python built with --with-address-sanitizer. This fix ensures the reference is properly released.
Fixes #28046

Pull Request Readiness Checklist
See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

 ✓ I agree to contribute to the project under Apache 2 License.
 ✓ To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
 ✓ The PR is proposed to the proper branch (4.x)
 ✓ There is a reference to the original bug report and related work (#28046)
 NA There is accuracy test, performance test and test data in opencv_extra repository, if applicable
Patch to opencv_extra has the same branch name.
 ✓ The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/python/src2/cv2_convert.cpp [hunk 1]
```diff
@@ -711,35 +711,36 @@ bool pyopencv_to(PyObject* obj, String &value, const ArgInfo& info)
...
             failmsg("Expected '%s' to be a str or path-like object", info.name);
             return false;
         }
+        obj = path_obj;
     }
 #endif
     if (getUnicodeString(obj, str))
     {
         value = str;
+        Py_XDECREF(path_obj);
```
Comment (asmorkalov) [inline modules/python/src2/cv2_convert.cpp]: `PyObject* path_obj = NULL;` is inside `#if` block. Build is broken for the case without limited api option.

File: modules/python/src2/cv2_convert.cpp [hunk 2]
```diff
@@ -711,35 +711,36 @@ bool pyopencv_to(PyObject* obj, String &value, const ArgInfo& info)
...
-            // Direct access to underlying slots of PyObjectType is not allowed
-            // when limited API is enabled
 #ifdef Py_LIMITED_API
             failmsg("Can't convert object to 'str' for '%s'", info.name);
 #else
             failmsg("Can't convert object of type '%s' to 'str' for '%s'",
                     obj->ob_type->tp_name, info.name);
 #endif
         }
+        Py_XDECREF(path_obj);
```
Comment (asmorkalov) [inline modules/python/src2/cv2_convert.cpp]: The same

**Comment by 0AnshuAditya0** [comment]
Thanks for fixing the scope issue! I see you've pushed the corrections directly - appreciate you taking the time to clean that up. I'll make sure to be more careful with preprocessor blocks in future contributions.

**Comment by 0AnshuAditya0** [comment]
It looks like the Windows x64 test failed due to a network error (ECONNRESET) rather than a code issue. The other CI checks have passed. Could someone restart this check when possible?

File: modules/python/src2/cv2_convert.cpp (hunk 1 above)
Comment (asmorkalov) [reply modules/python/src2/cv2_convert.cpp]: `PyObject* path_obj = NULL;` is still inside `#if` block.

Comment (0AnshuAditya0) [reply modules/python/src2/cv2_convert.cpp]: Fixed! I've moved the path_obj declaration outside the #if block. 
Thanks for catching this - the variable is now available for cleanup 
in all compilation scenarios.
