### PR TITLE
Fix resource leaks in Android Utils.java (#28697)

### LINKED ISSUE #28697: Resource leaks in Android Utils.java exportResource() and loadResource()
In Utils.java, exportResource() opens InputStream and FileOutputStream without try-with-resources. If IOException occurs during read/write, streams are never closed. Same pattern in loadResource(). On Android, leaked file descriptors can exhaust the process fd limit. Fix: convert to try-with-resources.

### PR DESCRIPTION
**Pull request by PDGGK**
## Summary

Fixes resource leaks in `exportResource()` and `loadResource()` in Android Utils.java.

Closes #28697

## Changes

- `exportResource()`: Converted InputStream and FileOutputStream to try-with-resources. Removed manual .close() calls and unnecessary printStackTrace().
- `loadResource()`: Converted InputStream and ByteArrayOutputStream to try-with-resources. Extracted data/dataLength before block closes.

Both methods previously leaked file descriptors on IOException.

### CODE REVIEW

File: modules/highgui/misc/java/src/java/highgui+HighGui.java [hunk 1]
```diff
@@ -157,7 +154,7 @@ public static int waitKey(int delay) {
                 latch.await(delay, TimeUnit.MILLISECONDS);
             }
         } catch (InterruptedException e) {
-            e.printStackTrace();
```
Comment (asmorkalov) [inline modules/highgui/misc/java/src/java/highgui+HighGui.java:157]: I propose to presume `e.printStackTrace();` to get stack information in logcat.

**Comment by PDGGK** [comment]
Thanks @asmorkalov, done. Added back e.printStackTrace() for logcat visibility while keeping Thread.currentThread().interrupt() to restore the interrupt flag.
