### PR TITLE
Fixed and updated OpenCL-VA interoperability

### LINKED ISSUE #18307: Cannot build OpenCV with Intel VA, asking for "CL/va_ext.h" file
##### System information (version)

- OpenCV => 4.4.0
- Operating System / Platform => Alpine 3.12
- Compiler => clang++

##### Detailed description

I am trying to compile opencv with VA_INTEL. I have compiled and installed Intel MSDK and OpenCL. But while compiling, the following error shows up

```
/tmp/opencv-4.3.0/modules/core/src/va_intel.cpp:29:12: fatal error: 'CL/va_ext.h' file not found
#  include <CL/va_ext.h>
           ^~~~~~~~~~~~~
[ 30%] Building CXX object modules/core/CMakeFiles/opencv_core.dir/stat.avx2.cpp.o
1 error generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:1176: modules/core/CMakeFiles/opencv_core.dir/src/va_intel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1464: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
```

This has something to do  with the fact its looking for a file `va_ext.h` in the `include/CL` directory it would seem; as specified here https://github.com/opencv/opencv/blob/master/modules/core/src/va_intel.cpp#L29.

The issue is, I can't find this file anywhere. Neither do I know how to install it. When OpenCL headers is installed, it doesn't come with this file. So not sure what I am doing wrong, as I have been stuck on this for so long.

##### Steps to reproduce

compile opencv with `-D WITH_VA_INTEL=ON`

##### Issue submission checklist

 - [X] I report the issue, it's not a question
 - [X] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [X] I updated to latest OpenCV version and the issue is still there
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by mshabunin**
resolves #18307 
supersedes #18318

* added cl_va_api_media_sharing_intel.h to OpenCL headers
* added ability to build with old and new header name (did not check with old file though)
* simplified `WITH_VA_INTEL` handling
* updated documentation
* use `clGePlatformInfo` directly to read device name

How to enable the feature:
```.sh
# prerequisite: libva-dev
cmake -DWITH_VA=ON -DWITH_VA_INTEL=ON ../opencv
```

Checked in `--privileged` Ubuntu 20.04 container with system `libva2` and [OpenCL runtime 20.37.17906](https://github.com/intel/compute-runtime/releases/tag/20.37.17906):
```.sh
# ../build/bin/example_va_intel_va_intel_interop ../opencv/samples/data/lena.jpg a b
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
VA display opened successfully
Interop ON : processing time, msec: 1.26111
```

**Note**: device name reading have been replaced due to an error with `PlatformInfo` constructor
```
Thread 1 "example_va_inte" received signal SIGSEGV, Segmentation fault.
0x00007ffff2fce128 in clGetDeviceIDs () from /lib/x86_64-linux-gnu/libOpenCL.so.1
(gdb) bt
#0  0x00007ffff2fce128 in clGetDeviceIDs () from /lib/x86_64-linux-gnu/libOpenCL.so.1
#1  0x00007ffff4649aff in OPENCL_FN_clGetDeviceIDs_switch_fn (p1=0x7ffff2fa18e0, p2=4294967295, p3=0, p4=0x0,
    p5=0x7fffffffe114)
    at /opencv/modules/core/src/opencl/runtime/autogenerated/opencl_core_impl.hpp:411
#2  0x00007ffff462bbd8 in cv::ocl::getDevices (devices=std::vector of length 0, capacity 0, platform=0x7ffff2fa18e0)
    at /opencv/modules/core/src/ocl.cpp:6521
#3  0x00007ffff462be21 in cv::ocl::PlatformInfo::Impl::Impl (this=0x55555644c1c0, id=0x555555902860)
    at /opencv/modules/core/src/ocl.cpp:6544
#4  0x00007ffff462c029 in cv::ocl::PlatformInfo::PlatformInfo (this=0x7fffffffe220, platform_id=0x555555902860)
    at /opencv/modules/core/src/ocl.cpp:6567
...
```

### CODE REVIEW

File: modules/core/src/va_intel.cpp [hunk 1]
```diff
@@ -137,7 +141,13 @@ Context& initializeContextFromVA(VADisplay display, bool tryInterop)
             contextInitialized = true;
 
             cl_platform_id platform = platforms[found];
-            std::string platformName = PlatformInfo(platform).name();
```
Comment (alalek) [inline modules/core/src/va_intel.cpp:140]: Please replace `platform` => `&platform`.

With verbose replacements it is better to keep original code (to avoid replacement back):
```
#if 0  // code doesn't works due to ...
   original code
#else
  ... verbose code ...
#endif
```

**Review by alalek — APPROVED** [review]

**Comment by Odianosen25** [comment]
Thanks for this @mshabunin, still couldn't figure out how to fix it.

You guys are the best

**Comment by mshabunin** [comment]
@Odianosen25 , OpenCL 2.2 should be backward compatible with 1.x. For example, I tested it with 2.1 runtime.

**Comment by Odianosen25** [comment]
@mshabunin,

Thanks for the response, and yes it actually is. Just gives out a warning 

```
In file included from /usr/include/CL/cl.h:20,
                 from /tmp/opencv-4.4.0/modules/core/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp:102,
                 from /tmp/opencv-4.4.0/modules/core/include/opencv2/core/opencl/runtime/opencl_core.hpp:68,
                 from /tmp/opencv-4.4.0/modules/core/src/dxt.cpp:44:
/usr/include/CL/cl_version.h:22:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
      |                                                                                                        ^
```

But its no show stopper.

Kind regards
