### PR TITLE
Fix encodeStructuredAppend() resulting in only one QR code problem, and false output data fix.

### LINKED ISSUE #22205: Problem with encodeStructuredAppend function
##### System information (version)

- OpenCV => 4.5.5 and 4.6.0
- Operating System / Platform =>Windows 64 Bit
- Compiler => Visual Studio 2022
- Language => C++

##### Detailed description

Hello there ! I’m working with OpenCV in order to generate QR Codes.
I want to use the function **encodeStructuredAppend** from **objdetect.hpp** so I used the test **test_qrcode_encode.cpp** to understand this function.

However, no matter what ```params.structure_number``` equal the number of QRcodes generated is one.

If I try with ```params.structure_number = 1``` it generates only one QR code with all the informations in it but if I put more than one it generates only one QR code with only the end of the string minus one.

I asked the question on the forum and a moderator told me to report the bug.
https://forum.opencv.org/t/problem-with-encodestructuredappend-function/9417

##### Steps to reproduce

    main.cpp
    // C++ code example

    #include <iostream>
    #include "opencv2/opencv.hpp"
    #include <opencv2/objdetect.hpp>
    #include <vector>
    
    
    int main()
    {
        std::string input_info = "Some text to test, more or less big, i tried differents things";
        cv::QRCodeEncoder::Params params;
        params.structure_number = 3;
        params.mode = cv::QRCodeEncoder::EncodeMode::MODE_STRUCTURED_APPEND;
    
        cv::Ptr<cv::QRCodeEncoder> encoder = cv::QRCodeEncoder::create(params);
    
        std::vector<cv::Mat> qrcodes;
    
        encoder->encodeStructuredAppend(input_info, qrcodes);
        
        if(qrcodes.empty()) std::cout << "Can't generate this QR images";
        std::cout << qrcodes.size() << std::endl;
    
        for (size_t k = 0; k < qrcodes.size(); k++)
        {
            cv::Mat qrcode = qrcodes[k];
            std::string sav = "qrcode/qr" + std::to_string(k) + ".jpg";
            cv::imwrite(sav, qrcode);
            std::cout << k << std::endl;
        }
    }
  

##### Issue submission checklist

 - [x] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [x] I updated to the latest OpenCV version and the issue is still there
   
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by genciberisha**
Fixes #22205 and #23105 

While splitting the data to multiple QR codes it constantly cleans the resulting vector(final_qr_codes).
The fix is to just clean the result vector after all work is done with it.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by genciberisha** [comment]
@alalek @AleksandrPanov 
Sorry to inform you that i had some problem with the original [PR](https://github.com/opencv/opencv/pull/23104?notification_referrer_id=NT_kwDOAwIlSbM1MjY3MTI4MDc1OjUwNDcyMjY1#event-8328030967) and had to create a new one.

**Comment by genciberisha** [comment]
@AleksandrPanov It seems like our decoder doesn't support _Structured Append_ mode yet, but i managed to validate the data using an [online decoder](https://me-qr-scanner.com/qr-scanner#scan-using-file) and it works.

Please let me know if i should add the data validation on the regression test and mark is as DISABLED.

**Review by AleksandrPanov — APPROVED** [review]
@genciberisha, thank for your work, LGTM

You're right, OpenCV decoder cannot read QR codes with Structured Append mode ([None of the QR codes from the sequence could be read with OpenCV](https://segno.readthedocs.io/en/latest/structured-append.html)).

File: modules/objdetect/test/test_qrcode_encode.cpp [hunk 1]
```diff
@@ -450,6 +450,34 @@ TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, DISABLED_regression)
...
+
+    cv::QRCodeEncoder::Params params;
+
+    for(const auto& encode_mode : encode_modes)
+    {
+        params.mode = encode_mode;
+        for(size_t struct_num = 2; struct_num < 5; ++struct_num)
+        {
+            params.structure_number = static_cast<int>(struct_num);
+            encoder = cv::QRCodeEncoder::create(params);
```
Comment (asmorkalov) [inline modules/objdetect/test/test_qrcode_encode.cpp:473]: RAII is preferable here:
```
cv::Ptr<cv::QRCodeEncoder> encoder = cv::QRCodeEncoder::create(params);
```

File: modules/objdetect/test/test_qrcode_encode.cpp [hunk 2]
```diff
@@ -450,6 +450,34 @@ TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, DISABLED_regression)
 
 #endif // UPDATE_QRCODE_TEST_DATA
 
+TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, regression_22205)
+{
+    cv::Ptr<cv::QRCodeEncoder> encoder = nullptr;
```
Comment (asmorkalov) [inline modules/objdetect/test/test_qrcode_encode.cpp:455]: Use local variable in loop.

File: modules/objdetect/test/test_qrcode_encode.cpp [hunk 3]
```diff
@@ -450,6 +450,34 @@ TEST(Objdetect_QRCode_Encode_Decode_Structured_Append, DISABLED_regression)
...
+    std::string input_data = "the quick brown fox jumps over the lazy dog";
+
+    std::vector<cv::QRCodeEncoder::EncodeMode> encode_modes = {
+        cv::QRCodeEncoder::EncodeMode::MODE_NUMERIC,
+        cv::QRCodeEncoder::EncodeMode::MODE_ALPHANUMERIC,
+        cv::QRCodeEncoder::EncodeMode::MODE_BYTE};
```
Comment (asmorkalov) [inline modules/objdetect/test/test_qrcode_encode.cpp:461]: It makes sense to use parameterized test approach. It's move verbose and easy to debug in case of failure. See https://github.com/opencv/opencv/blob/4.x/modules/calib3d/test/test_affine2d_estimator.cpp#L46 as example and https://github.com/google/googletest/blob/main/docs/advanced.md#value-parameterized-tests for documentation.

File: modules/objdetect/src/qrcode_encoder.cpp [hunk 4]
```diff
@@ -332,14 +332,18 @@ void QRCodeEncoderImpl::generateQR(const std::string &input)
...
+    size_t segment_end = 0;
+    auto string_itr = input.begin();
+    for (int i = struct_num; i > 0; --i)
     {
         sequence_num = (uint8_t) i;
-        int segment_begin = i * segment_len;
-        int segemnt_end = min((i + 1) * segment_len, (int) input.length()) - 1;
-        std::string input_info = input.substr(segment_begin, segemnt_end - segment_begin + 1);
+        segment_begin = string_itr - input.begin();
+        segment_end = (input.end() - string_itr) / i;
```
Comment (asmorkalov) [inline modules/objdetect/src/qrcode_encoder.cpp:343]: use RAII and local variables
```
        size_t segment_begin = string_itr - input.begin();
        size_t segment_end = (input.end() - string_itr) / i;
``

**Review by asmorkalov — CHANGES_REQUESTED** [review]

File: modules/objdetect/test/test_qrcode_encode.cpp (hunk 1 above)
Comment (alalek) [reply modules/objdetect/test/test_qrcode_encode.cpp:473]: It is not about RAII only. It is mostly about declaration of variables near their usage.
Prefer to keep variables scope minimal.

**Review by asmorkalov — APPROVED** [review]
