### PR TITLE
Append zero to trailing decimal place for FileStorage JSON write of a float or double value

### LINKED ISSUE #7951: Make FileStorage JSON float and double output meet JSON standard
##### System information (version)

- OpenCV => 3.2
- Operating System / Platform => All
- Compiler => All

##### Detailed description

FileStorage JSON output of float and double values leaves a trailing decimal place if no fractional part (i.e. value of 1.0 produces a "1." output). JSON standard requires a zero after the decimal place (output "1.0").

This was originally identified by @wiryls in comments on issue #7088 

##### Steps to reproduce

Create a JSON FileStorage and write a float or double (either native or a float/double matrix etc.) without a fractional part. Observe output file contents.

### PR DESCRIPTION
**Pull request by mattmyne**
resolves #7951
### This pullrequest changes

- Appends zero to trailing decimal place for FileStorage JSON write of a float or double value
- Needed to meet JSON standard
- Previous text output "1." now becomes "1.0"
- Only JSON format is modified, no change to XML or YAML output

### CODE REVIEW

File: modules/core/src/persistence.cpp [hunk 1]
```diff
@@ -4025,7 +4025,14 @@ static void
 icvJSONWriteReal( CvFileStorage* fs, const char* key, double value )
 {
     char buf[128];
-    icvJSONWrite( fs, key, icvDoubleToString( buf, value ));
+    int len = (int)strlen( icvDoubleToString( buf, value ) );
```
Comment (sergiud) [inline modules/core/src/persistence.cpp]: Why do you cast the result of `strlen` (which is of unsigned type `size_t`) to an `int`? This can cause an integer overflow. Also, `strlen` does not return negative values.

File: modules/core/src/persistence.cpp [hunk 2]
```diff
@@ -4829,6 +4836,17 @@ cvWriteRawData( CvFileStorage* fs, const void* _data, int len, const char* dt )
                 }
                 else
                 {
+                    if( elem_type == CV_32F || elem_type == CV_64F )
+                    {
+                        int buf_len = (int)strlen(ptr);
```
Comment (sergiud) [inline modules/core/src/persistence.cpp]: Same problem as before.

File: modules/core/src/persistence.cpp (hunk 1 above)
Comment (mattmyne) [inline modules/core/src/persistence.cpp]: Almost all the uses of strlen in persistence.cpp explicitly cast the return of strlen to an int, even when passed the same pointer as I am (such as line 4823 of original code). I kept this style to remain constant with the rest of the source code.

In both cases, strlen is called for buf which is a static char array of size 128 (first use) or 256 (second use). If a null character in the double-to-string conversion is not found before then, there would have been a more significant error and buffer overflow in the upstream code in any case.

I can make an exception to the previous source style and return the result as a size_t if you prefer - please confirm.

Comment (alalek) [inline modules/core/src/persistence.cpp]: I'm not sure that we need to force `size_t` here.
I see here potential problem about `buf` array size (128) that doesn't used/passed anywhere. But this problem is not related to this patch.

Comment (sergiud) [inline modules/core/src/persistence.cpp]: `size_t` is the actual return type of `strlen`, not an `int`. So if anything is forced here, it's the type cast to an `int`. In my opinion, bad style should not be duplicated. Someone may copy the code in the future again which may cause problems.

Nevertheless, feel free to merge the patch as is.

**Comment by mattmyne** [comment]
New commit following @sergiud comments.
Since this was my first PR (yay) my intention was to make as little change as possible to the code and style. I therefore continued the existing preference of casting the strlen return to an int rather than native size_t.
Though there would be no realistic runtime issue in this case, on reflection I agree with @sergiud that it is bad practise to duplicate poor coding decisions when there is no need. I trust this resolves the issue to everyone's satisfaction!

**Comment by alalek** [comment]
Looks good to me. Thanks!
:+1:
