### PR TITLE
Fix webp grayscale loading

### LINKED ISSUE #8637: `imread` with `CV_LOAD_IMAGE_GRAYSCALE` read webp images to have 3 channels
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => Ubuntu 14.04 ([nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04](https://gitlab.com/nvidia/cuda/blob/ubuntu14.04/8.0/devel/cudnn5/Dockerfile))
- Compiler => gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

##### Steps to reproduce

When input a webp image.

This code output `3`:

	cv::Mat imageGrayMat = imread(this->actImgPath, CV_LOAD_IMAGE_GRAYSCALE);
	cout << imageGrayMat.channels();

While this code output `1`:

	cv::Mat imageRGBMat = imread(this->actImgPath, IMREAD_COLOR);
	cv::Mat imageGrayMat;
	cv::cvtColor(imageRGBMat, imageGrayMat, COLOR_BGR2GRAY);
	cout << imageGrayMat.channels();

JPG files seems work OK.

### PR DESCRIPTION
**Pull request by berak**
resolves #8637

webp does not support grayscale images natively. there's a cvtColor() applied internally, when trying to write a grayscale img to webp, so there should be an internal cvtColor() applied, too, when IMREAD_GRAYSCALE was specified

### CODE REVIEW

File: modules/imgcodecs/src/grfmt_webp.cpp [hunk 1]
```diff
@@ -162,6 +162,8 @@ bool WebPDecoder::readData(Mat &img)
 {
     if( m_width > 0 && m_height > 0 )
     {
+        bool convert_grayscale = (img.type() == 0); // IMREAD_GRAYSCALE requested
```
Comment (alalek) [inline modules/imgcodecs/src/grfmt_webp.cpp]: `0` => `CV_8UC1`

Comment (berak) [inline modules/imgcodecs/src/grfmt_webp.cpp]: right, good idea

Comment (alalek) [inline modules/imgcodecs/src/grfmt_webp.cpp]: or `img.channels() == 1`

**Comment by alalek** [comment]
:+1:
