### PR TITLE
Fix RISC-V HAL solve/SVD and BGRtoLab

### LINKED ISSUE #27044: calib3d and photo test failures on RISC-V platforms
It seems that recent changes have broken several tests in calib3d and photo modules (https://github.com/opencv/ci-gha-workflow/actions/runs/13731764537):

calib3d:
```
  [  FAILED  ] 3 tests, listed below:
  [  FAILED  ] CV_RecoverPoseTest.regression_15341
  [  FAILED  ] Calib3d_SolvePnPRansac.double_support
  [  FAILED  ] Calib3d_SolvePnP.accuracy_planar_tag
```
photo:
```
  [  FAILED  ] 2 tests, listed below:
  [  FAILED  ] Photo_Decolor.regression
  [  FAILED  ] Photo_NPR_DetailEnhance.regression
```
These tests run on CanMV board and OpenCV has been built using Clang 17.

Probably one or several of the following PRs caused these issues: [merged:2025-03-02..2025-03-08](https://github.com/opencv/opencv/pulls?q=is%3Apr+label%3A%22platform%3A+riscv%22+is%3Aclosed+sort%3Aupdated-desc+merged%3A2025-03-02..2025-03-08) I suspect it could be solve and or cvtColor, but I didn't check exact functions yet. 

@amane-ame , @GenshinImpactStarts , @hanliutong , could you please take a look?

### PR DESCRIPTION
**Pull request by amane-ame**
Closes #27044.

Also suppressed some warnings in other HAL.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [ ] The PR is proposed to the proper branch
- [ ] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: 3rdparty/hal_rvv/hal_rvv.hpp [hunk 1]
```diff
@@ -6,6 +6,7 @@
 #define OPENCV_HAL_RVV_HPP_INCLUDED
 
 #include "opencv2/core/hal/interface.h"
+#include "../../imgproc/include/opencv2/imgproc/hal/interface.h"
```
Comment (asmorkalov) [inline 3rdparty/hal_rvv/hal_rvv.hpp:9]: `imgproc/include` should be added into include directories in cmake.

**Comment by amane-ame** [comment]
cc @asmorkalov This can prevent potential test failure in 5.x.

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp [hunk 2]
```diff
@@ -2304,13 +2304,19 @@ namespace LabTable
                 LvToVp_b[error1[i]] += error1[i + 1];
             #endif
 
+            static constexpr float BGR2XYZ[] =
+            {
+                0.180423f / 0.950456f, 0.357580f / 0.950456f, 0.412453f / 0.950456f,
+                0.072169f            , 0.715160f            , 0.212671f            ,
+                0.950227f / 1.088754f, 0.119193f / 1.088754f, 0.019334f / 1.088754f
+            };
```
Comment (asmorkalov) [inline 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2312]: it'll be great to add reference to the values origin, if you know where they from.

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp [hunk 3]
```diff
@@ -2322,28 +2328,51 @@ namespace LabTable
...
+            static constexpr int error2[] = {37,-1,124,-1,503,-1,4150,1,5548,1,6544,1,6659,1,8625,-1,11704,1,16108,-1,16347,-1,16446,-1,18148,1,19624,-1,22731,-1,23479,1,24001,1,24291,-1,25199,-1,25352,-1,27402,-1,28485,-1,29788,1,29807,-1,32149,-1,33451,-1,33974,-1,38265,-1,38403,-1,41038,-1,41279,1,41824,-1,42856,-1,48096,-1,49201,-1,50562,-1,51054,-1,51550,-1,51821,1,56973,-1,57283,1,62335,-1,67867,-1,70692,-1,71194,-1,71662,1,71815,1,72316,-1,73487,1,75722,-1,75959,1,82290,-1,82868,-1,83208,-1,83534,-1,84217,-1,85793,1,86683,-1,87939,-1,89143,1,90258,-1,91432,-1,92302,1,92325,-1,92572,1,93143,-1,93731,-1,94142,-1,95244,-1,96025,-1,96950,-1,97758,-1,102409,-1,104165,-1};
```
Comment (asmorkalov) [inline 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2368]: Could you add some comment what the tweak does and why it's needed. The code bellow is very cryptic.

**Comment by asmorkalov** [comment]
cc @mshabunin

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp [hunk 4]
```diff
@@ -2322,28 +2328,51 @@ namespace LabTable
...
+                            float L = applyCbrt(Y);
+                            L = L*116.0f - 16.0f;
+
+                            float d = 52.0f/std::max(X + 15.0f * Y + 3.0f * Z, FLT_EPSILON);
+                            float u = L*(X*d - 2.5719122887f);
+                            float v = L*(2.25f*Y*d - 6.0884485245f);
+
+                            RGB2Luvprev[idx  ] = (short)std::rint(LAB_BASE*L/100.0f);
+                            RGB2Luvprev[idx+1] = (short)std::rint(LAB_BASE*(u+134.0f)/354.0f);
+                            RGB2Luvprev[idx+2] = (short)std::rint(LAB_BASE*(v+140.0f)/262.0f);
```
Comment (asmorkalov) [inline 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2362]: FYI: rint behaviour may be changed in run-time with user settings. OpenCV cannot control it. https://en.cppreference.com/w/cpp/numeric/math/rint

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp (hunk 3 above)
Comment (amane-ame) [reply 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2368]: There is a comment on line 2248.

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp (hunk 2 above)
Comment (amane-ame) [reply 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2312]: All floating point values are copied from the cv::cvtColor series. The comments before each converting function describes it.

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp (hunk 4 above)
Comment (amane-ame) [reply 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:2362]: I will add a wrapper for this.

File: 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp [hunk 5]
```diff
@@ -33,6 +34,15 @@ namespace color {
...
     }
+
+    template<typename T> T rint(T val)
+    {
+        int rd = std::fegetround();
+        std::fesetround(FE_TONEAREST);
+        T ret = std::rint(val);
+        std::fesetround(rd);
+        return ret;
+    }
```
Comment (asmorkalov) [inline 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:45]: The function is called in a loop many times and modifies global state. It may be slow and affect other parallel threads. I propose to revert to the original rint and add a note to header(s) and documentation about  it. Also as alternative cvRound/cvFloor may be used or some other stateless function.

Comment (amane-ame) [reply 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp:45]: All calls to `rint` are made within the singleton initialization or static variables initialization, which has no performance penalty or thread safety issues.

Comment (amane-ame) [reply 3rdparty/hal_rvv/hal_rvv_1p0/color.hpp]: I have changed to `roundeven`.

**Comment by asmorkalov** [comment]
roundeven, roundevenf, roundevenl are available since C++23. Not sure if it's universal solution. @mshabunin What so you think?

**Comment by fengyuentau** [comment]
My performance results [perf.zip](https://github.com/user-attachments/files/19284156/perf.zip)

**Comment by fengyuentau** [comment]
@amane-ame I suggest you to solve conflicts with the following cli git commands instead of the GitHub webpage tool to ensure that your commits are continuous in your branch.

```
git remote add upstream https://github.com/opencv/opencv
git fetch upstream
git rebase upstream/4.x
```

**Comment by amane-ame** [comment]
@fengyuentau Uh, rebase will mess up the order of commits and comments in PR, because GitHub sorts them by commit date. If you are okay with this, it's fine.

**Comment by mshabunin** [comment]
> roundeven, roundevenf, roundevenl are available since C++23. Not sure if it's universal solution. @mshabunin What so you think?

Let's restore `rint` + `fesetround` - it should be thread-local. Perhaps we can try to reduce number of rounding-mode switching by wrapping whole table initialization in `fesetround` calls.

See also: https://en.cppreference.com/w/c/numeric/fenv

**Comment by amane-ame** [comment]
@mshabunin I can use `std::remainder` instead of `roundeven`.

**Comment by mshabunin** [comment]
@amane-ame , how does it affect performance? Or is the table initialized just once and it doesn't matter much? 

I thought that something like this would be good from both performance and safety standpoints:
```.cpp
int old_mode = fesetround(...);
// init whole table using rint
fesetround(old_mode);
```

**Comment by amane-ame** [comment]
@mshabunin `std::remainder` should not have any performance impact, since `LabTable` will only be initialized once in a **process**.

**Review by mshabunin — APPROVED** [review]

**Review by asmorkalov — APPROVED** [review]
