### PR TITLE
handle images with alpha better

### LINKED ISSUE #7121: UIImageToMat for UIImage with alpha creates Mat with garbage in clear pixels.
OpenCV => 3.1
Operating System / Platform => iOS 64 bit
Compiler => Xcode 7.3.1

UIImageToMat ends up with random memory values in background of UIImage with alpha.

##### Steps to reproduce

Use a UIImage created from a png with an alpha channel.  Create a Mat for it with UIImageToMat.  Use MatToUIImage and then draw the image. 

```
- (UIImage*) imageMethod: (UIImage*) inputImage
{
	CGImageAlphaInfo ainfo = CGImageGetAlphaInfo( inputImage.CGImage );
        
       cv::Mat image;  // or cv:Mat image = cv:Mat();
![bug3](https://cloud.githubusercontent.com/assets/222271/17720463/e8dbd61a-63d6-11e6-8768-7534d0ee60a4.png)

	UIImageToMat( inputImage, image, ainfo != kCGImageAlphaNone );
	return MatToUIImage( image );
}
```

calling code in an iOS project with an onscreen UIImageView into which to place the result

```
UIImage * anImage = [UIImage imageNamed: "test.png"];
UIImage * resultImage = [self imageMethod: anImage];

// put resultImage into an onscreen UIImageView to see it ugly
```

Source Image:

bug

Resulting image before fix varies quite a bit (ignore rotation - that's done after the above code for unrelated reasons):

bug2

after the fix:

bug3

A fix is to just initialize the Mat values with 0, as in the PR submitting next.

### PR DESCRIPTION
**Pull request by haikusw**
resolves #7121 

### This pullrequest changes
initializes the Mat before drawing a UIImage with an alpha channel onto it.

UIImages with alpha were ending up with garbage pixels in background (random memory values).  Need to initialize matrix pixels before drawing UIImage with alpha on it.

Note: didn’t fix Grayscale image with alpha stripping alpha in UIImage -> Mat conversion. Couldn't get that working; may be that CGBitmapContext doesn't support a Gray + Alpha two-channel configuration.

### CODE REVIEW

File: modules/imgcodecs/src/ios_conversions.mm [hunk 1]
```diff
@@ -116,6 +118,8 @@ void UIImageToMat(const UIImage* image,
         if (!alphaExist)
             bitmapInfo = kCGImageAlphaNoneSkipLast |
                                 kCGBitmapByteOrderDefault;
+        else
+            m = cv::Scalar(0);
```
Comment (terfendail) [inline modules/imgcodecs/src/ios_conversions.mm]: Looks like here we have an alpha channel and going to store it to RGBA image. Shouldn't we use kCGImageAlphaLast to store alpha channel as well?

Comment (haikusw) [inline modules/imgcodecs/src/ios_conversions.mm]: Thanks.  You can't see it on the default diff on github, but if you expand the section above it you can see on line 102 that bitmapInfo is set to `kCGImageAlphaPremultipliedLast` as a default value.  Not the way I'd code this function, but I was trying to make the smallest change possible that fixed the bug.

Comment (terfendail) [inline modules/imgcodecs/src/ios_conversions.mm]: Oh I see now.
May be it make sense to initialize the Mat for other branch as well to ensure the alpha channel doesn't contain garbage. As far as I understand it wouldn't be changed during CGContextDrawImage execution.

Comment (haikusw) [inline modules/imgcodecs/src/ios_conversions.mm]: I considered that.  I chose not to so for efficiency reasons since setting all those bytes takes time and this function is called to process frames in video streams in some use cases (like my current one).  Since the alpha channel is ignored it seemed like a reasonable efficiency tradeoff.

Comment (haikusw) [inline modules/imgcodecs/src/ios_conversions.mm]: I didn't actually time the cost of setting all those bytes to zero on a mobile device, but since 3/4 of the work is duplicated in the draw call (which sets RGB), it seemed wasteful.  We could initialize just the alpha channel to zero I suppose, if that's more efficient (misaligned data access may actually make this more costly on some processors/architectures).

Comment (vpisarev) [inline modules/imgcodecs/src/ios_conversions.mm]: it's the same cost - whether you set the whole image to 0's or just alpha channel, since the data is interleaved. I would say, in principle, setting the whole image to 0's may be even faster, if compiler generates proper instructions for it.

Comment (haikusw) [inline modules/imgcodecs/src/ios_conversions.mm]: yes, that's what I was saying about misaligned data access making setting only the alpha potentially slower than just setting all 4 channels.  In my case, the cost is not something necessary and reduces performance, hence my intentionally leaving that out when the image isn't using an alpha channel.   For real time video frame processing you really don't want any unnecessary computation cost.   I could add a comment in the header file about this if you think that's useful.

**Comment by vpisarev** [comment]
ok, so let's put it in :+1:
