### PR TITLE
Fixes #28396 : out-of-bounds read in SIMD type conversion

### LINKED ISSUE #27080: normL1 does not give consistent results with different compilers and optimization levels
### System Information

Latest 5.x.

### Detailed description

I was working on normL1 on 32s input data and found that the existing kernel

https://github.com/opencv/opencv/blob/7635d9a0122a038da760254905bfae4866560b70/modules/core/include/opencv2/core/base.hpp#L367-L374

cannot produce consistent results with different compilers and optimization levels.

 Reproducer is attached below. Here is the summary with the reproducer.

| Compiler | -O0 | -O3 |
| - | - | - |
| x64, gcc-12.3.0 | n=11074883890230.000000 | n=6878700842038.000000 |
| arm64, apple clang 16.0.0 | n=11074883890230.000000 | n=11073593898738.000000 |
| risc-v, gcc-14.2.0 | n=11074883890230.000000 | n=11074883890230.000000 |
| risc-v, clang-18.0.0 | n=11074883890230.000000 | n=8302375796980.000000 |

### Steps to reproduce

Download [main.cpp.zip](https://github.com/user-attachments/files/19282206/main.cpp.zip), extract, compile and run. Note that input data is collected from opencv performance tests.

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### LINKED ISSUE #28396: Out-of-bounds read in cvt_ in convert.simd.hpp
### System Information

WASM with 128-bit SIMD

### Detailed description

While running some of our code through ASAN, I noticed an out-of-bounds read in cvt_ in convert.simd.hpp.

The error looks to be in these lines of code:
https://github.com/opencv/opencv/blob/d8bc5b94b851d5b392c61e5b954fba992e18bb73/modules/core/src/convert.simd.hpp#L113-L125

The value of VECSZ is defined based on the vlanes of the source type. But when converting e.g. 8-bit uints to 32-bit floats on 128-bit SIMD system, vlanes for f32 is 4 while the vlanes for uint8 is 16.

The later line `vx_load_pair_as` ends up reading 32 elements from source array while we only verified in the if-statement above that 8 elements are available. This leads to a out-of-bound read unless the width of source array is divisible by 32.

### Steps to reproduce

```
uint8_matrix.convertTo(f32_matrix, CV_32FC1);
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [ ] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by 0AnshuAditya0**
Fixes #28396
Fixes #27080

The vx_load_expand function in WASM intrinsics was using 
wasm_v128_load which always loads a full 128-bit register 
(16 bytes), even when the function only needed 8 elements.

For example, when converting uint8 to float32:
- vx_load_expand needs 8 uint8 elements
- But wasm_v128_load reads 16 bytes from memory
- This causes an 8-byte out-of-bounds read

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/core/include/opencv2/core/hal/intrin_wasm.hpp [hunk 1]
```diff
@@ -1859,7 +1859,10 @@ inline _Tpwvec v_expand_high(const _Tpvec& a)                        \
 { return _Tpwvec(__CV_CAT(intrin, _high)(a.val)); }                  \
 inline _Tpwvec v_load_expand(const _Tp* ptr)                         \
 {                                                                    \
-    v128_t a = wasm_v128_load(ptr);                                  \
+    alignas(16) _Tp tmp[_Tpwvec::nlanes] = {};
```
Comment (akretz) [inline modules/core/include/opencv2/core/hal/intrin_wasm.hpp]: The zero initialization can be removed.

File: modules/core/include/opencv2/core/hal/intrin_wasm.hpp [hunk 2]
```diff
@@ -1859,7 +1859,10 @@ inline _Tpwvec v_expand_high(const _Tpvec& a)                        \
...
+    for(int i = 0; i < _Tpwvec::nlanes; i++)
+        tmp[i] = ptr[i];
+    v128_t a = wasm_v128_load(tmp);                                  \
     return _Tpwvec(intrin(a));                                       \
```
Comment (akretz) [inline modules/core/include/opencv2/core/hal/intrin_wasm.hpp]: Call too `intrin()` needs to be removed, as this was the previous function which did the type conversion.

**Review by akretz — COMMENTED** [review]
This seems to be the correct approach to fix the linked issue to me. Some observations:

* You need the backslashes at the end of the lines, otherwise the macro breaks.
* Don't you need to make the `tmp` array hold elements of type `_Tpwvec::lane_type` and then remove the call to `intrin()`? That's how it's done in the float16 implementation of `v_load_expand`. Because now the `wasm_v128_load()` reads over the end of the array.
* `v_load_expand_q` has the same bug that it reads too much data, right? In that case, a similar fix has to be applied there.

File: modules/core/include/opencv2/core/hal/intrin_wasm.hpp (hunk 1 above)
Comment (0AnshuAditya0) [reply modules/core/include/opencv2/core/hal/intrin_wasm.hpp]: Sure! Thanks for pointing out.

**Comment by 0AnshuAditya0** [comment]
Switched the temp buffer to _Tpwvec::lane_type and load directly into the vector, consistent with the float16 implementation. This guarantees safe 128-bit loads on WASM and resolves the ASAN OOB. Also fixed macro formatting and applied the same fix to v_load_expand_q.

**Comment by 0AnshuAditya0** [comment]
@asmorkalov reminder that this is pending review. Let me know if I should address any changes.

**Comment by asmorkalov** [comment]
Rebased on top of 4.x to re-trigger CI.
