### PR TITLE
cartToPolar/polarToCart: disable inplace mode

### LINKED ISSUE #21732: cartToPolar does not work in place
##### System information (version)
- OpenCV => 4.5
- Operating System / Platform => Linux
- Compiler => clang 11

##### Detailed description

```cartToPolar``` does not work in place: this should be fixed or there should be an error. ```polarToCart``` seems to work but I cannot confirm the OCL and IPP versions work. There should be a test for both anyway (like the code I provide below).

##### Steps to reproduce

The following code shows the issue. ```clang++ -g -O3 -l opencv_core -I /usr/include/opencv4/ -o test main.cc```

```.cpp
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include <iostream>


int main(int, char**argv){

cv::Mat1d A[2] = {cv::Mat1d(10, 10), cv::Mat1d(10, 10)};
cv::Mat1d B[2], C[2];
for(auto&a: A) cv::randu(a, 0, 10000);

cv::cartToPolar(A[0], A[1], B[0], B[1], false);
cv::polarToCart(B[0], B[1], C[0], C[1], false);
std::cout << "There is a small difference due to the 0.3 degree approximation" << std::endl;
std::cout << cv::norm(A[0], C[0], cv::NORM_INF) << " " << cv::norm(A[1], C[1], cv::NORM_INF) << std::endl;

cv::cartToPolar(A[0], A[1], B[0], B[1], false);
cv::polarToCart(B[0], B[1], C[0], C[1], false);
cv::polarToCart(B[0], B[1], B[0], B[1], false);
std::cout << "This gives 0" << std::endl;
std::cout << cv::norm(B[0], C[0], cv::NORM_INF) << " " << cv::norm(B[1], C[1], cv::NORM_INF) << std::endl;

cv::cartToPolar(A[0], A[1], B[0], B[1], false);
cv::cartToPolar(A[0], A[1], A[0], A[1], false);
std::cout << "This does not give 0 for the second norm showing it does not work in place" << std::endl;
std::cout << cv::norm(A[0], B[0], cv::NORM_INF) << " " << cv::norm(A[1], B[1], cv::NORM_INF) << std::endl;
}
```

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
 - [x] I updated to the latest OpenCV version and the issue is still there
 - [x] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by mshabunin**
Resolves #21732

Raise an exception if one of sources is the same as one of destinations since inplace mode works incorrectly (with and without IPP).

```
allow_multiple_commits=1
```

### CODE REVIEW

File: modules/core/test/test_arithm.cpp [hunk 1]
```diff
@@ -2620,5 +2620,38 @@ TEST(Core_Magnitude, regression_19506)
     }
 }
 
+using namespace ocl;
```
Comment (alalek) [inline modules/core/test/test_arithm.cpp:2623]: Is it necessary? used?

Comment (mshabunin) [reply modules/core/test/test_arithm.cpp:2623]: I think `EXPECT_MAT_NEAR` did not work without it. I'll check.

Comment (mshabunin) [reply modules/core/test/test_arithm.cpp:2623]: I've checked and it is `EXPEC_MAT_NEAR` which requires `ocl` namespace.

Comment (alalek) [reply modules/core/test/test_arithm.cpp:2623]: Could we use related calls with full namespace in this macro?

Comment (mshabunin) [reply modules/core/test/test_arithm.cpp]: Done! Also rebased to 3.4.
