### PR TITLE
Changing data_layout for pack in tf_importer

### LINKED ISSUE #22221: human_parsing example from dnn Assertion failed (int)_numAxes == inputs[0].size()
##### System information (version)

- OpenCV => 4.6
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

##### Detailed description

human_parsing example from dnn module not working properly no matter of input it every time asserting at:

`modules\dnn\src\layers\permute_layer.cpp:161: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'`

I tried to resize / convert input image in 384x384 dimensions and different formats but it still not helping,
I assume the problem is in lip_jppnet_384.pb that is told to use in comments to the example.

##### Steps to reproduce

1. download lip_jppnet_384.pb by [link ](https://www.dropbox.com/s/qag9vzambhhkvxr/lip_jppnet_384.pb?dl=0
) in the example 
2. run [c++](https://github.com/opencv/opencv/blob/4.x/samples/dnn/human_parsing.cpp) or [python example](https://github.com/opencv/opencv/blob/4.x/samples/dnn/human_parsing.py) of human_parsing from dnn module
3. observe assert in output window

##### Issue submission checklist

 - [*] I report the issue, it's not a question
 
 - [*] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
  
 - [*] I updated to the latest OpenCV version and the issue is still there
 
 - [*] There is reproducer code and related data files: videos, images, onnx, etc

### PR DESCRIPTION
**Pull request by fengyuentau**
Fixes #22221.

In this case, the `pack` operator stacks three 4-dimensional tensors into a 5-dimensional tensor. However, the data layout of the output of the `pack` operator is still recognized as 4-dimensional (`DATA_LAYOUT_NHWC`) in tf_importer, which will lead to some problems like #22221 . Changing the data layout to `DATA_LAYOUT_UNKNOWN` fixes the problem.

For testing, I doubt whether we should put the model in opencv_extra since it is ~432MB.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by zihaomu** [comment]
Hi @fengyuentau, you can use [generate_tf_models.py or generate_tf2_models.py](https://github.com/opencv/opencv_extra/blob/4.x/testdata/dnn/tensorflow) to export specific pb model.

File: modules/dnn/src/tensorflow/tf_importer.cpp [hunk 1]
```diff
@@ -2541,6 +2541,8 @@ void TFImporter::parsePack(tensorflow::GraphDef& net, const tensorflow::NodeDef&
     if (dim != 0)
         CV_Error(Error::StsNotImplemented, "Unsupported mode of pack operation.");
 
+    data_layouts[name] = DATA_LAYOUT_UNKNOWN;
```
Comment (zihaomu) [inline modules/dnn/src/tensorflow/tf_importer.cpp:2544]: In `tf_importer`, some layers are sensitive to the input's data layout (like `Transpose`). And these layers may error if they are after the `Pack` layer.
Maybe we can judge the output data layout by the input data layout. 
For example, the input is 4 dim and NHWC data layout, which means the output should be the 5 dims.
But I'm not sure if this is the right way to do it

**Review by zihaomu — COMMENTED** [review]
Thanks for your contribution.

File: modules/dnn/src/tensorflow/tf_importer.cpp (hunk 1 above)
Comment (fengyuentau) [reply modules/dnn/src/tensorflow/tf_importer.cpp:2544]: We can consider cases that have defined data layout in `tf_importer`, for example stacking hwc can have nhwc data layout output. The problem is we cannot take every single data layout into account since theoratically there is countless.

I wonder in which case pack is followed by transpose though.

Comment (fengyuentau) [reply modules/dnn/src/tensorflow/tf_importer.cpp:2544]: I think we keep it unknown for the output data layout of pack since there are only 4 data layouts defined:

```cpp
enum DataLayout
{
    DATA_LAYOUT_NHWC,
    DATA_LAYOUT_NCHW,
    DATA_LAYOUT_NDHWC,
    DATA_LAYOUT_UNKNOWN,
    DATA_LAYOUT_PLANAR  // 2-dimensional outputs (matmul, flatten, reshape to 2d)
};
```

These data layouts do not satisfy our need if we want to describe the output data layout of pack unless more are added.

Comment (zihaomu) [reply modules/dnn/src/tensorflow/tf_importer.cpp:2544]: A complete test example would be helpful.
From [stack API](https://www.tensorflow.org/api_docs/python/tf/stack), we can find that the axis is `[-(R+1), R+1)`.
The following code generates all possible cases of `tf.stack`.
```
for d in range(1, 7):
    for axis in range(-d - 1, d + 1):
        inp0 = tf.placeholder(tf.float32, list(range(1, d + 1)), 'input0')
        constant = tf.random_normal(list(range(1, d + 1)))
        pack_model = tf.stack([inp0, constant])
        print(pack_model)
        # save(inp0, pack_model, f'pack_dim{d}_{axis}', optimize=False)
```

**Review by vpisarev — APPROVED** [review]

File: modules/dnn/src/tensorflow/tf_importer.cpp (hunk 1 above)
Comment (fengyuentau) [reply modules/dnn/src/tensorflow/tf_importer.cpp:2544]: Testing a single `Pack` operator does not make any sense in this pull request. This pull request is changing the output data layout, and with or without this change, such tests will always pass.

**Review by zihaomu — APPROVED** [review]
LGTM! 👍
