### PR TITLE
deleted dublicated "private" createConvexHull and convertTo

### LINKED ISSUE #17585: minEnclosingTriangle Error using python3.8.3 on Windows
##### System information (version)
- OpenCV => 4.2
- Operating System / Platform => Windows 7 64 Bit
- Python 3.8.3
##### Detailed description
I'm trying to calculate the minEnclosingTriangle, but i'm getting error:

> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\copy.cpp:254: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'cv::Mat::copyTo'

here is my code:
```
import cv2 as cv
import numpy as np

arr = np.array([[0.0, 0.0],[0.0, 1.0],[1.0, 1.0]], dtype=np.float32)
print(arr)
c,r = cv.minEnclosingCircle(arr)
print(c,r)
t,t1 = cv.minEnclosingTriangle(arr)
print(t,t1)
```
and the output:

> λ python triangle.py
> [[0. 0.]
>  [0. 1.]
>  [1. 1.]]
> (0.5, 0.5) 0.7072067856788635
> Traceback (most recent call last):
>   File "triangle.py", line 8, in <module>
>     t,t1 = cv.minEnclosingTriangle(arr)
> cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\copy.cpp:254: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'cv::Mat::copyTo'

The circle was calculated, so assume the InputArray points should be OK.
What I'm doing wrong?

### PR DESCRIPTION
**Pull request by AleksandrPanov**
Fixes #17585
Function `createConvexHull` just cast `cv::Mat` to `vector<cv::Point2f>` by `convertTo()` and call `ConvexHull`.
There is problem: `convertTo()` can't cast `cv::Mat(n, 2, CV_32FC1)` to `vector<cv::Point2f>`. But `ConvexHull` can take `cv::Mat(n, 2, CV_32FC1)`.
To fix problem can delete `createConvexHull` (this is "private" function and calls once).

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [ ] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

File: modules/imgproc/src/min_enclosing_triangle.cpp [hunk 1]
```diff
@@ -319,29 +318,12 @@ namespace minEnclosingTriangle {
 static void findMinEnclosingTriangle(cv::InputArray points,
                                      CV_OUT cv::OutputArray triangle, CV_OUT double &area) {
     std::vector<cv::Point2f> resultingTriangle, polygon;
-
-    createConvexHull(points, polygon);
+    CV_Assert(points.getMat().checkVector(2) > 0);
```
Comment (alalek) [inline modules/imgproc/src/min_enclosing_triangle.cpp:321]: Lets remove this check, because `convexHull` has similar checks inside through `total = points.checkVector(2)`

Or replace it with `CV_Assert(!points.empty());`

**Review by alalek — APPROVED** [review]
Looks good to me! Thank you :+1:

File: modules/imgproc/src/min_enclosing_triangle.cpp (hunk 1 above)
Comment (AleksandrPanov) [reply modules/imgproc/src/min_enclosing_triangle.cpp]: replaced `CV_Assert(points.getMat().checkVector(2) > 0)` with `CV_Assert(!points.empty())`
