### PR TITLE
Java autotests fix for OpenCV 3.1

### LINKED ISSUE #7511: Regression issue with Imgproc.minEnclosingCircle
##### System information (version)

- OpenCV => 3.1 upstream/master (505c19bc20b971288f321f6092f9dfc479001e2b)
- Operating System / Platform => Mac OSX 10.11.5 (15F34)
- Compiler => Xcode Version 8.0 (8A218a)
##### Detailed description

Java unit test is failing the test case  **ImgprocTest.testMinEnclosingCircle** with the following message:

```
    expected:<1.0299999713897705> but was:<1.000100016593933>

junit.framework.AssertionFailedError: expected:<1.0299999713897705> but was:<1.000100016593933>
at org.opencv.test.iimgproc.ImgprocTest.testMinEnclosingCircle(Unknown Source)
at org.opencv.test.OpenCVTestCase.runTest(Unknown Source)
```

The test is running the following code:

```
    public void testMinEnclosingCircle() {
        MatOfPoint2f points = new MatOfPoint2f(new Point(0, 0), new Point(-1, 0), new Point(0, -1), new Point(1, 0), new Point(0, 1));
        Point actualCenter = new Point();
        float[] radius = new float[1];

        Imgproc.minEnclosingCircle(points, actualCenter, radius);

        assertEquals(new Point(0, 0), actualCenter);
        assertEquals(1.03f, radius[0], EPS);
    }
```
##### Steps to reproduce

Compile OpenCV with java enabled and run the autotests from the build folder using the following command:

```
python ../modules/ts/misc/run.py . -t java
```

Results of autotests can be seen on this page: opencv/build/modules/java/pure_test/.build/testResults/junit-noframes.html

### LINKED ISSUE #7512: Regression issue with Imgproc.HoughLinesP
##### System information (version)

- OpenCV => 3.1 upstream/master (505c19bc20b971288f321f6092f9dfc479001e2b)
- Operating System / Platform => Mac OSX 10.11.5 (15F34)
- Compiler => Xcode Version 8.0 (8A218a)
##### Detailed description

Java unit test is failing the test case  **ImgprocTest.testHoughLinesPMatMatDoubleDoubleInt** with the following message:

```
expected:<2> but was:<1>

junit.framework.AssertionFailedError: expected:<2> but was:<1>
at org.opencv.test.imgproc.ImgprocTest.testHoughLinesPMatMatDoubleDoubleInt(Unknown Source)
at org.opencv.test.OpenCVTestCase.runTest(Unknown Source)
```

The test is running the following code:

```
    public void testHoughLinesPMatMatDoubleDoubleInt() {
        int sz = 512;
        Mat img = new Mat(sz, sz, CvType.CV_8U, new Scalar(0));
        Point point1 = new Point(0, 0);
        Point point2 = new Point(sz, sz);
        Point point3 = new Point(sz, 0);
        Point point4 = new Point(2*sz/3, sz/3);
        Imgproc.line(img, point1, point2, Scalar.all(255), 1);
        Imgproc.line(img, point3, point4, Scalar.all(255), 1);
        Mat lines = new Mat();

        Imgproc.HoughLinesP(img, lines, 1, 3.1415926/180, 100);

        assertEquals(2, lines.cols());

        /*
        Log.d("HoughLinesP", "lines=" + lines);
        int num = (int)lines.cols();
        int buff[] = new int[num*4]; // CV_32SC4 as [ (x1, y1, x2, y2), (...), ...]
        lines.get(0, 0, buff);
        Log.d("HoughLinesP", "lines=" + Arrays.toString(buff));
        */
    }
```
##### Steps to reproduce

Compile OpenCV with java enabled and run the autotests from the build folder using the following command:

```
python ../modules/ts/misc/run.py . -t java
```

Results of autotests can be seen on this page: opencv/build/modules/java/pure_test/.build/testResults/junit-noframes.html

### PR DESCRIPTION
**Pull request by abratchik**
workaround #7510
resolves #7511
resolves #7512
### This pullrequest changes

Updates autotests for OpenCV 3.1 release.

- many auto tests were dependent on non-free/experimental algorithms, which are currently moved to contrib module. For this reason autotests should be compiled and used with contrib/non-free modules. 
- YAML format in test samples was inconsistent with generated one and with YAML specs. 
- feature detectors/descriptor extractors/matchers' parameters were loaded from YAML but the read method is not implemented in the corresponding class.  This fix will use corresponding parameter setters for algorithm initiation.
- removed 'empty' Feature2D tests, which seem to be obsolete.

running auto-tests can be done from the OpenCV build folder  using the following command:
`python ../modules/ts/misc/run.py . -t java`.

### CODE REVIEW

**Comment by alalek** [comment]
There is failed build without `opencv_contrib` (missing SURF).

**Comment by abratchik** [comment]
yes, I see (( will fix today.

**Comment by abratchik** [comment]
Tried to rebuild but there seems to be some problem with Win 7 x64 and Android? Cannot figure out Win 7 x64 build issue, looks strange since the build on Win 10 was successful. Android issue is also strange. Could it be because of previous unsuccessful build?

**Comment by abratchik** [comment]
Fix is ready, please kindly merge. The remaining problems are #7510, #7511 and #7512, which need to be analyzed before we could include these autotests to be run by build bots.

**Comment by abratchik** [comment]
Please do not merge yet, I will add fixes for the remaining 3 issues tonight

**Comment by abratchik** [comment]
please merge, this is ready.

File: modules/calib3d/misc/java/test/Calib3dTest.java [hunk 1]
```diff
@@ -237,22 +236,23 @@ public void testFindCirclesGridMatSizeMatInt() {
...
-            double y = Math.random() * 100 - 50;
-            pts.put(i, 0, x, y); //add(new Point(x, y));
-        }
-
-        Mat fm = Calib3d.findFundamentalMat(pts, pts);
-
-        truth = new Mat(3, 3, CvType.CV_64F);
-        truth.put(0, 0, 0, -0.577, 0.288, 0.577, 0, 0.288, -0.288, -0.288, 0);
-        assertMatEqual(truth, fm, EPS);
+        fail("Not yet implemented");
```
Comment (alalek) [inline modules/calib3d/misc/java/test/Calib3dTest.java]: Can we disable test instead of failure?

Comment (abratchik) [inline modules/calib3d/misc/java/test/Calib3dTest.java]: It is essentially disabling it. All not implemented autotests are not reported as failures.

Comment (alalek) [inline modules/calib3d/misc/java/test/Calib3dTest.java]: This behavior looks strange to me: "fail" should fail test instead of passing or skipping them.

BTW, Could we use "block" comments to minimize code changes (add `/* ... */` on new lines before and after test body)?

File: modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java [hunk 2]
```diff
@@ -28,7 +27,7 @@ private Mat getTestImg() {
     @Override
     protected void setUp() throws Exception {
         super.setUp();
-        extractor = DescriptorExtractor.create(DescriptorExtractor.BRIEF);
+        extractor = createAlgorythmInstance(XFEATURES2D_PACKAGE_NAME+"BriefDescriptorExtractor", ALGORITHM_FACTORY_NAME, null, null);
```
Comment (alalek) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: `Algorythm` -> `Algorithm`

File: modules/calib3d/misc/java/test/Calib3dTest.java (hunk 1 above)
Comment (abratchik) [inline modules/calib3d/misc/java/test/Calib3dTest.java]: Sure, I will change the comment and push it though. Will do some brushing as well.

File: modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java (hunk 2 above)
Comment (abratchik) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: ok, and that one too, will do today.

Comment (abratchik) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: I decided to drop "Algorythm" as well and call it "createClassInstance" as this method is  generic and can actually instantiate any class both using "new" operator and factory method technique. I thought it may be useful for other tests as well.

Comment (alalek) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: Sounds good.
BTW, Why is this functionality limited for tests only? I believe it should be available for regular Java applications too.

**Comment by abratchik** [comment]
Done, ready for the merge

**Comment by alalek** [comment]
:+1:

File: modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java [hunk 3]
```diff
@@ -69,12 +68,13 @@ public void testDescriptorType() {
...
     public void testEmpty() {
-        assertFalse(extractor.empty());
+//        assertFalse(extractor.empty());
+        fail("Not yet implemented"); // BRIEF does not override empty() method
     }
 
     public void testRead() {
         String filename = OpenCVTestRunner.getTempFileName("yml");
-        writeFile(filename, "%YAML:1.0\ndescriptorSize: 64\n");
+        writeFile(filename, "%YAML 1.0\n---\ndescriptorSize: 64\n");
```
Comment (alalek) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: Please revert this change: #7551

Comment (abratchik) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: ok, will do

Comment (abratchik) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: By the way, dashes are needed based on YAML spec:
`A YAML stream may contain several independent YAML documents. A document header line may be used to start a document and must be used to separate documents within a stream. This line must start with a document separator: “---” followed by a line break or a sequence of space characters. If no explicit header line is specified at the start of the stream, the processor should behave as if a header line containing an unadorned “---” was specified. `

**Comment by abratchik** [comment]
could you please have a look at the failed builds? The issues seem to be not related to this fix as it is only changing java tests. I've rebased on the upstream/master (4c667727839a678712f07bccefec1586df435969) so it should work with no issues.

**Comment by abratchik** [comment]
builds successfully completed, thank you. Ready for the merge

File: modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java (hunk 3 above)
Comment (abratchik) [inline modules/features2d/misc/java/test/BRIEFDescriptorExtractorTest.java]: changes completed, tested on the current master, java tests are completing without errors

**Comment by alalek** [comment]
Thank you! :+1:
