### PR TITLE
Fix copyTo on empty fixed-type matrices (#28343)

### LINKED ISSUE #28343: `cv::Mat_<T>::copyTo` can no longer be used on empty matrices
### System Information

After updating to OpenCV 4.13.0 one of my unit tests started failing with an OpenCV exception while trying to invoke `copyTo` on empty matrices of fixed type. In general, `copyTo` on empty matrices should be a no op and always succeed.

Bisecting the issue points to 64bbaa9f41be3e96a883cdbc11635eb84f18140c (#27972) as the commit that introduced the regression.

### Detailed description

`cv::Mat::copyTo` can no longer be invoked on empty matrices of fixed type. Trying to do so fails with the following exception:
```console
OpenCV(4.13.0) Error: Assertion failed (!fixedType() || ((Mat*)obj)->type() == mtype) in create, file /home/sergiu/Projects/opencv/modules/core/src/matrix_wrap.cpp, line 1321
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.13.0) /home/sergiu/Projects/opencv/modules/core/src/matrix_wrap.cpp:1321: error: (-215:Assertion failed) !fixedType() || ((Mat*)obj)->type() == mtype in function 'create'
```

### Steps to reproduce

```cpp
#include <opencv2/core.hpp>

int main()
{
    cv::Mat_<double> a;
    cv::Mat_<double> b;
    a.copyTo(b);
}
```

### Issue submission checklist

- [x] I report the issue, it's not a question
- [ ] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [x] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by WalkingDevFlag**
Resolves #28343

### Problem

PR #27972 added `_dst.create(size(), type())` in `copyTo`'s empty source block. This causes an assertion failure in Debug builds when copying empty fixed-type matrices (e.g., `Mat_<double>`).

**Root cause:** In Debug builds, `Mat::release()` resets `flags = MAGIC_VAL` (type becomes 0). When `_dst.create(size(), type())` is subsequently called, the assertion `!fixedType() || ((Mat*)obj)->type() == mtype` in `matrix_wrap.cpp:1321` fails because the destination's type (reset to 0) doesn't match the source's type.

### Solution

Skip `_dst.create()` for fixed-type destinations since they already have the correct type set, and calling `create()` with a potentially different type triggers the assertion failure.

```cpp
if( empty() )
{
    _dst.release();
    if( !_dst.fixedType() )
        _dst.create(size(), type());
    return;
}
```
### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under Apache 2 License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [x] The PR is proposed to the proper branch
- [x] There is a reference to the original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

### CODE REVIEW

**Comment by akretz** [comment]
I don't think this is the correct fix. If you call `b.type()` after `a.copyTo(b)` in your test, it throws in
https://github.com/opencv/opencv/blob/f3758f40ae4cbe2efc5d5b8fec52edb3bd6600c6/modules/core/include/opencv2/core/mat.inl.hpp#L1558
because as you have correctly pointed out, in debug builds the Mat's type information gets cleared in `Mat::release()` with
https://github.com/opencv/opencv/blob/f3758f40ae4cbe2efc5d5b8fec52edb3bd6600c6/modules/core/src/matrix.cpp#L556
The exception happens, because now the template type is inconsistent with the type flags.

I'm not sure why `Mat::release()` clears the flags just in debug builds. Maybe retaining the type flags with

```cpp
flags = (flags & CV_MAT_TYPE_MASK) | MAGIC_VAL;
```

would be appropriate.

**Comment by WalkingDevFlag** [comment]
Thanks for pointing this out! My original fix in copy.cpp was incomplete, since b.type() can still throw in Debug after copyTo.

I’ve updated the PR to try your suggestion and preserve the type bits in Mat::release():

```cpp
flags = (flags & CV_MAT_TYPE_MASK) | MAGIC_VAL;
```
Please let me know if this looks reasonable.

File: modules/core/test/test_mat.cpp [hunk 1]
```diff
@@ -1394,6 +1394,19 @@ TEST(Core_Mat, copyToConvertTo_Empty)
     ASSERT_EQ(C.type(), CV_32SC2);
 }
 
+// Regression test for https://github.com/opencv/opencv/issues/28343
+// copyTo on empty fixed-type matrices should be a no-op and succeed
+TEST(Core_Mat, copyTo_EmptyFixedType)
```
Comment (sergiud) [inline modules/core/test/test_mat.cpp]:
```suggestion
TYPED_TEST(Core_Mat, copyTo_EmptyFixedType)
```
I would suggest using [`TYPED_TEST`](https://google.github.io/googletest/reference/testing.html#TYPED_TEST_SUITE) and testing against all supported scalar types, not only `double`.

File: modules/core/test/test_mat.cpp [hunk 2]
```diff
@@ -1394,6 +1394,19 @@ TEST(Core_Mat, copyToConvertTo_Empty)
...
+{
+    cv::Mat_<double> a;
+    cv::Mat_<double> b;
+    ASSERT_TRUE(a.empty());
```
Comment (sergiud) [inline modules/core/test/test_mat.cpp]: I believe this assertion is redundant since it is implied by the subsequent test on `b`.

File: modules/core/test/test_mat.cpp (hunk 1 above)
Comment (WalkingDevFlag) [reply modules/core/test/test_mat.cpp]: Good point. The bug itself is type-independent (it’s in `Mat::release()` clearing the flags), but I agree broader coverage makes sense. I’ve updated the test to use `TYPED_TEST`.

File: modules/core/test/test_mat.cpp (hunk 2 above)
Comment (WalkingDevFlag) [reply modules/core/test/test_mat.cpp]: Fair point. I originally kept it to make the empty-matrix precondition explicit, but I’ve removed it to keep the test lean.

File: modules/core/test/test_mat.cpp (hunk 1 above)
Comment (sergiud) [reply modules/core/test/test_mat.cpp]: > [...] The bug itself is type-independent [...].

This is not correct. The issue does not arise with type-erased matrices, i.e., `cv::Mat`.

Comment (WalkingDevFlag) [reply modules/core/test/test_mat.cpp]: You’re right. I meant independent of the *scalar type* `T` (`Mat_<double>`, `Mat_<float>`, etc.), not type-erased `cv::Mat`. The issue only affects fixed-type matrices where `fixedType() == true`.

**Review by vpisarev — APPROVED** [review]
