### PR TITLE
imgproc: fixed imread with output image argument

### LINKED ISSUE #25694: `cv::imread` with `OutputArray dst` returns with empty output
### System Information

OpenCV version: 4.10.0
Operating System / Platform: macOS Sonoma 14.4.1
Compiler & compiler version: 
```
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### Detailed description

When using `cv::imread` with `OutputArray dst` given, the output will stay empty. The path to the image and the image file are both valid and can be read by the program and the user.

```cpp
CV_EXPORTS_W void imread( const String& filename, OutputArray dst, int flags = IMREAD_COLOR );
```

There is no error message in stdout/stderr. Calling the function with correct parameters doesn't throw any exceptions.

### Steps to reproduce

To the best of my understanding, the variable `dst` is expected to be a valid and non-empty `cv::Mat` after calling `cv::imread` in the following code:

```cpp
#include <stdio.h>
#include <opencv2/opencv.hpp>

int main(int argc, const char** argv) {
    if (argc != 2) {
        printf("[!] Usage: %s <image_path>\n", argv[0]);
        return 1;
    }

    printf("[+] image_path: %s\n", argv[1]);
    cv::Mat dst;
    cv::imread(argv[1], dst, cv::IMREAD_COLOR);
    if (dst.empty()) {
        printf("[!]: dst is empty\n");
        return 1;
    }
    cv::imshow("Image", img);
    cv::waitKey(0);
    return 0;
}
```

The test file, `corridor.jpg` is a valid JPEG file (this can be any supported image format, not limited to the JPEG format only) and located in `/tmp/` and can be read by anyone. This file is taken from opencv_contrib, in `samples/data/corridor.jpg`, https://github.com/opencv/opencv_contrib/blob/4.x/samples/data/corridor.jpg

```bash
./test /tmp/corridor.jpg
[+] image_path: /tmp/corridor.jpg
[!]: dst is empty
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by mshabunin**
Resolves #25694
Replaces #25695

* Moved `OutputArray` down the call stack
* Allow output images with smaller or larger size - will be recreated if necessary
* Added check for recreated image in calls to backend, if this happens, original image will not be updated - backend should be fixed in this case
* Fixed gray output handling in HDR (RGBE) backend - use cvtColor to convert
* Extended and moved corresponding test

Note: we rely on decoders to not recreate the input Mat in their `readData(Mat & img)` method. Otherwise destination image will not be updated just like in the issue.

### CODE REVIEW

**Comment by cocoa-xu** [comment]
Hi @mshabunin, thanks for the fix! This looks perfect. ;)

**Comment by sturkmen72** [comment]
is it too late to change API. 
```
void imread( const String& filename, OutputArray dst, int flags )
{
    CV_TRACE_FUNCTION();

    /// load the data
    imread_(filename, flags, dst);
}
```

`int imread( const String& filename, OutputArray dst, int flags )` will be good in that it is open to development in the future.

**Comment by mshabunin** [comment]
> is it too late to change API.

@sturkmen72 , this PR doesn't change public API (`imread`). Only internal functions are affected, e.g. `imread_`.

**Comment by sturkmen72** [comment]
> > is it too late to change API.
> 
> @sturkmen72 , this PR doesn't change public API (`imread`). Only internal functions are affected, e.g. `imread_`.

i mean if it is still possible ( it is newly added function and maybe ABI change policy allow )
 `int imread( const String& filename, OutputArray dst, int flags )` will be open further development in the future.
At least i propose doing such change in OpenCV5

File: modules/imgcodecs/src/loadsave.cpp [hunk 1]
```diff
@@ -462,16 +462,10 @@ imread_( const String& filename, int flags, OutputArray mat )
     // grab the decoded type
     const int type = calcType(decoder->type(), flags);
 
-    if (mat.empty())
```
Comment (sturkmen72) [inline modules/imgcodecs/src/loadsave.cpp:460]: this change seems wrong to me.

Comment (mshabunin) [reply modules/imgcodecs/src/loadsave.cpp:460]: `create` should not reallocate data if requested image size fits into existing Mat.

```.cpp
Mat img(1000, 1000, CV_8UC3);
imread(f, img); // should not reallocate data if image size is less than (1000, 1000)
```

Without this change it will not be possible to read multiple images of different sizes efficiently, because user would need to pass either empty Mat or a Mat with exact image dimensions on each iteration.

I.e. with proposed change, following code should work and should perform reallocations only when necessary:
```.cpp
Mat img;
for (auto f : filenames)
{
    imread(f, img); // will fail if images have different sizes
}
```

Comment (sturkmen72) [reply modules/imgcodecs/src/loadsave.cpp:460]: sorry you are right. `mat.create( size.height, size.width, type );` does the job.

Comment (sturkmen72) [reply modules/imgcodecs/src/loadsave.cpp:460]:
```
    TickMeter tm;

    Mat im;

    for (int i = 0; i < 5; i++)
    {
        tm.reset();
        tm.start();
        imread("read.png", im);
        tm.stop();
        printf("read time %f\n", tm.getTimeSec());
    }
    imshow("read.png", im);
    waitKey();
```

```
read time 0.692092
read time 0.615938
read time 0.615163
read time 0.615883
read time 0.617650
```
good job!

File: modules/imgcodecs/src/loadsave.cpp [hunk 2]
```diff
@@ -328,7 +344,7 @@ static ImageEncoder findEncoder( const String& _ext )
 }
 
 
-static void ExifTransform(int orientation, Mat& img)
```
[the remark this answers is not in the document]
Comment (mshabunin) [reply modules/imgcodecs/src/loadsave.cpp:331]: It seems that it won't work without changing public `imread` to accept `InputOutputArray` (https://docs.opencv.org/4.x/d0/d46/classcv_1_1__InputOutputArray.html). There is no obvious way to construct `InputOutputArray` from `OutputArray` (https://docs.opencv.org/4.x/d2/d9e/classcv_1_1__OutputArray.html).

**Review by asmorkalov — APPROVED** [review]
:+1:
