### PR TITLE
Finished with several samples support, need regression testing

### LINKED ISSUE #6227: predict_prob in opencv 3.1's RTrees class
### System information
- OpenCV version: 3.0 / 3.1
- Host OS: Linux (Ubuntu 14.04)  / Windows 10
### In which part of the OpenCV library you got the issue?
- ml
- random decision trees (RTrees)
### Issue

while the method "predict_prob" was available in opencv 2.4 for probabilistic output of CvRTrees, this very useful method has been removed in opencv 3.0 and 3.1.
### Possible solutions

It would be great if developers provide users with a small note in the documentation on 

```
a) how some one can get confidence / probabilistic output from RTrees, or

b) how some one can access to the number of votes for each label.
```

### PR DESCRIPTION
**Pull request by mrquorr**
Finished with several samples support, need regression testing

resolves #6227 

### This pullrequest adds
the predictProb function, which receives several samples to be predicted and returns the amount of votes each class receives.

### CODE REVIEW

File: modules/ml/include/opencv2/ml.hpp [hunk 1]
```diff
@@ -1164,6 +1164,14 @@ class CV_EXPORTS_W RTrees : public DTrees
      */
     CV_WRAP virtual Mat getVarImportance() const = 0;
 
+    /** Returns the result of each individual tree in the forest.
+    In case the model is a regression problem, the method will return each of the tree's
+    result for each of the sample cases. If the model is a classifier, it will return 
+    a Mat with samples + 1 rows, where the first row gives the class number and the 
+    following rows return the votes each class had for each sample.
+    */
+    CV_WRAP virtual Mat predictProb(const InputArray inputs, int flags) const = 0;
```
Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: Results should be returned via cv::OutputArray. See `predict()` method prototype for an example.

Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: Also now we can't add pure virtual methods to public classes. It can break ABI compatibility. In current implementation we already have implicit definitions for this method in `DTrees` and `Rtrees`, so it can be just virtual.

Comment (mrquorr) [inline modules/ml/include/opencv2/ml.hpp]: Ok, I'll try fixing it today.

Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: And `const` modifier is useless for `InputArray`

**Comment by mrquorr** [comment]
Should I squash it?

File: modules/ml/include/opencv2/ml.hpp [hunk 2]
```diff
@@ -1164,6 +1164,14 @@ class CV_EXPORTS_W RTrees : public DTrees
      */
     CV_WRAP virtual Mat getVarImportance() const = 0;
 
+    /** Returns the result of each individual tree in the forest.
+    In case the model is a regression problem, the method will return each of the tree's
+    result for each of the sample cases. If the model is a classifier, it will return 
+    a Mat with samples + 1 rows, where the first row gives the class number and the 
+    following rows return the votes each class had for each sample.
+    */
+    CV_WRAP virtual void getVotes(InputArray, OutputArray, int) {};
```
Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: ABI compatibility check still fails here, so I think It's better to create an implicit implementation. Here is an example how to call method of child `Impl` class:
```
Mat SVM::getUncompressedSupportVectors() const
{
    const SVMImpl* this_ = dynamic_cast<const SVMImpl*>(this);
    if(!this_)
        CV_Error(Error::StsNotImplemented, "the class is not SVMImpl");
    return this_->getUncompressedSupportVectors_();
}
```

**Comment by sovrasov** [comment]
Yes, squash is needed.

**Comment by mrquorr** [comment]
I had some problems with my environment and had to do a reinstall. In 7 hours, the pull request will be ready.

File: modules/ml/src/rtrees.cpp [hunk 3]
```diff
@@ -349,6 +349,61 @@ class DTreesImplForRTrees : public DTreesImpl
         }
     }
 
+    void getVotes( InputArray _samples, OutputArray _results, int flags ) const
+    {
+        CV_Assert( !roots.empty() );
+        int nclasses = (int)classLabels.size(), ntrees = (int)roots.size();
+        Mat samples = _samples.getMat(), results;
+        int i, j, nsamples = samples.rows;
+        printf("nsamples: %d\n", nsamples);
```
Comment (mrquorr) [inline modules/ml/src/rtrees.cpp]: Done, it matches. Resquashing new commit.

**Comment by sovrasov** [comment]
@mrquorr do you need any help with implementation of the test?

**Comment by mrquorr** [comment]
Err... I already tested regression, all was well. Unless you meant a formal test written on the code?

**Comment by sovrasov** [comment]
Yes, it's the last thing before merge this PR.

**Comment by mrquorr** [comment]
Ok, where should I write the test? I imagine that a test for classification is also needed. Sorry, I thought you were still reviewing it.

**Comment by sovrasov** [comment]
I think you can put the test [here](https://github.com/sovrasov/opencv/blob/master/modules/ml/test/test_mltests.cpp#L174).
Classification test for `RTrees` already exists, so only check for `getVotes` is required.

**Comment by mrquorr** [comment]
The function has 2 variants, when the `RTrees` is a classifier and when it does regression. I will implement tests for both cases. Also, how does the `TEST` function work? What do the parameters mean?

**Comment by sovrasov** [comment]
`TEST` is a macros which takes two names: name of a grpoup of tests and a name of the test. It comes from the  googletest framework.

**Comment by alalek** [comment]
@mrquorr Take a look on these simple tests examples [here](https://github.com/opencv/opencv/pull/8244/files#diff-40165347fbbf4111b80b7fe25006a3d1R1244). All checks should go via `ASSERT_`/`EXPECT_` macro (ASSERT will fail immediately, EXPECT dumps error message and continue execution).

**Comment by mrquorr** [comment]
Is it possible to have two classes with the same amount of votes? If so, what is the result of `predict`?

**Comment by mrquorr** [comment]
In any case, the test is finished as @sovrasov recommended. I also added a test that checked that the total number of votes was the same as the amount of trees in the forest.

File: modules/ml/test/test_mltests.cpp [hunk 4]
```diff
@@ -172,4 +172,49 @@ TEST(ML_NBAYES, regression_5911)
...
+        //predicted_class = max_votes < val? i;
+        if( max_votes < val )
+        {
+            max_votes = val;
+            predicted_class = i;
+        }
+        count += val;
+    }
+
+    EXPECT_EQ(count, rt->getRoots().size());
```
Comment (sovrasov) [inline modules/ml/test/test_mltests.cpp]: You need to cast `rt->getRoots().size()` into `int` to fix warning on Windows.

File: modules/ml/include/opencv2/ml.hpp [hunk 5]
```diff
@@ -1164,6 +1164,14 @@ class CV_EXPORTS_W RTrees : public DTrees
      */
     CV_WRAP virtual Mat getVarImportance() const = 0;
 
+    /** Returns the result of each individual tree in the forest.
+    In case the model is a regression problem, the method will return each of the trees'
+    results for each of the sample cases. If the model is a classifier, it will return 
+    a Mat with samples + 1 rows, where the first row gives the class number and the 
+    following rows return the votes each class had for each sample.
+    */
+    CV_WRAP void getVotes(InputArray, OutputArray, int) const;
```
Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: I missed this: all parameters should have names and be documented. Meaning of the last integer parameter is unclear without looking through the code.

**Comment by mrquorr** [comment]
Done.

File: modules/ml/include/opencv2/ml.hpp [hunk 6]
```diff
@@ -1164,6 +1164,16 @@ class CV_EXPORTS_W RTrees : public DTrees
...
 
+    /** Returns the result of each individual tree in the forest.
+    In case the model is a regression problem, the method will return each of the trees'
+    results for each of the sample cases. If the model is a classifier, it will return
+    a Mat with samples + 1 rows, where the first row gives the class number and the
+    following rows return the votes each class had for each sample; receives samples
+    through InputArray, gives results through OutputArray, and receives a flag parameter
+    through the last int.
+    */
+    CV_WRAP void getVotes(InputArray, OutputArray, int) const;
```
Comment (sovrasov) [inline modules/ml/include/opencv2/ml.hpp]: Actually I've told about description in Doxygen style:
```
...
     @param samples ...description
     @param votes ...description
     @param flags ...description
CV_WRAP void getVotes(InputArray samples, OutputArray votes, int flags) const;
```

**Comment by mrquorr** [comment]
Added the doxygen params.

**Comment by sovrasov** [comment]
:+1:
