### PR TITLE
Fix reference counting errors in registerNewType

### LINKED ISSUE #23059: Potential reference counting error in Python module
### System Information

OpenCV python version: 4.6.0.66
Operating System / Platform: Ubuntu 20.04
Python version: 3.9.15

### Detailed description

Hello! I have a Cpython version 3.9.15 built with NDEBUG flag. When I import cv2 in it, it aborted with garbage collection error. 

```
Modules/gcmodule.c:116: gc_decref: Assertion "gc_get_refs(g) > 0" failed: refcount is too small
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x55c596b9ad90
object refcount : 8
object type     : 0x55c596331780
object type name: type
object repr     : <class 'cv2.utils.nested.ExportClassName'>

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x0000149adc163600 (most recent call first):
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1173 in create_module
  File "<frozen importlib._bootstrap>", line 565 in module_from_spec
  File "<frozen importlib._bootstrap>", line 666 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1030 in _gcd_import
  File "/home/user/real_pure_python/cpython-3.9/Lib/importlib/__init__.py", line 127 in import_module
  File "/home/user/real_pure_python/cpython-3.9/my_python/lib/python3.9/site-packages/cv2/__init__.py", line 153 in bootstrap
  File "/home/user/real_pure_python/cpython-3.9/my_python/lib/python3.9/site-packages/cv2/__init__.py", line 181 in <module>
  File "<frozen importlib._bootstrap>", line 228 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 850 in exec_module
  File "<frozen importlib._bootstrap>", line 680 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007 in _find_and_load
  File "<stdin>", line 1 in <module>
Aborted (core dumped)
```

I think about this for some time and guess the problem is that the class "ExportClassName" is added to two modules in "registerNewType", which calls "PyModule_AddObject", which decrease the reference count of "ExportClassName" by one in the end. Thus, before calling PyModule_AddObject, one should either hold an existing reference of "ExportClassName" or increase the reference by one. 

Since I am new to opencv, there may be something I misunderstand. Thanks in advance. 

### Steps to reproduce

To reproduce this bug, import cv2 in any Cpython built with NDEBUG flag should be enough. 

```
import cv2
```

### Issue submission checklist

- [X] I report the issue, it's not a question
- [X] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [X] I updated to the latest OpenCV version and the issue is still there
- [X] There is reproducer code and related data files (videos, images, onnx, etc)

### PR DESCRIPTION
**Pull request by spikethehobbitmage**
Fixes #23059 

Fix reference counting error in registerNewType so it no longer double-steals sometimes.

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [X] I agree to contribute to the project under Apache 2 License.
- [X] To the best of my knowledge, the proposed patch is not based on a code under GPL or another license that is incompatible with OpenCV
- [X] The PR is proposed to the proper branch
- [X] There is a reference to the original bug report and related work
- N/A There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [ ] The feature is well documented and sample code can be built with the project CMake

Edit: Fixes bug, not just related.

### CODE REVIEW

File: modules/python/src2/cv2.cpp [hunk 1]
```diff
@@ -284,6 +284,7 @@ static bool init_submodule(PyObject * root, const char * name, PyMethodDef * met
 static inline
 bool registerTypeInModuleScope(PyObject* module, const char* type_name, PyObject* type_obj)
 {
+    Py_INCREF(type_obj); /// Give PyModule_AddObject a reference to steal.
```
Comment (VadimLevin) [inline modules/python/src2/cv2.cpp:287]: Thanks for contribution, so as for reference counting scheme will be the following:

type is registered in module scope:
 - `PyType_FromSpecWithBases` [ref = 1]
 - `registerTypeInModuleScope`-> increment [ref = 2] -> `PyModule_AddObject`-> steals - [ref = 2]
 - `registerTypeInModuleScope`-> increment [ref = 3] -> `PyModule_AddObject`-> steals - [ref = 3]
 - Decrement [ref = 2]
 
 type is registered in class score:
 - `PyType_FromSpecWithBases` -> [ref = 1]
- `registerTypeInClassScope` -> `PyDict_SetItemString` no ref changes -> [ref = 1]
 - `registerTypeInModuleScope`-> increment [ref = 2] -> `PyModule_AddObject`-> steals [ref = 2]
 - Decrement [ref = 1] 

From the above scheme it looks that `registerTypeInClassScope` also requires `Py_INCREF`, doesn't it?
Is my scheme wrong?

Comment (spikethehobbitmage) [reply modules/python/src2/cv2.cpp:287]: Not quite.

PyDict_SetItemString calls Py_INCREF internally, so the refcount increases at that step. That's why registerTypeInClassScope can safely borrow type_obj.

* PyType_FromSpecWithBases -> [ref = 1]
* registerTypeInClassScope -> PyDict_SetItemString (calls Py_INCREF internally) -> [ref = 2]
* registerTypeInModuleScope-> increment [ref = 3] -> PyModule_AddObject-> steals [ref = 3]
* Decrement [ref = 2]

Comment (VadimLevin) [reply modules/python/src2/cv2.cpp:287]: @spikethehobbitmage Oh, I see.

Call chain for reference [PyDict_SetItemString](https://github.com/python/cpython/blob/fd43fb69962361ce4ef8e1175fde0a32726cdf77/Objects/dictobject.c#L3912) -> [PyDict_SetItem](https://github.com/python/cpython/blob/fd43fb69962361ce4ef8e1175fde0a32726cdf77/Objects/dictobject.c#LL1896-L1896C15) -> `Py_INCREF(value)`

**Review by VadimLevin — APPROVED** [review]
